### ISSUE TITLE
HeaderTemplate has non-deterministic order for multi-valued headers

### ISSUE THREAD

**Issue by mbarkley** [OpenFeign/feign#1007]
[Here](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/template/HeaderTemplate.java#L72) and [here](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/template/HeaderTemplate.java#L85), `Collectors.toSet` is used, which results in multi-valued header values being stored in a `HashSet`. Consequently the order of multi-valued headers is non-deterministic.

As a `LinkedHashSet` is used in close proximity, I assume this is a bug.

**Comment by kdavisk6** [comment]
@mbarkley 

Thank you for bringing this to our attention.  I've flagged this as a bug and as help wanted asking for other to help us fix this.  If you are interested, please feel free to raise a PR with a potential fix.

**Comment by mbarkley** [comment]
@kdavisk6 [PR](https://github.com/OpenFeign/feign/pull/1009) sent.
