### ISSUE TITLE
How to use two @QueryMap annotations in an interface method?

### ISSUE THREAD

**Issue by lm1y** [OpenFeign/feign#1014]
example:

     @GetMapping("/url")
     void message(@SpringQueryMap XXRequest request1,@SpringQueryMap YYRequest request2);
     
feign.MethodMetadata:

    public final class MethodMetadata implements Serializable {
           ...
      private Integer queryMapIndex;
           ...
    }
    

feign.ReflectiveFeign.BuildTemplateByResolvingArgs#create：

    if (metadata.queryMapIndex() != null) {
         // add query map parameters after initial resolve so that they take
         // precedence over any predefined values
         Object value = argv[metadata.queryMapIndex()];
         Map<String, Object> queryMap = toQueryMap(value);
         template = addQueryMapQueryParameters(queryMap, template);
    }

**Comment by kdavisk6** [comment]
@lm1y 

You can define only **one** `@QueryMap`.  One approach you could take to workaround this is to combine the two maps into a single map instead.

**Comment by LiJohnson** [comment]
any solution make it work?

**Comment by joaomper-TE** [comment]
I'm also interested in a workaround for this. In my opinion it would make sense to have multiple @QueryMap
