### ISSUE TITLE
BaseContract.parseAndValidateMetadata no need always to call processAnnotationOnClass

### ISSUE THREAD

**Issue by hackingwu** [OpenFeign/feign#1017]
in class `BaseContract`, method `parseAndValidateMetadata(Class)` call `parseAndValidateMetadata(Class, Method)` for every themod.
but in method `parseAndValidateMetadata(Class,Method)` will call `processAnnotaionOnClass`, but targetType always never change, There is no need to call processAnnotaionOnClass for every method.

**Comment by kdavisk6** [comment]
@hackingwu 

`processAnnotationOnClass` is required for each method.  There are situations where annotations such as `RequestLine` and `Header` can be used at the type level, therefore, we must read those again for each method, since they apply to every method, when we are building the metadata.
