### ISSUE TITLE
Executing Feign clients in main or separate threads

### ISSUE THREAD

**Issue by gadgadskiy** [OpenFeign/feign#1026]
Hi. I have big old project with modules using Feign clients
Actually two modules run one Feign client from common library
In first module it always run in main thread:
`Thread.currentThread().getName(); //returns "Thread-100500"`
Other module runs it always in new separate thread
`Thread.currentThread().getName(); //returns "hystrix-my-client-1" etc`
Modules have identical configs related to threads & timeouts:
```
ribbon.ReadTimeout=10000
ribbon.ConnectTimeout=2000
feign.client.config.default.readTimeout=10000
feign.client.config.default.connectTimeout=2000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=20000
hystrix.threadpool.default.coreSize=25
```
I can't find any docs described this part of Feign client behavior and can't understand how to make them similar.
Please describe, what things affect this? How can I directly configure clients to run in main or  separate threads?

**Comment by kdavisk6** [comment]
@gadgadskiy 

I recommend that you look into understanding [Hystrix](https://github.com/Netflix/Hystrix/wiki/How-it-Works), as that is the component responsible for the behavior you are seeing.  In particular, pay attention to the Isolation and Thread and Thread Pool sections.

**Comment by gadgadskiy** [comment]
@kdavisk6 yes, you're right, problem was exactly in Hystrix.
It was enabled in first module, so Feign methods were invoked with HystrixInvocationHandler (that has his own multithreading strategy). Otherwise method were invoked with ReflectiveFeign.FeignInvocationHandler
For me it was enough to disable Hystrix with one line
```
hystrix.command.default.execution.isolation.strategy=SEMAPHORE
```
Thanks

**Comment by chaturvedishiva** [comment]
Not clear, at the end, how to develop a feign client code as part of a multithreading run method
