### ISSUE TITLE
FeignClient support for multiple inheritance

### ISSUE THREAD

**Issue by vishwanathpatil2193** [OpenFeign/feign#1029]
Hi Guys, I had to support two URI's in my project. For this, I made something like this:

preface:
1) FeignClient used is of "org.springframework.cloud.netflix.feign.FeignClient",
2) Name of the two feign clients are different

```java
public interface A extends ThirdPartyContract{
@RequestMapping(path="something", and other parameters)
public <type> someMethod(){
}
}

@ConditionalOnProperty(name="someProperty",havingValue="false", matchIfMissing=true)
@FeignClient(name="SomeName", url="SomeUrl", configuration={Config.class})
public interface Aa extends A{
}

@ConditionalOnProperty(name="someProperty",havingValue="true", matchIfMissing=false)
@FeignClient(name="SomeName-abc", url="SomeUrl", configuration={Config.class, ConfigSomeOtherType.class})
public interface Bb extends A{
}
```
Also,
**It worked perfectly fine when I ran in my local workstation but failed in the staging Environment.**

**The reason it said was:
```
Caused by: java.lang.IllegalStateException: Only single-level inheritance supported: Bb
     at feign.Util.checkState(Util.java:128)
     at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:53)**
```
I debugged in my local workstation using the stacktrace given above and found that for --**Only single-level inheritance supported** -- to happen, this condition--**if 

```java
(targetType.getInterfaces().length == 1) {
        checkState(targetType.getInterfaces()[0].getInterfaces().length == 0,
                   "Only single-level inheritance supported: %s",
                   targetType.getSimpleName());
      }
```

-- should be false. When this happens, the above exception is thrown. However, I did not face this in my local system but in staging Environment.

** question**
In any time, the code above should provide only one the beans and should work as expected, right?

**Comment by kdavisk6** [comment]
@vishwanathpatil2193 

Your issue not with Feign but your Spring Bean autoconfiguration.  Your configuration will result in both Beans `Aa` and `Bb` being created due to your conflicting `@ConditionalOnProperty` annotations.  I recommend you reduce your configuration to just one client get that working first before applying the autoconfiguration.

Since this is not a Feign issue, but a Spring Issue, I recommend that you reach out to folks there or on StackOverflow for more help.

**Comment by silkentrance** [comment]
@kdavisk6 The problem stems from interface `A` extending yet another interface `ThirdPartyContract` and is not because of some malformed spring configuration.
