### ISSUE TITLE
Query map parameters get encoded twice in the request URL

### ISSUE THREAD

**Issue by davide-maestroni** [OpenFeign/feign#1037]
### Issue
When using a parameter map in the API interface annotated with `@QueryMap(encoded=true)`, the resulting request URL query contains values which are url-encoded twice.

### Steps to reproduce
The unit test in the following snippet shows how to reproduce the issue. The query value is pre-encoded (`"this+is+a+test"`) and put into the query map. This cause the server to receive a decoded value which is incorrect.

```
  @Test
  public void queryEncodingIssue() throws IOException, InterruptedException {
    MockWebServer server = new MockWebServer();
    server.enqueue(new MockResponse().setResponseCode(200).setBody("{}"));
    server.start();
    try {
      String endpoint = "http://localhost:" + server.getPort();
      ObjectMapper objectMapper = new ObjectMapper();
      GetWithQueries getWithQueries = Feign.builder()
        .encoder(new FormEncoder(new JacksonEncoder(objectMapper)))
        .decoder(new JacksonDecoder(objectMapper))
        .logger(new Slf4jLogger())
        .client(new OkHttpClient())
        .target(GetWithQueries.class, endpoint);
      getWithQueries.get(Collections.singletonMap("query1", "this+is+a+test"));
      RecordedRequest recordedRequest = server.takeRequest();
      assertThat(recordedRequest.getRequestUrl().queryParameterValues("query1"))
        .containsExactly("this is a test");

    } finally {
      server.shutdown();
    }
  }

  public interface GetWithQueries {

    @RequestLine("GET /data?query1={query1}&query2={query2}&query3={query3}")
    Data get(@QueryMap(encoded=true) Map<String, Object> queryParams);

    class Data {
      String name;
    }
  }
```

Notice that the above test works fine with version 9.7.0 of Feign, while fails using the latest one (10.2.3). In fact, the printed logs for the two versions differ as follows:

**Feign 9.7.0**
`INFO: MockWebServer[60982] received request: GET /data?query1=this+is+a+test HTTP/1.1 and responded: HTTP/1.1 200 OK`

**Feign 10.2.3**
`INFO: MockWebServer[60971] received request: GET /data?query1=this%2Bis%2Ba%2Btest HTTP/1.1 and responded: HTTP/1.1 200 OK`

**Comment by kdavisk6** [comment]
This is expected behavior, specifically for the `+` (plus) sign.  Here is the latest in our documentation:

>What about plus? +
>
>Per the URI specification, a + sign is allowed in both the path and query segments of a URI, however, handling of the symbol on the query can be inconsistent. In some legacy systems, the + is equivalent to the a space. Feign takes the approach of modern systems, where a + symbol should not represent a space and is explicitly encoded as %2B when found on a query string.
>
>If you wish to use + as a space, then use the literal character or encode the value directly as %20

When using Feign 10.x, you must encode spaces using their [pct-encoded](https://en.wikipedia.org/wiki/Percent-encoding) variant.

**Comment by davide-maestroni** [comment]
Ok, I tested again with `this%20is%20a%20test` and it worked. So the issue was actually the + sign. Thanks
