### ISSUE TITLE
Response is  final

### ISSUE THREAD

**Issue by SoberChina** [OpenFeign/feign#1049]
What is the point of Response be a final class?   
I want to record the information in response to the request.I tried to focus on client.
But I found that this was not a good extension and wanted to design an Interceptor similar to RestTemplate, but feign did not have a stream copy like it. Response is a final and cannot be rewritten.
Looking forward to receiving a response. Thanks!

[Response.class](https://github.com/OpenFeign/feign/blob/9a4b21bc0e21349687fbba3ee72154f440630af2/core/src/main/java/feign/Response.java#L40)

**Comment by SoberChina** [comment]
Yes, you are right, I can use responseMapper. But not in line with my existing business, I need to log the request and response to a single line.

**Comment by SoberChina** [comment]
I feel more convenient than the RestTemplate Interceptor, if the feign Interceptor can support it, it has nothing to do with `okhttp`, `httpclient`.

**Comment by SoberChina** [comment]
**@kdavisk6** 
Yes, my problem is the same as that issues. I'm also tracking logs. I didn't find feign-supported components. I tried to rewrite Response so I got this issue. I need to log the request and response to a single line.Best of all is a log object that can be customized to print.

**Comment by lierox90** [comment]
I have education because i encounter issue with it being final as well, so how should we approach mocking, its final so that's not possible and test require boilerplate code when we just need to access for example only headers, plus final is actually blocking extending of class so how is that according to principle

**Comment by SoberChina** [comment]
@lierox90 I don't quite understand you,If you want to add public headers, you can use `Interceptor `.
Like he said [Response is part of our core API and is intentionally final...](https://github.com/OpenFeign/feign/issues/1049#issuecomment-524873023).Although I don't think inheritance is modification, the deeper meaning is extension.
