### ISSUE TITLE
Having [] in RequestParam doesn't substitute value in 10.x

### ISSUE THREAD

**Issue by legendjaks** [OpenFeign/feign#1051]
Using `SpringBoot 2.1.5` and OpenFeign for calling internal & external services `("io.github.openfeign:feign-httpclient:10.3.0")`

I need to call an external API which is having `[]` in query(request) param. In openfeign `10.x` when
`RequestParam` is having `[]`, it is not sending the proper value.

Here is the FeignClient
```
@FeignClient(name="product-proxy", url="\${product.url}")
interface ProductProxy {
    @GetMapping("/products", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun products(@RequestParam("id[]") ids: List<String>): List<Product>
}
```
While invoking feign-client,
```
 @Autowired
private lateinit var productProxy: ProductProxy
...
productProxy.products(listOf("1", "2"))
```
got the following log from feign,
```
[ProductProxy#products] ---> GET http://product-service/products?id%5B%5D=%7Bid%5B%5D%7D HTTP/1.1
```
which translates into `http://product-service/products?id[]={id[]}` . It must be `http://product-service/products?id%5B%5D=1&id%5B%5D=2` with `[]` being encodes as `%5B%5D`.

If the contract is,
`fun products(@RequestParam("id") ids: List<String>): List<Product>`

It is working fine as
`[ProductProxy#products] ---> GET http://product-service/products?id=1&id=2 HTTP/1.1`

The only problem is when we have `[]` in the RequestParam. The same code was working in openfeign `9.7.0`.

As a workaround, I am using the following interceptor to change the query param names,
```
@Component
class ArrayParamInterceptor : RequestInterceptor {

    companion object {
        private val log = LoggerFactory.getLogger(ArrayParamInterceptor::class.java)
    }

    val lookFor = "-array"
    val replaceTo = "%5B%5D"

    override fun apply(template: RequestTemplate) {

        template.queries().forEach { (key, value) ->
            if(key.trim().endsWith(lookFor)) {
                val sanitizedKey = key.replace(lookFor, replaceTo)
                log.info("Key changed from $key to $sanitizedKey")

                template.query(key, emptyList())
                template.query(sanitizedKey, value)
            }
        }
    }
}
```
changing the contract to use `-array` instead of `[]`
```
    @GetMapping("/products", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun products(@RequestParam("id-array") ids: List<String>): List<Product>
```

**Comment by legendjaks** [comment]
@kdavisk6 please move it to next stage

**Comment by kdavisk6** [comment]
@legendjaks 

I am not able to reproduce this issue using Feign core and our JAX/RS library extension, which is very similar to the Spring Cloud extension:

```java
interface ParameterTests {
   @GET
   @Path("/users")
   Response queryWithLists(@QueryParam("ids[]") List<String> ids);
}

// test case
tests.queryWithLists(Arrays.asList("1", "2"));

// result
/users?ids%5B%5D=1&ids%5B%5D=2
```

You may need to check your dependencies and ensure that you have `feign-core` at version `10.3.0` as well.  If you are still running into this issue, I suggest that you reach out to the Spring Cloud team as it may be an issue in how their contract is passing the information to Feign.

**Comment by legendjaks** [comment]
Thanks. I will check with Spring cloud feign.

**Comment by legendjaks** [comment]
The problem was with `Spring Cloud Greenwich.SR1`, after migrating to `Greenwich.SR2` the issue disappeared.
