### ISSUE TITLE
Specific HTTP error code FeignExceptions

### ISSUE THREAD

**Issue by pvdissel** [OpenFeign/feign#106]
Currently any error caused by the executed HTTP call results in a FeignException. This makes it impossible to handle according to the type of HTTP error. (Or am I missing something?)

Would it be an idea to:
- have HTTP error code ranged exceptions, like Http4xxFeignException for any 400-499 HTTP error, and Http5xxFeignException for 500-599 HTTP errors
- have the specific error code available in the exception

**Comment by Drdoteam** [comment]
@adriancole Do you have a plan which you add this feature to Feign ?

**Comment by adriancole** [comment]
I like the wiki/documentation approach. Users will have a better set of ranges that make sense to them.

I don't want to create http code range exceptions, particularly as in many cases this is nuanced and you'll need the underlying code anyway. Ex. 3xx range includes cache-related codes as well redirects. Also, many apis that feign restfulness use 500 for everything or tunnel errors through 200. In other words, we should allow folks to define application-specific exceptions.. absolutely, but I don't think that a shared set of ranged exceptions are high enough value to add to the codebase, knowing what we know.

**Comment by Drdoteam** [comment]
@adriancole Yeah I understand! There are many different ways to process HTTP status codes.
Thanks for your quick reply.
