### ISSUE TITLE
Support of `around Interceptor`

### ISSUE THREAD

**Issue by keygod** [OpenFeign/feign#1062]
Hello!  
Can we add a `Interceptor `  like 

`public class InterceptorE implements Interceptor{

	@Override
	public boolean before(Object proxy, Object target, Method method, Object[] args) {
	
		return true;
	}

	@Override
	public void around(Object proxy, Object target, Method method, Object[] args) {

	}

	@Override
	public void after(Object proxy, Object target, Method method, Object[] args) {
	}

}`

**Comment by finnetrolle** [comment]
@keygod 
Could you describe purposes of Interceptors according to Feign please?

**Comment by keygod** [comment]
> @keygod
> Could you describe purposes of Interceptors according to Feign please?
for global transaction,
I need to bind or unbind a  global ID in `Request` life cycle  ;

**Comment by velo** [comment]
you can use `requestInterceptor` 

```
            .requestInterceptor(template -> {
                final String tracker = "my ultra unique code";
                template.header("X-Request-Tracker", tracker);
            })
```
