### ISSUE TITLE
Unwanted request line overriding

### ISSUE THREAD

**Issue by artemsnisarenko** [OpenFeign/feign#1063]
When a `URI` is used as a parameter it replaces the base url.

For example,
```
interface GitHub {
    @RequestLine("GET /login/oauth/authorize?redirect_uri={redirect_uri}")
    void authorize(@Param("redirect_uri") URI redirectUri);
}
// used as
// github.authorize(URI.create("https://example.com/cb"));
// produces
// ---> GET https://example.com/cb/login/oauth/authorize?redirect_uri=https:%2F%2Fexample.com%2Fcb HTTP/1.1
```
It's counterintuitive. Does it absolutely have to behave like this?

**Comment by kdavisk6** [comment]
https://github.com/OpenFeign/feign#interface-annotations

Look at the section labeled **Overriding the Request Line**

**Comment by artemsnisarenko** [comment]
I've seen it before creating this issue and I don't see how it addresses my question. Because a parameter annotated as a part of the _contract_ still modifies the request target. To me "if there is a need" and if there is a `java.net.URI` in the parameter list are not equivalent.

**Comment by kdavisk6** [comment]
It explains the behavior you are seeing and gives you context.  The documentation explicitly states that using `java.net.URI` parameters will modify the request target.  If this is not appropriate for your use case, you will need to use something other than a `java.net.URI`.
