### ISSUE TITLE
Update Apache HttpClient to latest version

### ISSUE THREAD

**Issue by mxmlnglt** [OpenFeign/feign#1080]
Hello,

I discovered that the version of Apache HttpClient used by (Open)Feign is only the 4.5.3 - see https://github.com/OpenFeign/feign/blob/master/httpclient/pom.xml - which is more than 2 years 1/2 old:
> 27 January 2017 - HttpComponents HttpClient 4.5.3 (GA) released
This is a maintenance release that fixes a number of issues discovered since release 4.5.2.

While the 4.5.10 (GA) has just been released: https://hc.apache.org/news.html

Could you please update? Thanks.

**Comment by velo** [comment]
Hi Maxine,

Sure thing, send us a PR and I will review it asap

**Comment by mxmlnglt** [comment]
Note: I'm currently trying to replace (old) API calls with OpenFeign (through Spring Cloud) on a project (already) using Apache HttpClient (in v4.5.9); thus I want to make sure I don't downgrade it.

**Comment by velo** [comment]
Fwiw, you can overwrite the version of Apache http client by declaring the dependency on your project. Same is true for all feign dependencies

**Comment by velo** [comment]
Feign 10.5.1 is released with this changed. Closing this ticket.
