### ISSUE TITLE
encoded-option in @Param annotation does nothing?

### ISSUE THREAD

**Issue by MartinDevillers** [OpenFeign/feign#1087]
I believe the `encoded` option in the `@Param` annotation does nothing. Regardless whether I set the value to `false` or `true`, my input is always encoded again (which in my use case is undesirable).

Browsing around this repository, I can see the value being read in the `Default` implementation of the `Contract` interface, and then being added to the `indexToEncoded` variable in the `MethodMetadata` class. But, from there I cannot find any code that actually reads this value.

https://github.com/OpenFeign/feign/blob/c7d8f0ec1d57dd01bd72e063ab743ec7d6630753/core/src/main/java/feign/Param.java#L44

https://github.com/OpenFeign/feign/blob/c7d8f0ec1d57dd01bd72e063ab743ec7d6630753/core/src/main/java/feign/Contract.java#L272

https://github.com/OpenFeign/feign/blob/c7d8f0ec1d57dd01bd72e063ab743ec7d6630753/core/src/main/java/feign/MethodMetadata.java#L138

**Comment by kdavisk6** [comment]
@MartinDevillers 

`encoded` has been maintained for backward compatibility and should be deprecated.  We no longer need it as values that are already pct-encoded should be identified during expansion and passed through without any changes.  #1096 does indicate that there are some cases where we are not correctly identifying provided pct-encoded values.  I'll relate these two for investigation.

**Comment by kdavisk6** [comment]
We have marked this as parameter `deprecated` for now.  We will continue to look into a fix for `10.7`

**Comment by kdavisk6** [comment]
As noted in #1108, the `encoded` property has been deprecated.  In addition #1138 corrects our issues detecting fully and partially encoded values.
