### ISSUE TITLE
Feign 10.5.0 uses class file format 53.0 (Java 9)

### ISSUE THREAD

**Issue by breun** [OpenFeign/feign#1088]
Upgrading `feign-bom` from 10.4.0 to 10.5.0 on a Java 8 project (https://github.com/bolcom/katalog/pull/132) causes this exception on startup:

```
java.lang.UnsupportedClassVersionError: feign/slf4j/Slf4jLogger has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This suggests `feign.slf4j.Slf4jLogger` was built using Java 9 (class file version 53.0). According to https://github.com/OpenFeign/feign#java-version-compatibility Feign 10.x should be compatible with Java 8.

**Comment by velo** [comment]
Ouch, I did cut a release yesterday and saw a weird output during release related to java11 module, but seemed fine. I did some checking and all looking ok.

Seems I it's no, I it could a 10.5.1 release to fix this.

**Comment by velo** [comment]
Done, 10.5.1 is out
https://travis-ci.org/OpenFeign/feign/jobs/592797588

**Comment by breun** [comment]
Thanks, seems to work!
