### ISSUE TITLE
GET method with @RequestLine @Param containing a question mark (/index.php?/) is converted to POST

### ISSUE THREAD

**Issue by iNTEAM** [OpenFeign/feign#1089]
Hi.
I came from https://github.com/OpenFeign/feign/issues/838
This has been fixed in https://github.com/OpenFeign/feign/pull/841

When i use the code from last comment:

```
@RequestLine(value = "GET /index.php?/api/v2/get_tests/{runId}")
    @Headers({
            "Content-Type: application/json",
            "Accept: */*",
    })
    Test[] getTestsByRunId(@Param(value = "runId") Integer runId);
```

i get the following error even though i use the **GET** method (hide server & Authorization string):
````
 [feign.Logger] ---> GET https://testrail.server.domen/testrail/index.php?/api/v2/get_tests/999 HTTP/1.1
[feign.Logger] Accept: */*
[feign.Logger] Authorization: Basic *hidden*
[feign.Logger] Content-Length: 13
[feign.Logger] Content-Type: application/json
[feign.Logger] 
[feign.Logger] {"runId":999}
[feign.Logger] ---> END HTTP (13-byte body)
[feign.Logger] <--- HTTP/1.1 404 File Not Found (974ms)
[feign.Logger] connection: keep-alive
[feign.Logger] content-length: 61
[feign.Logger] content-type: application/json; charset=utf-8
[feign.Logger] date: Thu, 03 Oct 2019 08:58:19 GMT
[feign.Logger] server: nginx/1.10.2
[feign.Logger] x-powered-by: PHP/5.4.45
[feign.Logger] 
[feign.Logger] {"error":"Unsupported HTTP method \"post\" for this action."}
[feign.Logger] <--- END HTTP (61-byte body)
```

**Comment by scrat98** [comment]
@iNTEAM I think the problem is not that GET method converted to POST, but the problem that GET method will have body in request(Content-Length: 13; END HTTP (13-byte body)) and web server can't handle GET method with body parameters. I have written about that problem here and suggested a workaround.
https://github.com/OpenFeign/feign/issues/1038

**Comment by kdavisk6** [comment]
@iNTEAM 

I suspect your issue is the presence of the `Content-Type` header.  That indicates a POST request.  Have you tried without the `Content-Type` header?  `GET` requests do not require that header.

**Comment by iNTEAM** [comment]
@kdavisk6
Hi, i removed this header but now i get error `{"error":"Content-Type header invalid (use Content-Type: application\/json)"}`

**Comment by iNTEAM** [comment]
@scrat98 
Hi. Your workaround works well, thank you.

But still i want to get a fix for this
-------------------------------------
I use CustomInterceptor
`public class CustomFeignInterceptor implements RequestInterceptor {

    @Override
    public void apply(RequestTemplate template) {
        val method = Request.HttpMethod.valueOf(template.method());
        if (method == Request.HttpMethod.GET) {
            template.body(Request.Body.empty());
        }
    }
}`

and usage
`feignBuilder = Feign.builder()
        .encoder(new FormEncoder(new JacksonEncoder(objectMapper)))
        .logLevel(Logger.Level.FULL)
        .requestInterceptor(new CustomFeignInterceptor())
        .decoder(new JacksonDecoder(objectMapper))
        .logger(new Slf4jLogger());`

**Comment by kdavisk6** [comment]
@iNTEAM 

By using the `FormEncoder` your requests will have the parameters encoded into the request body.  That's the intent of that encoder.  I recommend not using the `FormEncoder` unless you **want** to support `application/x-www-form-urlencoded` POST requests.

I've looked into the related issue however; and it appears to be a bug.

**Comment by iNTEAM** [comment]
@kdavisk6 i use [this](https://github.com/OpenFeign/feign-form) example but get an error:
```
Content-Type header invalid (use Content-Type: application\/json)
```
i try next scenarios but get same error:
1. Use POST
2. update versions of all feign libraries

Here is my API:
```
public interface CasesControllerApi {
    @RequestLine(value = "GET /index.php?/api/v2/get_tests/{runId}")
    @Headers({"Content-Type: application/x-www-form-urlencoded"})
    Test[] getTestsByRunId(@Param(value = "runId") Integer runId);
}
```
my feignBuilder:
```
        feignBuilder = Feign.builder()
                .encoder(new FormEncoder(new JacksonEncoder(objectMapper)))
                .decoder(new JacksonDecoder(objectMapper))
                .logger(new Slf4jLogger());
```
Log:
```
---> GET https://myurl.com/testrail/index.php?/api/v2/get_tests/999 HTTP/1.1
Content-Length: 9
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

runId=999
---> END HTTP (9-byte body)
<--- HTTP/1.1 400 Bad Request (771ms)
connection: keep-alive
content-length: 77
content-type: application/json; charset=utf-8
server: nginx/1.10.2
x-powered-by: PHP/5.4.45

{"error":"Content-Type header invalid (use Content-Type: application\/json)"}
<--- END HTTP (77-byte body)
```

**Comment by kdavisk6** [comment]
I found the issue.  The code we have was only evaluating template variables on a query string when they are present in the query parameter value part of the expression.  We were not accounting for expressions that occur in the query parameter name portion, which is how query expressions presented in this issue get processed.  This is due to the fact that we expect `name=value` pairs on a query string when parsing.

I will work on a fix and present a PR shortly.
