### ISSUE TITLE
Incorrect encoding of %A[0-9] sequences

### ISSUE THREAD

**Issue by akrikheli** [OpenFeign/feign#1096]
**Feign 10.x**

I have a simple Feign proxy interface in my service named "facade" that just redirects requests to another service. The simple interaction of components looks like this:

_Facade Controller_ -> _CisServiceProxy_ -> FEIGN (HTTP-request) -> _Another Service Controller_

**CisServiceProxy.java**
```java
String findByCisId(@RequestParam("cisId") String cisId)
```
I'd like to pass this string as the cisId parameter: %A1 (without additional encoding, how it looks actually). 

>curl -X GET "http://127.0.0.1:8095/api/v3/facade/cis/info?cisId=%25A1" -H "accept: */*"

Facade controller logs:
>#getCisInfo: started with cisId = **%A1**

But the logs of Another Service Controller were surprised me!
>#getCisInfo: started with cisId=�

When I was researching this behaviour I noticed the code of class feign.template.UriUtils and pattern PCT_ENCODED_PATTERN that's used to determine if the value is already pct-encoded. 

```java
private static final Pattern PCT_ENCODED_PATTERN = Pattern.compile("%[0-9A-Fa-f][0-9A-Fa-f]");
```
So, how can I forward parameters that match this pattern "in original"?

**Comment by kdavisk6** [comment]
@akrikheli 

Your example should be identified as already encoded.  We will need to look into this further.

**Comment by kdavisk6** [comment]
See #1138.  This should correct this issue.
