### ISSUE TITLE
Fixing typo in Contract interface

### ISSUE THREAD

**Issue by cezar-tech** [OpenFeign/feign#1097]
Hello, I'm very new to open source programming but I have some experience with java.
I use some of OpenFeign in my project and thought I could start contributing somehow.

I saw this TODO over here and thought that maybe I can help.

What do you think of deprecating the methods with typo and redirecting them to a new method correctly spelled ?

Like this:
![image](https://user-images.githubusercontent.com/56096912/66968496-c89e0480-f05b-11e9-9e9b-b683928118b5.png)

**Comment by cezar-tech** [comment]
I could also go around the project and replace all deprecated usages

**Comment by velo** [comment]
A few API goes deprecated on feign 10, so, this ones we need to keep.

But, not the case for the example you posted, so feel free to make a PR fixing that one.

**Comment by cezar-tech** [comment]
@velo 
Created: https://github.com/OpenFeign/feign/pull/1098/files

**Comment by velo** [comment]
pr merged and new release is out.
