### ISSUE TITLE
Query parameter value with ":" (colon) is not encoded

### ISSUE THREAD

**Issue by philippeu** [OpenFeign/feign#1102]
with openfeign 10.2.3

query parameter value with ":" is not encoded , e.g. "url=http://toto.com" produces "url=http:%2F%2Ftoto.com" instead of "url=http%3A%2F%2Ftoto.com".
what i understand from [rfc3986 section 2.2](https://tools.ietf.org/html/rfc3986#page-12) is that ":" should be encoded

> URI producing applications should percent-encode data octets that
   correspond to characters in the reserved set unless these characters
   are specifically allowed by the URI scheme to represent data in that
   component.  If a reserved character is found in a URI component and
   no delimiting role is known for that character, then it must be
   interpreted as representing the data octet corresponding to that
   character's encoding in US-ASCII.

Note that ":" was encoded in openfeign 10.1.0.

Seems related to refactor done in `FragmentType` [UriUtils.java](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/template/UriUtils.java)

**Comment by kdavisk6** [comment]
@philippeu 

This appears to be an issue with our URI template encoding.  I'll mark it as a bug and related it to #1019
