### ISSUE TITLE
Is there a way to enable sending empty headers as well?

### ISSUE THREAD

**Issue by tolvaly** [OpenFeign/feign#1109]
It says like this in the documentation:
> **Request Headers Expansion**
> Headers and HeaderMap templates follow the same rules as Request Parameter Expansion with the  following alterations:
> 
> * Unresolved expressions are omitted. If the result is an empty header value, the entire header is removed.

The problem is, I need to send empty POST message to a 3rd-party api, and that one returns a 411 error, which means they require a Content-Length to be set. 
I tried many possibilities to force the "Content-Length: 0" to be sent to the client, but every time is ignored:
Tried:
- Setting @Headers 
- Setting @Body("")
- Writing a request interceptor and setting the header in that one

Is there a way that I could send that header?
I use Spring cloud Greenwich.M3 and spring-cloud-openfeign 2.1.0.M2

**Comment by kdavisk6** [comment]
How `Content-Length` is set depends on the underlying `Client`.  If you are using our `ApacheHttpClient`, `Content-Length` will be set automatically.  If you are using our default `Client` or `OkHttpClient`, you may need to set it explicitly.

Another option is to ensure that you are using the latest versions of those dependencies.  Spring Cloud is at Greenwich SR3.
