### ISSUE TITLE
Resilience4J Support

### ISSUE THREAD

**Issue by pwlan** [OpenFeign/feign#1110]
It says in the README.md that support for Resilience4J is part of the long term plan.
FYI there is already support for feign in the Resilience4J project.

**Comment by dharmeshjogadia** [comment]
Hi @pwlan 
Resilience4j has released support for feign with resilience4j. 
Please have a look [resilience4j-feign](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-feign)

**Comment by kdavisk6** [comment]
@pwlan 

We are aware of the that project.  Our goal here is to provide first party support for it, allowing it to take advantage of our latest features and changes when they are released.  Right now that project is 3 releases behind (as of this comment).  The result may be more of a partnership than ownership.

**Comment by pwlan** [comment]
Thanks for the update. That sounds great. I initialized the resilience4j-feign so if you ever nee help, let me know.
