### ISSUE TITLE
java9 requirement for jackson / httpclient binaries

### ISSUE THREAD

**Issue by mx1up** [OpenFeign/feign#1113]
hello,

i am using java 8 but when I add the feign's jackson or httpclient dependency, I get the following error:
`Caused by: java.lang.UnsupportedClassVersionError: feign/jackson/JacksonEncoder has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

it seems those jars are compiled for java 9? is this by intention or is it a bug? I got the jars from maven central.
is java 8 supported only for the core library?

cheers
matthias

**Comment by velo** [comment]
It was a bad release.

Move to 10.5.1

https://github.com/OpenFeign/feign/issues/1088

**Comment by mx1up** [comment]
thanks! i checked the bug database but must have excluded the closed bugs :/ sorry for the noise

**Comment by velo** [comment]
Not a problem
