### ISSUE TITLE
Exception in thread "main" feign.RetryableException: connect timed out executing GET

### ISSUE THREAD

**Issue by ffroliva** [OpenFeign/feign#1119]
Hi there,

I have the following code and I am behind a _proxy_ access to the internet. 

Do I need to configure a proxy inside `Feign.builder()`?
```
interface ViaCep {

    @RequestLine("GET /ws/{cep}/json")
    @Headers({"Content-Type: application/json"})
    Address getAddress(@Param("cep") String cep);
}

public class MyApp {

    private static final Logger log = LoggerFactory.getLogger(MyApp.class);

    public static void main(String[] args) {
        Address address = Feign.builder()
                .decoder(new GsonDecoder())
                .target(ViaCep.class, "https://viacep.com.br")
                .getAddress("71680389");

        log.info(address.toString());

    }
}
```
Thank you for the help in advance.

**Comment by ffroliva** [comment]
Hi, I was able to make it run behind the proxy using VM Options `-Dhttps.proxyHost=<proxy server> -Dhttps.proxyPort=<proxy server port>`

**Comment by kdavisk6** [comment]
@ffroliva 

You have two options, first is the one you've already discovered, use the JDK's proxy system properties.  Another is to use Feign's `Proxied` Client in place of the default client.  You can configure this client via the builder.  Just provide a new instance of it with your proxy settings and they will be used.
