### ISSUE TITLE
Do you support webflux now?

### ISSUE THREAD

**Issue by cashZhang27** [OpenFeign/feign#1120]
I see a feign-reactive-wrappers module, but the reactive execution support via Reactive Streams written in the medium-term plan, So can feign-reactive-wrappers use webflux? Support for webclient and non-blocking?

**Comment by kdavisk6** [comment]
WebFlux is a Spring construct and not really in the purview of OpenFeign.  You can see there has been some discussion on how best to provide fully-reactive support [in this issue](https://github.com/spring-cloud/spring-cloud-openfeign/issues/4) and, as you've seen, it is on [our roadmap](https://github.com/OpenFeign/feign/wiki/Feign-11-Proposed-Roadmap).

Spring has chosen to wait until we can support reactive execution natively before adapting WebFlux.  That is all the information I have at this time.  I hope this helps.

**Comment by MephistoLynn** [comment]
2020 says hello .For now does openFeign still not support webflux ? Do you know when Spring will not choose to wait it ?

**Comment by velo** [comment]
> 2020 says hello .For now does openFeign still not support webflux ? Do you know when Spring will not choose to wait it ?

Hi @MephistoLynn , yeah, 2020 and we are still waiting for pull request to such trivial feature. Maybe, you could show everybody how is done.

Cheers mate!

**Comment by kdavisk6** [comment]
Shore answer is, it's coming.  For now, since you are using Spring Cloud, feel free to use the community project here: https://github.com/kptfh/feign-reactive
