### ISSUE TITLE
feign 直连方式调用问题

### ISSUE THREAD

**Issue by xue8** [OpenFeign/feign#1122]
怎么通过直连的方式使用 feign，我在 `@FeignClient` 中指定了 url，但是 feign 在调用的时候还是使用了负载均衡的方式去获取服务，导致了 `Load balancer does not contain an instance for the service  xxx` 的问题，通过调试发现是在 `org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient` 这里的 `execute` 方法调用了 `ServiceInstance instance = loadBalancerClient.choose(serviceId);` 查找相应的服务提供者，找不到所以出错了。但是不是在 `@FeignClient` 中指定了 url 就会通过直连的方式请求了吗，这是什么问题呢？
具体代码如下：
```
@Service
@FeignClient(url = "xxx", name = "aaa")
public interface ProjectServiceFeign {

    @GetMapping(value = "/question")
    Project.Summary getSummary();
}

@SpringBootTest
@EnableFeignClients
class CcloudServerContainerApplicationTests {
    @Autowired
    ProjectServiceFeign projectServiceFeign;

    @Test
    void contextLoads() {
        Project.Summary summary = projectServiceFeign.getSummary();
    }

}
```

**Comment by velo** [comment]
Please reopen the question in English

**Comment by tudan110** [comment]
> 怎么通过直连的方式使用 feign，我在 `@FeignClient` 中指定了 url，但是 feign 在调用的时候还是使用了负载均衡的方式去获取服务，导致了 `Load balancer does not contain an instance for the service xxx` 的问题，通过调试发现是在 `org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient` 这里的 `execute` 方法调用了 `ServiceInstance instance = loadBalancerClient.choose(serviceId);` 查找相应的服务提供者，找不到所以出错了。但是不是在 `@FeignClient` 中指定了 url 就会通过直连的方式请求了吗，这是什么问题呢？ 具体代码如下：
> 
> ```
> @Service
> @FeignClient(url = "xxx", name = "aaa")
> public interface ProjectServiceFeign {
> 
>     @GetMapping(value = "/question")
>     Project.Summary getSummary();
> }
> 
> @SpringBootTest
> @EnableFeignClients
> class CcloudServerContainerApplicationTests {
>     @Autowired
>     ProjectServiceFeign projectServiceFeign;
> 
>     @Test
>     void contextLoads() {
>         Project.Summary summary = projectServiceFeign.getSummary();
>     }
> 
> }
> ```

最后怎么解决的？

**Comment by velo** [comment]
> 最后怎么解决的？

Quarta nao eh dia de feira.

**Comment by tudan110** [comment]
我也遇到了这个问题，发现是项目中引入了 sleuth 导致的，所以在本地调试的时候，把sleuth改成了false，以避免此问题的出现。

I also ran into this problem, and found that it was caused by the addition of sleuth to the project, so when debugging locally, I changed sleuth to false to avoid this problem.
