### ISSUE TITLE
Feign can not handle `;` correctly

### ISSUE THREAD

**Issue by aftersss** [OpenFeign/feign#1123]
spring-cloud version: Greenwich.SR3
spring-boot-version: 2.1.9.RELEASE

I wrote the following feign interface:

```
@FeignClient(name = "test")
@RequestMapping("/test")
public interface RemoteService  {


    @RequestMapping(path="str", method = RequestMethod.POST)
    String str(@RequestParam("str") String str);

    @RequestMapping(path="list", method = RequestMethod.POST)
    List<String> list(@RequestParam("list") List<String> list);

}

@RestController
public class RemoteServiceImpl implements RemoteService   {
    public String str(String str){
        return str;
    }

    public List<String> list(List<String> list){
        return list;
    }
}
```

and then invoke it via feign like this:

Case 1 :

```
        String ret = remoteService.str("hello;world");
        //the expected output should be:`hello;world` , but actually I got:`hello,world`, 
        System.out.println(ret);
```
the expected output should be:`hello;world` , but actually I got:`hello,world`, 

Case 2:
```
        List<String> list = new ArrayList<>();
        list.add("hello;world");
        String retList = remoteService.list(list);
        //the expected output should be:`["hello;world"]` , but actually I got:`["hello", "world"]`, 
        System.out.println(retList);
```

the expected output should be:`["hello;world"]` , but actually I got:`["hello", "world"]`, 

See also: https://github.com/spring-cloud/spring-cloud-openfeign/issues/246

**Comment by kdavisk6** [comment]
Hi @aftersss 

Thank you for bringing this to our attention.  This is a known issue related to our template handling.  We are working on a fix for this, however; in the meantime, you will need to pct-encode the semi-colon `;` as `%3B` wherever you need to use the character.  This tell Feign to treat the value as a single value and not a list of values.

For more information on the underlying problem, see these other issues:

- #1102 - Query parameter value with ":" (colon) is not encoded
- #1096 - Incorrect encoding of %A[0-9] sequences
- #1019 - Support additional URI Template Levels
