### ISSUE TITLE
How can I use BasicAuthRequestInterceptor for single client

### ISSUE THREAD

**Issue by taylancapraz** [OpenFeign/feign#1124]
Hi,

I am currently working on a spring boot project and using feign client. There are multiple feign clients and one of them requires basic authentication, others do not.

I don't want to add the header as @RequestHeader to all methods individually. Therefore I'm using BasicAuthRequestInterceptor. However, when I create BasicAuthRequestInterceptor as bean, it is applied to each feign client.

Is it possible to apply this interceptor to only one client?

Thanks

My BasicAuthRequestInterceptor
```
@Configuration
class FeignClientConfiguration {
    @Bean
    fun basicAuthRequestInterceptor(): BasicAuthRequestInterceptor {
        return BasicAuthRequestInterceptor("admin", "admin")
    }
}
```

My Feign Client
```
@FeignClient(name = "xxxxxxx", url = "\${xxxxxxx.server.url}", configuration = [FeignClientConfiguration::class])
interface XXXXXXClient : INodeClient 
```
I want this interceptor to be applied to client with configuration = [FeignClientConfiguration::class]), not all clients.

**Comment by taylancapraz** [comment]
When FeignClientConfiguration is excluded from ComponentScan, it worked. 

Solution is as below:
```
@ComponentScan(excludeFilters = [ComponentScan.Filter(
    type = FilterType.ASSIGNABLE_TYPE,
    classes = [FeignClientConfiguration::class]
)])
```

**Comment by sharovse** [comment]
Or will need remove @Configuration from FeignClientConfiguration
