### ISSUE TITLE
Method declaration doesn't support multiple @PathVariable annotations

### ISSUE THREAD

**Issue by sheldon-white** [OpenFeign/feign#1128]
(This is using feign-core 10.6.0)

If I declare a method like this:
```
    @RequestLine("GET /records/{recordId}/version/{version}")
    void getRecord(@PathVariable Long recordId, @PathVariable Long version);
```

I get the exception:
java.lang.IllegalStateException: Method has too many Body parameters: public abstract void classpath.getRecord(java.lang.Long,java.lang.Long)
at feign.Util.checkState(Util.java:130)
at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:124)
at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:62)
...(many lines omitted)...

I've also tried:

```
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    void getRecord(@PathVariable("id") Long recordId, @RequestParam(value = "version") Long version);
```
But I get:
"java.lang.IllegalStateException: Method classpath.getRecord(java.lang.Long,java.lang.Long) not annotated with HTTP method type (ex. GET, POST)\n\tat feign.Util.checkState(Util.java:130)\n\tat feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:100)\n\tat feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:62)\n\tat 

Are there some other annotations I should be using? I couldn't find any examples on the internet matching my situation.

Thanks in advance.

**Comment by velo** [comment]
Could you please confirm the import for `@PathVariable`?

**Comment by sheldon-white** [comment]
In my source file:
```
import feign.Headers;
import feign.RequestLine;
import org.springframework.web.bind.annotation.*;
```
I'm not certain if this is what you're asking.

**Comment by kdavisk6** [comment]
How are you creating the Feign client?  Do you know which Contract you are using?

**Comment by velo** [comment]
Seems you are mixing feign and spring annotations. Try using @param and you should be good to go.

**Comment by sheldon-white** [comment]
Thanks! Using @Param annotations worked. Thanks a lot for your assistance!
