### ISSUE TITLE
Body Template Expansion with nested JSON

### ISSUE THREAD

**Issue by garcia-jj** [OpenFeign/feign#1129]
When I'm trying to upgrade from Feign 10.2.0 to 10.7.0 I'm facing an error to decode my body template.

The needed literal JSON is: 
```
{"resize": {"method": "fit","width": 150,"height": 150}}
```

So I wrote the method as:
```
@Body("%7B\"resize\": %7B\"method\": \"fit\",\"width\": {size},\"height\": {size}%7D%7D")
void resize(@Param("file") String file, @Param("size") int size, @Param("target") String target);
```

It works fine. But during the upgrate to 10.7.0 I got the following JSON:
```
{"resize": %7B"method": "fit","width": 150,"height": 150%7D}
```

As I see, the 10.7.0 are not expanding JSON escape as 10.2.0. This behavior may be introduced with this change: #931

**Comment by kdavisk6** [comment]
This appears to be a gap in our test coverage.  Thank you for reporting this.

**Comment by kdavisk6** [comment]
@garcia-jj This has been fixed and published to OSS as a SNAPSHOT.  If you would like, you can test using version 10.7.1-SNAPSHOT
