### ISSUE TITLE
Read-me.md   mybe wrong ?

### ISSUE THREAD

**Issue by switchYello** [OpenFeign/feign#1131]
```
jdk 11
Feign 10.7.0
```

I read `README.md`,it has this description,

	What about slashes? /
	@RequestLine and @QueryMap templates do not encode slash / characters by default. 
	To change this behavior, set the decodeSlash property on the @RequestLine to false.

My understanding is `@QueryMap` will not encode `slash` to `%2F`, but in my test cast,`/` still encoded to `%2F`。

### my code
```java
 interface Fq {
        @RequestLine(value = "GET /product/item")
        String getItemCoupon(@QueryMap Map map);
    }

public static void main(String... args) {
        Fq target = Feign.builder()
                .logger(new Slf4jLogger())
                .logLevel(Logger.Level.FULL)
                .target(Fq.class, "http://localhost");

        Map<String, Object> map = new HashMap<>();

        map.put("d", "1+1");
        map.put("e", "1/4");
        String itemCoupon = target.getItemCoupon(map);
}


```

### result
```java
20:37:38.541 [main] DEBUG feign.Logger - [Fq#getItemCoupon] ---> GET http://localhost/product/item?d=1%2B1&e=1%2F4 HTTP/1.1

```

may i has misunderstanding ? thinks

**Comment by kdavisk6** [comment]
That does appear to be incorrect.  Encoding is consistent across the entire application.  Please feel free to open a PR to correct if you have time.
