### ISSUE TITLE
how feign client force network card when feign client  run on a server that has two network card?

### ISSUE THREAD

**Issue by wukongcxy** [OpenFeign/feign#1150]
feign client server ipconfig
ens33: 172.XX.XX.XX(rigint ip)
eth0:10.X.X.X（private ip，i can't connect）

feign client register eureka server use eth0 ip（private ip）
i can get application config from eureka server but i can't connect feign client with eth0 ip。

how feign client force network card use ens33 ip?

**Comment by velo** [comment]
hi @wukongcxy well... feign per say don't know anything about that.

Would would need to setup the http client to work that way. Which of the feign clients are you using? And how would you do that using the vanilla http client w/o feign?

**Comment by wukongcxy** [comment]
> hi @wukongcxy well... feign per say don't know anything about that.
> 
> Would would need to setup the http client to work that way. Which of the feign clients are you using? And how would you do that using the vanilla http client w/o feign?

i read the code of how product registy to eureka server and find use inetutiles to post itself info into eureka。inetutiles has a parameter that can ignore network card， so this problem is gone。
config：spring.cloud.inetutiles.ignored-interfaces: - eth0
I hope this config work well for others!
