### ISSUE TITLE
How to get http status code

### ISSUE THREAD

**Issue by carlos12silva94** [OpenFeign/feign#1159]
Hi. Im having a empty response, so what i need to get to know if the request went well is the http status code. However i cant get it and i cant find more information about how to do it on the web.

**Comment by nmaoez** [comment]
You could use a custom `ErrorDecoder`. See [Custom error handling](https://github.com/OpenFeign/feign/wiki/Custom-error-handling)

**Comment by carlos12silva94** [comment]
I've used Response class
