### ISSUE TITLE
Using query param always returning 500 status code

### ISSUE THREAD

**Issue by carlos12silva94** [OpenFeign/feign#1166]
Hi, im using a query param like this one for example:
`@Headers("Content-Type: application/json;")`
`@RequestLine("GET /v1/endpoint?phone={phoneNumber}")`
`public Response checkStuff(@HeaderMap Map<String, Object> headerMap, @Param("phoneNumber") String ph);`

however im always getting 500 status code.
In postman the endpoint is working fine. The headermap is just to set the api key.
I already used this approach in another api and it worked, so i dont know what to do now.

**Comment by kdavisk6** [comment]
I would suggest turning on logging to see what is being resolved and sent.

**Comment by carlos12silva94** [comment]
It was a server side error
