### ISSUE TITLE
NullPointerException when calling decodeSlash of RequestTemplate

### ISSUE THREAD

**Issue by NikDz** [OpenFeign/feign#1167]
Hello there, 

I'm getting a NullpointerException when calling the method decodeSlash of feign.RequestTemplate.
The Exception raises because the RequestTemplate tries to construct a new UriTemplate Object from the old one, but there is no old UriTemplate. So the call of uriTemplate.toString() fails in decodeSlash.

I'm implementing a BaseContract class (or am extending SpringMvcContract to be precise) for changing the behaviour of Feign Clients through my own annotations. Therefore I'm calling decodeSlash of the feign.RequestTemplate class during my overwritten method processAnnotationOnClass in my own class. That produces said NullpointerException.

As far as I understand it, there is no need to execute that construction of a new UriTemplate Object as long as there is no initial UriTemplate, so a simple check for null in decodeSlash should solve that problem.

I tried to call super.processAnnotationOnClass before using decodeSlash as workaround to initialize the uriTemplate, but this will only work when the Interface itself is annotated with RequestMapping, otherwise it has no effect.

But there is another workaround for this: calling the method uri("", true) initializes the uriTemplate and the following call for decodeSlash works fine. There seems to be no side effect by that solution.

I'm using feign-core 10.2.3, that comes with spring-cloud-starter-openfeign 2.1.3.RELEASE

I hope that information is useful.

**Comment by kdavisk6** [comment]
Please try the latest release and if the issue persists, can you please provide a minimal working example that demonstrates the issue?

**Comment by NikDz** [comment]
Could not reproduce it with the latest release. Thanks.
