### ISSUE TITLE
Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by carlos12silva94** [OpenFeign/feign#1171]
Invalid HTTP method: PATCH executing PATCH https://......

`@RequestLine("PATCH /v1/api/customers?customerId=1)`

How can I solve this?

**Comment by kdavisk6** [comment]
This issue does not have enough information.  Please update this issue with the following:

* A brief description of what you are trying to do.
* Expected vs Actual outcome
* A minimum working example demonstrating the issue.

**Comment by carlos12silva94** [comment]
Basically i'm calling a parter api, that requires to do a PATCH to https://domain.com/v1/user/1.

in my code i basically have something like this, for example:
`@RequestLine("PATCH v1/user/1?customerId=1)`

When I call the method that do this request, i got that error exception:  
Invalid HTTP method: PATCH executing PATCH https://......

When i debug in your Client.java, i see that PATCH http method is not in the list of the methods allowed by HTTPUrlConnection.

I'm using the v 8... But i already tried the most recent one, and the problem persists. I tried to do a simple HTTPUrlConnection without feign  (https://stackoverflow.com/posts/46323891/revisions) and it worked. However i would like to have this working with feign.

**Comment by velo** [comment]
Can you attach the stack trace? Preferably on a more recent version of feign, as I'm very unlikely to troubleshoot feign 8.

**Comment by carlos12silva94** [comment]
The only thing i got in the stack trace is this:
Invalid HTTP method: PATCH executing PATCH https://......

I wasn't able to active the logs in debug level :(

**Comment by velo** [comment]
Plan B, submit a unit test that demonstrates the problem. To the best of my knowledge PATCH just works

**Comment by carlos12silva94** [comment]
In my routes file:
`@RequestLine("PATCH /v1/applications/stuff/customers?country=PT&id={id}")
	public Response getMyMethod(@HeaderMap Map<String, Object> headerMap, @Param("id") String id);`

Then i call this method, in the map i just pass the API key.

and I just get that message. No more information i can give to you

**Comment by sivaprakasht** [comment]
I have come across this issue recently.
The Default client (Default implements Client) is using HttpsURLConnection in which the valid HTTP methods are 
` private static final String[] methods = {
        "GET", "POST", "HEAD", "OPTIONS", "PUT", "DELETE", "TRACE"
    };`
PATCH is not in the list, results the exception. Feign had nothing to with the issue.

I am using ApacheHttpClient for PATCH Requests now.

**Comment by kdavisk6** [comment]
For those that find this, `PATCH` is not supported using `HttpUrlConnection` or `HttpsUrlConnection` and will not be supported: https://bugs.openjdk.java.net/browse/JDK-7016595

However, we can update our `java11` module to include a standard `HttpClient` in addition to our `Http2Client` implementation for those on JDK9+

**Comment by kdavisk6** [comment]
Created #1348 for the `HttpClient` enhancement.
