### ISSUE TITLE
Can't resolve body param in AQL request

### ISSUE THREAD

**Issue by eSerpentine** [OpenFeign/feign#1175]
Hey, I'm migrating from feign 9.5.0 to 10.4.0, and I found a problem. I have [AQL](https://www.jfrog.com/confluence/display/RTF/Artifactory+Query+Languag) request. In 9.5.0 it looks like this:
```java
@RequestLine("POST /api/search/aql")
@Headers([
      "Content-Type: text/plain",
      "Accept: application/json",
  ])
  @Body('''items.find(
%7B
"$and": [
%7B
"$or": [
%7B "repo": %7B "$match":"*release*" %7D%7D,
%7B "repo": %7B "$match":"*snapshot*" %7D%7D
]
%7D,
%7B"@platform.artifact-type" : %7B"$eq" : "service"%7D%7D,
%7B"@platform.deployment.app-name" : %7B"$match" : "{keyword}"%7D%7D,
%7B"@platform.deployment.id" : %7B"$match" : "*"%7D%7D,
%7B"@platform.label" : %7B"$match" : "*"%7D%7D,
%7B"@platform.artifact.group" : %7B"$match" : "*"%7D%7D,
%7B"@build.number" : %7B"$match" : "*"%7D%7D
]
%7D
)
.include(
"updated",
"name",
"repo",
"original_sha1",
"@platform.deployment.id",
"@platform.deployment.app-name",
"@platform.template.id",
"@build.number",
"@platform.label",
"@platform.artifact.group"
)
.limit({limit})''')
  ArtifactoryAQLClientResponse findByPlatformArtifactType(
      @Param('keyword') String keyword,
      @Param('limit') int limit)
```

Param "keyword" and "limit" successfully substitutes, and before sending request, feign decoded it with URLDecoder. 
After migrating to 10.4.0, this request havent decoded with URLDecoder, and have become rejected with 400 status from artifactory.
I change it to decoded form myself:

```java
@RequestLine("POST /api/search/aql")`
 @Headers([
      "Content-Type: text/plain",
      "Accept: application/json",
  ])
  @Body('''items.find(
{
"$and": [
{
"$or": [
{ "repo": { "$match":"*release*" }},
{ "repo": { "$match":"*snapshot*" }}
]
},
{"@platform.artifact-type" : {"$eq" : "service"}},
{"@platform.deployment.app-name" : {"$match" : "{keyword}"}},
{"@platform.deployment.id" : {"$match" : "*"}},
{"@platform.label" : {"$match" : "*"}},
{"@platform.artifact.group" : {"$match" : "*"}},
{"@build.number" : {"$match" : "*"}}
]
}
)
.include(
"updated",
"name",
"repo",
"original_sha1",
"@platform.deployment.id",
"@platform.deployment.app-name",
"@platform.template.id",
"@build.number",
"@platform.label",
"@platform.artifact.group"
)
.limit({limit})
  ArtifactoryAQLClientResponse findByPlatformArtifactType(
      @Param('keyword') String keyword,
      @Param('limit') int limit)
```

But after that, feign cannot resolve "keyword" param, and send it with "{keyword}" as is. But param "limit" have successfully resolved.

**Comment by eSerpentine** [comment]
Solve with such interceptor
`public class BodyEncoderInterceptor implements RequestInterceptor {

    @Override
    public void apply(RequestTemplate template) {
        String bodyString = new String(template.body(), StandardCharsets.UTF_8);
        String decoded = bodyString.replace("%7B", "{").replace("%7D", "}");
        template.body(decoded);
    }
}`

**Comment by kdavisk6** [comment]
I'll start by saying this is not really what the `@Body` annotation is meant for.  You will be much better served using a custom `Encoder` when dealing with a request body that complex.

Second,  please try the most recent version of Feign 10.7.  This issue should have been corrected recently.
