### ISSUE TITLE
Allow Overrides for Parameter Name when expanding Beans or POJO

### ISSUE THREAD

**Issue by boggard** [OpenFeign/feign#1183]
Now `FieldQueryMapEncoder` put request parameter with name equals to field name.

What about add some annotation to allow override parameter  name in query map?

Something like `@JsonAlias` in jackson.

**Comment by boggard** [comment]
The issue relates to `BeanQueryMapEncoder` too.

**Comment by kdavisk6** [comment]
Can you please add the following so we can understand your issue better. 

* expected behavior with observed behavior
* provide a minimum working example that demonstrates your issue

**Comment by boggard** [comment]
I provide pull request to show what i mean and how i see the implementation

**Comment by kdavisk6** [comment]
An update to this issue, the PR talks about allowing for an override to the naming scheme used by both the `FieldQueryMapEncoder` and `BeanQueryMapEncoder`, which are used when a Java Bean or POJO is being expanded as part of `@QueryMap` usage.

The suggestion from the maintainers is to use the `@Param` annotation and update the name resolution logic in both of the aforementioned encoders to honor the annotation if present.

**Comment by velo** [comment]
#1184
