### ISSUE TITLE
Get request Parse  method failed

### ISSUE THREAD

**Issue by KOkkmiao** [OpenFeign/feign#1186]
![open](https://user-images.githubusercontent.com/24602436/76291580-5bc82700-62e8-11ea-9bf7-847dcef36bfc.png)
Contract-->processAnnotationsOnParameter method
  data.formParams().add(name);
this Action is so lower,if  don't  contains  param please throws Exception.

**Comment by velo** [comment]
Sorry, I don't understand what is the problem and what you expect to be done about it.

**Comment by KOkkmiao** [comment]
my means this
![](https://i.bmp.ovh/imgs/2020/06/a6e5261449654d5a.png)

**Comment by kdavisk6** [comment]
This is not something that we plan on taking on.  Our opinion on this is that we will validate what is referenced.  If you add a parameter and don't reference it in the template, it will be ignored.
