### ISSUE TITLE
Method has too many Body parameters

### ISSUE THREAD

**Issue by Sakura0408** [OpenFeign/feign#1192]
Hi,I encountered an error→Method has too many Body parameters.
I want to use the feign client of project A to call the service of project B.
the project B interface:
![1](https://user-images.githubusercontent.com/42940527/76925387-3785cf00-6914-11ea-8d39-6b2a80fae047.png)
the project B implement:
![2](https://user-images.githubusercontent.com/42940527/76925399-3fde0a00-6914-11ea-986e-f249317ad504.png)
the project A feign client:
![3](https://user-images.githubusercontent.com/42940527/76925403-47051800-6914-11ea-91f6-85ec8de95e21.png)
help me please

**Comment by Sakura0408** [comment]
I know why this happened.Remove BindingResult then it works.
But i can't remove it because i need to do parameter verification.
Can you tell me how to use ie in SpringCloud Feign enviroment.

**Comment by 678yoyo** [comment]
How do you solve this problem？
