### ISSUE TITLE
OpenFeign 10.7.4, 10.7.3 and 10.8 break backward compatibility

### ISSUE THREAD

**Issue by sofax** [OpenFeign/feign#1194]
Updating from v10.7.2 to v10.7.3, v10.7.4 or v10.8 breaks existing code, because `Request.requestBody()` was removed. The following line won't compile anymore:

```
      final Request.Body body = request.requestBody();
```

**Comment by kdavisk6** [comment]
@sofax, that move was intentional.  `requestBody()` was an internal method that mistakenly was made public.  Use `Request#body`.

**Comment by sofax** [comment]
That means we will NEVER be able to update OpenFeign, because we deliver artifacts that MUST NOT break existing code with minor, or - as in this case - even patch level version upgrades.

Sorry, guys, this is very bad! :(

**Comment by velo** [comment]
hi @sofax feel free to submit a PR with a fix for this.

Keep in mind the method will be removed for feign 11.

**Comment by sofax** [comment]
We are more interested in bug fixes for the 10.x branch, not a major upgrade. Breaking the code with a patch release violates the idea of semantic versioning, which I thought/was hoping you are adhering to. If the exposition of an internal API in a previous release was an accident you should provide a workaround for it instead of just hiding it again, or you will make all upcoming bugfix releases unusable for most people.

We will (have to) stick with v10.7.2 then.

**Comment by velo** [comment]
> We will (have to) stick with v10.7.2 then.

Or, you can get the souces and submit a PR restoring the missing method.

Also, feel free to also include the necessary tooling to prevent API for ever being broken again.

**Comment by kdavisk6** [comment]
Closed by #1200
