### ISSUE TITLE
Why define HystrixFeign.Builder & HystrixInvocationHandler is final ?

### ISSUE THREAD

**Issue by fudali113** [OpenFeign/feign#1198]
https://github.com/OpenFeign/feign/blob/af74e131dcf9a79eaca1f5c3c5f87617dcdda72b/hystrix/src/main/java/feign/hystrix/HystrixFeign.java#L45

i want define a common cache for feign, i can use `invocationHandlerFactory()` in `Feign.Builder`  impl  this, but i can't do `invocationHandlerFactory()` in `HystrixFeign.Builder`

i know `HystrixFeign.Builder` need `FallbackFactory` to create `InvocationHandlerFactory`, but can we keep some API to extension `HystrixFeign` ?

**Comment by kdavisk6** [comment]
@fudali113 

Feign favors [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).  If you wish to extend any of our components that are marked `final`, I recommend using the [delegate pattern](https://en.wikipedia.org/wiki/Delegation_pattern).  The resulting code should implement the changes you want in only the areas necessary and then delegating the rest.

**Comment by fudali113** [comment]
> @fudali113 
> 
> 
> 
> Feign favors [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).  If you wish to extend any of our components that are marked `final`, I recommend using the [delegate pattern](https://en.wikipedia.org/wiki/Delegation_pattern).  The resulting code should implement the changes you want in only the areas necessary and then delegating the rest.

But i can't set invocationHandlerFactory on hystrixFeign when target method running

**Comment by kdavisk6** [comment]
If you are the point were you want to modify the `InvocationHandlerFactory` you are not extending but building a brand new implementation.  `InvocationHandlerFactory` is an internal api used by Feign to create JDK Proxies for the methods in the annotated interfaces and implementation specific, hence why it is marked `final`.  Any changes to it will break compatibility with the other internal apis that depend on it.

My I suggest a an alternative.  The simplest is to create a new `Feign` `Client` that contains a Cache instance.  Here is a quick example that uses JCache to get your started:

```java
import feign.*;
import javax.cache.*;

@NotThreadSafe
public class CachingClient implements Client {
   private final Client delegate;
   private final Cache cache;

   public CachingClient(Client delegate, Cache cache) {
      if (delegate == null) { 
           throw new IllegalArgumentException("delegate is required.");
      }
      if (cache == null) {
          throw new IllegalArgumentException("cache is required.");
      }
      this.delegate = delegate;
      this.cache = cache;
   }

   public Response execute(Request request, Options options) throws IOException {
      // use the cached copy
      Response response = this.cache.get(request);
      
      // not cached, execute the request
      if (response == null) {
         response = this.client.execute(request, options);
         this.cache.put(request, response);
      }
      return response
   }
}
```

This is a crude, yet complete example on how you can introduce caching into a Feign client without the need to modify the `HystrixCommand`  implementation.  Taking this approach, successful requests will be cached but unsuccessful will not, and the fallback will be triggered.

**Comment by kdavisk6** [comment]
Since this issue has not had any activity for a while, I'm going to close it.  If you have any additional feedback on how we may be able to implement this differently, please feel free to comment and reopen this issue.
