### ISSUE TITLE
Feign.Builder: decode404() with JacksonDecoder is no longer working since v10.3.0

### ISSUE THREAD

**Issue by gregoavg** [OpenFeign/feign#1199]
Since v10.3.0 the `JacksonDecoder` was changed to not perform decoding of 404 status code.
In particular this part was removed:
```java
    if (response.status() == 404)
      return Util.emptyValueOf(type);
```
After that, the combination is not anymore returning empty or null placeholders:
```java
Feign.builder()
    ...
    .decoder(new JacksonDecoder())
    .decode404();
```
Instead it's trying to deserialize the response body to the target object, causing mapping exceptions like:
```
feign.FeignException: Cannot construct instance of `[...].Group$Builder` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (404)
 at [Source: (BufferedReader); line: 1, column: 1] reading PUT https://service-domain/groups
    at feign.FeignException.errorReading(FeignException.java:120)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:157)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
    at com.sun.proxy.$Proxy84.update(Unknown Source)
```
**I'm using v10.5.1 and extracted the above scenario from that version.**

Is this something expected? Is there any defined workflow if one needs to maintain the previous behaviour and map 404 to emply placeholders?

For now I've created a wrapper around `JacksonDecoder` that is handling this case (delegating the rest to actual decoder), as it was happening before the change:
```java
 private static class JacksonDecoderBackport extends JacksonDecoder {
        // constructor not included for simplicity
        @Override
        public Object decode(Response response, Type type) throws IOException {
            if (response.status() == 404) {
                return Util.emptyValueOf(type);
            }
            return super.decode(response, type);
        }
    }
```

More information here:
[JacksonDecoder.java on < v10.3.0](https://github.com/OpenFeign/feign/blob/10.2.3/jackson/src/main/java/feign/jackson/JacksonDecoder.java#L48)
[JacksonDecoder.java on v10.3.0](https://github.com/OpenFeign/feign/blob/10.3.0/jackson/src/main/java/feign/jackson/JacksonDecoder.java#L48)

**Comment by kdavisk6** [comment]
@gregoavg 

This change is intentional.  The original logic violated the contract specified by the use of the `decode404` flag, which indicates that responses with a status of `404` **must** attempt decoding.  The Jackson Decoder, as you saw, was ignoring this flag.  

The intent here is for services that respond with data under a `404` condition still be decoded and returned to the caller.  If your intention is to receive `null` placeholder values, the use of our `Optional` decoder may be more appropriate.  You can update your builder and interface as such:

```java
interface Service {
   @RequestLine("/data")
   Optional<Data> request(@Body byte[] body);
}

Feign.builder()
    .decoder(new OptionalDecoder(new JacksonDecoder()))
    .build();
```

Using the above example, `404` responses are mapped to `Optional.empty()`, replicating the previous behavior.

**Comment by gregoavg** [comment]
Hi @kdavisk6,

Thanks for the info provided!

Currently we cannot change the client API methods to `Optional<Data>` due to compatibility issues, since most of the clients are utilizing the `Data` interfaces.

Moreover, the example provided is not completely replicateting the previous behaviour.
What about the methods that are using `Collection<Data>` signature? 

The `OptionalDecoder` won't handle the 404 case for them, it will delegate the actions to the new `JacksonDecoder` (as seen here: https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/optionals/OptionalDecoder.java#L36). Thus, you'll get the same exception instead of an empty collection.

For now moving into something like this, allows us to stay compatible:
```java
    final class DecoderWith404Support implements Decoder {
        private final Decoder delegate;
        public DecoderWith404Support(Decoder delegate) {
            Objects.requireNonNull(delegate, "Decoder must not be null. ");
            this.delegate = delegate;
        }

        @Override
        public Object decode(Response response, Type type) throws IOException {
            if (response.status() == HttpStatus.SC_NOT_FOUND) {
                return Util.emptyValueOf(type);
            }
            return delegate.decode(response, type);
        }
    }
```
Thank you very much for the explanation and guidance on how to upgrade client APIs to become compatible with the new `decode404` contract.

**Comment by kdavisk6** [comment]
@gregoavg 

Sorry I couldn't be more help here.  This is one of those situations where we decided to go with the simplest option; however it does have some limitations.  I appreciate the feedback and if you have any suggestions on how we can provide both the ability for users to override our default error handling and still provide the flexibility to decode or not to decode a response, we'd like to hear it.

**Comment by kdavisk6** [comment]
Since there hasn't been much movement on this and it appears you have found a workaround for your use case, I'm going to close this issue.  If you have any additional feedback on how this could be handled differently, please open a new feature request and we can continue the discussion there.
