### ISSUE TITLE
Cannot find feign-java11 artifact version newer than 10.5.0

### ISSUE THREAD

**Issue by pzapasni** [OpenFeign/feign#1202]
Hello,

I'm currently working on a Spring Boot + OpenFeign + Java 11 project. I wanted to use the Java 11 ``feign.http2client.Http2Client`` client from the ``io.github.openfeign:feign-java11`` artifact, however I was not able to find a version newer than [10.5.0](https://mvnrepository.com/artifact/io.github.openfeign/feign-java11/10.5.0). My OpenFeign dependencies are set by Spring Boot BOM to 10.7.4, and unfortunately due to changes in the ``feign.Request`` class this version does not work with ``feign-java11`` v. 10.5.0. I can see that in the [java11 subdirectory in this repo](https://github.com/OpenFeign/feign/tree/master/java11) there are newer versions, but they seem to be not released to Maven Central. Am I missing something here?

**Comment by velo** [comment]
Hi @pzapasni , there is something broken on our release process, as `feign-java11` should be on maven central.

I will investigate what is going on.

**Comment by velo** [comment]
The release script on travis is running just for java 8.

I will make sure the recent released versions of feign get the java11 module build and published on maven central.

Still, I'm not sure how to fix this for good.

**Comment by velo** [comment]
I batch released missing jars to maven central.

Should be available in a few hours

**Comment by velo** [comment]
Releases now on maven central
https://repo1.maven.org/maven2/io/github/openfeign/feign-java11/

I will leave this open as a TODO on the release process

**Comment by pzapasni** [comment]
@velo thanks for your help!
