### ISSUE TITLE
runtime providing the interface class and the url to feign builder bean using target method

### ISSUE THREAD

**Issue by joshisaurabh2002** [OpenFeign/feign#1205]
from my application I am using feign to manage all the rest calls to south-bound applications, I create a singleton bean for Feign.Builder in my application
`@Bean(name = "feignBuilder")`
`    public Feign.Builder feignBuilder() {`
`        return Feign.builder()`
`                .client(new ApacheHttpClient(customHttpClient))`
`                .encoder(new JacksonEncoder())`
`                .decoder(new JacksonDecoder());`
`    }` 
I have multiple interfaces and I provide those interfaces to feignBuilder's target at runtime 
`if (instance instanceof SomeConfigClassRelatedToServerA) {`
`            return feignBuilder.target(InterfaceA.class, completeURL);`
`        } else if (instance instanceof SomeConfigClassRelatedToServerB) {`
`            return feignBuilder.target(InterfaceB.class, completeURL);`
`        }`

my question is -
1. would you recommend the above approach? because even though I have a singleton bean for feign builder the target would always create a new instance, snippet from your code -
`public <T> T target(Target<T> target) {`
`      return build().newInstance(target);`
`    } `
2. is there another(probably better) approach to handle multiple interfaces?
or would you recommend to create multiple feignBuilder beans per target?

**Comment by joshisaurabh2002** [comment]
continued...
or would you recommend to create multiple feignBuilder beans per target?

**Comment by velo** [comment]
The way I have being dealing with that is having a utility method that I call for the builder...

Something like:

```
@Bean
public SomeConfigClassRelatedToServerA serverA() {
    return feignBuilder().target(InterfaceA.class, completeURL);
}
```

That way I don't need to worry about the builder state or car about reuse.

**Comment by joshisaurabh2002** [comment]
@velo I refactored my code as per your suggestion and introduced a map in each server configuration bean(SomeConfigClassRelatedToServerA) to store multiple feignBuilder targets. 
This looks good.
