### ISSUE TITLE
me reading feign source code 

### ISSUE THREAD

**Issue by Mhunter132** [OpenFeign/feign#1207]
where can i find  design principle article of frame or design pattern article about feign,because i am learning programming through reading package source code

**Comment by kdavisk6** [comment]
Feign uses a few simple patterns throughout it's design.

First is adherence to [SOLID design principles](https://en.wikipedia.org/wiki/SOLID), first and foremost the [Open/Closed principle](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle).

Another is that we favor [Composition over Inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance), when it comes to extending our functionality.

And lastly, we lean heavily on Modules to separate and isolate functionality as to not leak domains and implementation details to our users.

Let me know if you have any more questions.

**Comment by aikin** [comment]
@kdavisk6  

Hi Kevin,

Could you please share more detail about how to separate heavily modules and isolate functionality? Are there any methodologies or books?
