### ISSUE TITLE
Feign with OkHTTP: method GET must not have a request body

### ISSUE THREAD

**Issue by choojoykin** [OpenFeign/feign#1209]
I have this dependencies
```
      <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.3.1</version>
        </dependency>

        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-okhttp</artifactId>
            <version>10.9</version>
        </dependency>
```
Feign interface looks like
```
  @RequestLine("GET /api/v1/auth/signin/{id}")
  @Headers({
    "Accept: application/json",
  })
  void signIn(@Param("id") String id);
```
Builder looks like
```
Feign.builder()
                     .client(new OkHttpClient())
```
When im sending get request `api.signIn("123");` im getting okhttp error =>
```
Exception in thread "main" java.lang.IllegalArgumentException: method GET must not have a request body.
	at okhttp3.Request$Builder.method(Request.kt:258)
	at feign.okhttp.OkHttpClient.toOkHttpRequest(OkHttpClient.java:88)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:168)
```
In stdout i dont see my request param
```
---> GET https://myurl/api/v1/auth/signin/ HTTP/1.1
```
My request param contains in request body.. So how fix it?

PS
If im using Client.Default no error there.

**Comment by choojoykin** [comment]
sry, my fault. im generate feign interface from swagger, where path param with "_" => so feign didnt see this path param and try to put it in body

**Comment by velo** [comment]
No problem all good.

@choojoykin out of curiosity, could you describe to me how you generated client from, swagger?

**Comment by choojoykin** [comment]
@velo https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-maven-plugin/README.md
