### ISSUE TITLE
Feign client with Empty target forcing absolute and relative path

### ISSUE THREAD

**Issue by nkramer44** [OpenFeign/feign#1212]
I am using `feign-core` and `feign-jackson` version `10.7.2` in a Spring Boot app to communicate with external services hosted on arbitrary domains.

I have a `Feign` client with an empty target, which is being constructed like this:
```java
final ObjectMapper objectMapper = ObjectMapperFactory.createObjectMapperForProblemsJson();
return Feign.builder()
      .encoder(new JacksonEncoder(objectMapper))
      .decode404()
      .decoder(new OptionalDecoder(new JacksonDecoder(objectMapper)))
      .target(Target.HardCodedTarget.EmptyTarget.create(OpenPaymentsClient.class));
```

I need the target to be `Empty` so that I can make requests to different hosts dynamically at runtime, which I am doing by passing in a URL to each Feign template like so:

```java 
@RequestLine("GET {baseUrl}/.well-known/open-payments")
@Headers({
  ACCEPT + APPLICATION_JSON,
  CONTENT_TYPE + APPLICATION_JSON
})
OpenPaymentsMetadata getMetadata(@Param("baseUrl") String baseUrl) throws ThrowableProblem;
```

The issue I'm facing with this setup is that if I pass in an absolute URL such as `https://example.com` for `baseUrl`, `RequestTemplate.uri(String uri, boolean append)` throws `IllegalArgumentException("url values must be not be absolute.")`.

However, if I pass in a relative path such as `example.com`, `EmptyTarget.apply(RequestTemplate input)` throws `UnsupportedOperationException("Request with non-absolute URL not supported with empty target")`.

Is there a way a recommended way of creating Feign clients with an Empty target so that I can set the base URL at runtime?

**Comment by kdavisk6** [comment]
@nkramer44 

The proper way to change the base uri at runtime using an Empty Target is outlined in our documentation here:

>Overriding the Request Line
>
>If there is a need to target a request to a different host then the one supplied when the Feign client was created, or you want to supply a target host for each request, include a java.net.URI parameter and Feign will use that value as the request target.
>
>```java
>@RequestLine("POST /repos/{owner}/{repo}/issues")
> void createIssue(URI host, Issue issue, @Param("owner") String owner, @Param("repo") String repo);
>```

You can then update your application interface like so:

```java
@RequestLine("GET /.well-known/open-payments")
@Headers({
  ACCEPT + APPLICATION_JSON,
  CONTENT_TYPE + APPLICATION_JSON
})
OpenPaymentsMetadata getMetadata(URI baseUrl) throws ThrowableProblem;
```

Feign will use the URI parameter to construct the full url.  Let me know if you run into any more issues or have more questions.

**Comment by nkramer44** [comment]
@kdavisk6 
Thanks for you help, I must have missed that in the docs.  This seems to be working for me. Closing.
