### ISSUE TITLE
Allow masking of request and response data when logging

### ISSUE THREAD

**Issue by solidjb** [OpenFeign/feign#1215]
The logging of request/response headers and bodies is a very useful feature.  However, sometimes those log events contain sensitive data.

It would be nice to have a mechanism for masking the values of specific headers.  
if I could give some logging object the name of headers I want masked, then instead of the log events looking like this:

```
[MyConnector#doSomething] Authorization: Bearer sdfsdfsdfsdfsdfsd
```
it could look like this:
```
[MyConnector#doSomething] Authorization: ########
```

It would also be nice when you have structured requests/responses (such as json or xml) to be able to mask the values at certain paths.  

so instead of logging this:

```
{
    "Some Object": {
         "name": "My Object Name"
    }
    "Some Sensitive Object: {
        "name": "Some Sensitive Name"
    }
}
```
you could have this:
```
{
    "Some Object": {
         "name": "My Object Name"
    }
    "Some Sensitive Object: {
        "name": "########"
    }
}
```

Trying to deal with these values after feign has already turned them into log events is very difficult and involves lots of ugly regexes.  Giving feign the capabilities to deal with this as they are creating the events would be extremely useful.

**Comment by kdavisk6** [comment]
Logging, among other things, is highly subjective and situational, by nature.  For needs such as the one's you have mentioned, we highly recommend that you supply your own `feign.Logger` implementation.  The built in `Default` implementation is very basic and only supports simple log messages.

You can then supply your `Logger` implementation to the `Feign` instance:

```java
Feign
   .logger(new MyLogger())
   .target("https://api.example.com", ExampleApi.class);
```
