### ISSUE TITLE
JAXRS contract on API with @HeaderParam("Content-Type") and @Consumes with multiple values cause feign client build fail

### ISSUE THREAD

**Issue by pdesoyres** [OpenFeign/feign#1217]
Version : 11.0

API :
```
    @POST
    @Path("/{stream:.+}")
    @Consumes({"application/xlsx", "text/csv"})
    @Produces("application/json")
    List<Integer> sourceFile(
            @PathParam("stream") String stream,
            @QueryParam("delimiterChar") @DefaultValue(",") String delimiterChar,
            @HeaderParam("Content-Type") String contentType,
            @RequestBody(required = true, description = "Input file") InputStream file
    ) throws IOException;
```

Calling API with :
```
myCtrl.sourceFile("stream", null, "text/csv", inputStream);
```

Causes the error :
```
java.lang.NullPointerException: null
	at feign.okhttp.OkHttpClient.toOkHttpRequest(OkHttpClient.java:64) ~[feign-okhttp-11.0.jar:na]
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:168) ~[feign-okhttp-11.0.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[feign-core-11.0.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-11.0.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-11.0.jar:na]
	at com.sun.proxy.$Proxy143.sourceFile(Unknown Source) ~[na:na]
```

Because at OkHttpClient:62 (`mediaType = MediaType.parse(value);`), `value` variable equals `"application/xlsx, text/csv"` instead of `"text/csv"`.
Method `MediaType.parse(value)` returns `null` as `"application/xlsx, text/csv"` is not a valid media type.

**Comment by velo** [comment]
Hi,

By default, feign will only take the first media type from `@Consumes`
https://github.com/OpenFeign/feign/blob/master/jaxrs/src/main/java/feign/jaxrs/JAXRSContract.java#L117

Problem is you also overwriting it as parameter and that should take precedence.

But I expected feign to do that
https://github.com/OpenFeign/feign/blob/master/jaxrs/src/main/java/feign/jaxrs/JAXRSContract.java#L141

Are you able to create a unit test for `JAXRSContract` showing the issue?

**Comment by pdesoyres** [comment]
Hi,

you'll find the unit test illustrating this here : https://github.com/pdesoyres/feign/commit/ecc89e23c0c591c0e2f11d2bc9ae311a232dc0bf

**Comment by velo** [comment]
@pdesoyres https://github.com/OpenFeign/feign/pull/1219

lemme know your thoughts on this fix.

**Comment by kdavisk6** [comment]
I think in this case Consumes should be translated into Accept and Produces translates into Content-Type. I’m not sure if we are doing that right. 

In any case, the HeaderParam here is odd. There should be no need for it given the Produces and Consumes annotations. 

The fix here should be accept more than one Consumes since is should map to Accept.

**Comment by velo** [comment]
@kdavisk6 image you are using the same interface for client and server...

For server, Consumes translates to Accept and Produce to Content-Type as you said.
But, on the client (feign) it needs to be the other way around.

**Comment by kdavisk6** [comment]
I understand that, but the JAXRS annotations don’t support multiple Produces values  i feel like this came up before. What does our JAXRS library say about it?

**Comment by velo** [comment]
Au contraire my good friend. Both support many values

<img width="834" alt="Screen Shot 2020-05-03 at 00 50 48" src="https://user-images.githubusercontent.com/136590/80864650-23393e00-8cd8-11ea-8b51-b0b290187f25.png">

The way encoders/decoders work on jax-rs allow they to handle multiple just fine.

**Comment by kdavisk6** [comment]
Learn something every day...
