### ISSUE TITLE
Changes in Feign 11.0 ?

### ISSUE THREAD

**Issue by csueiras** [OpenFeign/feign#1218]
Hi all, I was investigating an issue I was experiencing in Feign 10.9.x, I decided to upgrade to latest to figure out if the potential bug in Feign had been fixed and found that Feign 11.0 had been released to Maven Central. After upgrading to 11.0 the bug I was experiencing went away, I wanted to see the changelog for 11.0's release and I can't seem to find the 11.0 branch/release/nothing in this repository. Can someone point me to where this codebase lives or where is the changelog?

**Comment by kdavisk6** [comment]
That’s a bad artifact. 11.x is not ready. I’ll remove it from central

**Comment by csueiras** [comment]
Thanks @kdavisk6 that makes sense, turns out the bug I was experiencing had been fixed in the latest of 10.10.x (https://github.com/OpenFeign/feign/pull/1200)

**Comment by ChristianCiach** [comment]
Looks like the artifact has not been removed yet and some people are already depending on it.

**Comment by velo** [comment]
@kdavisk6 what if, we release feign 11 with current master?

**Comment by kdavisk6** [comment]
Yeah, looks like we'll have to.  There's no way to remove it from Central, I just found out.
