### ISSUE TITLE
Suggestion to upgrade okhttp3 from 3.14.6 to 4.6.0

### ISSUE THREAD

**Issue by Sam-Kruglov** [OpenFeign/feign#1221]
Hi, trying to use the Logbook logging interceptor but they are using 4.x version of OkHttp. Maven by default picks the lowest, which goes from `feign-okhttp` jar, which makes Logbook break on non-existing method. Just an inconvenience that I have to redefine okhttp to 4.x manually, fortunately, it seems to work.

**Comment by velo** [comment]
That is doable. Send us a PR and I will make sure to review it.

FWIW, you can pick the version you need by using
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management

**Comment by jonatan-ivanov** [comment]
Also, it seems okhttp 3.x only receives security fixes: https://github.com/square/okhttp/issues/6019

**Comment by velo** [comment]
Awesome.

**Comment by Sam-Kruglov** [comment]
Alright
