### ISSUE TITLE
Help handling RetryableExceptions when calling several clients

### ISSUE THREAD

**Issue by nicolassiandro** [OpenFeign/feign#1226]
Hey guys, I have a situation where from a given controller I am calling to different Feign clients and then we merge the responses from those clients. The problem is, if one client is inaccessible for some reason I get a RetryableException and the whole flow is ended. If I add an exception handler in the controllers advice, it's the same, the flow is cut short. Is the best approach to just do a try/catch for FeignExceptions and move forward with the next call? Thanks

**Comment by velo** [comment]
Feign will only "leak" the `RetryableException` after it retry 3 times (default), so your server was really not reachable.

If when on client fail you still wanna proceed with a call to a subsequent client, yeah, you need to capture the exception, ignore it and call the other service.


Another option if you always need to call 2 is using an Async request.
https://github.com/openfeign/feign#async-execution-via-completablefuture

**Comment by nicolassiandro** [comment]
Thanks for your reply!
