### ISSUE TITLE
Contract.parseAndValidatateMetadata should not be deleted

### ISSUE THREAD

**Issue by 61go** [OpenFeign/feign#1227]
V10,I found you delete the @decrepted method parseAndValidatateMetadata of Class Contract
inside module feign-core.
but this leads to tihrdparty which depends on this method doesn't work well now!
Can you fix it ,please!

**Comment by velo** [comment]
As you mention, this was a planned API deprecation.

If you really feel this is important, feel free to submit PR to fix it.

**Comment by 61go** [comment]
thx very much for your reply.
But how can I submit PR to fix it?
Forgive me that  I am a chinese feign user with poor English level.....

**Comment by velo** [comment]
Take a look on https://github.com/OpenFeign/feign/blob/master/CONTRIBUTING.md#pull-requests
