### ISSUE TITLE
Null values are skipped in @Param arguments

### ISSUE THREAD

**Issue by M4tiz** [OpenFeign/feign#1230]
If you pass a null value to method parameter annotated with `@Param` during invocation it's processing is skipped entirely according to `ReflectiveFeign#create` method. Is there a reason for this design decision?

Related line:
https://github.com/OpenFeign/feign/blob/1ffa9bea2059c55c09e0bf53cead8caabae59b6e/core/src/main/java/feign/ReflectiveFeign.java#L222

related to: spring-cloud/spring-cloud-openfeign#120

**Comment by velo** [comment]
Making a decision over nulls is always hard.

```
@RequestLine ("GET /service/{id}")
```

What is the correct behaviour if `@Param` `id` is null?
Remove it? Replace with `""` blank? Replace with `"null"` string?

Is that true for Headers? What about a body?

On feign we opted for not adding nulls to the Map containing templates.  Maybe, the ideal behavior would be throwing an exception and letting whoever is creating the client to provide multiple methods w/o option fields.

Any idea on how to have a universal answer for nulls?

**Comment by kdavisk6** [comment]
Take a look at our documentation on this subject here https://github.com/OpenFeign/feign/blob/master/README.md#undefined-vs-empty-values

We follow the rules outlined in the URI template specification for level one expressions. For this case, support for level 2, 3, or 4 expressions could be a solution as it allows the template author to define how the value should be expanded more specially.

We are considering supporting additional levels, but nothing in the immediate future.

**Comment by M4tiz** [comment]
@kdavisk6 thank you for the input
It looks like in the current version null values are replaced with empty string which is compliant with the RFC specification. Closing as it is working as intended.
