### ISSUE TITLE
how to set the timeout config dynamically after creating a feign instance?

### ISSUE THREAD

**Issue by HaoChou** [OpenFeign/feign#1238]
xxx target = Feign.builder()
                .encoder(new SdhmEncoder())
                .decoder(new SdhmDecoder())
                .retryer(Retryer.NEVER_RETRY)
                .options(new Request.Options(3000,3000))
                .target(Target.EmptyTarget.create(xxx.class));

how to set a new timeout value for the target when the application is running?
recreate a new targe?

**Comment by HaoChou** [comment]
> Looks like it's better to recreate the target. You can try to use reflection and go deep into Proxy that Feign builder created but it wouldn't be a pretty and readable solution.

HAHAHAHA i find a new way ,it is very easy. Just create a customize Client extends Client.Default ,and override the execute method. every time the execute method invoked use the customized timeout config.  


the code looks like :


public class CustomizeClient extends Client.Default {
    /**
     * Null parameters imply platform defaults.
     *
     * @param sslContextFactory
     * @param hostnameVerifier
     */
    public CustomizeClient(SSLSocketFactory sslContextFactory, HostnameVerifier hostnameVerifier) {
        super(sslContextFactory, hostnameVerifier);
    }
    @Override
    public Response execute(Request request, Request.Options options) throws IOException{
        return super.execute(request,new Request.Options(xxx,xxx));
    }
}
 


xxx target = Feign.builder()
.encoder(new SdhmEncoder())
.decoder(new SdhmDecoder())
.retryer(Retryer.NEVER_RETRY)
.client(new CustomizeClient(null,null))
.options(new Request.Options(3000,3000))
.target(Target.EmptyTarget.create(xxx.class));


so that every time you start a http request use the customized config instead of  the Option in the init of target.

**Comment by HaoChou** [comment]
> @HaoChou try this:
> https://github.com/OpenFeign/feign/blob/master/core/src/test/java/feign/OptionsTest.java#L34
> 
> Documentation seems to be lacking, would you be interested in adding that information to README?

thanks. I have find a way .Refer to my last reply

**Comment by velo** [comment]
Guess is ok to close then.

**Comment by HaoChou** [comment]
> Guess is ok to close then.

yes thanks. I think the Request.Option should be a interface so that users can customize options.haha
