### ISSUE TITLE
Support multiple inheritance in Contract

### ISSUE THREAD

**Issue by gab-fin** [OpenFeign/feign#1244]
It would be great to support it, we have a hierarchy of interfaces and it represents a lot of work/duplication to flatten it out. I believe that this is [request 3](https://github.com/OpenFeign/feign/issues/320) :-).

**Comment by kdavisk6** [comment]
Please do create duplicate issues.

**Comment by gab-fin** [comment]
I created this because the other one was closed. In this case you should re-open the other one.

**Comment by velo** [comment]
@gab-fin are you volunteering to work on it?
