### ISSUE TITLE
In GetMapping, Null values or White values arguments are not passed to the called interface

### ISSUE THREAD

**Issue by muxiaobai** [OpenFeign/feign#1245]
in my project，I define  the feign client，example：
```
@Component
@FeignClient(name = "app-auth")
public interface RemoteService {
    @GetMapping(value = "/next")
    String test(@RequestParam("normal") String normal,
          @RequestParam("nullvalue") String nullvalue,
          @RequestParam("emptyvalue") String emptyvalue, 
          @RequestParam("whitevalue") String whitevalue);
  }
}
```
and，user ` remoteService.test("1",null,""," ");` invoke feign,the `nullvalue    emptyvalue` can't passed,

I want have a url such as `/test?normal=1&nullvalue=&emptyvalue=&whitevalue=%20`, but not `/test?normal=1&whitevalue=%20`,because interface must have nullvalue and  emptyvalue .

**Comment by kdavisk6** [comment]
@muxiaobai This violates the URI Template specification, specifically [section 3.2.1](https://tools.ietf.org/html/rfc6570#section-3.2.1):

> A variable that is undefined (Section 2.3) has no value and is
   ignored by the expansion process.  If all of the variables in an
   expression are undefined, then the expression's expansion is the
   empty string.

`null` is considered `undefined` and therefore will be excluded.  

As for the `emptyvalue`, that one should be preserved if you are using the latest version of Feign.  For more information, please see our documentation on[ Undefined vs. Empty Values](https://github.com/OpenFeign/feign#undefined-vs-empty-values)

**Comment by muxiaobai** [comment]
@kdavisk6 ，Thank you very much for your reply。

that means null == undefined , only empty will pass the key to next，
our project feign version  is 10.1, and filter Util.isNotBlank(),
```
  private String queryString(String values) {
    if (this.pure) {
      return this.name;
    }

    /* covert the comma separated values into a value query string */
    List<String> resolved = Arrays.stream(values.split(","))
        .filter(Util::isNotBlank)
        .collect(Collectors.toList());

    if (!resolved.isEmpty()) {
      return this.collectionFormat.join(this.name, resolved, this.getCharset()).toString();
    }

    /* nothing to return, all values are unresolved */
    return null;
  }
```
 I see  the lastest version  [QueryTemplate](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/template/QueryTemplate.java)
that `this.collectionFormat.join(name, values, StandardCharsets.UTF_8).toString();`

I will upgrade。
