### ISSUE TITLE
Move to CircleCi

### ISSUE THREAD

**Issue by kdavisk6** [OpenFeign/feign#1246]
Travis, while an steady standby, has become increasingly slow and troublesome when it comes to releasing to Maven Central.  I'd like to propose that we move to CircleCi.

This change will:
* Speed up builds for both PRs and releases
   * Better dependency caching
   * On-Demand docker instances start builds faster
   * Built in reporting for tools such as Codecov, Sonar, and GitHub
* Simpler configuration
* Better Workflow control for Releases to Central.

**Comment by velo** [comment]
+1

Have zero experience with it and found configuration files on other projects very uninformative

**Comment by kdavisk6** [comment]
It is significantly faster than Travis since issues Docker underneath and supports dependency caching and can share an environment throughout a multiple-step workflow that would drastically speed up our release job:  https://circleci.com/docs/2.0/concepts/#workflows

It's not too different from Travis underneath

**Comment by velo** [comment]
Well, go for it =)

I have no special love for travis, is just the one I have being using

**Comment by kdavisk6** [comment]
Turns out Travis CI dot org is not long for this world.  I'll try to take this one shortly.

**Comment by kdavisk6** [comment]
Circle Configuration is now present and ready to go.  If anyone is working on a fork and is having issues with the build checks, please rebase with the master branch to ensure that you have the correct build configurations.
