### ISSUE TITLE
Consider using Checkstyle to catch formatting issues

### ISSUE THREAD

**Issue by kdavisk6** [OpenFeign/feign#1247]
At the moment, we rely on the Eclipse Code Formatter plugin to ensure consistency across our projects.  Our builds verify this *after* the process is complete, which can lead to longer feedback cycles on Pull Requests and reviews.  I would like the team to consider also  using Checkstyle, specifically as part of the `process-resources` stage during the build.  This will accomplish the following:

* Verify style *before* compilation
* Provide early feedback to developers about style issues *before* submitting a Pull Request
* Can be used along side our current formatter plugins

Thoughts?

**Comment by velo** [comment]
I'm my opinion, codestyle is very opiniative but not helpful. It tells you exactly what is wrong.

With current formatter, running the build locally will fix whatever needs fixing.

Would be nice if we could bridge both.

**Comment by kdavisk6** [comment]
I'm looking to avoid failed CI builds because of formatting.  We can make Checkstyle "opt-in" for those that want it.

**Comment by velo** [comment]
Yeah, checkstyle has a beautiful error message but does squat to fix the problem
formatter-plugin fix the problem for you, but doesn't tell what exactly is wrong

being able to combine both would be gold
