### ISSUE TITLE
Getting 411 Length Required Error

### ISSUE THREAD

**Issue by mayank-jain02** [OpenFeign/feign#1251]
I am trying to have a post call with token and hitting to the end URL, I am receiving 411 Length Required error. Even after creating the Interceptor and adding Content-Length: 0 to it, still I am receiving the same error. I am able to see that request has content-length : 0 but I am not able to understand how to resolve this issue. I am using here default feign client

**Comment by kdavisk6** [comment]
@mayank-jain02 To isolate where the issue may be, can you try using one of the other http clients, such as our OkHttp or Apache versions?

**Comment by mayank-jain02** [comment]
@kdavisk6 I have tried using Apache HttpClient and it is working using that.

**Comment by Somebodyisnobody** [comment]
I've excactly the same problem with the azure TTS-API.
This is being sent to azure:
![image](https://user-images.githubusercontent.com/35230554/97849790-5a25f600-1cf3-11eb-8a8d-18fbd3230453.png)

this is the log:
```
2020-11-02 09:48:07.652 DEBUG 14696 [        Timer-0] f.s.Slf4jLogger                          : [AzureTokenHttpClient#postIssueTokenRequest] ---> POST https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issueToken HTTP/1.1
2020-11-02 09:48:07.653 DEBUG 14696 [        Timer-0] f.s.Slf4jLogger                          : [AzureTokenHttpClient#postIssueTokenRequest] Content-Length: 0
2020-11-02 09:48:07.653 DEBUG 14696 [        Timer-0] f.s.Slf4jLogger                          : [AzureTokenHttpClient#postIssueTokenRequest] Content-Type: application/x-www-form-urlencoded
2020-11-02 09:48:07.653 DEBUG 14696 [        Timer-0] f.s.Slf4jLogger                          : [AzureTokenHttpClient#postIssueTokenRequest] Ocp-Apim-Subscription-Key: key
2020-11-02 09:48:07.653 DEBUG 14696 [        Timer-0] f.s.Slf4jLogger                          : [AzureTokenHttpClient#postIssueTokenRequest] ---> END HTTP (0-byte body)

```
and this is what I get if I just change the url pointing to a local test server:
![image](https://user-images.githubusercontent.com/35230554/97849836-6f9b2000-1cf3-11eb-83aa-e742a9f33633.png)

Notice that also a User-Agent header is set without showing it in the debug console or log.

I've tried to explicitly enable 
`feign.okhttp.enabled: true`
and with the same result
`feign.httpclient:enabled: true`

**Comment by tmoreira2020** [comment]
Hey @Somebodyisnobody, I'm facing the same issue with a pretty simple POST (without any body). Do you have any advice how to workaround the issue? I have tested my code with 10.10.1, 10.11 and 11.0.

Thanks

**Comment by Somebodyisnobody** [comment]
No I've no workarround for this and hope that someone who knows the code can help us

**Comment by Somebodyisnobody** [comment]
See also #1229

**Comment by tmoreira2020** [comment]
I was able to workaround the issue providing an empty JSON object ("{}") in the payload, worked like a charm. HTH

**Comment by Somebodyisnobody** [comment]
Thank you, that worked for me but I had to remove the Content-Type header and the manually set Content-Length header.

This does not fix the initial problem that values are shown in debugging which are not actually sent and that the Content-Length isn't zero.

**Comment by kdavisk6** [comment]
The setting of the `Content-Type` header is `Client` dependent.  For instance, the `ApacheHttpClient` will set the `Content-Length` header when a `Request.body` is present, even if the body is empty.  `OkHttp` does the same thing.  Would it be possible to provide your Feign interface so we can review?

**Comment by Somebodyisnobody** [comment]
As I changed the team I am working for I have no longer access to that project. But I want to encourage you to don't log Content-Length: 0 when it's not set to 0 ;).

**Comment by gongyho** [comment]
> 我能够在有效负载中提供一个空的 JSON 对象（“{}”）来解决这个问题，就像一个魅力。HTH

nice!
