### ISSUE TITLE
Receiver class feign.hystrix.HystrixDelegatingContract **

### ISSUE THREAD

**Issue by govardhanaraoganji** [OpenFeign/feign#1255]
I am trying to create a FeignClient object using the HystrixFeign and I am providing the fallback for MyClient but I am getting the below error.

Caused by: java.lang.AbstractMethodError: Receiver class feign.hystrix.HystrixDelegatingContract does not define or inherit an implementation of the resolved method abstract parseAndValidateMetadata(Ljava/lang/Class;)Ljava/util/List; of interface feign.Contract.
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:151)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:49)
	at feign.hystrix.HystrixFeign$Builder.target(HystrixFeign.java:63)
	at feign.hystrix.HystrixFeign$Builder.target(HystrixFeign.java:111)

`MyClient client = HystrixFeign.builder()
        .contract(new MyClientContract(new Contract.Default()))
        .encoder(new JacksonEncoder(objectMapper))
        .decoder(new JacksonDecoder(objectMapper))
        .logger(new Slf4jLogger(MyClient.class))
        .logLevel(Logger.Level.BASIC)
       .target(MyClient.class, URL, new MyClientFallback());

MyClientContract:
public class MyClientContract implements Contract {
  private final Contract delegate;

  /**
   * map key is constructed by ClassFullName + configKey. configKey is constructed by {@link
   * feign.Feign#configKey}
   */
  public static final Map<String, MethodMetadata> METADATA_MAP = new HashMap<>();

  public MyClientContract(Contract delegate) {
    this.delegate = delegate;
  }

  @Override
  public List<MethodMetadata> parseAndValidateMetadata(Class<?> targetType) {
    List<MethodMetadata> metadatas = delegate.parseAndValidateMetadata(targetType);
    metadatas.forEach(
        metadata -> METADATA_MAP.put(targetType.getName() + metadata.configKey(), metadata));
    return metadatas;
  }
}`

Using: 
feign-hystrix version: 10.2.3

**Comment by kdavisk6** [comment]
You may be mixing different versions of Feign.  Please ensure that `feign-core` and `feign-hystrix` are using the same base version.  The error you are seeing is because the version of `feign-core` being used is newer than `feign-hystrix`

**Comment by velo** [comment]
On newer version of feign there is a `feign-bom` artifact that may help you to lock all versions across the board.

**Comment by govardhanaraoganji** [comment]
Thank you @velo and @kdavisk6. I have many dependencies with our common modules so I used different approach is `feign-hystrix` as dependency to my component so issue got resolved. Earlier It was in our common module.
