### ISSUE TITLE
Ability to add client method parameters to the exception message

### ISSUE THREAD

**Issue by PSharlan** [OpenFeign/feign#1258]
Next example:

```
@FeignClient( ... )
public interface MyClient {

    @PostMapping( ... )
    MyResponse action(@RequestBody MyRequest request);

}
```

I want to add some info from `request` parameter to the exception in case of 404 code. Now it looks like that:

feign.FeignException$NotFound: status 404 reading MyClient #action(MyRequest) 

And I don't want to catch `FeignException` at the service method which calls this client action to override it with my own exception. 
Is it possible?

**Comment by herodj310** [comment]
Hi @PSharlan 

I think Feign Error Decoder (https://github.com/OpenFeign/feign-annotation-error-decoder) might help you in this use case.

**Comment by kdavisk6** [comment]
@herodj310 is correct.  For extensions like this, it's our recommendation that you build your own error decoders.
