### ISSUE TITLE
Donot wrap custom exception to HystrixRunTimeException in Feign Client Fall back methods

### ISSUE THREAD

**Issue by shivasantosh** [OpenFeign/feign#1260]
[Feign Client Issue Posted in Spring cloud ](https://github.com/spring-cloud/spring-cloud-openfeign/issues/356)

Please help in solving this issue. 
Here is my git public link which has two services
https://github.com/shivasantosh/feignproject

![image](https://user-images.githubusercontent.com/13864811/88460467-0c128280-ceba-11ea-82ef-f324ef215262.png)

Order service is calling Product service using feign client.
Steps for replication:

1. Run the two spring boot projects.
2. Call the POST end point "http://localhost:/order/{productId}". This end point which internally calls product service with feign client.
3. product service throws exception, entered into ProductFeignServiceFallBack.java where I want to throw exception to the client "ProductNotFoundException" as below

```java
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class ProductFeignServiceFallBack implements ProductFeignService{

	private static final Logger LOGGER = LogManager.getLogger(ProductFeignServiceFallBack.class);

	private final Throwable cause;

	public ProductFeignServiceFallBack(Throwable cause) {
		this.cause = cause;
	}

	@Override
	public ResponseEntity<String> validateProduct(long productId) {
		// my code for updating errors in my DB
		//throw exception to the client
		LOGGER.error(cause.getMessage());
		LOGGER.info("thrown exception from upstream so entered fall back");
		throw new ProductNotFoundException("PRODUCT_NOT_FOUND", "PRODUCT_NOT_FOUND");
	}

}
```

4. But I see in the Controller advice it is entering into HystrixRuntimeException block. I want it to be entered into productNotFoundException block. ProductNotFoundException is wrapped in HystrixRuntimeException.
I want the business exception to be thrown as it is instead of wrapping it in HystrixRuntimeException.
Because in my service class I donot want to catch with HystrixRuntimeException.

```java
@ControllerAdvice
public class OrderServiceExceptionHandler {

   /*Exception has to enter this block*/
   @ExceptionHandler(ProductNotFoundException.class)
   public @ResponseBody ResponseEntity<ErrorDetails> productNotFoundException(ProductNotFoundException ex) {
   	ErrorDetails errorDetails = new ErrorDetails(ex.getErrorMessage(), ex.getErrorCode());
       return new ResponseEntity<>(errorDetails, HttpStatus.EXPECTATION_FAILED);
   }
   
   /*Should not enter this block*/
   @ExceptionHandler(HystrixRuntimeException.class)
   public @ResponseBody ResponseEntity<String> hystrix(HystrixRuntimeException ex) {
       return new ResponseEntity<>("Hystrix bloc", HttpStatus.CONFLICT);
   }
}

```

**Comment by kdavisk6** [comment]
As the response on your Spring Cloud issue states, this is all by design and that you should reconsider this approach.  Fallbacks are designed to response with proper answers, not wrap exceptions.  This is incorrect usage of Hystrix and it's fallback capabilities.  Please visit the [Hystrix Documentation](https://github.com/Netflix/Hystrix/wiki/How-To-Use#ErrorPropagation) for more insight and best practices.
