### ISSUE TITLE
Request to update response time in more intelligent format

### ISSUE THREAD

**Issue by ravibarkhani** [OpenFeign/feign#1275]
We are using multiple downstream APIs from our application it is difficult for us to track which API took how much time, With debug enabled ate client level we get the time taken by downstream API, we want to generate metrics out of this time, 
Since time printed in debug logs are alphanumeric we can get best of this line. Sending this request to separate time and ms.

current format is 
LOG_THRESHOLD class_name_with_package ClientName_Including_Operation <---- http_version (000ms)

My request is to separate number with special char and ms.
package and class
feign.Logger ==>
Logging statement==> 
log(configKey, "<--- HTTP/1.1 %s%s (%sms)", status, reason, elapsedTime);

**Comment by kdavisk6** [comment]
Our included logger is very simple and meets only the most basic of needs.  If you need to customize the output, It's our recommendation that you implement your own `Logger` implementation.  See our [documentation on logging](https://github.com/OpenFeign/feign#logging) for more information.
