### ISSUE TITLE
Incorrect encoding when content contains %[0-9A-Fa-f][0-9A-Fa-f] sequences

### ISSUE THREAD

**Issue by zt52875287** [OpenFeign/feign#1276]
I want to pass the string `aaabbb%%55`   by the annotation @QueryMap

```
@RequestLine(value = "GET /aaa")
ServerResp<ServerData> censor(@QueryMap  Map<String, String> queryMap);
```
What i want is `aaabbb%25%2555`, but it was unexpectedly encoded to `aaabbb%25%55`

When I was researching this behaviour I noticed the code of class feign.template.UriUtils, it ignores the sub-string that matches  pattern PCT_ENCODED_PATTERN. 
Is there any way to encode the full string automatically?

**Comment by kdavisk6** [comment]
@zt52875287 

In your situation, my recommendation is to pct-encode the value before adding it to the Query Map.  This will ensure that we will not try to encode it again and that you receive the expected results.  Our `UriUtils` class is making a "best guess" at already encoded values.  With a string like the one you are referring to, the `%55` matches the pattern for an already encoded value, hence your experience.

**Comment by zt52875287** [comment]
To pct-encode the value before adding it to the Query Map is an effective way. 
 I hope there will be a way to make the "best guess" behavior configurable in the future.

**Comment by zt52875287** [comment]
To pct-encode the value before adding it to the Query Map is an effective way. 
 I hope there will be a way to make the "best guess" behavior configurable in the future.
