### ISSUE TITLE
MeteredClient doesn't propagate RuntimeExceptions properly

### ISSUE THREAD

**Issue by tommyk-gears** [OpenFeign/feign#1281]
`MeteredClient#execute` catches any `Exception` that is not an `IOException` and wraps it in an `IOException` before rethrowing it.
See https://github.com/OpenFeign/feign/blob/master/micrometer/src/main/java/feign/micrometer/MeteredClient.java#L50

I suppose this is just by mistake, and unchecked exceptions should be propagated as-is, not wrapped in an `IOException`. I.e. the following should be added before the `catch(Exception e)`-clause;

```java
catch(RuntimeException e) {
   throw e;
}
```

**Comment by velo** [comment]
You are absolutely correct.

Please file a PR for this, I will merge it ASAP
