### ISSUE TITLE
Support JEP 118 parameters

### ISSUE THREAD

**Issue by krzyk** [OpenFeign/feign#1297]
I haven't seen this issue, but it is quite hard to search for this so sorry for duplicate.

Java 8 introduced an additional javac option in ([JEP 118](http://openjdk.java.net/jeps/118)) using `-parameters` to allow retrieval of parameter names during runtime.

This retrieval is supported in e.g. Spring and Jackson to reduce amount of duplication, so I think it would be good to have it in feign also.

E.g. I have following method in interface:
```
    @Body("{content}")
    @Headers(value = {"Content-Type: application/json", "Accept: application/json"})
    @RequestLine("POST /prop/{property}/ver?cont={contact}&addr={address}")
    String createNewVersion(@Param("property") String property, @Param("contact") String contact, @Param("address") String address, @Param("content") Map<String, Integer> content);
```

As you see the same name is both in the parameter name as well as in annotation, if `-parameters` would be supported this could be simplified to:
```
    @Body("{content}")
    @Headers(value = {"Content-Type: application/json", "Accept: application/json"})
    @RequestLine("POST /prop/{property}/ver?cont={contact}&addr={address}")
    String createNewVersion(@Param String property, @Param String contact, @Param String address, Map<String, Integer> content);
```

Currently (in 9.7.0) it is not supported because `value` in `@Param` annotation is required.

**Comment by krzyk** [comment]
If you think this is a good addition to feign I could work on it.

**Comment by velo** [comment]
> If you think this is a good addition to feign I could work on it.

Awesome, that would be most appreciated!

**Comment by krzyk** [comment]
@velo I've created PR #1309 for this.
