### ISSUE TITLE
Support uri and exception tags in micrometer MeteredClient

### ISSUE THREAD

**Issue by Kuvaldis** [OpenFeign/feign#1301]
### Description

In `MeteredClient` implementation there is a try/catch block:
```
try {
      return meterRegistry.timer(
          metricName.name(),
          metricName.tag(template.methodMetadata(), template.feignTarget()))
          .recordCallable(() -> client.execute(request, options));
    } catch (IOException e) {
      throw e;
    } catch (Exception e) {
      throw new IOException(e);
    }
```

A couple of things might be improved here:
* `exception` and `uri` tags would be really helpful as part of `feign.Client` metric.
* IOException wrapping prohibits calling method to catch original exception. Seems to be unnecessary to do.

### Proposal

* Add extensions (e.g. as abstract methods) to `MeteredClient` and similar classes allowing to add custom tags.
* Remove `IOException` wrapping.

**Comment by hattesen** [comment]
The IOException wrapping (of RuntimeExceptions) has been fixed in #1281

**Comment by Kuvaldis** [comment]
Thank you @hattesen! Didn't notice that.

**Comment by kdavisk6** [comment]
@Kuvaldis 

Thanks for requesting this feature.  I agree that many of our users would benefit from this feature.  Before we get started, I'd like to discuss some of the details, specifically around what events should be reported and the meter specifications and get more feedback.

I propose we agree on a naming convention to reduce confusion and simplify development.  What are your thoughts on the following:

**Meter Prefix:** `target.method` name. 

Example 

```java
interface GitHub {
   @RequestMapping("GET /api/repositories")
   List<String> repositories();
}
```

Meters: `io.github.GitHub.repositories`

**Meters**
- `request`: Timer that records the request execution
   - Tags: `uri`, `status`, `method`, `outcome`, `exception`

**Full Example**
`io.github.Github.repositories.request{uri,status,method,outcome,exception}`
* `uri` - https://github.com/api/repositoires
* `status` - 200
* `method` - GET
* `outcome` - SUCCESS
* `exception` - none

Failed Example
* `uri` - https://github.com/api/repositoires
* `status` - 400
* `method` - GET
* `outcome` - CLIENT_ERROR
* `exception` - `feign.BadRequest`

**Questions**
* `uri`: What should this be?  The original URI Template or the resolved URI?
* `exception`: Where should this be resolved?  At the `Client` or after the `ErrorDecoder`?

Thoughts?

**Comment by r1jsheth** [comment]
is there any example depicting this use case?
