### ISSUE TITLE
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target executing POST

### ISSUE THREAD

**Issue by zhangfangdz** [OpenFeign/feign#1304]
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target executing POST

**Comment by krzyk** [comment]
@zhangfangdz This is not a feign issue, you just don't have appropriate cacerts for the server you try to connect to.

You can find those usually in `jre/lib/security/cacerts` (for <= Java 8) or `lib/security/cacerts`

**Comment by kdavisk6** [comment]
Correct, this is not a feign issue but a java SSL configuration issue.
