### ISSUE TITLE
java11 client should consider Options::connectTimeoutMillis

### ISSUE THREAD

**Issue by gb-klein** [OpenFeign/feign#1306]
feign.http2client.Http2Client seems not to consider Options::connectTimeoutMillis. In the course of #1233 request timeout was fixed - but not the connect timeout. 

Implementation note: this would have to be set on the HttpClient instance (e.g. via Builder::connectTimeout). One could do this manually by providing a custom built HttpClient to Http2Client. However it would be good to leave this over to Http2Client when it constructs the HttpClient for us. E.g. by replacing the default constructor with a constructor taking Options or (IMHO better) lazily instantiating HttpClient - if no custom was specified via constructor - when the request should be sent.

**Comment by ChunMengLu** [comment]
Yes, it is more complicated to implement. 

I think it is enough to customize connectTimeoutMillis in most scenarios on HttpClient.
