### ISSUE TITLE
feign.Request => requestBody() method disappeared 

### ISSUE THREAD

**Issue by Mr-DeWitt** [OpenFeign/feign#1308]
Hi!

We were using `feign-core:10.7` where there were two functions inside`feign.Request`

- `public byte[] body()` marked as @Deprecated
- `public Body requestBody()` marked to be used instead of `body()`

But in version `feign-core:10.8` the `requestBody()` method disappeared, despite of it was **not** marked as @Deprecated, and there was no major version increase on the project. It's interesting, that the deprecated body() function still there in the newer version, without deprecated flag. :D

**Version 10.7:**
![image](https://user-images.githubusercontent.com/11660065/98829622-b39bcc80-2439-11eb-8843-cffa28883b81.png)
**Version 10.8:**
![image](https://user-images.githubusercontent.com/11660065/98829672-c4e4d900-2439-11eb-9848-ec7270a28da2.png)

**Comment by kdavisk6** [comment]
See #1194 for more background.  TLDR; `requestBody` never should have been made public.  It was a mistake.

**Comment by Mr-DeWitt** [comment]
I see. 
Our problem was that we used a non deprecated, recommended function (by the comment), and we've got a compilation error after a minor version upgrade. As @sofax said 'Breaking the code with a patch release violates the idea of semantic versioning', especially when you instruct the developers in Javadoc to use a function which is intended to be removed ('use {@link #requestBody()} instead'). 
It's no problem for us, we could change our code accordingly, but in the future please be cautious about these type of changes.
