### ISSUE TITLE
AsyncResponseHandler 类抛出异常

### ISSUE THREAD

**Issue by cqyhm** [OpenFeign/feign#1314]
Object decode(Response response, Type type) throws IOException {
    try {
      return decoder.decode(response, type);
    } catch (final FeignException e) {
      throw e;
    } catch (final RuntimeException e) {
      throw e;
      // **throw new DecodeException(response.status(), e.getMessage(), response.request(), e);**
    }
  }
}
会把所有的异常都转换为DecodeException异常，导致自定义的解码器抛出自定义的异常失败。

**Comment by kdavisk6** [comment]
> will convert all exceptions to DecodeException, causing the custom decoder to throw a custom exception and fail .

This is intentional.  Errors that occur during encoding are explicit and wrapped accordingly.
