### ISSUE TITLE
WHY there is no global fallback setting mechanism in feign?

### ISSUE THREAD

**Issue by tbwork** [OpenFeign/feign#1317]
Current mechanism needs us to set fallback class for all @FeignClients which is so tedious, see following:
```java
@FeignClient(... fallback=DefaultFallback.class)
public interface userClient{}

@FeignClient(... fallback=DefaultFallback.class)
public interface userClient{}


@FeignClient(... fallback=DefaultFallback.class)
public interface carClient{}

@FeignClient(... fallback=DefaultFallback.class)
public interface moneyClient{}

@FeignClient(... fallback=DefaultFallback.class)
public interface orderClient{}

```
DON'T you feel weird?

**Comment by kdavisk6** [comment]
@tbwork This is not a Feign issue, but a limitation of Hystrix.  Feign uses Hystrix be wrapping each method into a `HystrixCommand` and command has it's own fallback.  For more advanced use cases we provide a `FallbackFactory` component.  This can be specified at the interface level and allows for finer control over the fallback handling.  You can find documentation here: https://github.com/OpenFeign/feign/tree/master/hystrix#considering-the-cause
