### ISSUE TITLE
Can't config connection request timeout for http client

### ISSUE THREAD

**Issue by swingboat** [OpenFeign/feign#1318]
There is a field named 'connectionRequestTimeout' in RequestConfig.java of http client, but I can't config it from openfeign.

- I don't find a property to config it from FeignHttpClientProperties.java
- I don't find a property to config it from Request.Options 

When a large number of requests are sent through openfeign, If we don't config this property, the connection pool is exhausted, there will be a large number of requests waiting for connections, and no timeout will occur. This will deplete the tomcat threads. 

Can you tell us how to config this property? Thanks!

**Comment by kdavisk6** [comment]
@swingboat They can be set in the builder

```java
Feign.builder()
   .options()
   .target();
```

This will configure those values for individual target.  I apologize that this is not documented.

**Comment by sam990** [comment]
Feign.Options supports only connect and read timeout not connection request timeout. I solved the issue by defining a bean for my custom ApacheHttpClient to be used by Feign in FeignConfiguration class as below:



```
@Bean
public Client customClient() {

       RequestConfig requestConfig = RequestConfig.custom() .setConnectionRequestTimeout(connectionRequestTimeout).build();
    	
       CloseableHttpClient closableClient= HttpClients.custom()
						 .setDefaultRequestConfig(requestConfig)
					         .build();
       return new ApacheHttpClient(closableClient);
}
