### ISSUE TITLE
Is this position optimized

### ISSUE THREAD

**Issue by Inmord** [OpenFeign/feign#1324]
There are a lot of iFs In the AsyncResponseHandler.java. Is this position optimized~

     if (Response.class == returnType) { // line 71
            if (response.body() == null) {
              resultFuture.complete(response);
            } else if (response.body().length() == null
                || response.body().length() > MAX_RESPONSE_BUFFER_SIZE) {
              shouldClose = false;
              resultFuture.complete(response);
            } else {
              // Ensure the response body is disconnected
              final byte[] bodyData = Util.toByteArray(response.body().asInputStream());
              resultFuture.complete(response.toBuilder().body(bodyData).build());
            }
          } else if (response.status() >= 200 && response.status() < 300) {
            if (isVoidType(returnType)) {
              resultFuture.complete(null);
            } else {
              final Object result = decode(response, returnType);
              shouldClose = closeAfterDecode;
              resultFuture.complete(result);
            }
          } else if (decode404 && response.status() == 404 && !isVoidType(returnType)) {
            final Object result = decode(response, returnType);
            shouldClose = closeAfterDecode;
            resultFuture.complete(result);
          } else {	
        resultFuture.completeExceptionally(errorDecoder.decode(configKey, response));
     }

**Comment by kdavisk6** [comment]
@Inmord  We have not run any benchmarks on this particular logic if that's what you mean.  If you have evidence of a performance issue related to this area, we'd appreciate that information.
