### ISSUE TITLE
QueryMap doesn't conform to the set property naming style.

### ISSUE THREAD

**Issue by Pilipets** [OpenFeign/feign#1326]
I have a feign client with Spring boot app, that has a signature like below - it uses SpringQueryMap to send URL parameters.
`@PostMapping(path="/api/services/helper/reduce")`
`ResponseEntity<List<String>> filterSupply(`
`    @SpringQueryMap FilterTripParams params,`
`    @RequestBody List<String> supply_list);`

The problem is mapped field names are in the camel case while I expect them in the snake case since have `spring.jackson.property-naming-strategy=SNAKE_CASE`

Serialization and deserialization with the `@RequestBody` work as expected.
I would consider it a bug.

**Comment by kdavisk6** [comment]
@Pilipets Your issue is with the Spring Cloud extension, as it is responsible for the mapping and jackson support.  I would open your issue there.

**Comment by Pilipets** [comment]
Good, thanks. Could you share the link for it here?

**Comment by Pilipets** [comment]
I have created one here as well - https://github.com/spring-cloud/spring-cloud-openfeign/issues/439.
Is it the right place?
