### ISSUE TITLE
Support JDK9+ HttpClient

### ISSUE THREAD

**Issue by kdavisk6** [OpenFeign/feign#1348]
The `Default` `Client` implementation uses `HttpUrlConnection` to make requests.  For users on older JDK (JDK 8 and prior), this is still a good option.  However, users of JDK9+ have access to the new `HttpClient` API.  Please consider adding support for the new `HttpClient` API.

**Comment by cantaylancapraz** [comment]
Any update?

**Comment by velo** [comment]
Yes, fixed a long while back
https://github.com/OpenFeign/feign/tree/master/java11

**Comment by janezmejias009** [comment]
Hi guys, **PATCH** is not supported?
