### ISSUE TITLE
Duplicated headers with Request Template

### ISSUE THREAD

**Issue by efres** [OpenFeign/feign#1361]
# Problem
When we use the request interceptor feign to set headers on runtime and we set the same header key with different values, the previous header will not be overwritten. This could cause business problems when the token is refreshed and the request persist trying to access the rest endpoint.

# Cause

Call appendHeader RequestTemplate.java:708 
```java

  /**
   * Specify a Header, with the specified values. Values can be literals or template expressions.
   *
   * @param name of the header.
   * @param values for this header.
   * @return a RequestTemplate for chaining.
   */
  public RequestTemplate header(String name, Iterable<String> values) {
    if (name == null || name.isEmpty()) {
      throw new IllegalArgumentException("name is required.");
    }
    if (values == null) {
      values = Collections.emptyList();
    }

    return appendHeader(name, values); // Line 708
  }
```
Then not verify header presence before appending him. RequestTemplate.java:732

```Java

  /**
   * Create a Header Template.
   *
   * @param name of the header
   * @param values for the header, may be expressions.
   * @return a RequestTemplate for chaining.
   */
  private RequestTemplate appendHeader(String name, Iterable<String> values) { // Line 732
    if (!values.iterator().hasNext()) {
      /* empty value, clear the existing values */
      this.headers.remove(name);
      return this;
    }

    if (name.equals("Content-Type")) {
      // a client can only produce content of one single type, so always override Content-Type and
      // only add a single type
      this.headers.remove(name);
      this.headers.put(name,
          HeaderTemplate.create(name, Collections.singletonList(values.iterator().next())));
      return this;
    }
    this.headers.compute(name, (headerName, headerTemplate) -> {
      if (headerTemplate == null) {
        return HeaderTemplate.create(headerName, values);
      } else {
        return HeaderTemplate.append(headerTemplate, values);
      }
    });
    return this;
  }
```

# Proposed Solution
Should be implemented validation according to "Content-Type" validation.  PR Open on this [link](https://github.com/OpenFeign/feign/pull/1362)

**Comment by kdavisk6** [comment]
@efres 

This is intentional as the function is designed to support the building of multi-value headers over multiple steps within the request building process.  From your example, the correct way to replace a header values is to first remove it, then append the new values.

To replace header values, you must use the `removeHeader` method to clear any existing header values, then use the `appendHeader` method.

```java
/* replace an entire header */
template.removeHeader("header");
template.appendHeader("header", values);
```

I suspect the issue you are facing is not due to a bug in Feign, but incorrect usage of the `RequestTemplate`

**Comment by efres** [comment]
@kdavisk6

Thank you for your response.

We use that feat  "remove header", but I think that's not the best way to fix the Authorization header problem. 

According to my previous commentary, if we set that header twice will cause bugs in an application when request.

We could improve if we set the Authorization Header singularity, according to the "Content-Type" header?

**Comment by efres** [comment]
@kdavisk6 has any update about that case?

**Comment by kdavisk6** [comment]
@efres 

The remove, then add method is the correct way of handling this situation.  The `Content-Type` changes are related to issues specifically with the JAX-RS Contract and really should be refactored into that Contract.  

It is not appropriate for Feign to be making decisions for users this way.  For every specification, there is an exception.  In this specific case, enforcing single and multi-value headers is a slippery slope, which may bring incompatibility to HTTP Clients like Apache and OkHttp, which are what we rely on to enforce the HTTP specifications.  It's our position that Users are responsible for these decisions and that we will faithfully honor those choices, even if they violate a given specification.
