### ISSUE TITLE
Threads created by feign client usage are not closed on actuator shutdown

### ISSUE THREAD

**Issue by vamsinarendrula** [OpenFeign/feign#1363]
I have a spring boot application running on embedded tomcat, after starting the application and making requests which invokes feign client and  then on actuator/shutdown application is not shutting down, and I see below threads are running.

**Daemon Thread [spring.cloud.inetutils] (Running)	
Thread [DestroyJavaVM] (Running)	
Daemon Thread [boundedElastic-evictor-1] (Running)	
Daemon Thread [boundedElastic-1] (Running)	
Thread [pool-7-thread-1] (Running)**	

Tomcat threads are closed
Application is de registered from eureka 
Database connection pool threads are closed

After application start up if I send actuator/shutdown with out making requests which trigger feign clients, application is shutting down properly with out any issues.

Spring boot : 3.2.5.RELEASE
spring cloud : Hoxton.SR9
using spring load balancer instead of ribbon.

I see below warning message in the logs for all above threads

WARN  o.a.c.loader.WebappClassLoaderBase.log : The web application [ROOT] appears to have started a thread named [pool-7-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)

**Comment by kdavisk6** [comment]
@vamsinarendrula This is not a Feign issue, but rather a Spring one.  Specifically, the use of Spring Cloud Loadbalancer and it's use of Reactor.  Feign core has not thread pools or thread pool management.  I recommend you ask the question of the Spring Cloud Load Balancer team.
