### ISSUE TITLE
When Response is json array, we cant treat it as a string to convert to an object

### ISSUE THREAD

**Issue by carlos12silva94** [OpenFeign/feign#1366]
If we are expecting a Response object as a result from a http request, and it is a json object:
{ "example": "123"}
it works fine, and we will see this in the response.body(). So after that we cant convert it easily to a java class.

however, if the http response is something like:
[
{ "example": "123"}
]
what we see in response.body() is this: feign.Response$InputStreamBody and we are not able to convert to a java class.

can you confirm this? And give an hint on how to solve it?

**Comment by kdavisk6** [comment]
If you are relying on the `toString()` method of `Response.body()`, that won't work.  You'll need to read the body using the `asReader` or `asInputStream` to convert it.

**Comment by carlos12silva94** [comment]
Yes. That's it!. I will lay here my solution:

`String responseString = null;
responseString = Util.toString(response.body().asReader());
JSONArray respJson = new JSONArray();
Gson gson = new Gson();
try {
	respJson = new JSONArray(responseString);
		
        destinationObj.setBillData(gson.fromJson(respJson.toString(), DestinationObj[].class));
}catch(Exception e) {
}
`
