### ISSUE TITLE
mock surport mockito

### ISSUE THREAD

**Issue by TaylorKanper** [OpenFeign/feign#1368]
The mock data must be the same as the returned data. Otherwise, the mock will return error 404. The mockito feature must be supported.

**Comment by kdavisk6** [comment]
Feign can be mocked using Mockito.  We use it ourselves in our own unit tests.  Controlling what the mock returns is outside of our scope and up to the implementer.  It is up to you to ensure that the mocked `Target` implementation returns what you need.
