### ISSUE TITLE
capabilities for async client

### ISSUE THREAD

**Issue by xificurC** [OpenFeign/feign#1374]
Am I misreading it or is it not possible to add capabilities for the async builder? Is it on the roadmap?

**Comment by kdavisk6** [comment]
@xificurC I don't follow your question.  Can you add more specifics on what you are looking for?

**Comment by xificurC** [comment]
Sure, I mean this

https://javadoc.io/doc/io.github.openfeign/feign-core/latest/feign/Feign.Builder.html#addCapability-feign.Capability-

https://github.com/OpenFeign/feign/blob/master/micrometer/src/main/java/feign/micrometer/MicrometerCapability.java

**Comment by xificurC** [comment]
To be more precise, there's no similar method on the AsyncFeign builder

**Comment by randysecrist** [comment]
It would be handy to make it so feign sends micrometer calls async; not blocking the main thread.  We have (rarely) observed timeouts with the underlying micrometer provider impacting the feign api calls.
