### ISSUE TITLE
header AND queryParam use sameple name,how to do it

### ISSUE THREAD

**Issue by luoqingming110** [OpenFeign/feign#1377]
![image](https://user-images.githubusercontent.com/7380805/111264384-5cfe0380-8662-11eb-901d-adb3762bfd8f.png)
![image](https://user-images.githubusercontent.com/7380805/111264490-96367380-8662-11eb-9f53-abe1d054bd7a.png)

**Comment by luoqingming110** [comment]
header  will  overwrite the  requestParam

**Comment by kdavisk6** [comment]
This is called out in our documentation.  This usage is not supported.  See: https://github.com/OpenFeign/feign#request-headers-expansion
