### ISSUE TITLE
Feign 11.1 missing release notes

### ISSUE THREAD

**Issue by krzyk** [OpenFeign/feign#1378]
I don't see release notes for feign 11.1 and it is available in maven central.
On release page I see only one commit from it relating to license headers.

Was 11.1 really released or was it a bug in the build process like in 11.0?

**Comment by kdavisk6** [comment]
Apologies.  The release was in Draft form.  I've published it.  11.1 is indeed the latest release.

**Comment by krzyk** [comment]
Thank you, I was waiting for 11.x release :)
