### ISSUE TITLE
Java 11 Http2Client Returns "OK" Status Message on 4XX Responses

### ISSUE THREAD

**Issue by JKomoroski** [OpenFeign/feign#1382]
If a server returns a 404 or 400 error (possibly other errors), and the FeignClient instance is backed using the Java 11 Http2 Client, the response will be set to OK unless a Reason-Phrase header is present in the response. Other client implementations appear to parse the status line of the response to generate this reason phrase.

I'm not certain if parsing the status line is possible, and I don't think this is actually standardized but it feels wrong getting a `404 OK` or `400 OK`.

The offending code appears to be:
[Http2Client.java](https://github.com/OpenFeign/feign/blob/3ea3708cddef0d20c0bf443c18f2364c8d8df062/java11/src/main/java/feign/http2client/Http2Client.java) Line 78

Example Builder Used to duplicate:

```
Feign.builder()
  .client(new Http2Client())
  .target(MyClient.class, hostUrl);
```

I found this when I swapped out a client and had some tests that were checking for Feign Exception message contents.

**Comment by kdavisk6** [comment]
@JKomoroski 

Thanks for bringing that to our attention.  This is definitely a bug.  We'll see when we can get to it, or if you are so inclined, submit a PR yourself.

**Comment by JKomoroski** [comment]
@kdavisk6 
Hmmm.... So I started putting in a fix then I looked at the Response model and saw the following:

```
  /**
   * Nullable and not set when using http/2
   *
   * See https://github.com/http2/http2-spec/issues/202
   */
  public String reason() {
    return reason;
  }
  ```
  
Are we married to this comment?
If so, we can simply null the field, when a reason phrase header is not present, otherwise we can make best effort to populate it.
