### ISSUE TITLE
Another pair of decoder and encoder for JSON-java 

### ISSUE THREAD

**Issue by radio-rogal** [OpenFeign/feign#1385]
I propose to add module e.g. feign-json that will provide decoder and encoder for JSONObject and JSONArray objects.

Related project https://github.com/stleary/JSON-java

If this proposal will be approved I could try to implement this module.

**Comment by velo** [comment]
@radio-rogal I think this is very reasonable

FWIW, I join the feign project after having a bunch of small feign modules spread across github.

You can either start with something you fully own and control (release cycles can be much faster) and include on feign later on.


Anyway, feel free to make a PR and ping me when you think is ready to review.
