### ISSUE TITLE
Question: Running tests from master causes test to fail on DefaultContractTest#autoDiscoverParamNames

### ISSUE THREAD

**Issue by silkentrance** [OpenFeign/feign#1417]
I am currently trying to build this locally and when running the tests in current master, I get

java.lang.IllegalStateException: Param annotation was empty on param 0.

when running the 

autoDiscoverParamNames

test.

I am using OpenJDK 11 on Debian/stable.

Debugging the code, I find that in Contract

```
 super.registerParameterAnnotation(Param.class, (paramAnnotation, data, paramIndex) -> {
        final String annotationName = paramAnnotation.value();
        final Parameter parameter = data.method().getParameters()[paramIndex];
        final String name;
        if (emptyToNull(annotationName) == null && parameter.isNamePresent()) {
          name = parameter.getName();
        } else {
          name = annotationName;
        }
        checkState(emptyToNull(name) != null, "Param annotation was empty on param %s.",
            paramIndex);
```

the parameter name is never present (arg0, arg1...)

Is this some issue with the OpenJDK or the overall compiler configuration where the original names have been optimized out?

I am using the standard configuration set by the feign poms except for additional compiler args (-Xlint:unchecked, -Xlint:deprecation).

TIA!

**Comment by silkentrance** [comment]
Just found https://www.logicbig.com/how-to/java-command/java-compile-with-method-parameter-names.html
which states that one must specify the -parameters compiler option in order to preserve these names.

**Comment by silkentrance** [comment]
The -parameters option does the trick, I wonder why this is not the default in the feign pom compiler configuration?

**Comment by velo** [comment]
That would be my fault =)

Could you please add a PR for this?


[image: --]

Marvin Froeder
[image: https://]about.me/velo
<https://about.me/velo?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by silkentrance** [comment]
@velo the problem is, though, whether this should be part of the release package or just be applied to the tests?
and how would this be your fault, since the builds over on circleci are still working just fine?

**Comment by velo** [comment]
I think just add to tests would be enough.

I agree that we can't prevent people from building their project w/o this arg, but, we could give a nice error message on that too.

**Comment by kdavisk6** [comment]
It is set in the pom. Look at the test compile set up

**Comment by kdavisk6** [comment]
https://github.com/OpenFeign/feign/blob/e230312230eab097062d86a3255a1d6144ed08a8/pom.xml#L453

**Comment by silkentrance** [comment]
@kdavisk6 hm, if it is set in the pom, then pulling from master didn't work as expected, will check into this.

**Comment by silkentrance** [comment]
> Ow, NVM then.
> 
> I guess all that is needed is something like this:
> 
> ```
>         if(emptyToNull(annotationName) != null) {
>             name = annotationName
>         } else if (parameter.isNamePresent()) {
>             name = parameter.getName();
>         } else {
>           throw new XYZ("Unabled resolve argument name. Either include field name using @Param or enabled java -XYZabc, please see https://github.com/OpenFeign/feign/issues/1417");
>         } 
> ```
> 
> What do you think?

The errors get collected and reported after that the annotation processors did their work, failing early, though.
So everything is fine with that part of the code.

**Comment by silkentrance** [comment]
pulling from master now gives me the correct pom level configuration (under windows), wonder why it did not work under linux (debian/buster).

**Comment by silkentrance** [comment]
closing as this is no longer an issue

**Comment by silkentrance** [comment]
except documentation wise, where people need to be instructed that when using auto discovery of parameter names they should be using the `-parameters` compiler arg...

**Comment by velo** [comment]
> except documentation wise, where people need to be instructed that when using auto discovery of parameter names they should be using the `-parameters` compiler arg...

could you update docs to reflect this?!
