### ISSUE TITLE
Using openfeign with webflux has an error

### ISSUE THREAD

**Issue by dh1991** [OpenFeign/feign#1428]
spring-cloud-dependencies  2020.0.2
spring-cloud-starter-openfeign 3.0.2
spring-boot-starter-webflux 2.4.1

Use the dependencies above ,
when run @Feignclient method it throw an exception:
java.lang.IllegalStateException: block()/blockFirst()/blocklast() are blocking , 
which is not supported in thread xxxxx.

The underlying code that caused the error is BlockingLoadBalancerClient.choose

when remove webflux  use spring-boot-web   it  works 

so it mean the new version of openFeign is not support using webflux?

**Comment by kdavisk6** [comment]
Feign is a blocking client and cannot be used with WebFlux without significant refactoring.  For new we recommend using the community supported: https://github.com/Playtika/feign-reactive

**Comment by xxscloud5722** [comment]
@kdavisk6   In 2023, Spring is already 3.1, aren't you ready to support it?

**Comment by velo** [comment]
> @kdavisk6 In 2023, Spring is already 3.1, aren't you ready to support it?

We are more than ready, ready and waiting for your PR. Please let me know when I can review your changes.
