### ISSUE TITLE
Is there any way to set Timeout for particular method of feign client?

### ISSUE THREAD

**Issue by 16bce062** [OpenFeign/feign#1432]
` **RequestMapping(value = "/**target1**")
  String **method1**(RequestParam Map<>param**)

  **RequestMapping(value = "/**target2**")
  String **method2**(RequestParam Map<>param)**`

suppose 2 methods are in 1 feign client class (method1, method2). 
Now i want to setup a timeout for first method (**method1**) only and not for at feignClient class level(which includes method2 also).

so for method1  i am trying something like this for timeout but it's not working.
`hystrix.command.feignClass#method1(String).execution.isolation.thread.timeoutInMilliseconds=100000`

can anyone help?
@jdamick 
@carlossg @dinomite @qualidafial @joschi [](url)

**Comment by jaredpetersen** [comment]
@16bce062 It appears so: https://github.com/OpenFeign/feign/pull/970

**Comment by jaredpetersen** [comment]
@16bce062 I later realized that you at this in the context of Hystrix. I needed to do the same thing myself and I documented my solution on [StackOverflow](https://stackoverflow.com/a/69199541/7583677).
