### ISSUE TITLE
maintainer gone for OpenFeign/feign-annotation-error-decoder?

### ISSUE THREAD

**Issue by BigMichi1** [OpenFeign/feign#1447]
it looks like there is no maintainer anymore for https://github.com/OpenFeign/feign-annotation-error-decoder. i opened there a pull request but no one approved the requested changes. looks like @saintf is not there anymore. can this repo be reactivated?

**Comment by velo** [comment]
To be honest, I didn't even knew this repo existed.

@kdavisk6 and I adopted feign after the original team moved to new and exiting projects.

Kevin, what you think about folding this annotation-error-decoder into the main project as a module?

@BigMichi1  would that help? Are you willing to create the PR on the main project instead?

**Comment by BigMichi1** [comment]
sure i can recreate the pr

**Comment by kdavisk6** [comment]
Makes a lot of sense. Feel free

**Comment by velo** [comment]
> sure i can recreate the pr

Awesome, please ping me once you have a PR ready.  I can make sure to release it right after it's merged

**Comment by BigMichi1** [comment]
just to clearify some things before i'm doing it wrong
- I will create on PR taking over the code from https://github.com/OpenFeign/feign-annotation-error-decoder to https://github.com/OpenFeign/feign without the feature addition of issue https://github.com/OpenFeign/feign-annotation-error-decoder/pull/30
  - the module name I think should stay? so it would be "feign-annotation-error-decoder" or should it be now "annotation-error-decoder"
  - should I target master or anything else? currently, the repo has its max compatibility with 10.7.0?
  - do you want to keep the git history when the code is taken over?
- after this PR has been merged i will create another PR for taking over the changes from https://github.com/OpenFeign/feign-annotation-error-decoder/pull/30

**Comment by velo** [comment]
We usually include feign on module names on maven, so `feign-annotation-error-decoder`, but not on the directories.

Target master for sure.

Compatibility also master/latest and greatest.

No need to keep history, as we squash merge. You can if you really want to, but most will be lost when we first merge button. @kdavisk6 any strong opinion here? Shall we not squash this one?!

Having you change in a separated PR sounds like a solid plan.
