### ISSUE TITLE
[Feature Request] Support custom tags for Micrometer

### ISSUE THREAD

**Issue by fdw** [OpenFeign/feign#1456]
If I add `.addCapability(new MicrometerCapability(meterRegistry))` to my Feign client, there seems to be no way to add custom tags to the Micrometer metrics. It would be nice to do this, for example by extending `MicrometerCapability` to `MicrometerCapability(meterRegistry, mapOfTags())`.

**Comment by r1jsheth** [comment]
I would also love to have this feature.
@kdavisk6 do you think this can be a `good first issue`?
I can work on it.

**Comment by BartekBanachowicz** [comment]
Hey, @kdavisk6 and @velo, I'd love to work on this. Could you assign this issue to me?

**Comment by kdavisk6** [comment]
You don't need our permission, just go ahead and submit a PR when you are ready 👍🏻
