### ISSUE TITLE
Open Feignclient integration with Netflix Ribbon not working in springboot

### ISSUE THREAD

**Issue by tarunsingh2789** [OpenFeign/feign#1471]
FeingClient Server
--------------------------------

@RestController
public class FeinApiCall {
    
    @Autowired
    CustomFeignClient customFeignClient;

    @GetMapping("/getinfothroughfeign")
    public String getFeignLoad() {
        String result =customFeignClient.getInstance();
        return result;
    }
}

-------------------------------------------------

@SpringBootApplication
@EnableFeignClients
@RibbonClient(name = "testServer", configuration = CustomIClientfiguration.class)
public class FeignLoadBalancingApplication {

    public static void main(String[] args) {
        SpringApplication.run(FeignLoadBalancingApplication.class, args);
    }

     
}

---------------------------------------------------

@FeignClient(name ="testServer")
public interface CustomFeignClient {
     @RequestMapping(method = RequestMethod.GET, value = "/getPort")
     String getInstance();
}

--------------------------------------------------

@Configuration
public class CustomIClientfiguration {

    public static final int DEFAULT_CONNECT_TIMEOUT = 1000;
    public static final int DEFAULT_READ_TIMEOUT = 1000;
    
    @Autowired
    IClientConfig ribbonClientConfig;
    
    @Bean
    public IClientConfig ribbonClientConfig() {
        System.err.println("CustomIClientfiguration overiding");
        DefaultClientConfigImpl config = new DefaultClientConfigImpl();
        config.loadProperties("testServer");
        config.set(CommonClientConfigKey.ConnectTimeout, DEFAULT_CONNECT_TIMEOUT);
        config.set(CommonClientConfigKey.ReadTimeout, DEFAULT_READ_TIMEOUT);
        return config;
    }
    
    @Bean
    public IPing ribbonPing(IClientConfig config) {
        return new PingUrl();
    }
    
    @Bean
    public IRule ribbonRule(IClientConfig config) {
        
        return new AvailabilityFilteringRule();
    }
}

application.properties of feignclient 
------------------------------------------------------------

server.port=9098

testServer.ribbon.eureka.enabled=true
testServer.ribbon.listOfServers=localhost:2289
testServer.ribbon.ServerListRefreshInterval=15000

testserver files
------------------------------

@RestController
public class TestController {

    @Autowired
    ApplicationContext context;
    
    @Value("${server.port}")
    private String portNumber;
    
    @GetMapping("/getPort")
    public String getString()
    {
        return "Port number "+this.portNumber;
    }
    
    @GetMapping("/")
    public String ping()
    {
        
        return "welcome";
    }
}

application.properties of testServer
-------------------------------------------------
server.port=2289
spring.application.name=testServer
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true

Error
----------------------------

Receiver class org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient does not define or inherit an implementation of the resolved method 'abstract org.springframework.cloud.client.ServiceInstance choose(java.lang.String, org.springframework.cloud.client.loadbalancer.Request)' of interface org.springframework.cloud.client.loadbalancer.ServiceInstanceChooser. java.lang.AbstractMethodError: Receiver class org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient does not define or inherit an implementation of the resolved method 'abstract org.springframework.cloud.client.ServiceInstance choose(java.lang.String, org.springframework.cloud.client.loadbalancer.Request)' of interface org.springframework.cloud.client.loadbalancer.ServiceInstanceChooser. at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:88) at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) at jdk.proxy3/jdk.proxy3.$Proxy83.getInstance(Unknown Source) at com.FeignLoadBalancing.api.FeinApiCall.getFeignLoad(FeinApiCall.java:19) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:567) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

**Comment by velo** [comment]
This seems to be a springboot issue...

**Comment by tarunsingh2789** [comment]
RestTemplate with ribbon is working fine. What could be wrong with openfeign with ribbon.


Are you able to reproduce the issue using above code?If

**Comment by tarunsingh2789** [comment]
# I have done following changes in my feignclient server #
    
1) created new configuration file 
---------------------------------------------------
 

@Configuration
public class OpenFeignConfiguration {
	
	@Autowired
	RibbonLoadBalancerClient ribbonLoadBalancerClient;
	
	@Bean
	public Feign.Builder feignBuilder() {
		return Feign.builder();
	}
}



2) Set my configuration file in feign client 
---------------------------------------------------

   
@FeignClient(name ="testServer",configuration = OpenFeignConfiguration.class)
public interface CustomFeignClient {
	 @RequestMapping(method = RequestMethod.GET, value = "/getPort")
	 String getInstance();
}

3) Created ChildRibbonLoadBalancerClient which implements RibbonLoadBalancerClient and overrides ServiceInstance choose() method 

@Component
public class ChildRibbonLoadBalancerClient extends RibbonLoadBalancerClient{

	@Autowired
	LoadBalancerClient loadBalancerClient;
	
	@Override
	public <T> ServiceInstance choose(String serviceId, Request<T> request) {
		 ServiceInstance server = this.loadBalancerClient.choose(serviceId);
		 return server;
	}

	public ChildRibbonLoadBalancerClient(SpringClientFactory clientFactory) {
		super(clientFactory);
	}

}
