### ISSUE TITLE
Feign Request returnType Response.class with "Transfer-Encoding: chunked"

### ISSUE THREAD

**Issue by hdfg159** [OpenFeign/feign#1474]
Why the reponse type is `Response.class` and `feign.Response#body` should not close when response data with header "Transfer-Encoding: chunked" and not contain "Content-Length"?
`response.body().length()` will return null and `shouldClose` variable will be set to `false`.

`feign.AsyncResponseHandler#handleResponse` 
```java
  void handleResponse(CompletableFuture<Object> resultFuture,
                      String configKey,
                      Response response,
                      Type returnType,
                      long elapsedTime) {
    // copied fairly liberally from SynchronousMethodHandler
    boolean shouldClose = true;

    try {
      if (logLevel != Level.NONE) {
        response = logger.logAndRebufferResponse(configKey, logLevel, response,
            elapsedTime);
      }
      if (Response.class == returnType) {
        if (response.body() == null) {
          resultFuture.complete(response);
        } else if (response.body().length() == null
            || response.body().length() > MAX_RESPONSE_BUFFER_SIZE) {
          shouldClose = false;
          resultFuture.complete(response);
        } else {
          // Ensure the response body is disconnected
          final byte[] bodyData = Util.toByteArray(response.body().asInputStream());
          resultFuture.complete(response.toBuilder().body(bodyData).build());
        }
       // ...
    } catch (final IOException e) {
      if (logLevel != Level.NONE) {
        logger.logIOException(configKey, logLevel, e, elapsedTime);
      }
      resultFuture.completeExceptionally(errorReading(response.request(), response, e));
    } catch (final Exception e) {
      resultFuture.completeExceptionally(e);
    } finally {
      if (shouldClose) {
        ensureClosed(response.body());
      }
    }
  }
```

If I don’t use `try-with-resource` process response `feign.Response#body`,apache httpclient can't re-use the connection，which waiting for get connection forever.
some tests which waiting for get connection forever:
```java
public class ApacheHttpClientTest extends AbstractClientTest {

  @Override
  public Builder newBuilder() {
    return Feign.builder().client(new ApacheHttpClient());
  }

  @Test
  public void responseNotClose() {
    final HttpClient httpClient = HttpClientBuilder.create()
            .setMaxConnPerRoute(1)
            .setMaxConnTotal(1)
            .build();

    final NoContentInterface testInterface = Feign.builder()
            .client(new ApacheHttpClient(httpClient))
            .target(NoContentInterface.class, "http://localhost:" + server.getPort());

    server.enqueue(new MockResponse().setResponseCode(201).setChunkedBody("", -1));
    server.enqueue(new MockResponse().setResponseCode(201).setChunkedBody("", -1));

    Response res1 = testInterface.NoContent1("test1");
    assertNotNull(res1);
	
    System.out.println("waiting.....");

    Response res2 = testInterface.NoContent1("test2");
    assertNotNull(res2);
    System.out.println("end.....");
  }

  public interface NoContentInterface {
    @RequestLine("POST /no-content1")
    Response NoContent1(@QueryParam("foo") String foo);
  }
}
```

However, after I enable  feign log output, `feign.Logger#logAndRebufferResponse` will rebuild response body with using `feign.Util#toByteArray`,`feign.Response#body` will consume and apache httpclient  re-use this connection.

I don't understand why it isn't necessary to close `feign.Response#body`.If  I enable feign log output, `feign.Response#body` is consumed in the end.
I  think it should be also rebuild response body with using `feign.Util#toByteArray` .Look forward to your reply.

**Comment by kelvin-j-li** [comment]
One of our application uses Feigh with Apache httpclient.

We observed connection pool got exhausted and had negative performance impact after upgrading to VMWare TAS-2.11.6 which comes with the breaking change (de-chunk feature is removed from golang) - https://community.pivotal.io/s/article/Clients-receive-responses-with-no-Content-Length-header-and-a-chunked-encoded-body-after-upgrading-Tanzu-Application-Service-for-VMs?language=en_US

In the feign http client, it no longer receives 'content-length' after the upgrade. Instead, it always gets 'Transfer-Encoding: chunked'. It seems to be related to this issue reported here.

Thanks.

Kelvin J Li

**Comment by kdavisk6** [comment]
An example of proper use:

Interface:
```java
public interface MyApi {
   @RequestLine("GET /data"
   Response getData();
}
```

Use of the method
```java
public static void main(String[] args) {
   MyApi api = Feign.target(MyApi.class);

   try (Response response = api.getData()) {
      /* process the response */
   }
}
```

**Comment by hdfg159** [comment]
> @hdfg159 It looks like our documentation is missing one very key piece of information. If your Feign interface returns a `Feign.Response` object, the caller is responsible closing the Response. We should add that documentation.

Although it is the omission of the document, I don't know why the caller is responsible closing the Response🙄

**Comment by kdavisk6** [comment]
> > @hdfg159 It looks like our documentation is missing one very key piece of information. If your Feign interface returns a `Feign.Response` object, the caller is responsible closing the Response. We should add that documentation.
> 
> Although it is the omission of the document, I don't know why the caller is responsible closing the Response🙄

By obtaining the `Response`, Feign relinquishes control to the caller, who is now responsible for handling the response, dealing with any errors, decoding the body, retrying, etc...  This is the trade off for using `Response` objects directly.

**Comment by kdavisk6** [comment]
> > An example of proper use:
> > Interface:
> > ```java
> > public interface MyApi {
> >    @RequestLine("GET /data"
> >    Response getData();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Use of the method
> > ```java
> > public static void main(String[] args) {
> >    MyApi api = Feign.target(MyApi.class);
> > 
> >    try (Response response = api.getData()) {
> >       /* process the response */
> >    }
> > }
> > ```
> 
> Hi Kevin, Thanks for your reply. I think the issue is specific to Feign with apache http client handling with 'Transfer-Encoding' header.
> 
> See the source code in 1st comment:
> 
> ```
>     } else if (response.body().length() == null
>         || response.body().length() > MAX_RESPONSE_BUFFER_SIZE) {
>       shouldClose = false;
>       resultFuture.complete(response);
>     }
> ```
> 
> If shouldClose is set to false, then it won't execute the below:
> 
> finally { if (shouldClose) { ensureClosed(response.body()); } }
> 
> This issue doesn't happen in Feign + okhttp client.
> 
> Thanks.
> 
> Kelvin J Li

This sounds like a bug, would you be able to create a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) and submit a new issue?

**Comment by garyteh** [comment]
Our team encountered the same problem. To illustrate the issue, I've created a [repository](https://github.com/garyteh/openfeign-1474) that reproduces the scenario.

**Comment by hdfg159** [comment]
> feign.Util#toByteArray

HTTP 1.1 Transfer-Encoding: chunked cannot use feign.Util#toByteArray to rebuild the responseBody, see #2419 . Additionally, the `Response ` should use try-with-resources to properly close the stream and recycle the connection. I will close this issue for now.
