### ISSUE TITLE
MeteredClient.execute()， The counter indicator increases by 2 each time

### ISSUE THREAD

**Issue by flysun3344** [OpenFeign/feign#1480]
<img width="667" alt="企业微信截图_02a28ec3-5b59-4210-9dbe-a472c0ed07ae" src="https://user-images.githubusercontent.com/11894211/128972701-07654037-4e35-4c46-871d-146c7c678032.png">

"sample.stop(timer)" in the finally code block should be placed in "if(time == null)"

**Comment by flysun3344** [comment]
The above problem is in feign-micrometer version 11.6

**Comment by radio-rogal** [comment]
No, it isn't.

If the `sample.stop(timer)` will be placed in this block we stop to call this method for any exception as there aren't any case when timer is `null` in `finally` block:
* we create timer in the end of happy path
* we create timer for any exception for all three cases including the highest level `Exception`, see [MeteredClient, last catch of Exception](https://github.com/OpenFeign/feign/blob/470631be507caf2f27a4c693537f9e2f93852dc3/micrometer/src/main/java/feign/micrometer/MeteredClient.java#L66)

Of course we can leave `if (timer == null)` to work with Error and Throwable.
But here should be only one call of the`stop`: we should remove it from main block try-catch.
