### ISSUE TITLE
@QueryMap not resolving to query parameters

### ISSUE THREAD

**Issue by Menighin** [OpenFeign/feign#1484]
Hi guys, checking #667  I was expecting my POJO anotated with `@QueryMap` to send the parameters in the URL. But it seems it sends in the body of the request. Is this the expected behavior? 
I opened a [question on StackOverflow](https://stackoverflow.com/questions/68761322/querymap-pass-parameters-in-the-body) but got no answers.

Thanks

**Comment by rage-shadowman** [comment]
Yes, `@QueryMap` works as you expect. However, it is vanilla feign. From your stackoverflow post, it looks like you're using the Spring feign libs.

**Comment by Menighin** [comment]
Thanks @rage-shadowman . I'm indeed using `spring-cloud-starter-openfeign`. Wouldn't expect it to change the behavior of a specific feign annotation though... Will open an issue there, thanks.

**Comment by Menighin** [comment]
Just a follow up: Indeed it was because I was using `spring-cloud`. While doing so, one must use `@SpringQueryMap` instead of `@QueryMap`
