### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by Sam-Kruglov** [OpenFeign/feign#1513]
Hi, I've been battling with getting Spring's `@Cacheable` annotation to work and actually won!
I saw your roadmap to implement this feature in "short term" (updated 2 years ago).

Here's my workaround, maybe it will be helpful to someone with a similar issue or give an idea to contributors:

```java
import feign.Capability;
import feign.InvocationHandlerFactory;
import feign.InvocationHandlerFactory.MethodHandler;
import feign.Target;
import org.aopalliance.intercept.MethodInvocation;
import org.springframework.cache.interceptor.CacheInterceptor;
import org.springframework.stereotype.Component;

import java.lang.reflect.AccessibleObject;
import java.lang.reflect.Method;
import java.util.Map;

import static java.util.stream.Collectors.toMap;

/**
 * Allows Spring's @Cache* annotations to be declared on the feign client's methods
 */
@Component
public class CachingCapability implements Capability {
    private final CacheInterceptor cacheInterceptor;

    public CachingCapability(CacheInterceptor cacheInterceptor) {
        this.cacheInterceptor = cacheInterceptor;
    }

    @Override
    public InvocationHandlerFactory enrich(InvocationHandlerFactory invocationHandlerFactory) {
        return (target, dispatch) -> invocationHandlerFactory.create(target, withCacheProxy(target, dispatch));
    }

    private Map<Method, MethodHandler> withCacheProxy(Target<?> target, Map<Method, MethodHandler> dispatch) {
        return dispatch.entrySet().stream()
                .map(e -> Map.entry(e.getKey(), (MethodHandler) argv -> cacheInterceptor.invoke(new MethodInvocation() {
                    @Override
                    public Method getMethod() {
                        return e.getKey();
                    }

                    @Override
                    public Object[] getArguments() {
                        return argv;
                    }

                    @Override
                    public Object proceed() throws Throwable {
                        return e.getValue().invoke(argv);
                    }

                    @Override
                    public Object getThis() {
                        return target;
                    }

                    @Override
                    public AccessibleObject getStaticPart() {
                        return e.getKey();
                    }
                }))).collect(toMap(Map.Entry::getKey, Map.Entry::getValue));
    }
}
```

As I was searching for a solution, apparently annotations in java interfaces don't get propagated onto the implementations, but looks like feign takes care of that with a proxy since it needs to read the annotations anyway.
The solution is inspired by this blog post about having interceptors on okhttp level for retrofit https://medium.com/swlh/annotation-based-offline-caching-in-retrofit-d7dbd775ac74

**Comment by velo** [comment]
> I saw your roadmap to implement this feature in "short term" (updated 2 years ago).

yeah, back then, I was working on a company that really cared about this feature and was willing to pay for me to actually do it.... needless to say, life is a bit more dynamic than that.  But, great thing about opensource is that we can always get external help, thanks for that.

That is nice, seems a good approach, but it's spring only....

Wondering if we should expand our `feign-spring` module, to include some vanilla stuff, or if this should really be dealt by spring folks.

**Comment by Sam-Kruglov** [comment]
See
PR [here](https://github.com/OpenFeign/feign/pull/1515)
Issue in [spring-cloud-openfeign](https://github.com/spring-cloud/spring-cloud-openfeign/issues/607)
PR in [spring-cloud-openfeign](https://github.com/spring-cloud/spring-cloud-openfeign/pull/608)
