### ISSUE TITLE
Feign logs HTTP/1.1 when OkHttpClient is using HTTP/2

### ISSUE THREAD

**Issue by efumas** [OpenFeign/feign#1533]
We are using OkHttpClient with http2client but the logs always show HTTP/1.1

https://github.com/OpenFeign/feign/blob/3a351fa0716c51b5b4d7caa0c5f72cd61f80445f/core/src/main/java/feign/Logger.java#L64

**Comment by radio-rogal** [comment]
Could we just remove a protocol version from the message?

The handler logs request before call so we don't know which version of HTTP will be used in connection
https://github.com/OpenFeign/feign/blob/cbda5e6958ff3ef4f8928fa065725eff867685d0/core/src/main/java/feign/SynchronousMethodHandler.java#L113

/cc @velo @kdavisk6

**Comment by velo** [comment]
That would work too.... But can't we get the right version somehow?

**Comment by radio-rogal** [comment]
There are some client methods that we can ask about version.

* HC5, HttpMessage.getVersion()
* java11 HttpResponse.version()
* OkHttp Response.protocol()

How it could be IMHO:
1. by default a client returns HTTP1.1 or just null (the version is not available).
2. if a client knows version, it will return it
3. the handler will ask a client about protocol version and writes it to log after it has executed request by client.
