### ISSUE TITLE
Bug Fixes part of the 11.7 release note is the same with 11.3

### ISSUE THREAD

**Issue by KENNYSOFT** [OpenFeign/feign#1541]
https://github.com/OpenFeign/feign/releases/tag/11.7
https://github.com/OpenFeign/feign/releases/tag/11.3

> ### Bug Fixes 🐞
> * Modify DefaultMethodHandler to work with Android (#1436)
> * Run java11 build, if JDK version is at least 11 (#1418)
> * Fix no response logging on async Feign (#1450)

**Comment by velo** [comment]
Thanks, removed bug fixes
