### ISSUE TITLE
Micrometer MeteredDecoder records timer twice in happy path

### ISSUE THREAD

**Issue by ErikKringen** [OpenFeign/feign#1553]
Similar to #1480.

The `sample.stop` call on L65 should be removed and let the one if the `finally` block handle all paths

https://github.com/OpenFeign/feign/blob/1f7ca4c74cefdeeea96d4b90be2a945d77e6905a/micrometer/src/main/java/feign/micrometer/MeteredDecoder.java#L65

**Comment by radio-rogal** [comment]
There is the fix #1548.
It has not been released yet.

**Comment by ErikKringen** [comment]
> There is the fix #1548.
> It has not been released yet.

#1548 Address `MeteredClient` only, this is in `MeteredDecoder` which has the same issue
