### ISSUE TITLE
Is there any way to replace the feign header 's value as "secret"?

### ISSUE THREAD

**Issue by MGunel** [OpenFeign/feign#1561]
Is there any way to replace the feign header's value in log ? I found the way to exclude headers from logs but I want to replace feign header's value as "secret" .I did this by overriding shouldLogRequestHeader method

**Comment by sakibulalam** [comment]
if you want to exclude secret values from the logs, why not configure your logger to mask those. We use `logback` and use `pathMask` and `valueMask` to mask sensitive values in the log.

**Comment by MGunel** [comment]
> if you want to exclude secret values from the logs, why not configure your logger to mask those. We use `logback` and use `pathMask` and `valueMask` to mask sensitive values in the log.

I use logbook for project but logbook. removeheader does not affect feign log  ,because feign log use slf4J  by default when it is logging.And So I can see sensitive data in log when request sent.

**Comment by MGunel** [comment]
I found [(https://github.com/OpenFeign/feign/pull/1530)](https://github.com/OpenFeign/feign/pull/1530)this .It is exculude but I want  to replace with"secret"

**Comment by radio-rogal** [comment]
@MGunel Logback can be used as implementation of slf4j: you can configure excluding as @sakibulalam said.

**Comment by kdavisk6** [comment]
Echoing @radio-rogal, You will need to provide your own `Logger` implementation for this sort of customized handling.  Our provided `Logger` implementations do not allow for pattern customization at this time.  Could be a good candidate for an enhancement.  If this is something you are interested in, feel free to submit a `proposal`.

**Comment by kdavisk6** [comment]
Given there's been no update or proposal, I'm assuming you are good.
