### ISSUE TITLE
#RESOLVED Client Certification file.pem and file.key

### ISSUE THREAD

**Issue by resplandes** [OpenFeign/feign#1566]
Hello, how is it possible to inform a file as client certificate equal in postman image using OpenFeign ?
![Screenshot_1](https://user-images.githubusercontent.com/3025776/149423211-58484af6-2dae-469f-9fca-bbc27363f06e.png)

**Comment by resplandes** [comment]
We need to make a request in a service that requires SSL certification, informing these two files with the request
![Screenshot_2](https://user-images.githubusercontent.com/3025776/149423421-7a845a7a-6a81-422f-8b5f-3ee4954f37c6.png)

**Comment by velo** [comment]
How would you do that with a non feign client?

**Comment by resplandes** [comment]
use feign client to consume endpoint

**Comment by radio-rogal** [comment]
```java
...
KeyStore keystore = KeyStore.getInstance(keystoretype);

keystore.load(certificateinputstream, keystorepassword);
socketfactory = SSLContexts.custom()
    .loadKeyMaterial(keystore, keystorepassword)
    .build()
    .getSocketFactory();
...
Feign.builder()
    .client(new Client.Default(socketfactory, (hostname, sslSession) -> "localhost".equals(hostname)))
...
```

**Comment by resplandes** [comment]
@radio-rogal 
Correct, but I have to use two certificates, a .PEM and a .key in the same request

**Comment by resplandes** [comment]
#SORTED OUT
you must use both certificates.

1-certificate .PEM
2 -certified .key

3- run the command to create the .p12 certificate

and use p12 in the request.
![Screenshot_1](https://user-images.githubusercontent.com/3025776/155181230-b3dab532-bbef-45da-a9e6-4925713993d3.png)

![Screenshot_3](https://user-images.githubusercontent.com/3025776/155181193-c5079cb1-4986-4481-afcc-b3ddf0ac7adf.png)
