### ISSUE TITLE
sundrio BOM plugin breaks build

### ISSUE THREAD

**Issue by radio-rogal** [OpenFeign/feign#1594]
The current version misses some methods:

> [ERROR] Failed to execute goal io.sundr:sundr-maven-plugin:0.40.1:generate-bom (default) on project parent: Error building generated bom:feign-bom: Could not create ReactorContext. org.apache.maven.session.scope.internal.SessionScope.memento()

New version of the plugin have not published dependencies or wrong their versions, related issue [308](https://github.com/sundrio/sundrio/issues/308):

> [ERROR] Failed to execute goal io.sundr:sundr-maven-plugin:0.50.4:generate-bom (default) on project parent: Execution default of goal io.sundr:sundr-maven-plugin:0.50.4:generate-bom failed: Plugin io.sundr:sundr-maven-plugin:0.50.4 or one of its dependencies could not be resolved: Could not find artifact **io.sundr:sundr-codegen:jar:0.50.4** in central (https://repo.maven.apache.org/maven2)

> [ERROR] Failed to execute goal io.sundr:sundr-maven-plugin:0.80.1:generate-bom (default) on project parent: Execution default of goal io.sundr:sundr-maven-plugin:0.80.1:generate-bom failed: Plugin **io.sundr:sundr-maven-plugin:0.80.1** or one of its dependencies could not be resolved: **io.sundr:sundr-codegen:jar:0.80.1** was not found in https://repo.maven.apache.org

**Comment by iocanel** [comment]
@radio-rogal: `io.sundr:sundr-codegen:jar` has been split into several modules, so it no longer exists. I also don't see it being referenced anywhere in the source code. 

A reproducer or even the output of `mvn dependency:tree` could help troubleshooting this.

**Comment by radio-rogal** [comment]
Sorry, it was my fault: the old version 0.40.1 has direct dependencies to codegen and I didn't remove it when increase version.

:(
