### ISSUE TITLE
Feign client returns null for non-nullable return value

### ISSUE THREAD

**Issue by Lunkers** [OpenFeign/feign#1595]
Hello,
I'm using a feign client that looks something like this:
```kotlin
@FeignClient("api", url = "\${api-url}", decode404 = true)
interface Client {

    @GetMapping("/api/article/{id}")
    fun getLatestRevision(
        @PathVariable("id") id: String,
    ): Optional<ArticleRevision>


    @GetMapping("/api/video/{id}/revision/{revision}")
    fun getRevision(
        @PathVariable("id") id: String,
        @PathVariable("revision") revision: Int
    ): ArticleRevision
}
```

The assumption that I'm making is that when the first method gets a 404 response, it should return `Optional.empty`, which it does. But since the return type of the second method is not nullable, I would assume that an exception would be thrown if the response is 404. However, this does not happen and the function just returns `null`. Is this expected behavior? Can I not use decode404 and expect a non-nullable return value to not be null?

**Comment by radio-rogal** [comment]
The documentation says: "This flag indicates that the {@link #decoder(Decoder) decoder} should process responses with 404 status, specifically returning null or **empty** instead of throwing....".

I think than the term _empty_ is regarding to collections, maps, strings and instances of `Optional`.

**Comment by radio-rogal** [comment]
And I have found the commit that changes behavior: #1012 

Also here is another issue and PR about decode404 flag: #1528 and #1529
