### ISSUE TITLE
Is it possible to customize the length of the body in FeignException?

### ISSUE THREAD

**Issue by jiahui-qin** [OpenFeign/feign#1606]
feign in master branch

I found that `FeignException` enforces the length of body not to exceed 400, use below two param:

```
    private static final int MAX_BODY_BYTES_LENGTH = 400;
    private static final int MAX_BODY_CHARS_LENGTH = 200;
```

Is there a way I can customize the length of these two variables to get more error messages?

Thank you!

**Comment by prashanth057** [comment]
I need this to. Any way to bump up the priority on this?

**Comment by velo** [comment]
Hi @prashanth057 , feign is mainly run by volunteers.  Either you need to get a volunteer interested to do it for you, or you file a PR for this and I will happily review it.

**Comment by ddeath** [comment]
This can be closed as the proposal was merged right?
