### ISSUE TITLE
Does openfeign support IPV6?

### ISSUE THREAD

**Issue by shenhongwei33** [OpenFeign/feign#1611]
I want to know if openfeign combined with eureka is suitable for IPV6 scenarios

**Comment by velo** [comment]
It should work just fine.

**Comment by wangchenglonggithub** [comment]
have you come to a conclusion @shenhongwei33

**Comment by kdavisk6** [comment]
Feign wraps the underlying components, so assuming that the HTTP Client or `Client` implementation used supports IPV6, you should be OK.
