### ISSUE TITLE
General question about AsyncClient

### ISSUE THREAD

**Issue by junhuhdev** [OpenFeign/feign#1617]
Are there any caveats of using the default async client? Also in my testing it seems like it is creating a thread per execution, is that the way it should behave? 

What is the underlying client implementation for the default async client? Does it perform well under pressure? 

Sorry for newbie questions, I was trying to read the code but had hard time understanding the implementation. 

What I am trying to answer is if AsyncClient is prod ready, I know it is experimental but still wondering what the general opinion is.

**Comment by velo** [comment]
> Are there any caveats of using the default async client? Also in my testing it seems like it is creating a thread per execution, is that the way it should behave?

You should give it a executor, it will reuse threads according to your executor.

> What is the underlying client implementation for the default async client? Does it perform well under pressure?

https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/AsyncClient.java

> What I am trying to answer is if AsyncClient is prod ready, I know it is experimental but still wondering what the general opinion is.

Yes, it is ready. Expirimental is more to indicate the API may change without warning

**Comment by velo** [comment]
you can try https://github.com/OpenFeign/feign/blob/master/hc5/src/main/java/feign/hc5/AsyncApacheHttp5Client.java

**Comment by junhuhdev** [comment]
thank you sorry last question, do u have an example how such configuration would look? I can see that u can pass an executorService to asyncClient?

This works 

```java
AsyncFeign.asyncBuilder()
				.options(options)
				.encoder(new GsonEncoder(gsonBuilder))
				.decoder(decoder)
				.requestInterceptor(new BasicAuthRequestInterceptor(integrationDetails.getUserName(), integrationDetails.getPassword()))
				.target(CcsFeignClient.class, "http://localhost:8080/api");
```

But when i add client seems it loses its typing, i need to cast, is it correct way?


```java
(TestClient) AsyncFeign.asyncBuilder()
				.client(new AsyncClient.Default(new Client.Default(null, null), executorService))
				.options(options)
				.encoder(new GsonEncoder(gsonBuilder))
				.decoder(decoder)
				.requestInterceptor(new BasicAuthRequestInterceptor(integrationDetails.getUserName(), integrationDetails.getPassword()))
				.target(CcsFeignClient.class, "http://localhost:8080/api")

```

**Comment by velo** [comment]
> Thank you @velo sorry last question, do u have an example how such configuration would look? 

Did you try taking a look on the README example?
https://github.com/OpenFeign/feign#async-execution-via-completablefuture
