### ISSUE TITLE
Is it incompatible with devtools

### ISSUE THREAD

**Issue by liuxinhaowan** [OpenFeign/feign#1624]
When devtools is integrated into a project with openfeign, the project cannot be started and an error is reported: cannot access its superclass org springframework. cloud. openfeign. HystrixTargeter

**Comment by kdavisk6** [comment]
Please provide a [minimal reproduceable example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates your issue along with the expected behavior and actual behavior observed.
