### ISSUE TITLE
Jakarta support for JAXRSContract

### ISSUE THREAD

**Issue by Hrozhek** [OpenFeign/feign#1635]
Since JAX-RS is substituted by Jakarta could you please consider adding support for Jakarta annotations. Currently using jakarta annotations like '@Path' causes IllegalStateException

**Comment by velo** [comment]
What do you mean by "JAX-RS is substituted by Jakarta"?

Any way, I would be happy to review a PR for a new Jakarta module!

Cheers

**Comment by Hrozhek** [comment]
Thank you for the fast reply! Probably I said it wrong what I meant was [so called transformation](https://lists.jboss.org/archives/list/resteasy@lists.jboss.org/thread/ZCXCCH76MNZ7LS2LPX3HHIVSUUTMVNVJ/), so new versions will be under the jakarta packages.
Will do then.
Best regards!

**Comment by Hrozhek** [comment]
https://github.com/OpenFeign/feign/pull/1649
