### ISSUE TITLE
openfeign and jaeger are incompatible

### ISSUE THREAD

**Issue by FIshInInnkGIT** [OpenFeign/feign#1702]
When I use attachment configuration：
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient

If there is no "opentracing-spring-jaeger-cloud-starter", it will be normal。or add "spring-cloud-openfeign-core", But this will lead to:
Caused by: java.net.ConnectException: Connection refused (Connection refused)

[xml version=1.md](https://github.com/OpenFeign/feign/files/9179577/xml.version.1.md)

**Comment by kdavisk6** [comment]
This appears to be an issue with Spring Cloud OpenFeign.  This project does not have the class you mention.  I recommend asking this question off the Spring Cloud OpenFeign team.
