### ISSUE TITLE
get request have double param

### ISSUE THREAD

**Issue by lxqing** [OpenFeign/feign#1709]
example：
``` java
@GetMapping(value = "/api/proxy/v106/uh5qyp14?headerStrategy=apiAuthHeader")
ActionResult<Object> scanTemplateUrlDetail(
   @RequestParam("imgUrl") String imgUrl, @RequestParam("templateId") String templateId);
```

```
api/proxy/v106/uh5qyp14?imgUrl=11&imgUrl=11&templateId=11&templateId
```

**Comment by kdavisk6** [comment]
Please provide a [minimal reproduceable example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates your issue.

Since your contract is provided by `SpringCloudOpenFeign` the issue _may_ be in how they are handling `@RequestParam` in this use case.
