### ISSUE TITLE
FeignMetricTagResolver lost Exception tag

### ISSUE THREAD

**Issue by pangengteng** [OpenFeign/feign#1716]
when call the method "feign.micrometer.FeignMetricTagResolver#tag(feign.MethodMetadata, feign.Target<?>, java.lang.Throwable, io.micrometer.core.instrument.Tag...)" as below, the "e" was lost as not pass to the inner method
  
public Tags tag(MethodMetadata methodMetadata, Target<?> target, Throwable e, Tag... tags) {
    return tag(methodMetadata.targetType(), methodMetadata.method(), target.url(), tags);
  }

**Comment by eshishkin** [comment]
Hi, I met the same issue in our project a couple of days ago. I created a PR (https://github.com/OpenFeign/feign/pull/1720), so it should solve the problem
