### ISSUE TITLE
`Flux` type reponse shoud be corresponding to `List`

### ISSUE THREAD

**Issue by CoderYellow** [OpenFeign/feign#1869]
the example [here](https://github.com/OpenFeign/feign/blob/d507ca3b1d19e7dd630e92e059af0ecdc75388ac/reactive/README.md?plain=1#L17) is not actually working with `JacksonDecoder`, got these errors:
```shell
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `feign.reactive.GitHubReactor$Contributor` from Array value (token `JsonToken.START_ARRAY`)
```
To support the json array response, I think we should wrap the response type to `List `for `Flux`, so that the decoder can decode it appropriately, some thing like [this](https://github.com/OpenFeign/feign/compare/master...CoderYellow:feign:feature/feign-reactor?expand=1)

**Comment by CoderYellow** [comment]
is it ok for pr

**Comment by velo** [comment]
Seems Jackson don't allow you to deserialize flux. Feign just delegates the job Jackson

**Comment by CoderYellow** [comment]
The key is, a json array response should be mapped to `Flux`, single object response should be mapped to `Mono`. So does rxjava, should use `Flowable` and `Single` respectively. We should do [this](https://github.com/OpenFeign/feign/blob/d507ca3b1d19e7dd630e92e059af0ecdc75388ac/reactive/README.md?plain=1#L108) for user transparently. That's what other framework like retrofit do. @kdavisk6, do you agree?
