### ISSUE TITLE
Can we set the root cause of exception in metrics?

### ISSUE THREAD

**Issue by chao-chang-paypay** [OpenFeign/feign#1882]
Setting the root cause(e.g. `SocketTimeoutException` ) as the tag value might be more helpful than the exception in feign layer(e.g. `RetryableException`)

https://github.com/OpenFeign/feign/blob/5b8cd4a1e7d1e3a0ab09002a84351369acd8ddd6/micrometer/src/main/java/feign/micrometer/FeignMetricTagResolver.java#L52

**Comment by velo** [comment]
That makes a lot of sense, feel free to make a PR for this change.

Cheers,
