### ISSUE TITLE
Different Trace ID for same request in two services

### ISSUE THREAD

**Issue by deadpool1418** [OpenFeign/feign#1893]
Hi,

I am trying to achieve distributed tracing using micrometer and for inter service communication I'm using Feign Client. But when I try to call Service A and Service A is making a internal call to Service B, I get different trace id's in the services. But when I use rest template instead of feign client I get the same trace id. I think feign client is not propagating the trace id to the other service.

I have following dependencies in my pom.xml file and I'm using spring boot 3.0.0-snapshot.
`

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-openfeign</artifactId>
			<version>3.1.5</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-micrometer</artifactId>
			<version>12.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-tracing-bridge-brave</artifactId>
		</dependency>
		<dependency>
			<groupId>io.zipkin.reporter2</groupId>
			<artifactId>zipkin-reporter-brave</artifactId>
		</dependency>

`

This is my feign client.

@FeignClient(name = "registration-onboarding-service", path = "/applicant")
public interface RegistrationClient {

    @GetMapping("/{uId}")
    UserResponse find(@PathVariable String uId);
}

And this is the way I'm calling the find method using the client created.

    @Autowired
    private RegistrationClient registrationClient;

 UserResponse userResponse = registrationClient.find(product.getUserId());

**Comment by DeepuGeorgeJacob1** [comment]
I am facing same issue with above configuration
