### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by adriancole** [OpenFeign/feign#190]
Occasionally, concerns about performance tradeoffs arise. I think we should have the following. pull requests or other ideas welcome.
- Core MicroBenchmarks - Feign core could be tested for efficiency wrt runtime, allocation etc. As feign core is used by all, we can ensure we don't degrade feign without knowing it. This would test components, and not likely make I/O calls. Years ago I did something [similar with caliper](https://github.com/adriancole/playground-caliper), but this is probably best accomplished with JMH.
- Integration Benchmarks - compares a native http/s client (ex ribbon or okhttp) vs the feign integration. This would show overhead and make it possible to compare choices in context of actual http calls. For example, this could show whether a choice of lock matters or Is completely washed out by implementation In the native library. Similar code exists in [OkHttp Benchmarks](https://github.com/square/okhttp/tree/master/benchmarks).

**Comment by adriancole** [comment]
@bstick12 I jotted this down wrt some of your recent and valid commentary. Feel free to make a start if doing something like this is of interest.

**Comment by foezor** [comment]
@adriancole since it has been add now can we close this issue? i also think maybe i should launch it for the build performing by @velo

**Comment by foezor** [comment]
Hello @adriancole can you close this issue i think the point have already been done.

**Comment by adriancole** [comment]
thx for the ping
