### ISSUE TITLE
'target' and 'feignTarget' are not rewrite at the same time

### ISSUE THREAD

**Issue by solio** [OpenFeign/feign#1923]
https://github.com/OpenFeign/feign/blob/0d0f724068371ae48b338c6cfbb771e15cf8fece/core/src/main/java/feign/RequestTemplate.java#L521

'target' and 'feignTarget' are not rewrite at the same time. 
It make some misunderstand

**Comment by kdavisk6** [comment]
I don't see a question here related to rewriting or a question at all.  Feel free to re-open if you have more context.
