### ISSUE TITLE
The header expander uses the toString() method of header object and i cannot prevent it

### ISSUE THREAD

**Issue by fatemehe** [OpenFeign/feign#2037]
Hi. I have an api like this:
```
@PostMapping(value= “/test”)
public void test(@requestHeader Context context){};
```

And I configured a feign client for my api. But when I call it from another project through feign client, somewhere through the process (I think in an expanding method for header expanding), the feign calls the .toString() method in my Context class and I don’t want this to be happening. is there any way to prevent feign from calling the toString() method?

**Comment by kdavisk6** [comment]
Feign is responding to the configuration provided by the Spring Cloud OpenFeign Contract parsing around the `RequestHeader` annotation is provides.  I recommend asking that team to help out.

However, if you have `Logging` set to the highest level in Feign, Headers are resolved and converted to Strings before being logged.  You may want to review your Feign logging level configuration.  https://github.com/OpenFeign/feign#logging
