### ISSUE TITLE
Logging shows wrong HTTP protocol

### ISSUE THREAD

**Issue by FouquerYohann** [OpenFeign/feign#2064]
In feign.SynchronousMethodHandler#executeAndDecode 

The request constructor default to HTTP protocol 1.1 
then it's logged 
And only afterward the client execute changes it to protocol version 2.0

![image](https://github.com/OpenFeign/feign/assets/11458469/7939b57f-f5d3-4113-9e73-1099982316a7)

note : I'm using Http2Client but that should still be true for other clients

**Comment by radio-rogal** [comment]
When the request was processed by the client, did the client update the protocol or is it the same?

It looks like an unrecoverable issue as the client shouldn't change the request object as it changes the protocol in its own conversation with a remote guest.

**Comment by radio-rogal** [comment]
There are two problems:
- we cannot create a request with HTTP2 version,
- we cannot update the request version to HTTP2.

Even if a client (Apache or java11) wants to update the version after it raised it in a physical dialogue with a server - it cannot do so.

**Comment by kdavisk6** [comment]
The logger is hard-coded and corrected by #2097
