### ISSUE TITLE
Reuse HttpContext in ApacheHttpClient for pooled mTLS connections

### ISSUE THREAD

**Issue by ugrepel** [OpenFeign/feign#2114]
I'm currently working on setting up mTLS for our OpenFeign + Apache HttpClient based clients. I noticed that HttpClient requires a HttpContext (HttpClientContext to be precise) object being passed into its execute methods, which OpenFeign's ApacheHttpClient does not.
Without such an HttpContext object, the pooling of mTLS based connections won't work, since HttpClient stores the client certificate in that HttpContext object, and without this the new execution will not use an existing mTLS connection in the pool.
HttpContext or rather the objects stored in it aren't thread safe, so one must take care to not use one in more than one thread at once.
I locally patched ApacheHttpClient to maintain a pool (using a ConcurrentLinkedDeque) of HttpClientContext objects and the connection pooling works for me. However I don't know whether the other stuff stored in HttpContext (e.g. Cookies) might cause problems for other people.
I could create a pull request if this is of general interest. Code snippet:

```
  Deque<HttpContext> httpContexts = new ConcurrentLinkedDeque<>();

  @Override
  public Response execute(Request request, Request.Options options) throws IOException {
    HttpUriRequest httpUriRequest;
    try {
      httpUriRequest = toHttpUriRequest(request, options);
    } catch (URISyntaxException e) {
      throw new IOException("URL '" + request.url() + "' couldn't be parsed into a URI", e);
    }

    // providing an HttpContext (which is not thread safe, thus the deque) allows connection pooling on
    // mTLS connections which otherwise will never be reused since they do not know that they'll use the
    // same client certificate.
    final HttpContext httpContext = getHttpContext();
    HttpResponse httpResponse;
    try {
      httpResponse = client.execute(httpUriRequest, httpContext);
    } finally {
      putHttpContext(httpContext);
    }

    return toFeignResponse(httpResponse, request);
  }

  private HttpContext getHttpContext() {
    final HttpContext httpContext = httpContexts.poll();
    if (httpContext != null) {
      return httpContext;
    } else {
      return new HttpClientContext();
    }
  }

  private void putHttpContext(final HttpContext httpContext) {
    httpContexts.add(httpContext);
  }
```

**Comment by dfjmax** [comment]
@ugrepel did you find any other way of making mTLS connection pooling work? Or you are still using the patched client above?

**Comment by ugrepel** [comment]
I am actually not using the patched client - it has its own problems unfortunately, since once-only 401 responses despite credentials being there resulted in the HttpContext to remember that 401 failure and then never again even trying to send the credentials (in our case basic authentication, with or without preemptive basic authentication).

Instead, I now create a wrapper around the http client that issues a new HttpContext each time (so the 401 failure is not remembered) and calls setUserToken("whatever"); on it before using it. The actual token itself doesn't matter, it just must be the same value as in the call that actually created the then-pooled connection.

The wrapper class holds the real HttpClient object as a delegate and delegates all calls to the delegate, but for those execute call versions that do not have a context param, it adds a context as described above.

The "real patch" required in OpenFeign would be to not call execute without a context, but always with a context including a set value for the user token.

Handling of cookies and other things done with the HttpContext would still not be there, but a patch wouldn't change that from the current behaviour.

**Comment by dfjmax** [comment]
@ugrepel thanks for the reply. 

I have been doing a bit more research. I was able to reuse the pool by disabling the connectionState in the HttpClient:

```
    public CloseableHttpClient getHttpClient(SSLContext sslContext) {
        return HttpClients.custom()
                .disableConnectionState()
                .setConnectionManager(createHttpConnectionManager(sslContext))
                .build();
    }
```

This should work well for a client that does not have to support multiple user identities.

**Comment by ugrepel** [comment]
@dfjmax thanks for this!

This seems like the correct solution while mine was just fooling around the symptoms...

It seems that instead of using .disableConnectionState() you could also use .setUserTokenHandler() with an appropriate handler that fulfil more specific needs than the NoopUserTokenHandler used by disableConnectionState could offer. But as you said in most cases, the NoopUserTokenHandler should actually be sufficient.

The NoopUserTokenHandler also has, since it basically does just nothing, have the slight benefit of being a tiny little bit faster :-). (I've just been - successfully - fighting for fractional microsecond performance gains in some completely different area...).

**Comment by kdavisk6** [comment]
Looks like you all figured it out.
