### ISSUE TITLE
Timeline of 12.4 release

### ISSUE THREAD

**Issue by N4zroth** [OpenFeign/feign#2120]
Is there any (however rough) timeline on the 12.4 release? We kinda need it and are debating if forking and building a company-intern release to bridge the gap until the official release is out but we would obviously want to avoid that if the release is somewhat close.

**Comment by velo** [comment]
Thanks for the nodge in the head:

https://github.com/OpenFeign/feign/releases/tag/12.4

https://repo1.maven.org/maven2/io/github/openfeign/feign-core/12.4/

**Comment by N4zroth** [comment]
Oh wow thanks!
