### ISSUE TITLE
[bug]the parm will lost '=' when it's value is empty string

### ISSUE THREAD

**Issue by 24kpure** [OpenFeign/feign#2122]
https://github.com/OpenFeign/feign/blame/2cb72cf3fa6e760a9596aed099f7e83da950360b/core/src/main/java/feign/template/QueryTemplate.java#L86
Example  detail just see #910.

My query params  are  {"key1":"","key2":"value2"}
```
//expect
http://url?ke1=&key2=value2
//actual
http://url?ke1&key2=value2
```

**Comment by 24kpure** [comment]
Please assign to me.

**Comment by kdavisk6** [comment]
Not a bug, but expected behavior. See https://github.com/OpenFeign/feign#undefined-vs-empty-values

**Comment by 24kpure** [comment]
@kdavisk6   Thanks for your response. I have read your url in detail,but the doc mean nothing to myquestion.Please reread my issue description,it is a bug which is brought in a refactor commit.

**Comment by 24kpure** [comment]
@kdavisk6 Reopen the issue，please.
