### ISSUE TITLE
Impossible to overload method with inner class parameters

### ISSUE THREAD

**Issue by Kabal163** [OpenFeign/feign#2144]
Problem:
I have feign with two methods. Methods have the same name but different parameter types:
```
public interface MyFeign {

   @RequestLine("POST /api/v1/service/create")
   void create(Models.Request request);

   @RequestLine("POST /api/v1/service/inner/create")
   void create(Models.Inner.Request request);
}

class Models {

   static class Request {
      // fields etc
   }

   static class Inner {
       static class Request {
          // fields etc
       }
   }
}
```

I expect that each method sends request to the specified URL but it doesn't. The problem is in the [Contract.BaseContract#parseAndValidateMetadata](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Contract.java#L98) because it uses the method [Feign.configKey](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Feign.java#L73) which resolves key not considering the full class name of parameter. Inside the `Feign.configKey` we have such instruction Types.getRawType(param).**getSimpleName()** which lead to the next key for both methods: `MyFeign#create(Request)`. As a result my feign has only one handler for both methods. This issue is floating because each time it has different handler, depending on the order of introspected methods.

**Comment by kdavisk6** [comment]
This type of inheritance is not supported in Feign.  Only simple single level inheritance from interfaces is supported.
