### ISSUE TITLE
希望在编译阶段生成Controller调用相关代码

### ISSUE THREAD

**Issue by zjarlin** [OpenFeign/feign#2149]
<img width="310" alt="image" src="https://github.com/OpenFeign/feign/assets/67467679/2bc0fcfc-7730-43e6-879e-f69bf21e41a0">
<img width="243" alt="image" src="https://github.com/OpenFeign/feign/assets/67467679/b67ce511-ca18-4bca-ba5a-e54af2c5f2d7">
加了这个注解,可以在编译时在源码目录对ExampleApi生成ExampleController,ExampleController中注入ExampleApi进行调用;
rest路径就采用ExampleApi中定义的即可

**Comment by velo** [comment]
Poootz, agora pegou


[image: --]

Marvin Froeder
[image: https://]about.me/velo
<https://about.me/velo?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
