### ISSUE TITLE
Add Moshi as a Feign Module 

### ISSUE THREAD

**Issue by vikadilly** [OpenFeign/feign#2176]
Hello team, 

I wrote a custom Feign module which adds support for encoding and decoding JSON using Moshi (https://github.com/square/moshi) 

I noticed that it's not supported by Feign and it's a popular project with over 9.2k stars. 

I am happy to tidy it up and create a code contribution for it. Is this something the maintainers would like ?

**Comment by velo** [comment]
Absolutely yes.

Make a PR for a new module I would happily review it.

Cheers
