### ISSUE TITLE
Feign Error

### ISSUE THREAD

**Issue by DobreMihai-echo** [OpenFeign/feign#2180]
Soo, I am using the following api endpoint:

@GetMapping(value="/api/data)
ResponseEntity<Data> getData(@AuthenticationPrincipal currentAuthenticatedUser, HttpServletRequest request);
This endpoint returns the following error when called through feign in a different microservice:

"Method has too many Body parameters".
Am I missing something? Because I don't use the @RequestBody and I don't use a body when calling my endpoint anyway. So why is this error being thrown?

**Comment by gromspys** [comment]
It looks like `@AuthenticationPrincipal` is not supported. See: https://github.com/OpenFeign/feign/tree/master/spring4#currently-supported-annotation-processing
