### ISSUE TITLE
RetryableException is ambiguous

### ISSUE THREAD

**Issue by Hagbards** [OpenFeign/feign#2217]
Hi. 

I'm using Version 13 and JDK 21.

I get a new error lately in my generated sources.

It says RetryableException is ambitious in:

`public class ApiErrorDecoder implements ErrorDecoder {

    private final Default defaultErrorDecoder = new Default();

    @Override
    public Exception decode(String methodKey, Response response) {
        //401/403 response codes most likely indicate an expired access token, unless it happens two times in a row
        Exception httpException = defaultErrorDecoder.decode(methodKey, response);
        if (response.status() == 401 || response.status() == 403) {
            return new RetryableException(response.status(), "Received status " + response.status() + " trying to renew access token",
                    response.request().httpMethod(), httpException, null, response.request());
        }
        return httpException;
    }
}`

I think it is because it generates a null where it can have either a long or a date Value. Is there a way i can fix it?

**Comment by velo** [comment]
You just need to cast your null to `byte[]` and should be fine
