### ISSUE TITLE
Is It possible to configure connectTimeout and readTimeout options per method request

### ISSUE THREAD

**Issue by IgorGudkov** [OpenFeign/feign#2230]
I know that it is possible to configure specific config by client name or default ones, using Spring like:

```
spring.cloud.openfeign.client.config.MyClient.connect-timeout=1000
spring.cloud.openfeign.client.config.MyClient.read-timeout=2000
```

Is it possible to do it per method key? Tried this configs below, and it don't work.  Does such config works and what is the correct syntax? Thanks for answer in advance.

```
spring.cloud.openfeign.client.config.MyClient#getSomething(String).connect-timeout=1000
spring.cloud.openfeign.client.config.MyClient#getSomething(String).read-timeout=2000
```

**Comment by gromspys** [comment]
I hope you can use Options in your methods like:
````
@GET
@Path("/withOptions")
public String getSomething(Options options);
....
Options options = new feign.Request.Options(1, SECONDS, 1, SECONDS, followRedirects)
client. getSomething(options)
````

See example here: https://github.com/OpenFeign/feign/blob/master/httpclient/src/test/java/feign/httpclient/ApacheHttpClientTest.java#L120

**Comment by IgorGudkov** [comment]
Works for me thank you!
