### ISSUE TITLE
[Question] Can I disable pct-encoding for @RequestLine

### ISSUE THREAD

**Issue by Psimage** [OpenFeign/feign#2238]
I have a use case where URI comes from external source in the string format and is already pct-encoded.

I defined my interface like this:
```Java
    @RequestLine("GET {path}")
    String getMeStuff(@Param("path") String path);
```

But when `path` variable expands, it will be pct-encoded by Feign.
This results in "double encoding".

Is there a way to pass `path` variable `as is` to Http Request line?

**Comment by velo** [comment]
If you have one parameter that is a URI, that will be used as you base URL for a request


```
    @RequestLine("GET /")
    String getMeStuff(URI uri);
```

https://github.com/OpenFeign/feign/blob/eff49d7fe3965953642275bf7ad8115579a08399/core/src/main/java/feign/Contract.java#L137

**Comment by Psimage** [comment]
Thanks @velo. It works, but with small correction.
I had to remove the `/` in request line, overwise it added a trailing slash
```
    @RequestLine("GET")
    String getMeStuff(URI uri);
```

**Comment by Psimage** [comment]
Is this within an expected usage scenario or we rely on current internal implementation that might change?
