### ISSUE TITLE
Can't set request header in json format

### ISSUE THREAD

**Issue by hyfsy** [OpenFeign/feign#2252]
![image](https://github.com/OpenFeign/feign/assets/46069922/8e09ffdc-ec62-48b8-9713-71bedd42b3f5)

**Comment by hyfsy** [comment]
spring-cloud-starter-openfeign: 3.1.4
feign-core: 11.8

**Comment by lquterqtd** [comment]
{"a":"b""c"}
这不是一个合法的json格式吧?
试试{"a":"b\"\"c"}

**Comment by hyfsy** [comment]
Regardless of whether the json format is correct or not, the example I gave above already shows that the header has been parsed as the wrong string, my problem is that the header should support json format, and should not be parsed as a template even if it has `{}`. In addition, the link you gave is the URI Template specification, not the HTTP Header specification which is showed here: https://datatracker.ietf.org/doc/html/rfc2616#section-4.2

**Comment by raizoor** [comment]
@hyfsy 

Please see that -> https://github.com/OpenFeign/feign/issues/1987

It seems the same problem..

**Comment by hyfsy** [comment]
It's the same problem, but it hasn't been solved
