### ISSUE TITLE
Support multiple methods of parameter expansion

### ISSUE THREAD

**Issue by tburch** [OpenFeign/feign#234]
Would it be possible to support other forms of parameter expansion? My use case is that I have a JAX-RS annotated interface like:

```
public interface WeatherService {
  String WEATHER_BASE_CONTEXT = "/weather";
  String WEATHER_TIMESTAMPED_CONTEXT = "/timestamp";
  @GET
  @Path(WEATHER_BASE_CONTEXT + WEATHER_TIMESTAMPED_CONTEXT)
  DailyWeather retrievePointInTimeForecast(@QueryParam("lat") double latitude, @QueryParam("lng") double longitude, @QueryParam("ts") DateTime timestamp);
}
```

On the server side, I can use Jersey2/Jackson with a custom `ParamConverterProvider` to deserialize the `ts` param into a `DateTime`. It would be great if I could reuse the `ParamConverterProvider` to serialize the `DateTime` into the `ts` parameter for the request that Feign is building.

I don't think I saw a way to plug something like this into Feign, but maybe I missed it. If not, I'd be willing to give it a shot at the implementation if you're open to a PR. Any pointers as to where to start would be appreciated.

**Comment by adriancole** [comment]
To be clear, are you asking specifically about jaxrs?

Recently, we added `@Param(expander=..` for this purpose when using feign
annotations.

**Comment by tburch** [comment]
Yeah, I was thinking it could be an additional piece in the `Contract` for how parameters are handled/expanded. So for the JAX-RS contract I could easily hook in one or more `ParamConverterProvider` implementations.

**Comment by adriancole** [comment]
Long brain-dump below. TL;DR; try using InvocationHandlerFactory

I'd like to see if we can address this in a way that works with how the base code works. That might mean refactoring the base code.

ParamConverter is very similar, though more widely defined than Param.Expander (as ParamConverter needs to work server-side whereas Param.Expander does not).

Currently, Param.Expander implementation works like this.
 1. Param.Expanders are parsed in the default contract and stored in MethodMetadata.
  * Note that this is stored as a map of classes to instantiate, as MethodMetadata intends to be serializable and not use any unknown types. This design constraint was here to support compile-time generation of MethodMetadata, given annotated interfaces, something never actually attempted.
 2. `BuildTemplateByResolvingArgs`, a factory, instantiates these and uses the same expander instances for all invocations.

The concern is not making a `Param.Expander` out of a `ParamConverter`. that's basically delegating `Param.Expander#expand` to ParamConverter#toString`

The key concern area is that the current implementation of feign expects a concrete class per Param.Expander, whereas `ParamConverter` is a result of a call of `ParamConverterProvider`. We can get as far as invoking `ParamConverterProvider#getConverter` during jaxrs contract processing, but we hit a wall as MethodMetadata wants to store the *class* of Param.Expander, not an instance of it. 

Stepping back, Jaxrs doesn't know `ParamConverterProvider` until runtime. AFAICT, jaxrs doesn't process ParamConverters using annotations. `ParamConverterProvider` is more like a generic Encoder. Hence, I think it is not a good fit to try an use contract/methodmetadata to support ParamConverterProvider integration.

I can see how `Contract` integration approach seems convenient: that's how the current JaxRS implementation is stitched-in. However, this is not a straight-forward way to achieve  `ParamConverterProvider` integration. In fact, most of feign cannot access the runtime type information ParamConverterProvider needs. The only way I can think of for doing this is using `InvocationHandlerFactory`.

`ParamConverterProvider#getConverter(Class<T>, Type, Annotation[])` could woven in using InvocationHandlerFactory (at least for now), basically changing the values of `argv` in `MethodHandler.invoke()`
 * One way or another, this would work, as InvocationHandlerFactory has access to the reflect `java.lang.reflect.Method` object `ParamConverterProvider` needs.
  * Conversely, this doesn't require changing MethodMetadata to now store the input to contract processing, nor affecting the tree of logic around `ParseHandlersByName`.
 * This style of integration was added for [halfpipe's Hystrix support](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-client/src/main/java/halfpipe/client/HystrixInvocationHandler.java) cc @spencergibb
 * Using this style of integration will buy time to focus on the "integrated stacks" idea which could better implement this in the future #220.
  * Put another way, we can't afford to change the whole core of feign to support one feature of jaxrs. If we need to do big refactoring, we should take into account similar feature requests from other stacks.
