### ISSUE TITLE
Even using OptionalDecoder I get an exception on 404

### ISSUE THREAD

**Issue by ramgom** [OpenFeign/feign#2340]
Given this feign client:

`interface UserClient {

    @RequestLine("GET /users/{name}")
    fun getUser(@Param("name") name: String): Optional<User>
}`

`val userClient = Feign.builder()
        .encoder(JacksonEncoder(objectMapper))
        .decoder(OptionalDecoder(JacksonDecoder(objectMapper)))
        .target(UserClient::class.java, BASE_URL)
`

when I unit test this:

`
WireMock.stubFor(
            WireMock.get("/users/test")
                .willReturn(WireMock.notFound())
        )

        userClient.getUser("test")
`

I'm getting this exception: [404 Not Found] during [GET] to [http://localhost:7070/users/test] [UserClient#getUser(String)]: []

And I was expecting to actually get an empty optional.

**Comment by gromspys** [comment]
@ramgom try to use dismiss404():
```
val userClient = Feign.builder()
    .dismiss404()
    .encoder(JacksonEncoder(objectMapper))
    .decoder(OptionalDecoder(JacksonDecoder(objectMapper)))
    .target(UserClient::class.java, BASE_URL)
```
I think it should help you.

**Comment by kdavisk6** [comment]
@ramgom you can find this information in our Documentation.
