### ISSUE TITLE
@PatchMapping and @DeleteMapping insert unwanted slash when using url and specific value

### ISSUE THREAD

**Issue by MarcelTon** [OpenFeign/feign#2347]
Replicate problem:

Pom relevant deps:
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2022.0.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-hc5</artifactId> <!-- Required to use PATCH over default HttpURLConnection -->
        </dependency>
```

Config in `application-local.properties`
```
feign.patch.url=https://subdomain.address.com/endpoint
```

Client:
```
@FeignClient(name = "test-client", url = "${feign.patch.url}")
public interface TestClient {
    @PatchMapping(value = "('{id}')")
    void patchTest(@PathVariable String id, @RequestBody TestDto dto);

    @DeleteMapping(value = "('{id}')")
    void deleteTest(@PathVariable String id);
}
```

Expected behaviour is a call from `client.patchTest(id, dto)` results in a call to:
`https://subdomain.address.com/endpoint('id')`
Measured behaviour however is a call to:
`https://subdomain.address.com/endpoint/('id')`
introducing an additional slash and creating a bad request for both the `PATCH` and the `DELETE`, `GET` and `POST` do not exhibit this.

Desired behaviour is no magic slash.

**Comment by velo** [comment]
You probably want to raise that with spring tem

**Comment by MarcelTon** [comment]
If you think that's the best place I will @velo - thnx. Spring has so many repo's, where would you place this one (as I am not fully sure which exact project causes this)?

**Comment by MarcelTon** [comment]
Ticket opened for Spring team: https://github.com/spring-cloud/spring-cloud-openfeign/issues/1004
