### ISSUE TITLE
did we forget to publish version 13.3 to maven central?

### ISSUE THREAD

**Issue by maosi** [OpenFeign/feign#2453]
in maven central, the latesd version is 13.2.1

![image](https://github.com/OpenFeign/feign/assets/3891505/c0334d64-768d-41f8-866b-6db8d44523a0)

**Comment by derklaro** [comment]
13.3 is available in central now: https://repo1.maven.org/maven2/io/github/openfeign/feign-core/13.3/

**Comment by velo** [comment]
Sweet, thanks for reporting it
