### ISSUE TITLE
Feign Client and Jakarta, where? Jaxrs3Contract extends Jaxrs2Contract

### ISSUE THREAD

**Issue by okrische** [OpenFeign/feign#2481]
I am bit lost. So i migrate an API annotated with Java's JAX-RS annotations to the one from Jakarta. Instead of openfeign-jaxrs2 i thought i have to use openfeign-jaxrs3 or openfeign-jakarta. But they all seem to use the jaxrs2 stuff. Is this even implemented? Or am just blind? :)

**Comment by velo** [comment]
Yes, it uses byte code transformation black magic

**Comment by okrische** [comment]
Thx! Sorry for the noise!
