### ISSUE TITLE
@EnableFeignClients does not detect feign bean in multi-module.

### ISSUE THREAD

**Issue by young0264** [OpenFeign/feign#2522]
Hi, I have discovered issue.
In a multi-module Spring Boot project, when @EnableFeignClients is configured in the main application class, it does not detect Feign clients defined in other modules. 

// ========== gradle code ============
`
implementation project(':common-lib')
`
//================================

In a situation where a module references a library module like common-lib using implementation project(':common-lib'), the beans are not being detected.

However, when explicitly setting the package path in @EnableFeignClients(ex: @EnableFeignClients("org.project")), it successfully scans and registers Feign clients from other modules. 

I'm curious whether this is the intended behavior or if it might be an issue.

If this behavior is not intentional, it would be helpful to document it in the related documentation.

**Comment by Nazukin-Dmitry** [comment]
In my opinion this question should be addresed to [spring-cloud-openfeign](https://github.com/spring-cloud/spring-cloud-openfeign) project. Auto registration of feign clients is implemented there. I think this [class](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java) does it.

As I understand, package of @EnableFeignClients annotated class and subpackages are scanned, if packages are not specified explicitly.
For example, if annotated class is in package `org.project.app` and feign clients are in package `org.project.clients`, then feign clients are not registered. If feign clients are in package `org.project.app.clients`, then they are registered.

**Comment by kdavisk6** [comment]
@Nazukin-Dmitry is correct here.  `EnableFeignClients` is supported through Spring Cloud OpenFeign, I recommend you reach out through their support channels.  However, if it is discovered the issue is in our libraries, feel free to re-open this issue.

**Comment by young0264** [comment]
[https://github.com/spring-cloud/spring-cloud-openfeign/issues/1053](https://github.com/spring-cloud/spring-cloud-openfeign/issues/1053)

I have raised an issue in the Spring Cloud OpenFeign repository and added additional explanations to the guide. Thank you for taking interest in this issue. : )
