### ISSUE TITLE
Is feign-vertex project dead?

### ISSUE THREAD

**Issue by jakub-bochenski** [OpenFeign/feign#2569]
The repository isn't archived or anything, but:
https://github.com/OpenFeign/feign/issues/2568
https://github.com/OpenFeign/feign/issues/2567
https://github.com/OpenFeign/feign-vertx/issues/21

**Comment by hosuaby** [comment]
Hello @jakub-bochenski 

No `feign-vertx` is not dead and even regularly maintained. You opened your first two issues in the wrong project, this is why I didn't noticed that. I will check them soon.

**Comment by velo** [comment]
Hi @hosuaby , thanks for chasing this 

BTW, do you think it would make sense to nerve vertex into the main project? 

If we do so, I would give you maintener powers on the main project. 

Lemme know what you think

**Comment by hosuaby** [comment]
Hello @velo 

Even if I find the proposal of merging this extension into the main project flattering, I don't think this is a good idea from a technical perspective. First, vertx is coming with its own unique implementation of reactive programming, based on Vertx Futures, that are different from both `Observable`s from RxJava and `Future`s of JDK. If I were a core feign maintainer, I would be rather focused on integration with more universal RxJava, if it was not done yet.

The second reason, my work on this project for the last couple of years was a maintenance of an intricate dependency matrix, constantly bridging the gap between ever-shifting versions of both feign and vertx. And will not be able to do that with the same ease if the project will become the part of the core.

So I rather suggest to keep this project separately like now, and meanwhile I will check requests left by @jakub-bochenski .

**Comment by jakub-bochenski** [comment]
> No feign-vertx is not dead and even regularly maintained. You opened your first two issues in the wrong project, this is why I didn't noticed that. I will check them soon.

It's often unclear where to open those issues. Many projects only track issues in the main one and not in subprojects.

**Comment by jakub-bochenski** [comment]
> If I were a core feign maintainer, I would be rather focused on integration with more universal RxJava, if it was not done yet.

Feign already has support for async programming, I think it would be good to rewrite the feign-vertex project to accommodate that model instead of rolling it's own.

Here is my attempt to make Vertex HTTP Client work with Feign Async client directly: https://stackoverflow.com/q/79039589/1237617

**Comment by velo** [comment]
> If I were a core feign maintainer, I would be rather focused on integration with more universal RxJava, if it was not done yet.

I see no problem with that, as long we keep compatibility with existing functionality

> intricate dependency matrix, constantly bridging the gap between ever-shifting versions of both feign and vertx

Yeah, I noticed the same think with other modules, like feign-forms.... by merging to main project you no longer have the feign side of equation.
