### ISSUE TITLE
Publish relocation info on Maven Central for feign-form* modules

### ISSUE THREAD

**Issue by DidierLoiseau** [OpenFeign/feign#2598]
Since the `groupId` has changed from [`io.github.openfeign.form`](https://mvnrepository.com/artifact/io.github.openfeign.form) to `io.github.openfeign` for `feign-form` and `feign-form-spring` (and `parent`), it would be nice to publish relocation details on Maven Central to help guide people upgrading.

See also OpenFeign/feign-form#123

**Comment by velo** [comment]
Feign forms is the right place for it

**Comment by DidierLoiseau** [comment]
@velo, the [README over there](https://github.com/OpenFeign/feign-form?tab=readme-ov-file#form-encoder) says the right place is here though:

>  IMPORTANT: the repository is inactive and was merged with the main feign project.

Clearly, this indicates that asking over there is not the right place for it and is useless (that repo should probably be archived).

The change of groupId also comes from here (212324a4f337a0536af9f1416fe7e1c4de52e138) and not from there.

Maybe @xxlabaza, who added the note in the feign-form’s README, could suggest what to do?
