### ISSUE TITLE
implement Observable

### ISSUE THREAD

**Issue by codefromthecrypt** [OpenFeign/feign#27]
making this v4 so that we can delete IncrementalCallback :)

If viewed in the light that Iterator is to Observer as Iterable is to Observable, the essential relationships needed to make a functional Observer pattern are relatively tight.
- add Subscription interface, with a single method `unsubscribe()` which means "stop giving me stuff!"
- rename IncrementalCallback to Observer
- return Subscription on methods that accept an Observer param.
  - This is the Async equiv to returning a lazy Iterator from a single http request
  - ex. `Subscription contributors(String account, String repo, Observer<Contributor> contributors);
- allow Observable as a return type
  - Observer has a single method: `Subscription subscribe(Observer<T> observer);`
  - each time subscribe is called, a new http request is sent and the observer observes that.
  - This is the Async equiv to an Iterable, where each Iterator is a new http request

**Comment by allbutone** [comment]
does Feign support Observable now ?

**Comment by adriancole** [comment]
https://github.com/OpenFeign/feign/tree/master/hystrix can return observables
