### ISSUE TITLE
Document the fact that query params are removed from query line if null

### ISSUE THREAD

**Issue by stromnet** [OpenFeign/feign#277]
If I have (borrowed from unittest)

```
   interface WithPathAndQueryParams {                                                                                            

     @RequestLine("GET /domains/{domainId}/records?name={name}&type={type}")                                                     
     Response recordsByNameAndType(@Param("domainId") int id, @Param("name") String nameFilter,                                  
                                   @Param("type") String typeFilter);                                                            
   }                                                                                                                             
```

and call

.recordsByNameAndType(1, "name", null)

the executed HTTP request will be "GET /domains/records?name=name", and &type= will be stripped.

As far as I can see, this was not documented anywhere. At least not main readme where most of feign is documented otherwise.

**Comment by adriancole** [comment]
I suppose that doc would go in the RequestLine javadoc, right?

**Comment by stromnet** [comment]
Seems right, yes!
Couldn't find any javadoc link from README.md though. And not much mention of query params at all really.

**Comment by adriancole** [comment]
So, maybe link README to the source for now? That way at least we don't
replicate work. I don't think we are hosting javadocs anywhere...

**Comment by kdavisk6** [comment]
Related to #772

**Comment by kdavisk6** [comment]
Readme has been updated and now indicates what values are kept and what are omitted during expansion.
