### ISSUE TITLE
No way to encode slashes with JAXRSContract

### ISSUE THREAD

**Issue by davidscottcohen** [OpenFeign/feign#285]
In my application, it is legal for some method parameters to contain slashes.  In order to use path parameters, I need the slashes to be URL encoded.  However, the only way to mess with RequestTemplate.decodeSlash(boolean) is through the Contract, and the JAXRSContract does not allow this.  In particular, JAXRSContract is final and does not provide any direct way to modify the template.

In case this is helpful, I solved this locally by forking JAXRSContract and modifying as follows:

```
    public enum EncodeSlashBehavior {
        ENCODE, DECODE
    }

    @Override
    protected MethodMetadata parseAndValidateMetadata(Class<?> targetType, Method method) {
        MethodMetadata methodMetadata = super.parseAndValidateMetadata(targetType, method);
        methodMetadata.template().decodeSlash(EncodeSlashBehavior.DECODE.equals(this.encodeSlashBehavior));
        return methodMetadata;
    }
```

I am not sure if that change would be appropriate for merging or if there is some reason for decodeSlash=true that I am not aware of.

**Comment by adriancole** [comment]
It is curious to have a slash encoded in a http path, and while feign does
try to be flexible, I suspect optimizing for apis like this would raise
more questions than those answered. Is there a framework propagating this
practice? Maybe we can tell them to stop :P

**Comment by kdavisk6** [comment]
Superseded by #1019
