### ISSUE TITLE
Allow variable substitution in any part of Header value

### ISSUE THREAD

**Issue by kavanpuranik** [OpenFeign/feign#288]
Currently it's limited to the beginning of the header value. 

In feign.RequestTemplate#resolve():

```
public RequestTemplate resolve(Map<String, ?> unencoded) {

    for (String field : headers.keySet()) {
      Collection<String> resolvedValues = new ArrayList<String>();
      for (String value : valuesOrEmpty(headers, field)) {
        String resolved;
        if (value.indexOf('{') == 0) {  <<<<<<<<<<<<<<< unnecessary limitation?
          resolved = expand(value, unencoded);
        } else {
          resolved = value;
        }

  }
```

`value.indexOf('{') == 0` unnecessarily limits the variable substitution.

So in the following awesomeVariable will get replaced:
`@Headers({"My-Awesome-Header:  {awesomeVariable} something"})`

but not in:
`@Headers({"My-Awesome-Header:  something {awesomeVariable}"})`

**Comment by adriancole** [comment]
Is there a particular standard header you are looking to support? Or is
this a custom one?

**Comment by kavanpuranik** [comment]
Yes, this is a custom header, where I have to pass a user id dynamically. 

For example,
@Headers({"X-Jive-Run-As:  userid 100001"})

Documentation around this custom header "X-Jive-Run-As" is at https://community.jivesoftware.com/docs/DOC-110343

**Comment by adriancole** [comment]
Ahh interesting. Yeah I thought about it, and don't thing this is a big
deal. Feel free to raise a PR to allow this!

**Comment by ajones-miovision** [comment]
FWIW, the auth0 v2 api expects a query string like ?q=field:{fieldValue} (ie /api/v2/users?search_engine=v2&q=email:"me@you.com"). This is troublesome to for feign because it is looking for { at position 0.

**Comment by ajones-miovision** [comment]
That being said, it is possible to encapsulate weird api's like this by writing a wrapper class around your feign client. That's what i did. Keeps feign clean.

**Comment by backfx** [comment]
I ran into this issue when trying to send an Authorization-Header with a Bearer token.
```@Headers("Authorization: Bearer {access_token}")```

Actually I'm using an Expander to fill in "Bearer " as prefix to the token. Would be more smarter when placeholders can be at any index.

**Comment by kdavisk6** [comment]
With #778 merged, it is now possible to declare headers as templates and have them resolved using method parameters.  I'm going to close this issue for now.  If others on this thread find that support is still lacking, please feel free to create a new issue.
