### ISSUE TITLE
Retryer not working with HystrixFeign

### ISSUE THREAD

**Issue by codependent** [OpenFeign/feign#300]
Using HystrixFeign to enable circuit breaking capabilities makes impossible to configure a Retryer.

The problem occurs in `SynchronousMethodHandler.invoke(Object[] argv)`:

```
try {
        return executeAndDecode(template);
      } catch (RetryableException e) {
        retryer.continueOrPropagate(e);
        if (logLevel != Logger.Level.NONE) {
          logger.logRetry(metadata.configKey(), logLevel);
        }
        continue;
      }
```

If the destination service is down, `executeAndDecode(template)` raises 

```
java.lang.UnsupportedOperationException: No fallback available.
    at com.netflix.hystrix.HystrixCommand.getFallback(HystrixCommand.java:284) ~[hystrix-core-1.4.20.jar:1.4.20]
```

due to a:

```
java.util.concurrent.TimeoutException: null
    at com.netflix.hystrix.AbstractCommand$9.call(AbstractCommand.java:596) ~[hystrix-core-1.4.20.jar:1.4.20]
```

Since the try-catch block only captures `RetryableException` there's no way of the retryer to kick in.

Digging into `SynchronousMethodHandler.invoke() -> executeAndDecode()`, the actual place where the exception is raised is here:

```
try {
      response = client.execute(request, options);
    } catch (IOException e) {
      if (logLevel != Logger.Level.NONE) {
        logger.logIOException(metadata.configKey(), logLevel, e, elapsedTime(start));
      }
      throw errorExecuting(request, e);
    }
```

Maybe it should also take care of the `java.lang.RuntimeException`?

**Comment by kdavisk6** [comment]
I think there may be a way to achieve what you are looking for.  One way is to modify the `HystrixInvocationHandler` to look specifically for `HystrixTimeoutExceptions` and raise them as `IOExceptions`.  Thoughts?

**Comment by iura1981** [comment]
Hi,
Probably there was a misunderstanding how Hystrix and feign Retryer should work.
As whole client call is wrapped in Hystrix command it means that all retries should be invoked in the command's timeframe.
So if you set hystrix command's timeout to 30 seconds and you use default Retryer (3 attempts), your http client timeout should be 10 seconds or even less (by default connection timeout is 10 seconds and read timeout 60 seconds).
Hope this helps.

**Comment by kdavisk6** [comment]
Closing as it's clear that our stance is to not use our Retryer instance with Ribbon/Hystrix or any other circuit breaker or framework with their own built in retry support.
