### ISSUE TITLE
URL Encoding of Braced Query Param (w/ Ribbon)

### ISSUE THREAD

**Issue by rs017991** [OpenFeign/feign#306]
When the content of a Query Param starts with a left curly brace(ex: JSON), using Ribbon causes the entire parameter to lose its URL Encoding.

When using Feign alone this is not an issue; it only happens after adding Ribbon.

To reproduce this, you may edit [RibbonClientTest.urlEncodeQueryStringParameters()](https://github.com/Netflix/feign/blob/9a7e84e158bd671e5debff8680aaef9982aef8d6/ribbon/src/test/java/feign/ribbon/RibbonClientTest.java#L124) and change to:

``` java
    String queryStringValue = "{some string with braces}";
    String expectedQueryStringValue = "%7Bsome+string+with+braces%7D";
```

From what I gather:
1. Feign has already constructed the correctly-encoded URI by the time it gets to [LBClient$RibbonRequest.toRequest()](https://github.com/Netflix/feign/blob/9a7e84e158bd671e5debff8680aaef9982aef8d6/ribbon/src/main/java/feign/ribbon/LBClient.java#L94)
2. The URI is decoded and then re-encoded (sounds pointless and slow, but I'm sure there's a reason) incorrectly.

**Comment by jwdevs** [comment]
Hi, 

Is there anything going on here? I confirm this behavior, I have the same problem - trying to use JSON in query parameters and Ribbon creates a problem here. 
What I've found out is that in RibbonResponse#execute() method there is a call request.toRequest() that causes the problem. 
`public RibbonResponse execute(RibbonRequest request, IClientConfig configOverride)
      throws IOException {
    Request.Options options;
    if (configOverride != null) {
      options =
          new Request.Options(
              configOverride.get(CommonClientConfigKey.ConnectTimeout, connectTimeout),
              (configOverride.get(CommonClientConfigKey.ReadTimeout, readTimeout)));
    } else {
      options = new Request.Options(connectTimeout, readTimeout);
    }
    Response response = request.client().execute(**request.toRequest()**, options);
    return new RibbonResponse(request.getUri(), response);
  }`

RibbonRequest#toRequest() calls RequestTemplate#request() method that uses queryLine() method to construct the final request. This take query parameters (that were decoded and stored in a hashmap) and puts them not encoded in the url. 

Maybe somebody with more Ribbon knowledge could have a look at it. I will give it a try to provide a patch but I'm not sure about the side effects... 

Cheers,
Jakub

**Comment by jwdevs** [comment]
It looks like this code is different in the master branch and looks like it be already fixed. :)

**Comment by kdavisk6** [comment]
@jwdevs I believe your are correct.  This was already corrected.  If you are still experiencing this, please feel free to open a new issue.
