### ISSUE TITLE
Unexpected exception when no header parameter is set for GET request 

### ISSUE THREAD

**Issue by sonerd** [OpenFeign/feign#309]
I am using feign version `8.12.1` with the `feign-httpclient` extension.
When I am creating a `GET` request without header parameters like:

``` java
protected interface MyClient {
   @RequestLine("GET /foo?key={bar}")
   ResponseBean getFoo(@Param("bar") final String bar);
}

MyClient client = Feign.builder().client(new ApacheHttpClient()).target(MyClient.class, "anyUrl"); 
ResponseBean response client.getFoo("bla");
```

The underlying apache http client implementation is throwing following exception: 

```
Caused by: org.apache.http.ProtocolException: Content-Length header 
already present at org.apache.http.protocol.RequestContent.process(RequestContent.java:96)
```

Which is strange as I am not setting any header parameter. The workaround to avoid that exception was to set any header parameter e.g.:

``` java
@Headers("Accept: text/html")
@RequestLine("GET /foo?key={bar}")
ResponseBean getFoo(@Param("bar") final String bar);
```

It seems that in case of no header parameter is set, feign is creating some default header parameters which is also including `Content-Length`. This causes apache http client to throw the above exception.

**Comment by kdavisk6** [comment]
@sonerd 

You are correct.  The Apache Http Client implementation you are using does set a number of headers for you based on the Request being passed.  This was corrected in #324
