### ISSUE TITLE
Support fallbacks for hystrixcommand and rx types.

### ISSUE THREAD

**Issue by codefromthecrypt** [OpenFeign/feign#317]
If your fallback object has a HystrixCommand or Rx return type, it won't work..

Ex.

```
java.lang.ClassCastException: rx.internal.util.ScalarSynchronousObservable cannot be cast to org.springframework.cloud.netflix.feign.valid.FeignClientTests$Hello

    at org.springframework.cloud.netflix.feign.valid.FeignClientTests.testHystrixFallbackObservable(FeignClientTests.java:400)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

That's because it is blindly casting, when it should be smarter.

Here's a way out..

If the return type is a HystrixCommand, that means we need to call `.execute()` on it, like so..

``` java
@Override
protected Object getFallback() {
  ...
  Object result = method.invoke(fallback, args);
  return result instanceof HystrixCommand ? ((HystrixCommand)result).execute() : result;
--snip--
```

If the return type is an rx type, we probably need to return it in `resumeWithFallback`.

**Comment by adriancole** [comment]
@spencergibb @christopherlakey if one of you wanna give this a crack.. be my guest!

**Comment by adriancole** [comment]
ps this implementation approach is pure conjecture :P I just looked at hystrix docs, trying to figure a way that wouldn't invalidate the fallback sharing interface with the api.

**Comment by simonlinj** [comment]
@adriancole  is this still a limitation when using HystrixCommand??

example

```
interface YourApi {
  @RequestLine("GET /yourtype/{id}")
  HystrixCommand<YourType> getYourType(@Param("id") String id);

  @RequestLine("GET /yourtype/{id}")
  Observable<YourType> getYourTypeObservable(@Param("id") String id);

  @RequestLine("GET /yourtype/{id}")
  Single<YourType> getYourTypeSingle(@Param("id") String id);

  @RequestLine("GET /yourtype/{id}")
  YourType getYourTypeSynchronous(@Param("id") String id);
}
```

**Comment by adriancole** [comment]
@simonlinj I don't have any special knowledge.. doesn't look like there's been any follow-up on this issue

**Comment by simonlinj** [comment]
@adriancole  ok, thanks for your reply
