### ISSUE TITLE
allow anotation of hystrix commandKey and groupKey for interfaced feign methods

### ISSUE THREAD

**Issue by cforce** [OpenFeign/feign#334]
There are defaults for cmdKesy = methodname and groupKey=classname.
 If hytsrix cfg in application.yml is linked via this default names and method or class names get refactored the configuration is delinked without recognizing. Therefore explict labeling via custom commandKey and groupKey anotated above the Feign (interface) method would help to explicit link that and thre are no problems with code refactorings.

This is related to https://github.com/Netflix/feign/issues/189#issuecomment-95688652

**Comment by spencergibb** [comment]
`application.yml` is a spring-cloud construct. Feign knows nothing about it, but I get the idea, if the method is renamed any config won't see the new name.

**Comment by caarlos0** [comment]
@cforce check #360

**Comment by cforce** [comment]
@caarlos0 WIll this also work together with @FeignClient anotation?

**Comment by caarlos0** [comment]
@cforce I don't know this annotation and cannot find it in the sources...

**Comment by spencergibb** [comment]
It's part of spring-cloud-netflix.

**Comment by caarlos0** [comment]
oh, don't know then...

**Comment by caarlos0** [comment]
@cforce can you test it?
