### ISSUE TITLE
Escape slashes

### ISSUE THREAD

**Issue by bsideup** [OpenFeign/feign#350]
When string with "/" passed as a parameter to the method then Feign will include it in query "as is". Example:

``` java
@RequestMapping("/foo/{id}")
String getFooById(String id) {
}
```

``` java
myFeignClient.getFooById("/1/2/3")
```

I see `/foo/1/2/3` as an URL after Feign's magic.

**Comment by adriancole** [comment]
Magic is probably a valid term ;)

Since this isn't a new situation, I would make a Param.Expander that
encodes the slashes. Maybe in the future we add a flag to Param, but for
now, this would probably work.

**Comment by adriancole** [comment]
If it doesn't work, let me know. Slash inception is annoying, but I might
be able to figure something out.

**Comment by kdavisk6** [comment]
Anyone coming to this issue, you can use the `decodeSlash` property of `@RequestLine` to solve this problem.  See [Request Parameter Expansion](https://github.com/OpenFeign/feign#request-parameter-expansion) documentation.
