### ISSUE TITLE
Provide means to trace calls

### ISSUE THREAD

**Issue by adriancole** [OpenFeign/feign#36]
A vendor management system at netflix started looking at feign and realized they needed a way to trace every java call that results in feign calls.

While this could be done via the feign [Logger](https://github.com/Netflix/feign/blob/master/feign-core/src/main/java/feign/Logger.java), it is cleaner to extract out a profiling interface.   I don't have a specific design, yet, but we could borrow from retrofit's [Profiler](https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit/Profiler.java).

Before making a final choice, we should document what metadata is needed in the requests and see how (if at all) this is addressed in other systems such as JAX-RS 2.0, WebSocket, Netty, etc.

**Comment by dinomite** [comment]
Re: Feign's own Logger implementation…would it be a worthwhile undertaking to replace that with slf4j?  It'd be much nicer to have request logging work in a standard way, rather than it all being one level via the existing `feign-slf4j`.

**Comment by kdavisk6** [comment]
The set up today in Feign is to provide simple, basic implementations in `feign-core` to keep the dependencies light and allow developers to plug in as they go.  It's the price we pay for extensibility.  

However, if there is enough interest in this and in making `feign-core` more general use, we can certainly look into it.

**Comment by spencergibb** [comment]
I'd prefer tracing not be in core

**Comment by dinomite** [comment]
I created #738 to describe what I was really getting at.

**Comment by kdavisk6** [comment]
https://github.com/OpenFeign/feign-opentracing looks to be a good solution for this.
