### ISSUE TITLE
More advanced RequestTemplate

### ISSUE THREAD

**Issue by didvae** [OpenFeign/feign#374]
Hi!

I think could be a great idea add more functionality to the request template, specialy if we enter a null value.

for example: Having this "match(a:{label}) return a" if label is null it hasn't change if I'm not wrong.
we can improve a bit the sintax, for example "match(a{:{label}}) return a" can become like this "match(a) return a" if label is null.

Another option is to integrate Apache Velocity templates, and take profit of all syntax that provides.

Tell me if this can be a good idea, and I can implement myself.

Regards

**Comment by adriancole** [comment]
I think this is the sort of thing that would end up in a new repo under a
feign org per #373

**Comment by kdavisk6** [comment]
Closing, marking this issue as stale.  If this issue still exists, please open a new issue.
