### ISSUE TITLE
Allow to recover gracefully from error decoding

### ISSUE THREAD

**Issue by bandrzejczak** [OpenFeign/feign#381]
Right now the only way you could handle response status `>=300` is either via using `Response` class as a return type, or via throwing a custom exception from `errorDecoder` (https://github.com/Netflix/feign/blob/6a6271727ad14dd776e3c3fb029f15fdf95c9c4a/core/src/main/java/feign/SynchronousMethodHandler.java#L112-L135).
This prevents handling failed responses via spring `ResponseEntity` and generally prevents handling failures gracefully with `errorDecoder`.

If we would change `throw` to `return` in https://github.com/Netflix/feign/blob/6a6271727ad14dd776e3c3fb029f15fdf95c9c4a/core/src/main/java/feign/SynchronousMethodHandler.java#L134, we could both return custom error object if needed, and throw an exception if desired.

**Comment by adriancole** [comment]
This topic has been covered pretty thoroughly in #290. Please have a look at it for background.
