### ISSUE TITLE
Publish project(':feign-core').sourceSets.test.output to maven central

### ISSUE THREAD

**Issue by velo** [OpenFeign/feign#388]
Hey guys,

I have being developing a few extensions to feign as well and I would like to leverage the assertions on my projects as well =D 

Maybe a feign-assertj :P

Thanks

**Comment by kdavisk6** [comment]
@velo you can fix this yourself now ;)

**Comment by velo** [comment]
Someone already fixed that one.

**Comment by velo** [comment]
https://repo1.maven.org/maven2/io/github/openfeign/feign-core/9.7.0/feign-core-9.7.0-tests.jar
