### ISSUE TITLE
Feign forms encoder

### ISSUE THREAD

**Issue by xxlabaza** [OpenFeign/feign#389]
Hi! 

I have created an [encoder](https://github.com/xxlabaza/feign-form) for different types of forms (application/x-www-form-urlencoded and multipart/form-data). Moreover it can decorete another encoders for using them both.

Is it able to include my module in Feign-core or mention it in documentation?

**Comment by adriancole** [comment]
I think we need to get the new org open..

https://github.com/Netflix/feign/issues/373

**Comment by spencergibb** [comment]
@xxlabaza looks like we could put it in a project similar to https://github.com/OpenFeign/feign-vertx

**Comment by kdavisk6** [comment]
https://github.com/OpenFeign/feign-form is available in case anyone makes it to this issue.
