### ISSUE TITLE
Allow multiple query parameters with same key

### ISSUE THREAD

**Issue by VincentN** [OpenFeign/feign#398]
Say you need to talk to an API that requires you to repeat the same query parameter key per value, then you can't use the QueryMap feature since it's a map...

For instance:
API: https://my.api.com/data.json?ApiVersion=1.0&Filter=Source:Github&Filter=Locale:en_US&Filter=Type:Issue&Sort=IssueId:asc&Limit=100&Offset=0

Since Filter occurs more than once, only the last value would be saved to the query map.
Is it possible to implement the query parameter collection feature in such a way that it doesn't enforce/relies on unique keys?

**Comment by dsyer** [comment]
I think it probably just works if the value in the map is a collection (per the javadocs). Did you try that?

**Comment by VincentN** [comment]
Didn't try that, and I'm not able to try this out anymore. We have switched
out Feign for standard Apache HTTP, for now.


Vriendelijke groeten,
Vincent

2016-06-17 14:21 GMT+02:00 Dave Syer <notifications@github.com>:

**Comment by edio** [comment]
Afaik, Feignt does not support form-like lists expansion. That means, that 
```
{ "paramName": ["collection", "of", "values"]} 
```
will be expaneded as
```
paramName=collection,of,values
```

rather than
```
paramName=collection&paramName=of&paramName=values
```

And under the hood, Param.Expander can produce only a string for each parameter. Thus, as far as I understand, implementing form-like expansion in Feign won't be easy without modifying Feign itself.

So feature request is totally valid.

**Comment by dsyer** [comment]
What you say is true if there is an `Expander`. If no `Expander` is specified the result will be as desired, I believe. See also #403 for supporting expanders in collections as well.

**Comment by kdavisk6** [comment]
Looking over #403 and the current crop of test cases, if you use a an `Iterable` `@Param` and use the default `Expander`, this will work as requested.
