### ISSUE TITLE
OkHttp had problems with silent retries on POST-Requests

### ISSUE THREAD

**Issue by androideo** [OpenFeign/feign#401]
I had problems with silent retries on POST-Requests while i was OkHttp3.2. [Since they fixed it in 3.3](https://github.com/square/okhttp/issues/2394), you should consider to update your version. I should say that i do not use your library, so i am not sure if you are also facing the problem.

**Comment by ThanawatMas** [comment]
Why am I facing the same issue on OkHttp3.4.2 ? 

I had an issue on my site too. That occurred within 10ms (double request at the same time) .

**Comment by kdavisk6** [comment]
Ok Version is 3.6  I'm going to close this.  If this issue is still present in this version of OkHTTP, we can reopen.
