### ISSUE TITLE
Custom Error Handling & Retries

### ISSUE THREAD

**Issue by breznik** [OpenFeign/feign#405]
If I want to implement my own custom ErrorDecoder, should I also replicate the feign.codec.ErrorDecoder.RetryAfterDecoder logic that's part of the Default error decoder for 503 responses? I'd rather re-use what's there, but the current design seems to discourage this, so I'm wondering if I'm missing something in terms of the best way forward?

**Comment by adriancole** [comment]
ErrorDecoder is a single-method (aka functional) interface, so you can
use composition as opposed to inheritance to do whatever you want. For
example, you can pass a lambda that decorates a call to an instance of
the default error decoder.

**Comment by breznik** [comment]
Thanks~

**Comment by DevAwas** [comment]
when is 503 error reading <feignclient> thrown?
