### ISSUE TITLE
query value contain `{aa%` cause feign returned http status code 400

### ISSUE THREAD

**Issue by Coramo** [OpenFeign/feign#422]
I'm using feign in spring-cloud , i have got a problem.

This is my feign client def.
```
@FeignClient("food-service")
public interface FoodService {
  @RequestMapping(
    value = {"/food"},
    method = {RequestMethod.GET}
  )
  List<Food> find(@RequestParam("name") String name);
}
```

`foodService.find("{co%%");`
this call will be returned status code 400 .

Then i review the code , and i found this code in `RequestTemplate` class :
```
private String encodeIfNotVariable(String in) {
    if (in == null || in.indexOf('{') == 0) {
      return in;
    }
    return urlEncode(in);
  }
```

The method `encodeIfNotVariable` called in query(String name, String... values) .

This means if the value containing `{` and in the first , the value cannot to be encode.

So, how can i fix this ?

**Comment by Coramo** [comment]
spring-cloud issues in here: [https://github.com/spring-cloud/spring-cloud-netflix/issues/1194#issuecomment-234206549](https://github.com/spring-cloud/spring-cloud-netflix/issues/1194#issuecomment-234206549)

**Comment by Dreampie** [comment]
@adriancole

**Comment by adriancole** [comment]
recent versions of feign can allow you to opt-out of query param encoding, but it requires you to use `@QueryMap`. The annotation mentioned isn't in this project.
