### ISSUE TITLE
How Feign Retryer should working when combining with Ribbon

### ISSUE THREAD

**Issue by seno5979** [OpenFeign/feign#430]
Per my understanding Feign has Retryer mechanism, so does Ribbon.

But when integrating Feign together with Ribbon, how does retryer supposed to working ?

Should I just disabled either one ? or better sugestion ?

**Comment by spencergibb** [comment]
Yes, it makes sense to disable one or the other.

**Comment by adriancole** [comment]
I'm starting to regret having the Retryer at all :) it was there before we more generally supported Hystrix.

**Comment by kdavisk6** [comment]
With the most recent version of Feign, you can provide your own `Retryer` that effectively doesn't retry, to disable Feign's support.  I'll see about updating the documentation.

**Comment by kdavisk6** [comment]
Closing as our stance on this is that you probably shouldn't use our retryer with Ribbon/Hystrix or any other circuit breaker with built in retry support.
