### ISSUE TITLE
Prefer method with Exception argument for fallbacks

### ISSUE THREAD

**Issue by tjuchniewicz** [OpenFeign/feign#431]
Maybe this is not standard case but it would simplify a lot when we use declarative Feign Clients using Spring Cloud tools. 

Please see idea described here: https://github.com/spring-cloud/spring-cloud-netflix/issues/1117

**Comment by adriancole** [comment]
can you please be specific about what change you want here? it is less effortful than having to look at other repos and makes your issue more relevant to this codebase.

**Comment by tjuchniewicz** [comment]
Now when executing fallback, Feign expects exactly the same method signature as a target API. Proposal is that it should support (prefer if exists) the same method signature plus Exception to easily get exception information in fallback method.

**Comment by adriancole** [comment]
So concretely, if the method on the api interface was get() the fallback
interface might have get(Throwable cause) or similarly post(Foo foo) ->
post(Foo foo, Throwable cause)

Is that right?

**Comment by tjuchniewicz** [comment]
Right.

**Comment by ryanjbaxter** [comment]
I like this idea.  @tjuchniewicz why not create a pull request?

**Comment by spencergibb** [comment]
We knew going in that our integration was going to be basic to start.

**Comment by adriancole** [comment]
https://github.com/OpenFeign/feign/pull/443
