### ISSUE TITLE
Allow feign-jaxb SAXParserFactory to operate in a namespace-aware manner

### ISSUE THREAD

**Issue by raulk** [OpenFeign/feign#456]
When working with an XML Schema file that uses namespaces (most of them) and generating JAXB entities from it automatically (e.g. Maven plugin), the resulting entities will carry the namespace tags.

Unfortunately, SAXParserFactory ignores namespaces during parsing by default, as documented in https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/SAXParserFactory.html, making the generated JAXB entities not match.

Ideally there would be a configuration flag / Builder for JAXBDecoder in feign-jaxb to explicitly set the underlying `SAXParserFactory.setNamespaceAware` property to true if needed.

**Comment by chrismanning** [comment]
This is a regression caused by #415 

We've just attempted to upgrade from 8.3.x and got bitten by this.
