### ISSUE TITLE
Problem with custom targets on 9.3.1

### ISSUE THREAD

**Issue by jonashartwig** [OpenFeign/feign#457]
So i am doing this:

```
private final static Feign _feign = Feign.builder()
        .encoder(new JacksonEncoder())
        .decoder(new JacksonDecoder())
        .build();
//...
final RtcService rtcService = _feign.newInstance(new Target.HardcodedTarget<>(RtcService.class, "http://localhost"));

public interface RtcService extends BaseApi {
    @RequestLine("POST /query/raw")
    @Headers("Content-Type: application/json")
    List<Map<String, Object>> query(RawQuery query);

    @RequestLine("GET /store/count/{storeName}")
    Map<String, Long> getCount(@Param("storeName") String storeName);
}
```

the error i get:

java.net.MalformedURLException: no protocol: /store/count/ads-create-test-41

doing this:

rtcService.getCount("stuffs");

according to the code i saw and the documentation this should work, right?

Regards

**Comment by adriancole** [comment]
The code you pasted doenst seem to have a custom target. HardCodedTarget
from feign is effectively the same as default right?

**Comment by jonashartwig** [comment]
Hi, yes. Well I created a class inheriting from HardcodedTarget and overwriting apply. If I see the code correct Builder.target(Class<T>, url) does internally the same.

**Comment by adriancole** [comment]
so this part of the stock target is what prevents the error you pasted earlier:

```java
      if (input.url().indexOf("http") != 0) {
        input.insert(0, url());
      }
```
This assumes url() is returning something valid

do you have that in your class?

**Comment by jonashartwig** [comment]
No, I missed that. Interesting. Why is that required? Thanks for the help!

**Comment by adriancole** [comment]
because this is the job of Target :)

**Comment by adriancole** [comment]
oops accidentally early send.. From the javadoc:

Targets a template to this target, adding the {@link #url() base url}
and any target-specific headers or query parameters.


Basically we want a single owner for inserting the base url of a
request. This for example allows you to use the same interceptors and
otherwise to two different regions of the same service, or ones with
two different api version headers or something. Ex.
CloudService1Target CloudService2Target

**Comment by jonashartwig** [comment]
Ok. I understand. Thanks to pointing that out. It obviously works now :) I close this issue.

**Comment by adriancole** [comment]
NP
