### ISSUE TITLE
Throwable in extended fallback is null for timeouts

### ISSUE THREAD

**Issue by pavelzhur** [OpenFeign/feign#464]
There was similar [issue in Hystrix](https://github.com/Netflix/Hystrix/issues/974). 
I'm getting throwable parameter as null in my FallbackFactory for TimeOutException.

`Object fallback = fallbackFactory.create(getFailedExecutionException());`

In Hystrix issue it was fixed by replacing `getFailedExecutionException()` on `getExecutionException()`. Is it possible fix this in Feign-Hystrix too?

**Comment by adriancole** [comment]
sounds sensible, presumably the new method can be relied on (ex we dont
have to check both)

**Comment by zhurpavel** [comment]
I think we don't need to check both. According hystrix documentation `getExecutionException()` return `1) failed execution (in this case, same result as {@link #getFailedExecutionException()}.`

**Comment by eacdy** [comment]
Found this issue, too. Seems fixed in feign 9.4.0

**Comment by tiantianbaobao** [comment]
be careful the version about feign.we should be take care of the different implements about the feign in it's diff-version
