### ISSUE TITLE
HystrixFeign doesn't support custom invocationHandlerFactory

### ISSUE THREAD

**Issue by lehphyro** [OpenFeign/feign#466]
It throws UnsupportedOperationException.

**Comment by adriancole** [comment]
that's deliberate because hystrix is implemented with one. What are
you trying to achieve with your invocationHandlerFactory?

**Comment by lehphyro** [comment]
I'm calling an API that needs an authentication step before it can be used and that provides a token to be used in the following API calls. I've implemented an InvocationHandler that will catch Unauthorized responses (because of token expiration) and call the login endpoint again to get a new authorization token.

**Comment by lehphyro** [comment]
Any ideas for using HystrixFeign in my specific case?

**Comment by kdavisk6** [comment]
You could always try creating your own InvocationHandler that delegates to the Hystrix one.  Have you considered that?

**Comment by lehphyro** [comment]
@kdavisk6 yes.

This issue has been open for two years now, it's not relevant to me anymore. You may close it if you want.
