### ISSUE TITLE
Issue on QueryMap when the value start with '{'

### ISSUE THREAD

**Issue by seno5979** [OpenFeign/feign#470]
I'm facing issue when using queryMap when value starting with '{' like below example :

```
publiic interface TestService {
    @RequestLine("GET /test")
    Country getCountry(@QueryMap Map queryMap);
}
```

The encodeIfNotVariable logic made the encode step be skipped because the query map value starting with '{'
https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/RequestTemplate.java#L365

**Comment by spencergibb** [comment]
`{` is how variables are distinguished. Are you using that without variables?

**Comment by seno5979** [comment]
Hi Spencer,

I have a case to call solr service which one of the value is in json format. 

Currently as a workaround, I need to encode the value by myself before put to the queryMap and disable the auto encoding by @QueryMap(encoding=true)

**Comment by adriancole** [comment]
personally, I think this is a reasonable workaround as json is an odd thing to put in the request line.

note there's also this option which is another way to accomplish the same #465

**Comment by seno5979** [comment]
Hi Adrian,

By your comment above, can I say that when using feign we are not allowed to have value start with '{' ? (which default @QueryMap encoded false)

In my case, I'm creating a feign client to call a SOLR service. Below is the documentation which is in some cases, the query value need to send a **curly bracket**

[https://cwiki.apache.org/confluence/display/solr/The+Standard+Query+Parser](https://cwiki.apache.org/confluence/display/solr/The+Standard+Query+Parser)

Below is the exception I received before disable the auto encoded in QueryMap(@QueryMap(encoded=true)) :

```
Caused by: java.net.URISyntaxException: Illegal character in query at index 106: http://solrServiceClientProductSearchCloudRestCF/solr/SYS_4741549800/select?q=swei&df=keywordSearch_en&fq={!tag=categoryName}(categoryName:"Awesome I")&sort=score+desc&start=0&rows=24&fl=productLocaleKey%2Cscore&preferLocalShards=true&spellcheck=true&spellcheck.collate=true&facet=true&facet.field={!ex=categoryName}categoryName&f.categoryName.facet.sort=alpha&f.categoryName.facet.mincount=1&f.categoryName.facet.limit=-1
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
```

**Comment by adriancole** [comment]
Just was asking if you can use another approach, such as encoding the curly
braces. This avoids us having to optimize feign core code for a very very
rare api style

**Comment by seno5979** [comment]
Thanks Adrian.

As I have mentioned that the workaround that I mentioned is working just fine. 
But  I'm not aware of this behavior until I hit the runtime error. (which is not good experience)

Again. I just sharing, not justify anything.

And thanks all for replying.

**Comment by adriancole** [comment]
I agree it isn't good and willing to review a pull request if someone figures out an elegant way to do this (that doesn't double our parser code :) ).

thanks for raising the topic, it might come up again, and this would be helpful next time.

**Comment by lowzj** [comment]
@adriancole I'm facing the same issue. I debug the code and think that there is somewhere a little unreasonable(or I'm wrong). [source](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/ReflectiveFeign.java#L217)

```java
213      RequestTemplate template = resolve(argv, mutable, varBuilder);
214      if (metadata.queryMapIndex() != null) {
215        // add query map parameters after initial resolve so that they take
216        // precedence over any predefined values
217        template = addQueryMapQueryParameters(argv, template);
218     }
```

Method `addQueryMapQueryParameters` in the line 217 is invoked after method `resolve`, and all variables replacement([source](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/RequestTemplate.java#L215)) has been finished in the method `resolve`, and I think there are no variables remaining when invoking `addQueryMapQueryParameters`, so we can not infer that values starting with `{` are variables.

So `addQueryMapQueryParameters` should encode the `QueryMap` keys and values, then put them into query parameters. 
Or making `RequestTemplate` to provide a new `query` method that directly invoking `urlEncode` instead of `encodeIfNotVariable`.

**Comment by adriancole** [comment]
here's an impl that popped up. can someone else have a look too?

https://github.com/OpenFeign/feign/pull/540
