### ISSUE TITLE
How to ignore business exception in feign client with hystrix. 

### ISSUE THREAD

**Issue by sumit4myself** [OpenFeign/feign#472]
How to ignore business exception in feign client with Hystrix.

**Comment by spencergibb** [comment]
Use Hystrix fallback support? https://github.com/OpenFeign/feign/tree/master/hystrix#fallback-support

**Comment by tjuchniewicz** [comment]
@sumit4myself Here is described concept I currently use: https://github.com/spring-cloud/spring-cloud-netflix/issues/969#issuecomment-242131309

But this is for `@FeignClient`. It should work also for pure Feign.

**Comment by sumit4myself** [comment]
@spencergibb @tjuchniewicz  I don't want to write any fallbak for business exception as i need to show it to the end user. Eg. If authentication fails i need to show the message to end user. 
but when i use hystrix with feign hystrix warp the my business exception with HystrixRuntimeException. 

HytrixCommand accept list of exception to be ignored is there any configuration for fiegn also.

**Comment by tjuchniewicz** [comment]
Feign uses network for transport. Exceptions are not propagated from service to client over network by default. For now the only way I found is to use concept like this:
1. On service side when exception occurs return HTTP 500 and JSON with exception class name and message. Service code have be updated.
2. On Client side use custom `ErrorDecoder` which translates JSON error message to exception and throw it.

**Comment by sumit4myself** [comment]
@tjuchniewicz i have implemented it in the same way. but problem is hystrix wrap my business exception with HystrixRuntimeException how can i ignore it, I dont want to off hystrix for fiegn client.

code : 
@Component
public class ErrorResponseDecoder implements ErrorDecoder {

	private ErrorDecoder delegate = new ErrorDecoder.Default();

	private ObjectMapper mapper = new ObjectMapper();

	@Override
	public Exception decode(String methodKey, Response response) {
		HttpHeaders responseHeaders = new HttpHeaders();
		for (Map.Entry<String, Collection<String>> entry : response.headers().entrySet()) {
			responseHeaders.put(entry.getKey(), new ArrayList<>(entry.getValue()));
		}
		try {
			String body = Util.toString(response.body().asReader());
			Map<String, String> map = new HashMap<>();
			map = mapper.readValue(body, new TypeReference<Map<String, String>>() {
			});

			if (StringUtils.equals("com.....common.exception.BussinessException",
					map.get("exception"))) {
				return new BussinessException(map.get("code"), map.get("message"));

			} else if (StringUtils.equals("com......common.exception.SystemException",
					map.get("exception"))) {
				return new SystemException(map.get("code"), map.get("message"));
			}

		} catch (IOException e) {
			throw new SystemException(SystemErrorCode.SYSTEM_ERROR, e);
		}
		return delegate.decode(methodKey, response);
	}
}

**Comment by tjuchniewicz** [comment]
Code looks good. I have similar solution but I return [`HystrixBadRequestException`](https://github.com/Netflix/Hystrix/wiki/How-To-Use#error-propagation) to disable circuit-breaker logic for business exceptions. For this case I had to fix this:  https://github.com/Netflix/Hystrix/issues/1366. See our private branch: https://github.com/ebjwc/Hystrix/commit/75fa50d8a685824e5efafd529c98eaaeb9133493.

**Comment by sumit4myself** [comment]
@tjuchniewicz thanks, When the updated code will be available ?

**Comment by tjuchniewicz** [comment]
Not sure. I'm not a Netflix/Hystrix developer. Please vote!

**Comment by kdavisk6** [comment]
This appears to be quite old and going through the Hystrix projects, this situation should be able to be handled by using Hystrix directly.  Also, the changes referenced above have been accepted into Hystrix core.  

I suggest that this can now be closed.
