### ISSUE TITLE
Is there any example for client pooling?

### ISSUE THREAD

**Issue by thusithathilina** [OpenFeign/feign#474]
Feign client is great. But due to the reflection API, it's having some hits on performance. Therefore can I create a Client pool at the initialization phase, so I don't have to create the client on demand.
Is there any example to show that sort of scenario?

Thanks 
Thusitha

**Comment by spencergibb** [comment]
You should only create clients once and reuse them.

**Comment by thusithathilina** [comment]
What is we want to handle states with client calls?

**Comment by spencergibb** [comment]
Feign is stateless by default.

**Comment by orwashere** [comment]
This question seems to be answered by Spencer. It can be closed to cleanup the backlog. What do you think @adriancole , @velo ?
