### ISSUE TITLE
Can we add ClientRequestFilter/ClientResponseFilter to a Fegin Client?

### ISSUE THREAD

**Issue by thusithathilina** [OpenFeign/feign#475]
I;m trying to integrate the Fegin client with my application. In my current implementation, I'm having a ClientRequestFilter and a ClientResponseFilter. Is there a way to integrate them to Fegin client?

**Comment by spencergibb** [comment]
What are `ClientRequestFilter` & `ClientResponseFilter` and where are they from?

**Comment by thusithathilina** [comment]
This was get done with a wrapper :) I thought we can register jaxrs ClientRequestFilter/ClientResponseFilter to a Fegin client.

**Comment by spencergibb** [comment]
See the limitations on our support for JaxRS https://github.com/OpenFeign/feign/tree/master/jaxrs#limitations.

Basically, we support the annotations.

**Comment by kdavisk6** [comment]
You may be able to achieve similar results using a `RequestInterceptor` and a `ResponseMapper`.  Have you considered using those?

**Comment by kdavisk6** [comment]
For anyone that finds this, the suggestion here is to use `RequestInterceptor` and `ResponseMapper` respectively.
