### ISSUE TITLE
Why Feign return empties/null on HTTP 404 response?

### ISSUE THREAD

**Issue by thusithathilina** [OpenFeign/feign#476]
This is related to https://github.com/coveo/feign-error-decoder/issues/1
I tried this with for exception which is thrown with the HTTP 404. In that case, I'm not getting the intended exception to the client.
I checked the code and https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Util.java#L233 always returns null since https://github.com/OpenFeign/feign/blob/master/jackson/src/main/java/feign/jackson/JacksonDecoder.java#L52 when the status code is 404. 
But 404 response can contain a body. Therefore, in my opinion, that should be handled similarly to other status codes.

**Comment by spencergibb** [comment]
Read the javadoc here https://github.com/spring-projects/spring-boot/issues/7148#issuecomment-253140090

**Comment by jebeaudet** [comment]
I don't think you got the right link @spencergibb...

**Comment by spencergibb** [comment]
haha!

**Comment by thusithathilina** [comment]
@spencergibb Why don't we remove the https://github.com/OpenFeign/feign/blob/master/jackson/src/main/java/feign/jackson/JacksonDecoder.java#L52 Then 404 will be handles similar to other exceptions as well.

**Comment by spencergibb** [comment]
See the reasoning here https://github.com/OpenFeign/feign/commit/24885fe9620ed620af43f4d2d6ffcfc82980e097#diff-b54b942c0c272042049c1fbdbe6084aa

**Comment by thusithathilina** [comment]
@spencergibb Thanks for the info. But as far as I understand in all the test cases you haven't consider a not null response/entity body. 404 can contain an entity body. What is the resolution for that?

**Comment by kdavisk6** [comment]
#290 allows for decoding of 404 responses.
