### ISSUE TITLE
How can we configure Hystrix options?  Specifically, the threadpool coreSize?

### ISSUE THREAD

**Issue by PhilWritesCode** [OpenFeign/feign#477]
Sorry if this isn't the place for questions -- but I'm running into an issue where the default threadpool size of 10 is too small for my needs.

I've seen Hystrix docs point to something like this:
HystrixThreadPoolProperties.Setter().withCoreSize(20);

But that doesn't seem to fly with HystrixFeign.

I ran into a similar issue a while back when handling timeouts, and was able to apply the timeout value to each method offered by my proxy:
String methodName;
        for (int i = 0; i < methods.length; i++) {
            methodName = methods[i].getName();
            ConfigurationManager.getConfigInstance().setProperty(String.format("hystrix.command.%s.execution.isolation.thread.timeoutInMilliseconds", methodName), 2500);
        }

But, for threadpool, we're not working with 'commands', so the same methodology won't work.  How do I:

a) configure the threadpool size for all of HystrixFeign
or
b) figure out the threadpool name so that I can just set the property using ConfigurationManager

Thanks!

**Comment by adriancole** [comment]
you can check this out for common properties:
https://github.com/OpenFeign/feign/tree/master/hystrix#group-and-command-keys


Not sure if this addresses all of your concerns or not

**Comment by PhilWritesCode** [comment]
Huh...  turns out I was using com.netflix.feign, and not openfeign.  The older netflix version doesn't have SetterFactory support.  I updated my version, then dealt with about 3 hours of pom hell, and then it all worked.

Thanks!
