### ISSUE TITLE
Use the first produces attribute if several are set in your @FeignClient instead of having an error, you must have to set only one produces

### ISSUE THREAD

**Issue by alexandrenavarro** [OpenFeign/feign#478]
Use the first produces attribute if several are set in your @FeignClient instead of having an error, you must have to set only one produces.

The problem is when you share your Interface between your client and your server, you may want to expose 2 types of produces (xml and json for your external client) but use only one when your are the client (json for instance).

**Comment by spencergibb** [comment]
`@FeignClient` is from spring cloud Netflix. There is already an open issue there for this.

**Comment by tjuchniewicz** [comment]
See: https://github.com/spring-cloud/spring-cloud-netflix/issues/808

**Comment by alexandrenavarro** [comment]
Sorry, thanks.
