### ISSUE TITLE
Feign-Jackson encoding fails when API parameter type is not serializable but concrete instance is

### ISSUE THREAD

**Issue by choliver** [OpenFeign/feign#494]
An `EncodeException` is thrown when all of the following are true:

1. There is a supertype that is not directly Jackson-serializable, and a subtype that is (because, say, it has Jackson `@JsonProperty` annotations),
2. A Feign client is used to proxy an API that specifies a supertype parameter,
3. The client is invoked with a subtype instance argument.

**Repro**

- Repo: https://github.com/quartictech/feign-jackson-issue
- Run: `./gradlew test`
- Expected: All tests pass
- Actual: `FeignTest.feign_encodes_subtype` fails with `EncodeException`.

From https://github.com/quartictech/feign-jackson-issue/blob/develop/src/test/java/io/quartic/feign/FeignTest.java:

```
@Value.Style
@JsonSerialize
public @interface MyStyle {}

@MyStyle
@Value.Immutable
public interface Foo {
    @Value.Parameter String bar();
}

public interface MyService {
    @RequestLine("POST /") void postFoo(Foo foo);
}

private final ImmutableFoo foo = ImmutableFoo.of("hello");

@Test
public void feign_encodes_subtype() throws Exception {
    final MyService service = Feign.builder()
            .encoder(new JacksonEncoder(mapper))
            .target(MyService.class, "http://localhost:8080");
    service.postFoo(foo);
}
```

**Analysis**

The first test-case (`feign_encodes_subtype` above) demonstrates the end-to-end problem (we're using [Immutables](https://immutables.github.io/) library to autogenerate the Jackson-annotated subtype).

It appears the issue is [`JacksonEncoder`'s use of `ObjectMapper.writerFor`](https://github.com/OpenFeign/feign/blob/master/jackson/src/main/java/feign/jackson/JacksonEncoder.java#L55) - this forces Jackson to encode as the type specified in the API, rather than the type of the supplied argument, as demonstrated by the next two test-cases (`writerFor_causes_issue` and `writerFor_succeeds_for_subtype`).

The fourth test-case (`not_using_writerFor_succeeds`) demonstrates a potential solution - just use `mapper.writeValueAsString` directly.

**Workaround**

This can be worked around by specifying `@JsonSerialize(as = ImmutableFoo.class)` on the supertype.  However, in a codebase with dozens of types, it would be desirable to avoid that boilerplate.

(The equivalent deserialization boilerplate can be avoided by use of a custom Jackson `AbstractTypeResolver`.)

**Comment by kdavisk6** [comment]
I know this is an old issue, but I'm pretty sure this is a limitation of Jackson's Type API.  I'm going to close this issue.  If this comes up again, I'm happy to resume this discussion.
