### ISSUE TITLE
Align Ribbon/Hystrix/Archaius versions

### ISSUE THREAD

**Issue by johnament** [OpenFeign/feign#498]
Right now, Feign points to:

- Hystrix 1.4.26
- Ribbon 2.1.1

The problem is that Hystrix brings in Archaius 0.4.1 and Ribbon brings in 0.6.6.  Depending on the order you declare these dependencies in your dependency management tool, you may get one version of archaius or the other.  If you get the older one, Ribbon will not work as it requires access to some package scoped constructors.

To fix this, I'd propose manually bumping Archaius to 0.6.6 in the Hystrix pom.

**Comment by kdavisk6** [comment]
This looks like has been taken care of, we should close this.
