### ISSUE TITLE
Implement a Feign CDI Module

### ISSUE THREAD

**Issue by johnament** [OpenFeign/feign#500]
Feign is an amazing library for working with type safe REST clients.  It simplifies a lot of day to day development work being able to leverage the client.

CDI is a dependency injection tool.  While a user can define producer methods there is still the boilerplate overhead that they may have to deal with.

I'd like to propose adding a CDI module, which will look for interfaces supporting Feign and provide injection points to CDI users to simply inject their clients.  No additional development, all annotation based and configured as needed.

It should provide some kind of fallback to look for common builders for interfaces and leverage those whenever possible.

**Comment by adriancole** [comment]
I can open up a repo for you now, if you like.. feign-cdi?

**Comment by johnament** [comment]
If you're interested in taking it on, sure.  After moving in the code it was clear it didn't fit quite right in the existing feign core module.  So yeah a separate CDI module may make more sense.

I'm assuming the version need not align to feign version?

**Comment by adriancole** [comment]
nope version doesn't need to align. Note one thing though.. most
satellite repos are driven either by the lead or on an on-demand
basis.

For example, feign-form is completely run by @xxlabaza using a
standard maven based release process
https://github.com/OpenFeign/feign/blob/master/RELEASE.md

https://github.com/OpenFeign/feign-form/issues/6

This process helps us release others' work in case someone wants to go
to fiji forever.

If you are interested in this..

* I'd open a repo
* I'd give you access to all the things and/or tell you where to ask for access
* I'd open bintray, travis etc for feign-cdi
* you'd likely copy/paste/find/replace feign-form to feign-cdi to save effort
* you'd manage the releases until/unless others become interested in helping

soo.. your call :)

**Comment by johnament** [comment]
I'd be OK with that plan.  The original idea came up in the [DeltaSpike dev list](https://lists.apache.org/thread.html/1b1b65b0e143a9770f50671e151935e7aba29ff56e3d427443691cc0@%3Cdev.deltaspike.apache.org%3E), as something that would be good, but probably didn't make sense to do in DS

Is there any setup you'd need from me for bintray?  I *think* I have an account.

**Comment by adriancole** [comment]
This issue was moved to OpenFeign/feign-cdi#1
