### ISSUE TITLE
Hystrix rx.Single not resolving properly

### ISSUE THREAD

**Issue by arielsegura** [OpenFeign/feign#506]
Hi, 
I've been working with feign-hystrix and I figured out that Singles don't work fine when only adding a subscriber. For instance, in one of your tests (https://github.com/OpenFeign/feign/blob/177ce5e0ec8395ac770fb44035ddca76a7044d7e/hystrix/src/test/java/feign/hystrix/HystrixBuilderTest.java#L343-L343)
there is a valid test for singles that passes without issues:
```java
@Test
  public void rxSingleInt() {
    server.enqueue(new MockResponse().setBody("1"));

    TestInterface api = target();

    Single<Integer> single = api.intSingle();

    assertThat(single).isNotNull();
    assertThat(server.getRequestCount()).isEqualTo(0);

    TestSubscriber<Integer> testSubscriber = new TestSubscriber<Integer>();
    single.subscribe(testSubscriber);
    testSubscriber.awaitTerminalEvent();
    Assertions.assertThat(testSubscriber.getOnNextEvents().get(0)).isEqualTo(new Integer(1));
  }
```

My concern is that the following test (created by me locally) should fail since I expect the subscriber to invoke the `fail()` instruction, but the test is fine :
```java
@Test
  public void weirdShouldFailButDoesnot() {
    server.enqueue(new MockResponse().setBody("1"));

    TestInterface api = target();

    Single<Integer> single = api.intSingle();

    single.subscribe(integer -> fail());
  }
```

In order to make it work, I had to add these lines and the test failed properly: 
```
assertThat(single).isNotNull();
assertThat(server.getRequestCount()).isEqualTo(0);
```
or 
```
TestSubscriber<Integer> testSubscriber = new TestSubscriber<Integer>();
single.subscribe(testSubscriber);
testSubscriber.awaitTerminalEvent();
```

```java
@Test
  public void weirdShouldFailAndFails() {
    server.enqueue(new MockResponse().setBody("1"));

    TestInterface api = target();

    Single<Integer> single = api.intSingle();

    single.subscribe(integer -> {
      fail();
    });

    assertThat(single).isNotNull();
    assertThat(server.getRequestCount()).isEqualTo(0);

    TestSubscriber<Integer> testSubscriber = new TestSubscriber<Integer>();
    single.subscribe(testSubscriber);
    testSubscriber.awaitTerminalEvent();
  }
```
So the question is basically why this is the behaviour. Is it because of hystrix?

**Comment by arielsegura** [comment]
I noticed that this issue doesn't happen if `HystrixInvocationHandler` returns `observe` instead of `toObservable`:
```java
if (isReturnsHystrixCommand(method)) {
      return hystrixCommand;
    } else if (isReturnsObservable(method)) {
      // Create a cold Observable
      return hystrixCommand.observe();
    } else if (isReturnsSingle(method)) {
      // Create a cold Observable as a Single
      return hystrixCommand.observe().toSingle();
    } else if (isReturnsCompletable(method)) {
      return hystrixCommand.observe().toCompletable();
    }
```

**Comment by adriancole** [comment]
hey @arielsegura thanks for looking into this. one of the problems of being a mono-repo is that people w/ specific expertise on a subsystem aren't necessarily going to be notified (or are watching).

when curious about why something was done a particular way, best to use "git blame" or similar to see when it was added and mention that person directly.

In this case, the comments say "cold Observable" whereas if it were changed to "observe()" it would not be cold because it would be eagerly started. a change like you mentioned would be fairly significant and in that case would need to cc folks who routinely affect this file.

anyway, does this help? is there a way to address your concern w/o making this a hot observable?

**Comment by arielsegura** [comment]
oh I see. I wonder how useful returning that cold observable is though. Anyway, I'll do a little research on this to find a way to solve my issue without hot observables. Thanks

**Comment by adriancole** [comment]
valid questions!
