### ISSUE TITLE
Query params are sent as body instead of empty body due to wrong usage of Apache HttpClient

### ISSUE THREAD

**Issue by Infeligo** [OpenFeign/feign#510]
I define my client like this:

```java
    @RequestLine("POST /test?query={query}")
    Foo test(@Param("query") String query);
```

I expect it to send empty body and "query" named parameter as part of query string. It does so when I use Feign's default client. However, it behaves differently when Apache HttpClient is used. The reason is in [these lines](https://github.com/OpenFeign/feign/blob/master/httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java#L137) of ApacheHttpClient:

```java
if (request.body() != null) {
      ...
      requestBuilder.setEntity(entity);
}
```

There is no "else" part. Feign only sets entity when body is not null. However, Apache HttpClient's RequestBuilder [documentation ](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/methods/RequestBuilder.html)states the following:

> Please note that this class treats parameters differently depending on composition of the request: if the request has a content entity explicitly set with setEntity(org.apache.http.HttpEntity) or it is not an entity enclosing method (such as POST or PUT), parameters will be added to the query component of the request URI. Otherwise, parameters will be added as a URL encoded entity.

See also RequestBuilder's [source](https://apache.googlesource.com/httpclient/+/4.5.x/httpclient/src/main/java/org/apache/http/client/methods/RequestBuilder.java#459) for exact implementation of this description.

**Comment by spencergibb** [comment]
What would the `else` part be?

**Comment by Infeligo** [comment]
I created a PR with a possible fix.
