### ISSUE TITLE
Document project history in README

### ISSUE THREAD

**Issue by chrylis** [OpenFeign/feign#512]
When Netflix took hands off the project, the name and the `groupId` both changed. Since there are many posts and articles on Netflix Feign, it would be helpful to have a prominent section in the main project README explaining that this is the official continuation of the Feign project.

**Comment by adriancole** [comment]
Netflix/feign redirects here (there is no upstream fork as this is indeed the official repo).  What type of change are you looking for? Want to try a short non-distracting pull request? perhaps as a NOTICE.md?

**Comment by adriancole** [comment]
ps noticed a couple old references not cleaned up. There was no explicit mention of this being a netflix project, but hopefully the implicit references being gone helps. https://github.com/OpenFeign/feign/commit/59ebc48ded11f63b56729ca13acd14853c92ae73

**Comment by abccbaandy** [comment]
Any Netflix official announce? I can't find anything about this...

I didn't even notice Netflix gave up this project until [this issue](https://github.com/OpenFeign/feign/issues/646).

I was consider import feign in my next project :(

**Comment by adriancole** [comment]
Netflix never officially announced feign, why would they need to officially un-announce it?

**Comment by abccbaandy** [comment]
oh, I don't know that...

So they just change the group name from Feign to OpenFeign some day without any discuss/reddit?

**Comment by spencergibb** [comment]
@abccbaandy the `feign` project was moved from the `Netflix` github org to the `OpenFeign` github org. The maven `groupId` changed from `com.netflix.feign` to `io.github.openfeign`. Versions 8.x.y and under were netflix, 9.0.0 and greater, open feign. If users wanted new, they switched groupId. @adriancole is the creator and maintainer from the beginning.

**Comment by adriancole** [comment]
there was discussion https://github.com/OpenFeign/feign/issues/373
then later a call for help https://github.com/OpenFeign/feign/issues/606
and then more recently what you noticed

**Comment by abccbaandy** [comment]
Thanks for great response(reference).

For anyone find this page and want TL;DR
@adriancole is the author of feign from the beginning, and OpenFeign is just a name to prevent ppl think it's still a Netflix project.
