### ISSUE TITLE
Close stream automatically (SynchronousMethodHandler)

### ISSUE THREAD

**Issue by SirWayne** [OpenFeign/feign#514]
Hello everybody,

i would like to return an `ResponseEntity<InputStream>` at my interface. Therefore i have an own feign decoder fo an octet strea,. 
```
       if (contentType.equals(OCTET_STREAM)) {
            return new ResponseEntity<InputStream>(response.body().asInputStream(),
                    HttpStatus.valueOf(response.status()));
        }
```

This works really good, but i cannot read from this input stream, because the stream is closed by SynchronousMethodHandler.
The SynchronousMethodHandler close the response body at `executeAndDecode`
```
finally {
      if (shouldClose) {
        ensureClosed(response.body());
      }
    }
```
Why is the stream closed automatically?

**Comment by spencergibb** [comment]
IIRC, Feign isn't designed for streaming. Is that right @adriancole?

**Comment by adriancole** [comment]
>
> IIRC, Feign isn't designed for streaming. Is that right @adriancole
> <https://github.com/adriancole>?
>
> actually, the flag mentioned (shouldClose) is conditional on the body
being a specific size. If within a threshold, it is rebuffered. Otherwise,
it is left as a stream. There's probably a test case showing this somewhere.

**Comment by phymbert** [comment]
Hello, I have submitted StreamDecoder sub interface to let decoder to close the input stream itself in [#586](https://github.com/OpenFeign/feign/pull/586)
Please vote if it solves your cases; also interface name could be discussed.
