### ISSUE TITLE
hystrix-javanica annotation support?

### ISSUE THREAD

**Issue by johnpang28** [OpenFeign/feign#515]
Will Feign support hystrix-javanica annotations? Example below:

```
import com.netflix.hystrix.contrib.javanica.annotation.HystrixCommand;
import com.netflix.hystrix.contrib.javanica.annotation.HystrixProperty;
import feign.Param;
import feign.RequestLine;

public interface ReviewManager {

    @RequestLine("GET /reviews/{id}")
    @HystrixCommand(commandProperties = {
            @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "2000")
    })
    String getReview(@Param("id") String reviewId);

}
```

**Comment by spencergibb** [comment]
Can you tell us why you want that?

**Comment by johnpang28** [comment]
@spencergibb - It's just for readability. In our project, I don't anticipate that Hystrix settings will need to be changed independently from the code. Having the Hystrix properties in the Feign client interface just makes it easier for other developers to see how it would behave.

**Comment by spencergibb** [comment]
IMO it seems like more work than it is worth.

**Comment by vsbatista** [comment]
I am working in a project with multiple feign clients, and for some of these clients, I'd like to customize hystrix settings(e.g.: [threshold percentage](https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/HystrixCommandProperties.html#circuitBreakerErrorThresholdPercentage--)) in a per feign-client basis.

My up vote for this :)

**Comment by adriancole** [comment]
if there were something like this, it would probably be an extension which would be run by whoever wants this enough to maintain it. There are hooks to do this via SetterFactory

https://github.com/OpenFeign/feign/pull/447

**Comment by kdavisk6** [comment]
This is something that we will not support directly and will probably need to be done in either it's own extension or part of the Hystrix extension.
