### ISSUE TITLE
Base64 not accessible

### ISSUE THREAD

**Issue by codemaker219** [OpenFeign/feign#516]
Hi,
I have a problem with the Base64-Class used in the feign-core (for Basicauth). Is it somehow possible to make this class public or at least not final?

**Comment by adriancole** [comment]
is the problem a bug we should fix?

**Comment by codemaker219** [comment]
No!!!
But I write a very small (with an old java version) client. If this class would be public I could exclude an additional lib.

**Comment by adriancole** [comment]
I'd recommend copy/pasting it from okhttp like we did (or copy/paste ours
which was copy/pasted). This code is extremely stable.

**Comment by kdavisk6** [comment]
Closing, marking this issue as stale.  If this issue still exists, please open a new issue.
