### ISSUE TITLE
Feign ApacheHttpClient ignores default RequestConfig

### ISSUE THREAD

**Issue by koppenheim1000** [OpenFeign/feign#517]
Apache HttpClient supports definition of a default RequestConfig during client creation via HttpClientBuilder#setDefaultRequestConfig.  The default RequestConfig allows the user to override the Apache defaults for all RequestConfig properties.  The overridden property values are used for all requests executed by the HttpClient but may be overriden using RequestBuilder#setConfig.

The issue is that feign.httpclient.ApacheHttpClient#toHttpUriRequest ignores the default RequestConfig overrides, and, instead, creates a new RequestConfig, setting only the connect timeout and socket timeout.  This effectively resets all the other user defined configuration back to the Apache defaults.  

I think the correct approach would be to initialize the RequestConfig with the defaults and then override those defaults with the values from Request.Options.

**Comment by adriancole** [comment]
wanna give a go (with tests to show it works?)

**Comment by koppenheim1000** [comment]
Yes, i'd like to try to fix it.  One thing to note is that Apache's HttpClient doesn't provide an API to retrieve the default config.  This means I will have to create another constructor in feign.httpclient.ApacheHttpClient that takes the default RequestConfig.

**Comment by kdavisk6** [comment]
This has been addressed in #734
