### ISSUE TITLE
Error handler for api calls ?

### ISSUE THREAD

**Issue by anton-arsentyev** [OpenFeign/feign#522]
What if I got error during creating URL, how to deal with it in Feign ?

 I think its responsibility of Feign to handle things like UnknownHostException.

Some ErrorHandler practice ?)

**Comment by adriancole** [comment]
>
> I think its responsibility of Feign to handle things like
> UnknownHostException.
>
UnknownHostException is a transport-level problem. Feign's primary level of
abstraction is application.

For example, via hystrix, you can provide a fallback when there are
problems like these. Feign doesn't include in its scope all types of error
conditions (like a problem reading bytes 36 out of 100, unknown host,
disconnect etc)

**Comment by anton-arsentyev** [comment]
@adriancole Thanks for reply

**Comment by kdavisk6** [comment]
Closing, marking this issue as stale.  If this issue still exists, please open a new issue.
