### ISSUE TITLE
Replace @RequestMapping variable at runtime

### ISSUE THREAD

**Issue by anshchauhan** [OpenFeign/feign#523]
Hi,

I want to replace a string in requestMapping URL at runtime. It's not a key-value pair. It's just an encrypted string. 
```
@FeignClient(name = "base-service", url = "http://demo.india.com")
public interface BseService {
	@RequestMapping(value = "/ClientOrderPayment.aspx?{q}", method = RequestMethod.POST)
	public Response getPaymentUrl(@QueryParam("q") String q, @RequestParam("clientCode") String clientCode);
}
```

I've tried @Param, @PathVariable and @QueryParam but it did not work. I'm getting the following exception:
```
Caused by: java.lang.NullPointerException: null
	at feign.RequestTemplate.replaceQueryValues(RequestTemplate.java:605) ~[feign-core-9.3.1.jar:na]
```

**Comment by spencergibb** [comment]
`@FeignClient` and `@RequestMapping` are from spring-cloud-netflix, please open there.

**Comment by anshchauhan** [comment]
Thanks @spencergibb 
Since you are contributor in spring-cloud-netflix as well would you mind answering this. I've opened the issue here https://github.com/spring-cloud/spring-cloud-netflix/issues/1645
