### ISSUE TITLE
Returno body If http status not is sucsses

### ISSUE THREAD

**Issue by diegobmd** [OpenFeign/feign#524]
Is it possible parse And return a response body when error http code is != 200 ? Theo error decode    only permits i return a exception 

It is important i m using with a spring clouds

Thenks

**Comment by spencergibb** [comment]
From [ErrorDecoder.java](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/codec/ErrorDecoder.java#L57-L61)

> certain RPC apis return errors defined in the `Response#body()` even on a 200 status. For example, in the DynECT api, a job still running condition is returned with a 200 status, encoded in json.  When scenarios like this occur, you should raise an application-specific exception (which may be `feign.RetryableException` retryable).

So create a custom `ErrorDecoder` that puts the response body in a custom exception.
