### ISSUE TITLE
Feign + Hystrix: Cleaner error propagation

### ISSUE THREAD

**Issue by mNantern** [OpenFeign/feign#528]
I have multiple Feign clients and sometimes they return Exception that must not trigger Hystrix circuit breaker or fallback mechanisms.

I can handle that easily with an ErrorDecoder that wraps my exception into a `HystrixBadRequestException` but then I must change a lot of my code to catch `HystrixBadRequestException` instead of my own exception.

Do you know a way to unwrap `HystrixBadRequestException` ?

I tried the following workaround with success (but it's rather ugly 😞 ): overriding `decomposeException` in `HystrixInvocationHandler`.

Is there a cleaner way  ?

Thank you !

**Comment by spencergibb** [comment]
Not sure there's anything feign can do. `HystrixBadRequestException` is from hystrix itself.

**Comment by mNantern** [comment]
Maybe allowing to customize the HystrixCommand methods (like run, getFallback or in my case `decomposeException`) in HystrixInvocationHandler ?

**Comment by tjuchniewicz** [comment]
@mNantern Maybe `ExceptionNotWrappedByHystrix` will help you:

```java
public class MyBussinnessException extends HystrixBadRequestException 
    implements ExceptionNotWrappedByHystrix
```

throw `MyBussinnessException` in `ErrorDecoder`. See https://github.com/Netflix/Hystrix/pull/1414 for more details.

**Comment by mNantern** [comment]
Unfortunately that doesn't work with `HystrixBadRequestException` which is returned before unwrapping (see https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/AbstractCommand.java#L1563).

I opened an issue directly in Hystrix: https://github.com/Netflix/Hystrix/issues/1478

**Comment by kdavisk6** [comment]
The issue on the Hystrix side has been resolved.  Should we still consider this issue?  Can it be closed?

**Comment by mNantern** [comment]
Yes we can !
