### ISSUE TITLE
Same interface multiple client names

### ISSUE THREAD

**Issue by mguilherme** [OpenFeign/feign#535]
I'm using feign with spring cloud

I have one micro service that needs to call 3 other micro services, each of these 3 micro services have one end point "/pay" but the implementation is completely different.

This works with feign if I create 3 feign interfaces and call the one I need.

My goal is to create one feign interface and call the service I need (the only thing that changes is the name, since the endpoint is the same for the 3) but I haven't found a way to inject the name in the interface.

This could be done using resttemplate since in runtime I know the service I need to call.

The idea behind this concept is to add more microservices without changing the first microservice.

**Comment by spencergibb** [comment]
If you are using `@FeignClient` please open an issue open an issue on spring-cloud-netflix if there is a bug, or ask a question on stackoverflow or gitter otherwise.
