### ISSUE TITLE
Feign for dev (IDE) and production

### ISSUE THREAD

**Issue by mguilherme** [OpenFeign/feign#536]
My goal is to use everything in production (eureka, ribbon, config, hystrix, etc )
But in dev I should skip this process.

When I first tried feign I added name and url and things work great, but I would like to add both and use url if not registered in eureka and name if registered, is this possible?

**Comment by spencergibb** [comment]
If you are using `@FeignClient` please open an issue open an issue on spring-cloud-netflix if there is a bug, or ask a question on stackoverflow or gitter otherwise.
