### ISSUE TITLE
No way to configure whether we want to encode url or not

### ISSUE THREAD

**Issue by vikrantk365** [OpenFeign/feign#537]
I have an application where I'm using feign client to talk to back-end system and they don't seem to support encoded url.
In the annotation **feign.RequestLine**, there is no way to _**configure whether we want to encode url or not**_.
e.g. There is a flag **decodeSlash** which we can configure for that specific request.
It would be great if we can have flag like encodeUrl which can be true by default.
but **feign.Contract** expects you to use **feign.MethodMetadata**, which is a final class and cannot be extended.

**Comment by igorbljahhin** [comment]
Same here. Our app can't send path parameter with "/" inside. Any plans on fixing this issue?

**Comment by kdavisk6** [comment]
Closed via #778 and `decodeSlash`

**Comment by amendoza-navent** [comment]
Hi, is there some way to disable all the chars encoding? I can't send esclamation marks inside a request body with `Content-Type: application/x-www-form-urlencoded;`. Thanks
