### ISSUE TITLE
Support Multiple Collection Formats

### ISSUE THREAD

**Issue by bbdouglas** [OpenFeign/feign#542]
I recently ran into a compatibility issue of representing a query parameter with multiple values. The server I was talking to expected a comma-separated list of values, while feign produced repeated parameters.

    /?foo=bar&foo=baz  // This is what was sent
    /?foo=bar,baz      // This is what was expected

It seems there is no single standard for which form to use. I believe JAX-RS uses repeated parameters, while [Swagger](http://swagger.io/specification/#fixed-fields-45) defaults to csv. This issue has come up before with the [Spring Data REST Endpoint](https://github.com/spring-cloud/spring-cloud-netflix/issues/1634), which had a workaround of adding a RequestInterceptor.

One possible change that would clarify and expand the behavior would be to allow setting the collection format type in the [@RequestLine](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/RequestLine.java) annotation. It could look something like this:

    public @interface RequestLine {
      String value();
      boolean decodeSlash() default true;
      // new parameter for declaring how collections should be encoded
      String collectionFormat() default "multi";  // or "csv", "ssv", "tsv", "pipes" a la Swagger
    }

I believe this is a cleaner solution than custom RequestInterceptor code as it is a short declarative statement as opposed to boilerplate code that would need to be copied for each new service added. It also documents the default behavior, which has been unclear to users in the past (see #398). The name of the new parameter and the various options in this case are inspired by [Swagger](http://swagger.io/specification/#fixed-fields-45). The default value would be the current behavior, so backwards compatibility would be maintained. The implementation should be easy and I can submit a pull request if there interest in this approach.

Please let me know how you feel about this idea.

**Comment by spencergibb** [comment]
I think the issue with an option on request line is extensibility. How would you add formats?

**Comment by bbdouglas** [comment]
I understand your concern with extensibility. How about this for an alternative: extend the Param.Expander class to cover concatenation of elements in a collection?

The current Param.Expander class already allows you to format individual elements in a collection, but can't be used to customize how they are concatenated. What if another method was added to Param.Expander called `expandCollection` that accepted a `Collection<?>` instead of an `Object`? Implementing the current behavior (repeating the parameter name for each element) becomes a little trickier since the expander needs access to the parameter name. I could imagine a few ways around this, such as returning `null` for the default behavior or additionally passing in the parameter name.

**Comment by Kindrat** [comment]
Faced same issue with wolfram|alpha API. Some collection rapameters are repeatable, some are somma-separated. @spencergibb so what's with proposal to extend expander logic to support collections?

**Comment by spencergibb** [comment]
No proposal that I know of

**Comment by Kindrat** [comment]
@spencergibb the one from bbdouglas's comment - to allow collection processing for collections intead of processing them per each item.

**Comment by rage-shadowman** [comment]
Instead of extending the `Param.Expander` interface, you could just add another optional parameter to `@Param` (something like `IterableFormat iterableFormat() = IterableFormat.REPEAT_PARAM` -- defaults to current behavior but allows using `IterableFormat.CSV_STRING` if you want).

That wouldn't break backward compatibility or require updating to java8 for interface default methods.

**Comment by kdavisk6** [comment]
Addressed by #543
