### ISSUE TITLE
Proposal: make Decoders more composable

### ISSUE THREAD

**Issue by seanjreilly** [OpenFeign/feign#544]
Hi. I'd like to propose a change to `feign.codec.Decoder` to make it easier to compose Decoders.

Right now, Decoders are unable to advertise what responses they support decoding. For example, the default decoder handles byte arrays, strings, responses without a body, and 404s. Ideally, a custom decoder would delegate to the default decoder for those cases, but that's very difficult to do, and in practice I would guess that many people either skip that logic or duplicate it.

This effects other Decoders today: the JacksonDecoder duplicates part of the logic of the default decoder (null body and 404s), but not all of it. This means that the JacksonDecoder doesn’t support methods that return String or byte[], but it easily could if it was easier for JacksonDecoder to delegate to the default decoder. A quick check through the source code found other similar examples.

The proposed change is to add a method to Decoder: `public boolean supports(Response response, Type type)`. This would allow a decoder to cleanly delegate to as follows:

```
if (default.supports(response, type)) {
    return default.decode(response, type);
}
//other logic goes here
```

This pattern would work equally well with delegation or subclassing.

I am willing and able to add the change to Decoder, add tests, and modify the existing Decoders in the core source tree to support the new behaviour and delegate to the default decoder. But I thought that I would check to see what people thought before I started this.

Any thoughts?

**Comment by seanjreilly** [comment]
The big complication that I can see is that this requires a change to the interface Decoder. If this was purely a Java 8 project I would suggest a default method on the interface, but with Java 6 support that’s probably not possible.

The conversation on Gitter suggested either a completely separate marker interface, or a sub interface `ComposableDecoder`.

**Comment by adriancole** [comment]
If you look at the sax decoder, it has dispatch ability. Some other
thoughts to keep in mind is many of the decoders are extremely little code
(a few lines of real code involved which rarely changes), so re-use value
of that is helpful, but not as critical as if it were heavier (like our
http clients are)

**Comment by seanjreilly** [comment]
@adriancole I've looked at the sax decoder, and I'm not entirely sure what you mean about dispatch ability. I can see that a user can make SaxDecoder's builder register content handlers for different types, but I don't understand exactly how that would make delegating to a SaxDecoder easier.

Am I missing something?

**Comment by adriancole** [comment]
it was mainly a call to check out something else that does internal
dispatching related to decoding.

In general, feign does a lot to try and reduce the amount of runtime
checks.. this ends up in the Contract utility. The decoder has to do some
amount of conditionality due to different response codes, etc. However, I'm
curious about how much dispatching you are requiring (as anything like this
would be in front of all response parsing).

concretely speaking I would generally expect an api to have reasonably
similar content, vs some endpoints being XML and others JSON. Feign
instances are cheap, so if there's a very large api or set of apis which
have different representation types, you could have different feign
instances behind them (eliminating the need to put conditionals in front of
response parsing)

What's the motivation here? Is it that there's a configuration management
issue where it is easier to move logic into feign as opposed to configuring
feign instances separately for dramatically different apis? Or is there
something more interesting at play?

**Comment by seanjreilly** [comment]
Ok, thanks for the clarification.

I agree that the use case is definitely not a REST API that's both Xml and Json. Those do exist, but usually clients pick one and use it everywhere. However, I've encountered (and written) quite a few really RESTful APIs that mix JSON with binary content — for example, the twitter API allows apps to retrieve user profile and background images as binary content, as well as POST binary content to change those images. In situations like this it feels weird to use a totally different Feign instance just for a few calls on the edge of the API. 

I've been using Feign for two projects in a row, and both times I've needed to write a custom decoder. In one case, I wouldn't have needed to write a custom decoder at all if JacksonDecoder could handle `String` and `byte[]` response types. In the other, I would have had an easier time writing the decoder if it was easier to delegate to Decoder.Default from a custom decoder. Having written 2 — I can't think of a use case where I wouldn't want Decoder.Default's logic for 404s, responses without bodies, etc.

You're right that I could have configured two different Feign instances, one for the binary content and one for the JSON content, but in APIs when these two things are otherwise closely related that feels weird. It also makes configuration more error prone — users should probably use the same HTTP connection pool, authentication settings, and so on between the two instances. It's easy to mess that up.

With respect to the weight of the checks, that's a valid concern, but in my opinion what I'm proposing is pretty lightweight, with no reflection, and should be dwarfed by the cost of actually marshalling the response. For Decoder.Default, the overhead would be a null check, a 404 check, and two calls to `.equals()`.

Perhaps most importantly, there's code several places in the feign codebase with copy-n-paste functionality (and copy-n-paste tests) duplicated from Decoder.Default. If there's ever a bug (or worse, a security vulnerability) found in that code it would have to be manually fixed everywhere. It seems pretty easy to clean this up, and if we get really lucky the overall codebase should be a tiny bit smaller, because I can replace many duplicated unit tests with a single contract test.

**Comment by seanjreilly** [comment]
While I was writing that reply I had a thought: what about only adding the `supports(Response response, Type type)` method to Decoder.Default and StringDecoder as a conservative first step? If it's really useful we can push that method up to a sub-interface of Decoder later, and in all of the use cases I've thought of so far, a user would usually only want to delegate to Decoder.Default.

**Comment by adriancole** [comment]
A lot of the arguments seem to be around copy/paste and concerns about that.

The few lines code from default is indeed pretty reusable.

if (response.status() == 404) return Util.emptyValueOf(type);
if (response.body() == null) return null;
if (byte[].class.equals(type)) {
  return Util.toByteArray(response.body().asInputStream());
}

This could be pulled into an abstract Decoder type which could do this
stuff and delegate to doDecode or something. Such an abstract type
could also try to un-nest wrapped IOExceptions etc. It could be
ReaderDecoder, which opens and closes Reader reader =
response.body().asReader(); as typically done in implementations. For
example, this could do the defensive code present in Jackson, but not
others, about a reader of empty.

However, I would say this is a separate concern than adding a registry
of things that accept certain types. You could build the latter on the
former, but the latter isn't required to support the former.


For example, such a thing could reduce StringDecoder to something like..

public class StringDecoder extends ReaderDecoder {

  @Override
  public Object decode(Reader reader, Type type) throws IOException {
    if (String.class.equals(type)) {
      return Util.toString(reader);
    }
    throw new DecodeException(format("%s is not a type supported by
this decoder.", type));
  }
}

If it did runtime wrapped IOException unwrapping, it could reduce
JacksonDecoder to..

public class JacksonDecoder extends ReaderDecoder {
  ...

  @Override
  public Object decode(Reader reader, Type type) throws IOException {
    return mapper.readValue(reader, mapper.constructType(type));
  }
}

I think this sort of this has high value as it gets rid of the key
concerns you have in a portable way, but without introducing dispatch
on type as a concern (at least at this level of abstraction)..

**Comment by seanjreilly** [comment]
> However, I would say this is a separate concern than adding a registry
of things that accept certain types. You could build the latter on the
former, but the latter isn't required to support the former.

I'm not really sure where that idea came from. It wasn't my intention to have any sort of registry of types for encoding or decoding, or anything that heavyweight. I think the current arrangement feign decoders have with types is fine.

**Comment by adriancole** [comment]
The supports hook is what i was referring to. That style is usually used
when you have more than one thing that is being tested. Registry is manual
(fixed if statements) or a list iterated or something else. Perhaps to be
more precise is I dont think most of the goals mentioned require a type
with a supports method.

**Comment by seanjreilly** [comment]
Here's why I think these goals are better served by a supports method, at least on Decoder.Default():

1. This style allows composition instead of inheritance, which is a very good thing.

2. Yes, if somebody really wants to, it would allow them to delegate to more than one upstream decoder. I don't think either of us expects that to be the norm, but "[simple things should be simple, complex things should be possible](https://en.wikiquote.org/wiki/Alan_Kay)".

3. If inheritance is forced, this sort of thing still often has a method like that, unless the template pattern is used (it's just protected instead of public). Even with a template method, it can still show up if the parent class isn't sure whether or not it needs to invoke a method hook (a decoder that wants to use some of the default behaviour, but not all of it).

It's partly personal preference, but I'd discourage using a template method. The template method pattern ties implementations to a fixed inheritance structure (so it's not possible to have a JacksonCodec class that implements Decoder and Encoder), has a number of other [drawbacks for long term maintenance](http://puredanger.github.io/tech.puredanger.com/2007/07/03/pattern-hate-template/), and would be a more significant change to the existing feign codebase.

**Comment by adriancole** [comment]
there's no forcing here. we don't routinely break apis or force people to
use new ones. If we added a ReaderDecoder it would be optional and of
course you can also implement Encoder!

* the counter-proposal was to solve the concern you had about repetitive
logic via an abstract type which is itself optional and would be an
internal detail of those decoders choosing to extend it.
* for most code in feign including decoders, composition is already
preferred and regularly recommended vs type hierarchies.

also having maintained feign for a long time (even if sparsely recently),
I'm aware of maintenance impact to it. That's one reason why I'm usually
opposed to change until it is strongly supported by a variety of requestors
and for compelling reasons (see HACKING for example). You'll notice that
most bespoke extensions don't end up in the core codebase, and this change
certainly hasn't hit a level of interest to warrant it, yet. In attempts to
help reduce the surface area to something that decreases maintenance, I
suggested to solve something that has a greater good for points you have
mentioned.

If you aren't interested in anything beyond the "supports" thing, I would
encourage you to market it to the point where more people are interested in
it. I'm personally over time on this topic, so encourage other maintainers
to step in if they want this change.

**Comment by seanjreilly** [comment]
It's not that I'm only interested in the "supports thing", but the change that you prefer introduces an inheritance structure where the best practice is for Decoder implementations to implement an interface (Decoder), and be part of an inheritance hierarchy with three ancestors (the new AbstractDecoderImpl, Decoder.Default, and StringDecoder).

My name would be tied to that contribution, and it isn't really on brand for what I want to be publicly known for — I'm an "overall simplicity" guy, and this doesn't fit with that.

So with the best of feelings about it, if that's the approach you want to choose, you should, and I'll step back at this point. Best of luck, and thanks for batting ideas around with me. I enjoyed the conversation.
