### ISSUE TITLE
Maven or gradle

### ISSUE THREAD

**Issue by lanwen** [OpenFeign/feign#545]
Now the project has both `pom.xml` and `build.gradle`. What the main build system? Why both? 

I can help to clean up another to not confuse contributors.

**Comment by spencergibb** [comment]
I only see pom.xml. maven is the build system.

**Comment by lanwen** [comment]
For example:
https://github.com/OpenFeign/feign/blob/master/core/build.gradle
https://github.com/OpenFeign/feign/blob/master/slf4j/build.gradle

so I can send PR to remove such?

**Comment by spencergibb** [comment]
Sure, AFAIK, those are unused.

**Comment by adriancole** [comment]
those were sample projects, which have no direct dependency on the current
project. both maven and gradle were supplied there in case users prefer one
or the other. These were for users, not developers of feign.

Regardless, removing gradle from there is fine. Also, we can even consider
bumping these to another repo since we have an org now.

**Comment by lanwen** [comment]
I think one repo with modules is much more maintainable with less effort. It simplifies refactorings and cleanups a lot. Moving to another repo could be done if it will be more people interested in maintaining modules as separate libs. Then it becomes much easier developing process - core still small and robust, but ecosystem can grow without barriers

**Comment by adriancole** [comment]
fyi these sample repos aren't connected by the build tool, so they won't
benefit automatically from refactoring. I think the decision with samples
is a very different than a new library.

**Comment by lanwen** [comment]
Ah, that's why I have some troubles running tests with IDEA with root project opened! :)
So maybe you are right - moving to separate repo will be useful in this case
