### ISSUE TITLE
Feign JAXRSContract does not support QueryMap.

### ISSUE THREAD

**Issue by aray1** [OpenFeign/feign#550]
Feign JAXRSContract does not support QueryMap. 
Please refer JAXRSContract #processAnnotationsOnParameter. This method misses the check for QueryMap.
Is this intended or just a miss.

The feign default contract supports the same 
`else if (annotationType == QueryMap.class) {
          checkState(data.queryMapIndex() == null, "QueryMap annotation was present on multiple parameters.");
          data.queryMapIndex(paramIndex);
          data.queryMapEncoded(QueryMap.class.cast(annotation).encoded());
          isHttpAnnotation = true;
}`

Could you please clarify whether it is a wanted behaviour or a defect

**Comment by adriancole** [comment]
Querymap is not a jaxrs annotation..

**Comment by aray1** [comment]
Thanks
