### ISSUE TITLE
ApacheHttpClient hardcodes RequestConfig

### ISSUE THREAD

**Issue by andysworkshop** [OpenFeign/feign#553]
Please can you not [hardcode the RequestConfig](https://github.com/OpenFeign/feign/blob/master/httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java#L96) if the ApacheHttpClient has been supplied externally in the constructor?

The RequestConfig contains some critical stuff, such as the HTTP proxy configuration, that you are explicitly denying access to by not allowing us to customize the request config.

It would be sufficient to not specify a RequestConfig at all since you can assume that if we have taken control by specifying an apache http client in the constructor then we have set up appropriate request configuration of our own.

**Comment by adriancole** [comment]
Do you have a suggestion (preferably as a pull request) that does what you
feel is better but doesnt impact existing users?

**Comment by andysworkshop** [comment]
Hi Adrian, yes I do. I'll try to put together a PR this weekend. Can't do it from work unfortunately.

**Comment by kdavisk6** [comment]
This is something that we should really add to the documentation.  Closing as we have a few newer issues related to the same issue #781
