### ISSUE TITLE
class Request is not a type supported by this encoder

### ISSUE THREAD

**Issue by leasontou** [OpenFeign/feign#563]
`@RequestLine("GET /request/url")
Response getRequestUrl(Request request);`
this is my request code,it throw a EncodeException:class com.leason.model.request.Request is not a type supported by this encoder.The request url is like /request/url?userId=1&x=2&y=3&...,and I don't want to use a QueryMap annotation and Map param,How can I fix this problem?

**Comment by kdavisk6** [comment]
This would be an enhancement.  We will need more votes to consider this for inclusion.
