### ISSUE TITLE
decodeSlash(false) is ignored when set via requestInterceptor

### ISSUE THREAD

**Issue by choliver** [OpenFeign/feign#564]
`decodeSlash(false)` is not honoured if set as part of a `requestInterceptor` template:

    client = Feign.builder()
            .contract(JAXRSContract())
            .requestInterceptor(template -> template.decodeSlash(false))
            ...

Looking through `SynchronousMethodHandler.invoke`, it seems that this is because the URL is resolved (via `buildTemplateFromArgs.create`) **before** the interceptors are applied (via `executeAndDecode` -> `targetRequest`).

Is this a bug or expected behaviour?

**Comment by adriancole** [comment]
Hmm kindof surprised this method was made public.. probably it was done so
for custom contracts

**Comment by kdavisk6** [comment]
To answer this question, the reason this is not honored is that by the time the Request Template is provided to the interceptor, the uri template has already been resolved.  The `decodeSlash` parameter has already been interrogated and processed.

If you need to modify this property, please consider doing it via the annotation.
