### ISSUE TITLE
how can i create a feign client

### ISSUE THREAD

**Issue by niuhp** [OpenFeign/feign#565]
i know the serviceId on eureaka and the path,but don't know how many servers for the serviceId,how can i create a feign client with coding??

**Comment by adriancole** [comment]
are you using feign directly or spring-cloud-netflix?

**Comment by niuhp** [comment]
spring cloud

**Comment by adriancole** [comment]
https://stackoverflow.com/questions/tagged/spring-cloud-netflix for questions on this. The code in question doesn't live here. good luck
