### ISSUE TITLE
Feign and Eureka integration

### ISSUE THREAD

**Issue by ruben-perez** [OpenFeign/feign#568]
I want to use `Feign` to send requests to another service, that is registered in our Eureka. 

Reading the documentation (https://github.com/OpenFeign/feign/tree/master/ribbon#usage), I see:

```java
MyService api = Feign.
    builder().
    client(new RibbonClient()).
    target(MyService.class, “https://myAppProd”);
```

But I'm not sure how should it work with Eureka. My guess is that `myAppProd` would be the _vip address_, but... how should I let the Feign instance know where is Eureka, and that it should be using it...?

**Comment by kdavisk6** [comment]
I believe the connection is actually within `Ribbon` and `Eureka` and not `Feign`.  See [Netflix Ribbon Programmers Guide](https://github.com/Netflix/ribbon/wiki/Programmers-Guide)
