### ISSUE TITLE
RequestTemplate does not conform to RFC7230 - case-insensitive header field names

### ISSUE THREAD

**Issue by pisarek** [OpenFeign/feign#570]
Hi,
Feign RequestTemplate's header field names are not case-insensitive.

Here is the RFC fragment in question:
https://tools.ietf.org/html/rfc7230#section-3.2

Here is the code fragment from `RequestTemplate`:

```java
 private final Map<String, Collection<String>> headers =
      new LinkedHashMap<String, Collection<String>>();
```

And a JUnit test case:

```java
@Test
public void headerFieldNamesShouldBeCaseInsensitive() throws Exception {
    RequestTemplate request = new RequestTemplate();
    String value = "value";
    request.header("TEST", value);
    assertThat(request.headers().get("test"), contains(value)); // Actual   :null
}
```

**Comment by adriancole** [comment]
The primary use of the request object is to convert into http client's native request type, which would handle this situation..

It is always best to raise the use case that led to a problem. Are you trying to override or add a second value to a header that already exists? Or are you doing something conditional in an interceptor?

**Comment by pisarek** [comment]
We're overriding the header value. To do this we first have to search for the actual key name case-insensitively. If we do not, we're going to have multiple headers that differ in field name case.

**Comment by adriancole** [comment]
Thanks. Sounds completely legit. Do you want to raise a PR?
