### ISSUE TITLE
animalsniffer dependency should be optional

### ISSUE THREAD

**Issue by brenuart** [OpenFeign/feign#571]
`feing-core` declares `org.jvnet:animal-sniffer-annotation` as runtime dependency.
However, animal sniffer is used only during compilation.
It should ideally be declared _optional_ and/or _provided_.

**Comment by adriancole** [comment]
agreed. optional is usually used I think. wanna raise a PR?

**Comment by brenuart** [comment]
PR is merged... 
Can we close the issue ?
