### ISSUE TITLE
Does Feign support the dynamic calling services?

### ISSUE THREAD

**Issue by tangwenliang** [OpenFeign/feign#579]
Does the **Feign** support the feignclient's name is not only a constant but also a variable, such as this scene?
![image](https://user-images.githubusercontent.com/29816726/28995754-3d5769fc-7a24-11e7-93dc-2627fb5c5e30.png)
@adriancole @spencergibb

**Comment by 358235737** [comment]
support , I had support  dynamic calling services, not use @FeginClient ,use config like this :
//LoadBalancerFeignClient执行，不走@FeignClient标签
Map<String, Collection<String>> headers = SpringCloudUtils.toCollectionHeaders(header);
StringBuilder builder = new StringBuilder();
builder.append("http://").append(cloudRequestConfig.getApplicationName())
.append("/").append(cloudRequestConfig.getRootUri())
.append("/").append(cloudRequestConfig.getUri());
LOGGER.info( "url：" + builder.toString());
//String url = "http://"+openApiSpringCloudRequestConfig.getApplicationName()+"/"+openApiSpringCloudRequestConfig.getSysCode()+"/"+openApiSpringCloudRequestConfig.getReqMethod();
int connectTimeoutMillis = Integer.parseInt(cloudRequestConfig.getConnectionTimeOut()) ;
int readTimeoutMillis = Integer.parseInt(cloudRequestConfig.getReadTimeOut()) ;
Object params = apiRequest.getRequestParam2String();
byte[] hessianBody = SpringCloudUtils.serializeHessian(cloudRequestConfig.getDesMethod(), params);
Request request = Request.create(cloudRequestConfig.getMethodType(), builder.toString(), 
			headers, hessianBody, chrset);
long cloudPrepareDownCost = System.currentTimeMillis()-cloudPrepareUpStartTime;
LOGGER.info( "cloudPrepareDownCost：" + cloudPrepareDownCost);
Response response = client.execute(request, new Options());
//Response response = client.execute(request, new Options(connectTimeoutMillis, readTimeoutMillis));
long cloudAlmostCost = System.currentTimeMillis()-cloudPrepareUpStartTime;
LOGGER.info("cloudAlmostCost: "+cloudAlmostCost);

**Comment by kdavisk6** [comment]
see #743
