### ISSUE TITLE
Two different bugs when I use: Feign + OAuth2 + SSL

### ISSUE THREAD

**Issue by pakkk** [OpenFeign/feign#581]
Hello,

I have an OAuth2 Authorization Server with the following URLs (SSL enabled):

```
security:
  oauth2:
    client:
      accessTokenUri: https://localhost:8443/oauth/token
      userAuthorizationUri: https://localhost:8443/oauth/authorize
```

** First step/bug **

The first time, when I launch my Feign client, the following class/method/line is called:

- Class: org.springframework.cloud.security.oauth2.client.feign.OAuth2FeignRequestInterceptor
- Method: public OAuth2AccessToken getToken()
- Line 139: throw e;
- Exception cause: org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval

I have implemented a Hystrix fallback, and the input parameter "throwable" is null. Then, I cannot identify the exception from Feign :(

If I don't use SSL, i.e.:

```
accessTokenUri: http://localhost:8443/oauth/token
userAuthorizationUri: http://localhost:8443/oauth/authorize
```

Then, "throwable" is not null and I can identify the exception...

** Second step/bug **

The second time, after the previous step, the following class/method/line is called:

- Class: org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessToken
- Method: public String obtainAuthorizationCode(OAuth2ProtectedResourceDetails details, AccessTokenRequest request)
- Lines 156-157: 
ResponseEntity<Void> response = getRestTemplate().execute(resource.getUserAuthorizationUri(), HttpMethod.POST, getRequestCallback(resource, form, headers), extractor, form.toSingleValueMap());
- Exception after calling the previous method: 
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

I think the Rest Template must accept "key store path" and "key store password" to support SSL calls.

If I don't use SSL, i.e.:

```
accessTokenUri: http://localhost:8443/oauth/token
userAuthorizationUri: http://localhost:8443/oauth/authorize
```

Then, the previous Rest call will be successful...

Regards,
Paco.

**Comment by pakkk** [comment]
The second bug it is also happening in the following class/method/line:

- Class: org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport
- Method: OAuth2AccessToken retrieveToken(AccessTokenRequest request, OAuth2ProtectedResourceDetails resource, MultiValueMap<String, String> form, HttpHeaders headers)
- Line 137:
return getRestTemplate().execute(getAccessTokenUri(resource, form), getHttpMethod(), getRequestCallback(resource, form, headers), extractor , form.toSingleValueMap());

**Comment by kdavisk6** [comment]
@pakkk these errors are not related to feign per-se, but in your OAuth2 configuration.  I would remove feign from your project and get that working first.  

Your first exception is due to incomplete configuration.  Per the OAuth2 spec, if you are using the `authorization` grant flow, you must have a redirect defined to ask your users to confirm access.  It has nothing to do with SSL.  

Your second exception is due to incorrect SSL configuration within your application.  You do not have a `trustStore` defined with the certificates of the Authorization servers stored.

I recommend looking at [Spring Boot OAuth2](https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/htmlsingle/#boot-features-security-oauth2) and [Spring Security OAuth2](http://projects.spring.io/spring-security-oauth/docs/oauth2.html)

**Comment by kdavisk6** [comment]
Closing as this not a Feign issue.

**Comment by jroig-evooq** [comment]
For anyone having the second problem with Feign builder, configuring the Spring OAuth2 didn't work for me. Instead I had to override the connectionFactory of the accessTokenProvider of `OAuth2FeignRequestInterceptor`. Here the code

`
var oAuth2FeignRequestInterceptor = new OAuth2FeignRequestInterceptor(new DefaultOAuth2ClientContext(), credentials);
var feignBuilder = Feign.builder();
feignBuilder.client(new Client.Default(getSSLContext().getSocketFactory(), new DefaultHostnameVerifier()));
var accessTokenProvider = new ClientCredentialsAccessTokenProvider();
accessTokenProvider.setRequestFactory(clientHttpsRequestFactory);
oAuth2FeignRequestInterceptor.setAccessTokenProvider(accessTokenProvider);
`

where `clientHttpsRequestFactory` is 

`
private final ClientHttpRequestFactory clientHttpsRequestFactory = new SimpleClientHttpRequestFactory() {
    @Override
    protected HttpURLConnection openConnection(URL url, Proxy proxy) throws IOException {
      var httpsConnection = (HttpsURLConnection) url.openConnection();
      httpsConnection.setSSLSocketFactory(getSSLContext().getSocketFactory());
      return httpsConnection;
    }
  };
`

where `getSSLContext()` returns the SSL context created from your keystore
