### ISSUE TITLE
feign.Response doesn't go through ErrorDecoder

### ISSUE THREAD

**Issue by srikumarcs** [OpenFeign/feign#585]
Hi,

We are using a Feign client which calls an external API. The response of the Feign client is feign.Response instead of a Custom JSON response or any other custom JSON response. One of the things we have observed is that if the APIs return a Feign response, it doesn't go through any of the error decoders. If on the other hand, we return a custom JSON response, I can see that the error decoders get invoked when the status code is 500 or greater (I am intentionally ignoring 404 statuses here). All of this is happening in SynchronousMethodHandler.java. 

**Question : What was the rationale behind the design decision of not invoking error decoders / when the response type is feign.Response? Why are the error decoder invoked only when the response type is NOT feign.Response? Shouldn't the product have the flexibility of invoking the ErrorDecoder for all response types? ** 

My apologies for this generic question, but we are only trying to understand the product better before we go ahead with a full blown implementation of using Feign for a 100 odd APIs here in our organisation. 

Regards,
Sri

**Comment by adriancole** [comment]
When we see the type Response, we assume the user is not trying to do application level behavior, rather be able to handle the raw response directly. Both Decoder and ErrorDecoder aim to raise the abstraction from http to application.

Decoder would take a raw body from the response and decode it. Without type information, we don't know what class to decode into.
ErrorDecoder similarly takes a raw http response and tries to decode it into an application level exception.

**Comment by srikumarcs** [comment]
Thanks for the quick response @adriancole .. that makes sense. I wasn't aware of the logical separation. I am closing this issue now.

**Comment by dangoslen** [comment]
I know this is closed, but what would the thoughts be for making that configurable? There are times when a `Response` is needed in my application to get location headers when creating new resources against a target service.

**Comment by kdavisk6** [comment]
This is similar to #618 in that the request is to have finer grain control over what goes through the `Decoder` and what does not.  If you feel that your question is not similar enough, please create a new issue.

**Comment by dangoslen** [comment]
Thanks @kdavisk6. I hadn't seen that one.
