### ISSUE TITLE
Feign Hystrix and hystrix-codahale-metrics-publisher

### ISSUE THREAD

**Issue by icehockeystar** [OpenFeign/feign#589]
Hello,
we used to publish metrics from all Hystrix calls into our Graphite Server. It works fine with the standard Hystrix-Commands. 
```
<dependency>
	<groupId>com.netflix.hystrix</groupId>
	<artifactId>hystrix-codahale-metrics-publisher</artifactId>
</dependency>
```

Recently I tried out your Feign lib in conjunction with Hystrix like you documented it. Everything works well besides the metrics publishing. There get published metrics paths but no metrics data is actually published.

Could fix the bug?

**Comment by kdavisk6** [comment]
This is probably something outside of the realm of Feign and more closely aligned with Hystrix.  I'm going to close this issue for now, but if this does come up again, and with more information, I'll gladly look into it more.
