### ISSUE TITLE
Can I set timeout configuration for feign or where can I find the configuration document?

### ISSUE THREAD

**Issue by aisensiy** [OpenFeign/feign#590]
Right now the info is not enough.

**Comment by Ryan-Miao** [comment]
Some configuration is needed to add, like https://github.com/spring-cloud/spring-cloud-netflix/issues/1612

**Comment by aisensiy** [comment]
Thanks for your reply.

What is the relationship between OpenFeign/feign and spring-cloud-netflix? Right now I just use feign independently. I do not have the annotation `@FeignClient`. Does it mean I should use spring-cloud-feign instead of feign?

**Comment by Ryan-Miao** [comment]
I think the feign is just a wrapper of hystrix, so I just associate the hystrix doc: https://github.com/Netflix/Hystrix/wiki/Configuration
For the feign timeout config, here is my usage:
```java
ConfigurationManager.getConfigInstance()
                .setProperty("hystrix.command.PhotoService#getToken(String,String,String).execution.isolation.thread.timeoutInMilliseconds", 7000);
 return Feign.builder()
                .decoder(new GsonDecoder())
                .encoder(new GsonEncoder())
                .options(new Request.Options(cognitoToken.getConnectTimeoutMillis(), cognitoToken.getReadTimeoutMillis()))
                .target(PhotoService.class, baseUrl);
```

**Comment by aisensiy** [comment]
Thanks for you reply. It solved my problem.

**Comment by minorpoet** [comment]
i find HystrixFeign  just use FeignClient's configuration , so  the  HystrixCommand's timeout then the FeignClient's  timeout config?
