### ISSUE TITLE
Error when use HystrixFeign.builder with SpringMvcContract

### ISSUE THREAD

**Issue by rodrigoords** [OpenFeign/feign#603]
When I use HystrixFeign fallback feature with the builder:
`HystrixFeign.Builder contract = HystrixFeign.builder()
                                                .decoder(new JacksonDecoder())
                                                .encoder(new JacksonEncoder())
                                                .contract(new SpringMvcContract());`
 and the Feign Client interface:
`public interface AtlasFeignClient {

  @GetMapping("${sms.atlas.sender.path}")
  SmsAtlasResponse sendSms(@RequestParam("destination") String destination,
                           @RequestParam("messageText") String messageText,
                           @RequestParam("key") String key,
                           @RequestParam("flag")AdminInformation flag);

}`
Feign cant resolve the "${sms.atlas.sender.path}" propertie and send a get to /"${sms.atlas.sender.path}".
Debugin the SpringMvcContract implementation you can check that in the resolve they want a ConfigurableApplicationContext intance of resourceLoader, but it get a TomcatEmbeddClassLoader so they cant parse the variable.
This problem happen only with SpringMvcContract, but if i dont use this contract i got other problem: Feign cant see Get annotation, this issue is releated in  [](https://github.com/spring-cloud/spring-cloud-netflix/issues/760)

**Comment by spencergibb** [comment]
This should be in the spring-cloud-netflix issue tracker.
