### ISSUE TITLE
Enable OptionalDecoder to parse 204 responses into Optional.empty

### ISSUE THREAD

**Issue by androidfred** [OpenFeign/feign#604]
GIVEN
An API that returns

```
{"userId": "1", "friends": [{"name": "John"},{"name":"Jane"}]}
```

on GET /users/1/friends, and returns 204 no body on GET /users/2/friends (I would prefer people didn't design their APIs like this, but it's not uncommon)

STEPS TO REPRODUCE
```
class FriendsResponse { String userId; List<Friends> friends; }
```

```
interface SomeAPI { //wired up with OptionalDecoder
  @RequestLine("GET /users/{userId}/friends")
  Optional<FriendsResponse> getFriendsFor(@Param("userId") String userId);
}
```

```
someAPI.getFriendsFor("2");
```

EXPECTED RESULT
Returns Optional.empty

ACTUAL RESULT
Doesn't return Optional.empty

**Comment by kdavisk6** [comment]
I wonder if we can combine this with #618 as a way to add more fine tuned control to decoding responses.  

In any case, `204` does mean `NO CONTENT`, so I think your approach is sound.  We'll look at the PR as part of a future release.
