### ISSUE TITLE
Help manage this project

### ISSUE THREAD

**Issue by adriancole** [OpenFeign/feign#606]
I would love to know if someone can help proceed this project including releases. Still i see a lot of issues addressed to me personally eventhough I havent been able to dedicate time. Kindof swamped. So this issue is looking for someone who needs feign to work and is willing and able to ask hard questions, co-own change with requestors etc. If that person is you, please reply back and/or contact me on gitter or gmail. I am up to coaching faciltating etc, and this could be a good opportunity for someone to take the reigns.

**Comment by androidfred** [comment]
@adriancole Sorry to hear you're swamped. Consider putting a call for contributors to the top of the README so more people can see it.

https://github.com/OpenFeign/feign/pull/617/files

**Comment by adriancole** [comment]
So far, I haven't heard anyone reach out github (though had one person F2F mention some interest). If someone decides to try this out, I can take a few hours with them, reviewing the PR queue and preparing a release together.

**Comment by adriancole** [comment]
dupe of #646
