### ISSUE TITLE
almost all the core interface in feign is not visiable

### ISSUE THREAD

**Issue by stillotherguy** [OpenFeign/feign#621]
it's so hard to make a extension to feign, for example in Feign.Builder there are some code like this:  
<pre>
public Builder invocationHandlerFactory(InvocationHandlerFactory invocationHandlerFactory) {
    this.invocationHandlerFactory = invocationHandlerFactory;
    return this;
}
</pre>

when I make a extension to InvocationHandlerFactory:
<pre>
public interface InvocationHandlerFactory {

  InvocationHandler create(Target target, Map<Method, MethodHandler> dispatch);

  interface MethodHandler {

    Object invoke(Object[] argv) throws Throwable;
  }

  static final class Default implements InvocationHandlerFactory {

    @Override
    public InvocationHandler create(Target target, Map<Method, MethodHandler> dispatch) {
      return new ReflectiveFeign.FeignInvocationHandler(target, dispatch);
    }
  }
}
</pre>

see? the interface MethodHandler is not visiable, if you guys just want to extend it yourself, why u put it in the builder? and why u guys like inner class so much?

**Comment by adriancole** [comment]
effective java book explains this. also mentioned here https://github.com/OpenFeign/feign/issues/558#issuecomment-300659537

Pull request welcome to update HACKING file

**Comment by kdavisk6** [comment]
I think there is enough information in HACKING to address this.  I'm going to close this.
