### ISSUE TITLE
Feign Default Retryer retries without sleep when thread gets interrupted

### ISSUE THREAD

**Issue by MichalSzewczyk** [OpenFeign/feign#624]
Hi,
I found the problem in method continueOrPropagate in class Retryer.Default. 
When the thread in which Retryer is running gets interrupted, Retryer performs retrying without sleep.
Flow looks like that:
1. Thread gets interrupted
2. The next attempt is performed if maxAttepts is not yet met
3. Thread should sleep for a given interval - but it's already interrupted so the InterruptedException is thrown
4. Current thread gets interrupted and retrying is performed again.

The following procedure is performed until the higher level methods/thread groups handle interruption which can take some time and lead to fleed of retrials.

In my opinion, this situation should be handled (for example by propagation of RetryableException).

```
public void continueOrPropagate(RetryableException e) {
    if (attempt++ >= maxAttempts) {
        throw e;
    }

    long interval;
    if (e.retryAfter() != null) {
        interval = e.retryAfter().getTime() - currentTimeMillis();
        if (interval > maxPeriod) {
            interval = maxPeriod;
        }
        if (interval < 0) {
            return;
        }
    } else {
        interval = nextMaxInterval();
    }
    try {
        Thread.sleep(interval);
    } catch (InterruptedException ignored) {
        Thread.currentThread().interrupt();
    }
    sleptForMillis += interval;
}
```

**Comment by slaby93** [comment]
👍

**Comment by spencergibb** [comment]
Can you explain why you think it should sleep?

**Comment by MichalSzewczyk** [comment]
I think that it should stop retrying in case of the interrupted state. 
Now, if it gets interrupted, it retries without intervals until maxAttepts is met (the flow I explained above).

**Comment by spencergibb** [comment]
ping @adriancole

**Comment by MichalSzewczyk** [comment]
ping @adriancole
