### ISSUE TITLE
feign interface unit test 

### ISSUE THREAD

**Issue by fudali113** [OpenFeign/feign#626]
I want to test the correctness of the feign interface. What should I do?

**Comment by benmanbs** [comment]
@fudali113 it looks like you got some help in the Feign gitter chat. Is this issue solved to your satisfaction?

**Comment by velo** [comment]
Take a look on this project I made:
https://github.com/velo/feign-mock

I use it when I wanna validate the client only.

**Comment by kdavisk6** [comment]
You can checkout the documentation on how to check your use of the interface by using [Feign Mock](https://github.com/OpenFeign/feign/tree/master/mock)
