### ISSUE TITLE
How to get the Hystrix Execution Exception for Feign without provide my own fallback class? 

### ISSUE THREAD

**Issue by eacdy** [OpenFeign/feign#632]
I use Spring Cloud Feign with Hystrix.
Now, I want to get the com.netflix.hystrix.AbstractCommand#getExecutionException for Feign.
After diving into the code, I find `feign.hystrix.FallbackFactory.Default`. This is the default fallbackFactory.
But we must use `@FeignClient(fallback = xx.class)` to use `feign.hystrix.FallbackFactory.Default`.

The refered code is `feign.hystrix.HystrixFeign.Builder#target(feign.Target<T>, T)` , like below:

```java
public <T> T target(Target<T> target, T fallback) {
	return build(fallback != null ? new FallbackFactory.Default<T>(fallback) : null)
	.newInstance(target);
}
```

This code is called by `org.springframework.cloud.netflix.feign.HystrixTargeter#targetWithFallback` , like below:

```java
private <T> T targetWithFallback(String feignClientName, FeignContext context,
									 Target.HardCodedTarget<T> target,
									 HystrixFeign.Builder builder, Class<?> fallback) {
		T fallbackInstance = getFromContext("fallback", feignClientName, context, fallback, target.type());
		return builder.target(target, fallbackInstance);
	}
```

And `targetWithFallback` method is called by  `org.springframework.cloud.netflix.feign.HystrixTargeter#target` , like below:

```java
@Override
	public <T> T target(FeignClientFactoryBean factory, Feign.Builder feign, FeignContext context,
						Target.HardCodedTarget<T> target) {
		if (!(feign instanceof feign.hystrix.HystrixFeign.Builder)) {
			return feign.target(target);
		}
		feign.hystrix.HystrixFeign.Builder builder = (feign.hystrix.HystrixFeign.Builder) feign;
		SetterFactory setterFactory = getOptional(factory.getName(), context,
			SetterFactory.class);
		if (setterFactory != null) {
			builder.setterFactory(setterFactory);
		}
		Class<?> fallback = factory.getFallback();
		if (fallback != void.class) {
			return targetWithFallback(factory.getName(), context, target, builder, fallback);
		}
		Class<?> fallbackFactory = factory.getFallbackFactory();
		if (fallbackFactory != void.class) {
			return targetWithFallbackFactory(factory.getName(), context, target, builder, fallbackFactory);
		}

		return feign.target(target);
	}
```

I just want to get the cause of fallback, I don't want to provide my own fallback class nor fallbackFactory class.

Is there any way to achieve ?

**Comment by kdavisk6** [comment]
@eacdy I'm not sure I understand the your question.  The main reason to use Hystrix is for it's fallback capability.  If you do not want to use a Fallback, then don't configure one.  The `HystrixRuntimeException ` will be thrown, so you can catch it in your calling function:

```java
/* assume githubService is a Feign Client */
try {
   this.githubService.getRepos(user);
} catch (HystrixRuntimeException ex) {
  // handle hystrix exception here
}
```
