### ISSUE TITLE
Question: What might cause the feign.Response to contain ByteArrayBody or InputStreamBody?

### ISSUE THREAD

**Issue by nitish-dubey** [OpenFeign/feign#633]
Background:
I have implemented ErrorDecoder interface and in the decode method implementation I am reading the JSON from response.body() and displaying appropriate error code and message.

When I run that on local, works perfectly fine as the Response.body has ByteArrayBody.

When I deploy my code to ec2 instance, it fails to parse response.body for obvious reason that it has InputStreamBody.

The error I get is:
Unrecognized token 'feign': was expecting 'null', 'true', 'false' or NaN
 at [Source: feign.Response$InputStreamBody@40897f9b; line: 1, column: 6]

I might be asking a dumb question :( please help me understand!

**Comment by kdavisk6** [comment]
@nitish-dubey To help us prioritize this, do you consider this issue more of a `question` or a `bug`?

**Comment by kdavisk6** [comment]
In general, you should now need to know exactly what type of body it is.   You should be using the `Body#asInputStream` if you want an `InputStream` and `Body#asReader` if you want a `Reader`.  Work with the interface, it will take care of this for you.

**Comment by bushwakko** [comment]
I have a similar issue. I'm logging the response object, and locally where is ByteArrayBody it prints fine, but on the server it prints feign.Response$InputStreamBody@285a5791.

In this case, it's the response toString()-method that doesn't handle this correctly, and no the user/programmer per se.

**Comment by educostadev** [comment]
> I have a similar issue. I'm logging the response object, and locally where is ByteArrayBody it prints fine, but on the server it prints feign.Response$InputStreamBody@285a5791.
> 
> In this case, it's the response toString()-method that doesn't handle this correctly, and not the user/programmer per se.

I have an issue like this and it was caused by the use of a Map interface rather than a concrete HashMap class within a  @RequestBody parameter. 

My class was
` public class MyClass {
  private String title;
  private Map<String, String> data = new HashMap<>();
}
`
And change to the following fixed the issue:

` public class MyClass {
  private String title;
  private HashMap<String, String> data = new HashMap<>();
}
`

**Comment by alsaghir** [comment]
I really would like to know what would make such a decision for that exact use-case

**Comment by EarthCitizen** [comment]
This issue is closed, but I am having the same issue where extracting the body content locally works fine, but deployed causes an IO exception.
