### ISSUE TITLE
how to add a signature query parameter which is a hash of url

### ISSUE THREAD

**Issue by tuan-nng** [OpenFeign/feign#634]
Hi, in my authenticated endpoint, I need to send a GET request like
https://host.com?q=abc&signate=x
where x is the hash of https://host.com?q=abc.

How could I achieve this with feign?
Using interceptor is not a good choice because in some other queries, I don't need to have signature.

**Comment by odin-delrio** [comment]
I made exactly the same by using an interceptor, if yo don't need the interceptor for all queries, you can always create 2 different feign clients, one with the configured interceptor and another one without it.

```java
public class XxxProviderRequestSignerInterceptor implements RequestInterceptor {

  private final String pass;

  public XxxProviderRequestSignerInterceptor(String pass) {
    this.pass = pass;
  }

  @Override
  public void apply(RequestTemplate template) {
    String queryToSign = template.queryLine();
    String sign = someHashingAlgorithm(pass, queryToSign.length() > 0 ? queryToSign.substring(1) : "");

    template.query("sign", sign);
  }
}
```

**Comment by tuan-nng** [comment]
Right. I can create two clients. Thank you very much.

I wonder if there is any other elegant ways in Feign too.
