### ISSUE TITLE
Is there a way to Change or Add Query Params with RequestInterceptors

### ISSUE THREAD

**Issue by inf3cti0n95** [OpenFeign/feign#635]
I am working on WooCommerce REST API with Feign, but for its one legged Authentication I  need to pass the signatures and all in the Query Param dynamically. I tried this

```

@Override
    public void apply(RequestTemplate requestTemplate) {
     .....
      requestTemplate.query("ouath_signature",signature);
}

```

But it is still sending me 401 .

**Comment by kdavisk6** [comment]
@inf3cti0n95 that should work.  From your example, is the request parameter named correctly?  Are you sure that is shouldn't be `oauth_signature` and not `ouath_signature`?

**Comment by kdavisk6** [comment]
@inf3cti0n95 

Were you able to solve this?

**Comment by inf3cti0n95** [comment]
@kdavisk6 Thanks for asking, but I don't even remember about the project anymore. Sorry to keep this issue open. I restrospect, that typo might be the *root of the evil*.
