### ISSUE TITLE
Fluent interfaces support for chained calls

### ISSUE THREAD

**Issue by a8t3r** [OpenFeign/feign#639]
I implemented a case like this:
```java
interface StoreInterface {
  @RequestLine("GET /api/store/{id}")
  String get(@Param("id") String id);

  ProductInterface products(@Param("store_id") String storeId);
}

interface ProductInterface {

  @RequestLine("GET /api/stores/{store_id}/products/{product_id}")
  String get(@Param("product_id") String id);
}
```
Inner feign interface supports chained calls:
```java
StoreInterface api = Feign.builder().target(StoreInterface.class, "...");
api.products("store_1").get("product_1")
````
I did it for my project, but code looks not really good.
What do you think, would that feature be interesting for the community?

**Comment by benmanbs** [comment]
I'm not convinced this is how REST should work. When you do a get on `products`, I would expect it to return a collection of product objects, not a means to obtain a specific object. 

Something I found myself doing for complicated endpoints is to incorporate a builder object. In this use case, I would imagine something like this:

```java
interface ProductInterface {

  @RequestLine("GET /api/stores/{store_id}/products/{product_id}")
  String get(
    @Param("store_id") String storeId,
    @Param("product_id") String productId
  );

  default String get(
    GetRequest request
  ) {
    return get(request.storeId, request.productId);
  }

  class GetRequest{
    private String storeId;
    private String productId;

    public GetRequest withStoreId(String storeId) {
      this.storeId = storeId;
      return this;
    }

    public GetRequest withProductId(String productId) {
      this.productId = productId;
      return this;
    }

  }
}
```

Then to use it, you would call something like 

```java
String productId = productInterface.get(new GetRequest().withStoreId("1").withProductId("2"));
```

Obviously it looks a little silly with just two params, but when you have complicated endpoints with 5 or more arguments, a builder can make things a bit more readable while still sticking to REST convention.
