### ISSUE TITLE
Do a release

### ISSUE THREAD

**Issue by adriancole** [OpenFeign/feign#643]
I will help do a release by the end of the week. Ping here PRs you think should make the cut. Ping also here if you want to audit the release!

**Comment by velo** [comment]
I can try out the release... have a few projects with feign and could easily bump versions  to see how it behaves.

**Comment by adriancole** [comment]
@velo let's get you in shape to do a test release. Forget about features for now until https://github.com/OpenFeign/feign/issues/646

**Comment by velo** [comment]
ok, so, how are we going to do that?

are you going to stage a build or shall I build one?

**Comment by adriancole** [comment]
@velo you'd be on point and I'd help you with what you need

**Comment by velo** [comment]
Ok, add doNotCloseAfterDecode flag to Feign builder was merged  #649 

Are we waiting on something else or shall I get started?

**Comment by foezor** [comment]
@velo maybe this issue #651 it can help to validate benchmark on the version but i'm not sure if everything is ok on it since the build is not passing

**Comment by velo** [comment]
my impression was that we would just include the `closeAfterDecode` and leave the StreamDecoder behind

https://github.com/OpenFeign/feign/pull/587#issuecomment-370302970

**Comment by phymbert** [comment]
I have updated #651 with all requested changes identified by @adriancole. I think we may let this feature a chance in 9.6 without waiting so much.

**Comment by phymbert** [comment]
_in-extenso_ Is there enough feature in `9.6` on master to start a feature release right now ?

**Comment by velo** [comment]
Fair point, only includes `add doNotCloseAfterDecode`

**Comment by Ladybogue** [comment]
when do think the new version will be out?

**Comment by velo** [comment]
@MrBogue what feature of 9.6.0 are you waiting on?

We are waiting on #651

**Comment by MrBogue** [comment]
@velo we are waiting on #651 too.

**Comment by velo** [comment]
Beging release

**Comment by velo** [comment]
Seems `9.6.0` is now on maven central.  What next?

**Comment by adriancole** [comment]
Update the examples to use it just to verify all is ok. Thats about it

**Comment by adriancole** [comment]
Nice work btw
