### ISSUE TITLE
Optional query parameters with compile-time checks

### ISSUE THREAD

**Issue by rage-shadowman** [OpenFeign/feign#645]
It would be nice if we could specify optional query parameters such that we get compile failures if they aren't specified correctly.

Ideally, we could pass in in a POJO which can be used to generate the expected map through reflection.

Less ideally, allowing the query parameter map to have enum keys (no compile failure on invalid value types, but at least we will get a compile failure on an invalid parameter name).

**Comment by rage-shadowman** [comment]
Another ideal solution could be a fluent interface where you can build the request adding the parameters you care about before actually executing it.

**Comment by benmanbs** [comment]
I believe you can do this sort of thing now with using non-primitive types which support null values. 

I've used homebrew fluent interfaces for requests myself, I've sketched out what they look like here - https://github.com/OpenFeign/feign/issues/639#issuecomment-370830662. I don't know if there's a generic enough way to build something like this, and building your own builder is pretty simple.

**Comment by rage-shadowman** [comment]
I think this pull request would solve the issue nicely: https://github.com/OpenFeign/feign/pull/620

I would like to see it work with the annotations on member variables as well, but this is a good start.

**Comment by rage-shadowman** [comment]
I saw another post elsewhere with a similar solution: http://source.coveo.com/2016/07/21/feign-request-object/

**Comment by rage-shadowman** [comment]
@benmanbs right now you could end up with a dozen parameters, most of them strings. This would make it very easy to accidentally swap a parameter. That's why I like the idea of annotated POJOs or fluent operations. It makes mistakes more obvious, as they are labeled better (`new GetStuffOptions.Builder().setFoo(foo).setBar(bar).setBlah(blah).build()` lets you spot mistakes like `setFoo(bar)` easier than `client.getStuff(bar, foo, blah)`).

**Comment by benmanbs** [comment]
Sure, that PR would certainly make things clearer (and I left a bunch of comments on that PR for the author to help him get the code ready for inclusion in this library). 

My point of linking the custom builder is to address your point exactly. You write `client.getStuff(bar, foo, blah)` once and exactly once, and everywhere else that you use it you use the builder.

**Comment by rage-shadowman** [comment]
@benmanbs yes, the interface default method is one way to add the support. Unfortunately, it also leaves the 12 argument version as a publicly callable method for the poor fools who think that's a good reliable means of calling the method.

PS - I'm not a fan of the interface default method, or of abstract classes for that matter (occasionally they are the best option, but much less often than most programmers seem to think, and if you make an abstract class, then please liberal use the final keyword -- it should at least be on all concrete methods involved in the contract invariants).

**Comment by rage-shadowman** [comment]
Created a new ticket #661 that is more specific.
