### ISSUE TITLE
Update group id in the benchmark folder

### ISSUE THREAD

**Issue by foezor** [OpenFeign/feign#652]
In order to launch the benchmark of the project, the group id of pom, the project and also dependencies should be updated. The goal is to be able to launch benchmark for every release

**Comment by benmanbs** [comment]
I believe this is handled in this pr - https://github.com/OpenFeign/feign/pull/651, I think @phymbert wants to get that merged in for the next release or so...

**Comment by foezor** [comment]
Thanks it's true. then i close this one
