### ISSUE TITLE
Is it time to move on? Should feign move to `java 8`?

### ISSUE THREAD

**Issue by velo** [OpenFeign/feign#656]
Right now, feign is compatibility is bound to `java 6`.

Is it time to release feign 10.0 with `java 8`? (10.x was @spencergibb suggestion)

@kdavisk6 suggested we start a discussion about it.

**Comment by adriancole** [comment]
Up to you, but if this changes, please change the group ID and the package
ID as it won't be bytecode compatible anymore so definitely a major
release. Decisions like this are open, but because the collateral damage
extends well beyond those watching issues, just be very cautious if
implementing this. We don't want to create work for "innocent bystanders"
and changing package and group Id helps with this.

**Comment by adriancole** [comment]
ps @spencergibb <https://github.com/spencergibb> might disagree with me
about if changing package names helps or not. It does invalidate other
layered tools.. so don't take my word as gospel

**Comment by spencergibb** [comment]
Spring doesn't change group id or artifact id for minimum Java versions

**Comment by adriancole** [comment]
>
> Spring doesn't change group id or artifact id for minimum Java versions
>
I guess what I mean to ask isn't so much about spring code, but spring
cloud impact. When feign is rewritten to java 8 it will not be compatible
anymore with java 7. Is this an issue for spring cloud? If so, maybe group
id, package. If not, then maybe unnecessary.

At any rate the android support statements should be dropped if this
happens, so yeah just update that part. In other projects I've avoided
bumping to java 8 (and dealing with this) via retrolambda. Anyway there are
a few folks who will be invalidated. For example, anyone using feign inside
a metrics library as an exporter, it will invalidate the ability to use it
(which might be fine as they just put a <10 update comment in their version
matrix).

**Comment by velo** [comment]
> the android support statements should be dropped if this happens.
In my mind, android had java 8 support
https://developer.android.com/studio/write/java8-support.html
Am I missing something?

Yeah, https://github.com/orfjackal/retrolambda seems a good option.
We could even build the official packages with java 8 and offer retrofitted java 6 jars using classifier.

**Comment by adriancole** [comment]
>
> In my mind, android had java 8 support
> https://developer.android.com/studio/write/java8-support.html
> Am I missing something?
>
>  There's an SDK version level concern. For example, the current code is
compatible with older versions
https://github.com/Netflix/denominator/blob/master/example-android/build.gradle#L14

**Comment by spencergibb** [comment]
Nope, spring cloud (and framework and boot) are now all baselined to Java 8.

**Comment by kdavisk6** [comment]
By moving to Java 8, what will we gain?  (Not sarcastic, honest question).

**Comment by spencergibb** [comment]
Use of java 8 language and APIs inside core feign.

**Comment by velo** [comment]
> By moving to Java 8, what will we gain?
Can squash `feign-java8` into `feign-core`, which is meh level of awesomeness

Allow us to merge this https://github.com/OpenFeign/feign/pull/638
Right now, the PR introduces a java 8 change to `feign-hystrix`

**Comment by kdavisk6** [comment]
I understand that #638 wants to add `CompleteableFuture`, which sounds really good from a user perspective.  Are there specific areas within feign, internally now that would benefit immediately from Java 8 API's?  Are we considering this a spring board for a complete refactor or simply to support things like #638?

**Comment by kdavisk6** [comment]
Just to be clear, I'm all for moving to Java 8.  I am trying to get an idea on how much do we need to change versus should change to get there.

**Comment by kdavisk6** [comment]
Is this something we still want to pursue?  If so, what do we need to get started?

**Comment by velo** [comment]
I think we should consider feign 10 with java 8.

I don't have any features in mind, but that will open doors for sure.
May be, for feign 10 we publish java 8 and use `retrofeign` to keep publishing java 6 libraries, with plans to remove java 6 support on feign 11.

How does that sound like?

**Comment by masc3d** [comment]
>  but that will open doors for sure.

it will certainly close door to being compatible with android < sdk24 very quickly.

**Comment by velo** [comment]
@masc3d as you can see, this was done 3 months ago.
Do you think `retrofeign` would help?

**Comment by masc3d** [comment]
> Do you think retrofeign would help?

@velo I assumed this was rather about retrofitting async support https://github.com/OpenFeign/feign/issues/644

**Comment by velo** [comment]
Meant to type retrolambda
