### ISSUE TITLE
PATCH does not allow a body that is null

### ISSUE THREAD

**Issue by andersflemmen** [OpenFeign/feign#665]
I have been using the OkHttpClient for some time, and have been using a POST endpoint that takes no body. I recently changed this endpoint to use PATCH instead, but now the client throws an IllegalArgumentException, as it requires a PATCH request to have a body. I found the reason for not having this issue with POST in the code below, and I am wondering if there is any good reason why this does not also apply to PATCH? Also, the url in the code does not work.

feign/okhttp/src/main/java/feign/okhttp/OkHttpClient.java, line 77:
```
    byte[] inputBody = input.body();
    boolean isMethodWithBody = "POST".equals(input.method()) || "PUT".equals(input.method());
    if (isMethodWithBody) {
      requestBuilder.removeHeader("Content-Type");
      if (inputBody == null) {
        // write an empty BODY to conform with okhttp 2.4.0+
        // http://johnfeng.github.io/blog/2015/06/30/okhttp-updates-post-wouldnt-be-allowed-to-have-null-body/
        inputBody = new byte[0];
      }
    }
```

**Comment by kdavisk6** [comment]
In spirit, methods like `PUT` and `PATCH` are meant to update existing resources.  While there is nothing explicit in the HTTP specification regarding their use without a request body, their use without a record or information to change in a record seems awkward.

But, your issue is not about your architectural decision, but your issue.  The decision not to accept `PATCH` without a body is in OkHttp and not Feign.  If you want to continue to use the OkHttp client, you must send a request body with a `PATCH`

**Comment by andersflemmen** [comment]
I agree that it might seem awkward, but the data can be passed in other ways than through the body. Anyway, this is not really relevant to the question. 

I know that the OkHttp client requires a body for PATCH, but it also does for PUT and POST. As the code in my previous post shows, those are given special treatment in the Feign client, which makes it possible to use them without a body. Working around the issue is not a big problem, but I'm just trying to understand why it makes sense to treat those two differently than PATCH.

**Comment by kdavisk6** [comment]
The history of this change appears to be related to the PR #271 and #322

**Comment by rage-shadowman** [comment]
@velo I think those pull requests are meant to reference #655 but this is #665 and I believe unrelated to those pull requests.

**Comment by kdavisk6** [comment]
Right, it was my mistake when submitting the PR.

**Comment by kdavisk6** [comment]
@andersflemmen Feel free to submit a PR for this, if this is still an issue for you.
