### ISSUE TITLE
Unsupported JAX-RS 2.x annotations render entire interface useless

### ISSUE THREAD

**Issue by masc3d** [OpenFeign/feign#669]
Causing ```IllegalStateException: Method has too many Body parameters``` when creating target.

I have noticed async is not supported (yet). Until then it would be beneficial to simply ignore them so regular endpoints of the interface remain accessible.

Maybe there is a way to mitigate this in 9.6.1 and I just haven't found it. Is there any?

**Comment by masc3d** [comment]
`final class JAXRSContract` 😢

**Comment by masc3d** [comment]
The same applies to `@Context` btw which is used for SSE endpoints.

**Comment by kdavisk6** [comment]
I looked over your change, why not submit a PR for feedback?  From my perspective it looks good.  I would add a test case or update the existing test cases to verify.

**Comment by masc3d** [comment]
`feign-jaxrs2` is available in `9.7`
