### ISSUE TITLE
Feign与ribbon使用ZoneAvoidanceRule 负载均衡规则会出错

### ISSUE THREAD

**Issue by weixuedong** [OpenFeign/feign#673]
Feign与ribbon使用ZoneAvoidanceRule 负载均衡规则会出错，由于多个feignService使用相同得负载均衡器造成得问题，因为可用服务列表是可变得。

**Comment by velo** [comment]
Let's keep the tickets in English.

**Comment by weixuedong** [comment]
The use of ZoneAvoidanceRule load balancing rules for Feign and ribbon can be a problem because multiple feignServices use the same load balancer, because the list of available services can be changed.
