### ISSUE TITLE
Problem accessing .404 not found.

### ISSUE THREAD

**Issue by iver3on** [OpenFeign/feign#677]
one project interface call local feignclient 404:Problem accessing .404 not found.
@FeignClient("xx")
public interface ZZ {
	
	@PostMapping("bb/cc")
	public void cc(String json);
	

}

another project is web project with jsp
service name is xx
 and restcontroller like: 

@RestController
public class controller {
@Autowired
ZZ  zz;
     
	@PostMapping("bb/cc")
	public void cc(String json){
         return "zzzzzzzzz";
       }
}

**Comment by kdavisk6** [comment]
I'm not sure there is a question here.
