### ISSUE TITLE
fallback

### ISSUE THREAD

**Issue by huoyan403** [OpenFeign/feign#680]
how can i get a unite fallback 

i get many fallback method in project  
and every method have a common fallback json without override all the method in fallback.class

**Comment by huoyan403** [comment]
if i get a json from elasticsearch .there is a lot method .but they get a common back json parttern  ,
and i want use a unite fallback method

**Comment by kdavisk6** [comment]
If I understand you want a single fallback for all your methods.  If that is the case, use a `FallbackFactory` instead.  It is driven by the Exception instead of the method.

**Comment by huoyan403** [comment]
thanks , i understand it .

**Comment by huoyan403** [comment]
I was misled by some blogs
