### ISSUE TITLE
How to enable @CacheResult in feign client

### ISSUE THREAD

**Issue by JerryChaox** [OpenFeign/feign#683]

**Comment by velo** [comment]
What is `@CacheResult`?

**Comment by kdavisk6** [comment]
`@CacheResult` is a Spring concept, part of their Cache Abstraction.  Feign does not have first class support for these constructs, but you can use them in concert.  

First, adding these annotations to Interfaces is not recommended.  See [Enable caching annotations](https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#cache-annotation-enable) in the Spring Documentation

It is recommended that you add the annotations to a concrete class.  For example:
```java
public class UserRepository {
   // our feign client
   private GitHub gitHub;
  
  // find the github user and cache the result
  @CacheResult
  public User findByName(String name) {
      return this.gitHub.findUser(name);
  }
}
```

In this example, Feign is responsible for calling the API and the `UserRespository` is responsible for caching the results.  Hope this helps.

**Comment by kdavisk6** [comment]
This is a question regarding Spring Cache Abstraction usage and not Feign.
