### ISSUE TITLE
Release 9.7

### ISSUE THREAD

**Issue by velo** [OpenFeign/feign#685]
A few new features made into master.

Sounds about the right time for a new release.

Is there any ticket not merged that should be included?

**Comment by rage-shadowman** [comment]
I'd love to see the POJO based QueryMap support included.

**Comment by velo** [comment]
@rage-shadowman done.

I would like to hear more about
> Fixed the conflicts. Though I am unable to test it as your master fails tests for me right now (and thus so does my branch now that I've merged your master back into it).

**Comment by velo** [comment]
https://github.com/OpenFeign/feign/issues/687

I would like to include this one on the release too

**Comment by velo** [comment]
Build in progress
https://travis-ci.org/OpenFeign/feign/builds/375148795

**Comment by velo** [comment]
Looks like the process is completed and artifacts are on maven central.
http://repo1.maven.org/maven2/io/github/openfeign/feign-core/9.7.0/
