### ISSUE TITLE
idea: include feign testing tools

### ISSUE THREAD

**Issue by PaulBoutes** [OpenFeign/feign#687]
Should we consider to reuse [feign-mock](https://github.com/velo/feign-mock) made by @velo,  and add it to feign (new module ?) ? 
I am currently working to integrate it, I find this library really useful, we could get something similar to what is done in RxJava2 (TestObserver, ...) for testing.

What do you think ?

**Comment by velo** [comment]
@PaulBoutes could you review the PR I just made?
