### ISSUE TITLE
Feign  is out of support HTTP2

### ISSUE THREAD

**Issue by rabbitgyk** [OpenFeign/feign#688]
example of code `logger` and `Response` build:

```
log(configKey, "<--- HTTP/1.1 %s%s (%sms)", status, reason, elapsedTime);
```
[Logger](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Logger.java)

**Comment by kdavisk6** [comment]
I'm sure if there is a question, comment, or bug?  @rabbitgyk can you please provide more information?

**Comment by kdavisk6** [comment]
This is a log message, not an indication of HTTP2 support
