### ISSUE TITLE
Code format

### ISSUE THREAD

**Issue by velo** [OpenFeign/feign#700]
While working on `feign-mock` I couldn't find a way to format the new source code in a way that matched existing code.

I applied the code guide formatter on source, and both IDEs changed everything

IntelliJ: https://github.com/OpenFeign/feign/pull/698
Eclipse: https://github.com/OpenFeign/feign/pull/699

So, I wonder if we should drop either hammer and start enforcing code format

**Comment by spencergibb** [comment]
In spring boot and cloud we check in an eclipse setting end the intellij users use the eclipse formatting plugin

**Comment by velo** [comment]
I checked in the settings files on #699, well on both
I would probably tweak it to reduce the format impact.
13k lines is a bit too much.

**Comment by kdavisk6** [comment]
I can take a look first thing tomorrow morning.

**Comment by kdavisk6** [comment]
I think we can close this issue. #699 is merged
