### ISSUE TITLE
Custom ErrorDecoder and RetryableExceptions

### ISSUE THREAD

**Issue by Kidlike** [OpenFeign/feign#703]
I have set up a custom ErrorDecoder which is used for all 4xx responses, but for example if the inbound server is down, my custom ErrorDecoder is never used, and instead just a RetryableException is thrown.

Is there something else I could override that will control what exception is thrown regardless of the scenario ?

Also something like this would help to create better logs... Now the logs are inconsistent because of this conditionality.

**Comment by kdavisk6** [comment]
I suspect that the `Client` instance you have configured is set up to automatically retry connection based exceptions.  Do you have an example of the `Builder` configuration you used?

**Comment by Kidlike** [comment]
I use `org.springframework.cloud.netflix.feign.FeignClient`:
```
@FeignClient(name = "filerepo", url = "${filerepo.host}")
```

**Comment by kdavisk6** [comment]
That is a special `Spring` version of an auto-configured Feign client.  Have you asked your question with the Spring Cloud folks?  There are too many variables there for me to help you out.  For example, you can manually configure a `Client`, or used the default one that `Spring` gives you, which is based on a number of different scenarios. 

I suggest that you check with them first and see if there is something you can audit or update in your Spring configuration first.

**Comment by Kidlike** [comment]
Thanks, I will investigate from the Spring side of things :)

**Comment by Squiry** [comment]
@kdavisk6 It's the issue with default SynchronousMethodHandler, not with Spring Cloud.
SynchronousMethodHandler invokes ErrorDecoder in case of http response only. If there's no http response (IOException thrown by Client) then it wrappes exception with RetryableException and throws it. [code](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/SynchronousMethodHandler.java#L103)

**Comment by Kidlike** [comment]
@Squiry Nice catch :)

Any suggestions?

**Comment by Squiry** [comment]
Well ErrorDecoder should decode erros and there's nothing to decode anyway.
You can proxy Client and handle IOException there if you really need it. Or you can just handle RetryableException.

**Comment by Kidlike** [comment]
Yeah at the moment I'm just handling RetryableException. I guess I'll stay like this. Thanks though !

**Comment by kdavisk6** [comment]
The current implementation treats all `IOException`s from the Client as something related to the communication and should be retried.  This will continue for the `maxAttempts` and then throw the `RetryableException` out, if you use the default `Retryer`.  If this is not the behavior you want, you can implement your own `Retryer` and process them accordingly.

**Comment by kdavisk6** [comment]
Closing based on the last comment.

**Comment by shavkat1121** [comment]
thanks
