### ISSUE TITLE
Retryer always throws RetrybaleException but not origin cause

### ISSUE THREAD

**Issue by metalpalo** [OpenFeign/feign#709]
I implemented own decoder (similar to Default, overtaken possibility to retry, see bellow) to throw custom exceptions based on status codes.
These exceptions are subclasses of _RuntimeException_(not _RetryableException_) and I would like to them to be retryable via **RETRY_AFTER** flag.
This is ensured by following routine overtaken from _ErrorDecoder.Default_, but here my exception is wrapped to _RetrybaleException_

```java
@Override
public Exception decode(String methodKey, Response response) {

    RuntimeException exception = decodeException(response);

    //overtaken from Default
    Date retryAfter = retryAfterDecoder.apply(firstOrNull(response.headers(), RETRY_AFTER));
    if (retryAfter != null) {
        return new RetryableException(exception.getMessage(), exception, retryAfter);
    }
    return exception;
}
```

I understand that such type is necessary for _SynchronousMethodHandler_ to repeat this operation.

My problem is that when the default retryer reaches _maxAttemps_ it throws _RetrybaleException_ instead of _Throwable_ see

```java 
public void continueOrPropagate(RetryableException e) {
    if (attempt++ >= maxAttempts) {            
       throw e;
    }
}
```

What whould be good for me is something like this:

```java
public void continueOrPropagate(RetryableException e) {
  if (attempt++ >= maxAttempts) {
      if (e.getCause() instanceof RuntimeException)
          throw ((RuntimeException)e.getCause());
      throw e;
  }
```
What do you this about this? Is my idea wrong?

**Comment by dinomite** [comment]
From [PR730](https://github.com/OpenFeign/feign/pull/730#issuecomment-403044441)

@kdavisk6:
> However, with that said, it may reasonable to consider refactoring the proxy to read and throw the exceptions returned from the decoder directly, instead of masking them.

Kevin is describing adding a new `catch` block in `ReflectiveFeign.invoke()` to throw the exception cause:

```
try {
} catch (Throwable th) {
    throw th.getCause();
}
```

**Comment by kdavisk6** [comment]
I think it would be worth while to create a preliminary PR to see the scope of this change.  I don't think it will be very far reaching, but it's worth giving it a shot.  @dinomite see if you can create a first pass at this and see if it reacts the way you need.

**Comment by dinomite** [comment]
Preliminary PR https://github.com/OpenFeign/feign/pull/737

**Comment by kdavisk6** [comment]
Closing via #737
