### ISSUE TITLE
Space Character in QueryMap

### ISSUE THREAD

**Issue by ChrisLeeBare** [OpenFeign/feign#718]
Hi there,

we're trying to get feign to work with a foreign API which uses oData for filtering results. 

The URL looks something like this:
https://[URL]/[path]/[to]/[resource]?$filter=[SomeFieldInResultJson] eq '100000'

Our Interface looks like this:
```Java
@Headers("Content-Type: application/json")
public interface APIInterface {
	@RequestLine("GET /resource?$filter={Filter}")
	public String getResource(@Param("Filter") String inFilterQuery);
[...]
}
````

Feign now replaces space characters with + in the query section which should be %20.
If I got this right in the RequestTemplate on line 215 (openfeign version 8.18.0) you are replacing + with %20 but only in the URL part (which is [resource] in my example but not in the querymap.

See:
```Java
  public RequestTemplate resolve(Map<String, ?> unencoded) {
    replaceQueryValues(unencoded);
    Map<String, String> encoded = new LinkedHashMap<String, String>();
    for (Entry<String, ?> entry : unencoded.entrySet()) {
      encoded.put(entry.getKey(), urlEncode(String.valueOf(entry.getValue())));
    }
    String resolvedUrl = expand(url.toString(), encoded).replace("+", "%20");

```

The result looks like this:
https://[URL]/[path]/[to]/[resource]?%3F%24filter%3DCardCode+eq+%2710000000%27+

So the foreign API answers with Bad Request. 
If we replace + with %20 and send this via postman we got the response we wanted.

We even tried to implement our own URLRequestInterceptor:

```Java
public class URLInterceptor implements RequestInterceptor{

    @Override
    public void apply(RequestTemplate template) 
    {
        if(!template.queries().equals(null)) {
            Map<String, Collection<String>> newQueryHashMap = new HashMap<>();
            Map<String, Collection<String>> currentHashMap = template.queries();
                 for(Entry<String, Collection<String>> map : currentHashMap.entrySet()) {
                List<String> queryValues = new LinkedList<>();
                
                for(String queryString : map.getValue()) {
                    String newQuery = queryString.replaceAll(" ", "%20");
                    queryValues.add(newQuery);
                }
                
                newQueryHashMap.put(map.getKey(), queryValues);
                        }
            template.queries(newQueryHashMap);
          }
      }
}
```

And included this Interception within building our Interface:

```Java
 			apiInterface= Feign
 					.builder()
 					.decoder(decoder)
 					.encoder(encoder)
                                        .requestInterceptor(new URLInterceptor)
 					.client(new OkHttpClient())
[...]
```

But this resulted in getting the %20 URLEncoded into %2520. Which results in, you may guessed it, http 400 - bad Request . :)

Any help would be appreciated, because we're running out of ideas how to solve this issue.

regards
Chris

**Comment by kdavisk6** [comment]
Without digging into this in more detail, my "shoot from the hip" guess is that the individual clients, `ApacheHttp` and `OkHttp` are were this issue is.  As a way to test, have you tried using the `ApacheHttp` client instead of `OkHttp`?

**Comment by ChrisLeeBare** [comment]
Hi,

I switched to the ApacheHttp Client and it seems like, it did the trick. Now the response is HTTP 200 and the oData Filterquery is correctly encoded. 

Thank you!

**Comment by kdavisk6** [comment]
Glad to help.

**Comment by aqHi** [comment]
Thanks for this issue  . I got the same problem .

Whether I use  the `okhttp` or use the `httpclient`  the spaces in  url  to be encoded as '+', I finally used the interceptor to replace the '+' with '%20'  to solve the problem.

Refer to your code:

``` java
public class FeignURLInterceptor implements RequestInterceptor {
    @Override
    public void apply(RequestTemplate template) {

        template.queries().forEach((key, value1) -> {
            Collection<String> value = value1
                    .stream()
                    .map(str -> urlEncode(str).replaceAll("\\+", "%20"))
                    .collect(Collectors.toList());

            template.query(true, key, value);
        });
    }


    private String urlEncode(String s) {

        try {
            return URLEncoder.encode(s, StandardCharsets.UTF_8.name());
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
            throw new RuntimeException(e.getMessage());
        }
    }

}
```
