### ISSUE TITLE
No easy way of preventing feign retries on POST/PUT requests

### ISSUE THREAD

**Issue by pasinski** [OpenFeign/feign#719]
I am using feign 9.5.1. In one interface I am doing POST, PUT and GET methods. I am OK with GET methods being retried on IOException coming from client (for instance, readTimeout etc.). Still I find it quite dangerous to retry POST/PUT methods.

In the Retryer interface I have no way of knowing what HTTP method was being used on this particular request (continueOrPropagate method accepts only RetryableException). Also, the method feign.FeignException#errorExecuting is static and for all IOException throws RetryableExcetpion. I haven't seen any easy way of altering this behaviour when studying the code of feign.SynchronousMethodHandler...

```
Response response;
        try {
            response = this.client.execute(request, this.options);
            response.toBuilder().request(request).build();
        } catch (IOException var15) {
            if(this.logLevel != Level.NONE) {
                this.logger.logIOException(this.metadata.configKey(), this.logLevel, var15, this.elapsedTime(start));
            }

            throw FeignException.errorExecuting(request, var15);
        }
```

1. Making errorExecuting method of FeignException static and not allowing to impact for what requests to throw RetryableExcetpion is a poor design

2. Putting into RetryableExcetion or FeignException information on what request lead to the exception might solve the problem, as the developer could have more control over when to retry. After all, information about the request is being passed to  FeignException.errorExecuting method.

**Comment by kdavisk6** [comment]
I agree.  How about you take a shot at creating a PR for this.  Let me know if you need any help or more suggestions.

**Comment by pasinski** [comment]
I would love to, will take care of that this weekend

niedz., 24 cze 2018, 2:00 AM użytkownik Kevin Davis <
notifications@github.com> napisał:
