### ISSUE TITLE
@QueryMap expansion with BaseContract

### ISSUE THREAD

**Issue by shangal** [OpenFeign/feign#722]
@QueryMap Custom Object expansion works with Default Contract. If i am trying to use SpringMvcContract(spring-cloud-openfeign) which extends the BaseContract, while processing the annotation, it only checks for annotation type of http, if not found it considers it as RequestBody.

Is there a way i can use @QueryMap with SpringMvcContract?

**Comment by kdavisk6** [comment]
If I recall, the Spring MVC Contract has a different method of doing this.  I think you can use the Spring `@RequestParam` annotation instead of the core Feign `@QueryMap`.  Try that out and let me know.
