### ISSUE TITLE
There is an issue when i use @FeignClient + @RequestBody + RequestMethod.POST 

### ISSUE THREAD

**Issue by Jeffsyl01** [OpenFeign/feign#727]
Below is my code:
`

public class TestRequest {

	private String name;

	private String password;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
}
`
`

@FeignClient(name = "cloudDemo", path = "/test")
public interface ITestRestService {
	@RequestMapping(value = "/getByBody", method = RequestMethod.POST)
	public BosCommonResponse getByBody(@RequestBody TestRequest body);
}
`

`

@RestController
@RequestMapping("/test")
public class TestController implements ITestRestService {
	public BosCommonResponse getByBody(TestRequest body) {
		return BosCommonResponse.success(body);
	}
}
`

I test this by Postman.send a post request（Content-Type is application/json）,the body of response is incorrect.
![1](https://user-images.githubusercontent.com/39359189/42021247-b831e37c-7aec-11e8-99f1-7fa6b7c07ff1.png)

If send a post request（Content-Type is application/x-www-form-urlencoded ）,the body of response is incorrect too.
![2](https://user-images.githubusercontent.com/39359189/42021281-ca9c7702-7aec-11e8-9552-22d50bcf52da.png)

**Comment by kdavisk6** [comment]
I think you may have misunderstood how to use `Feign` and particularly, how to use it with `Spring`. 
 The interface `ITestInterface` can be used directly.  You do not need to implement it in your controller.  In doing so, you bypass `Feign` all together.  

```java
@FeignClient(name = "cloudDemo", path = "/test")
public interface ITestRestService {
    @RequestMapping(value = "/getByBody", method = RequestMethod.POST)
    public BosCommonResponse getByBody(@requestbody TestRequest body);
}


@RestController
@RequestMapping("/test")
public class TestController  {
      ITestRestService testRestService;
      public TestController(ITestRestService testRestService) {
         this.testRestService = testRestService;
      }
      
      @RequestMapping("/getByBody")
      public BosCommonResponse getByBody(TestRequest body) {
         /* proxy to the interface */
         return this.testRestService.getByBody(body);
      }
}
```
Please checkout the README for more examples as well as the documentation at Spring Cloud
