### ISSUE TITLE
Java 8 Modernization

### ISSUE THREAD

**Issue by kdavisk6** [OpenFeign/feign#736]
@velo Let's get a list going of areas we can look to refactor now that we have updated the minimum version to Java 8.  Here are a few ideas I've been mulling over.

* Remove `DefaultMethodHandler` backport
* Implement `default` interface methods where appropriate
* Determine an approach to asynchronous handling, ex support for `Future`

**Comment by masc3d** [comment]
this will break android compat < sdk24. 
in fact, `feign-10` is already broken due to java8 lambdas in `JAXRSContract`

**Comment by kdavisk6** [comment]
No longer necessary.
