### ISSUE TITLE
Slf4jLogger has not work,log not print，why not?

### ISSUE THREAD

**Issue by L-ee** [OpenFeign/feign#740]
RemoteService service = Feign.builder()
                .logLevel(Logger.Level.FULL)
                .logger(new Slf4jLogger())
                .target(RemoteService.class, ADDRESS_URL);

**Comment by kdavisk6** [comment]
Can you please provide more information?  There are number of reasons that you may no be seeing any messages.

**Comment by L-ee** [comment]
i want to print the request of infromation，eg : request url & request params. but console nothing to print of request infromation , below my code 
`
public class App {
    private static final String ADDRESS_URL = "http://localhost:10009";
    public static void main( String[] args ) {
        feign();
    }
    public static void feign(){
        RemoteService service = Feign.builder()
                .logLevel(Logger.Level.FULL)
                .logger(new Slf4jLogger())
                .target(RemoteService.class, ADDRESS_URL);
        System.out.println(service.getDesc());
    }
}
`
`
public interface RemoteService {
    @RequestLine("GET /rest/index")
    public String getDesc();
}
`
`
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-core</artifactId>
            <version>9.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-slf4j</artifactId>
            <version>9.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-hystrix</artifactId>
            <version>9.5.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-jackson</artifactId>
            <version>9.5.0</version>
        </dependency>
`

**Comment by L-ee** [comment]
i want to print the request of infromation，eg : request url & request params. but console nothing to print of request infromation , below my code 
`
public class App {
    private static final String ADDRESS_URL = "http://localhost:10009";
    public static void main( String[] args ) {
        feign();
    }
    public static void feign(){
        RemoteService service = Feign.builder()
                .logLevel(Logger.Level.FULL)
                .logger(new Slf4jLogger())
                .target(RemoteService.class, ADDRESS_URL);
        System.out.println(service.getDesc());
    }
}
`
`
public interface RemoteService {
    @RequestLine("GET /rest/index")
    public String getDesc();
}
`
`
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-core</artifactId>
            <version>9.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-slf4j</artifactId>
            <version>9.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-hystrix</artifactId>
            <version>9.5.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-jackson</artifactId>
            <version>9.5.0</version>
        </dependency>
`

**Comment by kdavisk6** [comment]
What is your SLF4J logger level set?  Feign logs all messages at the `debug` level when using SLF4J.  The Feign `Logger.LogLevel` controls what `feign` logs and not the log level of SLF4J
