### ISSUE TITLE
Support for JWS

### ISSUE THREAD

**Issue by Nyamiou** [OpenFeign/feign#741]
JWS (https://tools.ietf.org/html/rfc7515) is a standard to sign and validate JSON responses. Since Feign is based on CXF which supports it : http://cxf.apache.org/docs/jax-rs-jose.html#JAX-RSJOSE-JWSSignature it should be possible to add support for it somehow.

**Comment by Nyamiou** [comment]
My specific needs right now is to be able to verify signatures on JWS responses before decoding responses using Jackson. Your proposed solution seems interesting, I'll look into it, thanks.

**Comment by kdavisk6** [comment]
Since this is mainly a question and not a feature request, I'm going to close this for now.
