### ISSUE TITLE
Concurrent service calls

### ISSUE THREAD

**Issue by jfsanchez-gh** [OpenFeign/feign#742]
I have serviceA, serviceB and serviceC, in this model, serviceA is in charge of calling serviceB and serviceC to aggregate the data they return and then return the aggregated data. 
I would like to use Feign clients in serviceA for calling serviceB and serviceC but in parallel.
Something like this:  
```
                                         (call) ---> serviceB   
                                      /                                 \  
serviceA - [ in parallel ]                                      ===== aggregate results --> (RETURN)  
                                      \                                 /  
                                         (call) ---> serviceC  

```
And my question is:   
- Is it possible to call multiple services in parallel using Feign client?  
If it is possible, can you provide some documentation or working example?  
Thanks!

**Comment by kdavisk6** [comment]
You will need to do this type of coordination yourself.  Service A could have `Feign` clients configured for Service B and C.  It would then be up to the Service A implementation to call Service B and C in parallel and aggregate.
