### ISSUE TITLE
Set header without passing it as a param

### ISSUE THREAD

**Issue by niteshchaudhary** [OpenFeign/feign#745]
In my api interface, I have:
`@RequestLine("GET /testUser/{uuid}")
    TestUser get(@Param("uuid") UUID uuid);`

And in my test case, I test it like this:
`TestUser testUser = TestUserApi.get(uuid);`

I do not want to pass authorization as a header in api definition, but I want to set it in my test case.
So, do we have any thing like `TestUserApi.setHeader("something", "something")`?

**Comment by kdavisk6** [comment]
One option is to use a `RequestInterceptor`.  You can modify the request headers that way as well.

**Comment by niteshchaudhary** [comment]
Thanks @kdavisk6. If possible, can you help me with a example?

**Comment by niteshchaudhary** [comment]
It worked, thanks @kdavisk6
