### ISSUE TITLE
Mix query parameters with body params

### ISSUE THREAD

**Issue by cinatic** [OpenFeign/feign#749]
Hi in a current project i am using feign, which is really nice to work with.

Now i am totally lost in an issue connecting to worlds bestest software co. M$... The MS Endpoint required POST request with api-version as query parameter. Now i tried this but w/o success

```kotlin

@FeignClient(url = "\${datasource.timeseriesinsight.endpoint}", name = "timeSeriesInsightClient", configuration = [FeignClientConfiguration::class])
@JsonIgnoreProperties(ignoreUnknown = true)
interface TimeSeriesInsightClient {

    //    @PostMapping(value = ["/aggregates?api-version=2016-12-12"], consumes = [MediaType.APPLICATION_JSON_VALUE])
//    @PostMapping(value = ["/aggregates?asdasd=123"], consumes = [MediaType.APPLICATION_JSON_VALUE])
    @RequestMapping(method = [RequestMethod.POST], value=["/aggregates?api-version=2016-12-12"])
    fun getAggregates(
        @RequestHeader(HttpHeaders.AUTHORIZATION, required = true) bearerTokenHeader: String?,
        @RequestParam(value = "searchSpan", required = false) searchSpan: JSONObject?): String?
}
```

i would expect that what is passed to Mappings value is used as an query parameter as it is and the passed params as body params. Am i missing something? I also tried RequestLine but nothing worked for me.

Any idea, am i missing something?

**Comment by kdavisk6** [comment]
If you need the parameters to be send in the request body, you must define them as such, otherwise all `@Param` values (in this case Spring's `@RequestParam` is equivalent), are translated into Query Parameters.  The appropriate way to have the value applied as the body, using feign's Default Contract, is to not annotate it at all.

```java
interface GitHub {
   // the authenticate request will go through the encoder and be used as the 
   // Request Body
   @RequestLine("POST /authenticate")
   User authenticate(AuthenticationRequest auth); 
}
```

I don't know off hand what the equivalent set up is in SpringCloud OpenFeign, but I'm pretty sure there is one.  I would look at their documentation.

**Comment by cinatic** [comment]
thanks i already tried to add `@RequestLine` but it seems to be ignored when i use the `@FeignClient` annotation.

When i set the `@RequestLine` annotation i will get a "Missing Method" error, when i use 
```
@RequestMapping(method=["POST"])
@RequestLine("POST /blah")
```

the error is gone but the path is not mapped.

I am not very familiar with springs but i tried almost everything and did not found anything so far. Is this even the right place here or do they have an own github project?

**Comment by kdavisk6** [comment]
They have their own [project page and documentation](https://cloud.spring.io/spring-cloud-openfeign/)

**Comment by cinatic** [comment]
ah i see they have a own github repository as well, so i will try it there, thanks
