### ISSUE TITLE
feign client deserialization issues with type Instant

### ISSUE THREAD

**Issue by niteshchaudhary** [OpenFeign/feign#750]
In my model, there are some fields of type Instant. Looks like feign is unable to deserialize it. I get below error message while running my tests:
```
feign.FeignException: Can not construct instance of java.time.Instant: no String-argument constructor/factory method to deserialize from String value ('2018-07-29T21:28:23.013Z')
 at [Source: java.io.BufferedReader@3f06abd; line: 1, column: 805] (through reference chain: com.test.api.profile.model.testProfile["finishDate"]) reading GET http://localhost:8080/testProfile/<uuid>
```

**Comment by kdavisk6** [comment]
You will need a decoder for any non-trivial primitive data.  If you are using JSON and Jackson, you can use the `JacksonDecoder` with a custom `ObjectMapper` with Jackson's JSR-310 support.  

Take a look at the Jackson and GSON decoders for examples, if those do not work for you.

**Comment by niteshchaudhary** [comment]
@kdavisk6 it worked thanks
`new ObjectMapper().registerModule(new JavaTimeModule()).disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES))`

**Comment by scoppola84** [comment]
I solved using `org.joda.time.Instant `instead of `java.time.Instant` since the first retain the trailing zero 

eg: 2018-07-04T08:00:50.000Z remain the same after serialization intead with `java.time.Instant` it becomes 2018-07-04T08:00:50Z
