### ISSUE TITLE
Response body charset 

### ISSUE THREAD

**Issue by arebya** [OpenFeign/feign#757]
How can I pass the defined charset such as GBK to Response body when create InputStreamBody.
![image](https://user-images.githubusercontent.com/1525048/43760952-2ac8d8c2-9a56-11e8-904c-6285fb589330.png)

**Comment by velo** [comment]
You are correct, we need another `asReader(Charset encoding)`

As work around, you can use `asInputStream()` to create your own.

If you create a pull request for this, I can include on `10.0` release

**Comment by arebya** [comment]
I have created a pull request at [#764](https://github.com/OpenFeign/feign/pull/764)

**Comment by kdavisk6** [comment]
Closed via #766
