### ISSUE TITLE
Add Support for Multiple Types in JAX-RS Contract

### ISSUE THREAD

**Issue by dangoslen** [OpenFeign/feign#763]
When using the JAX-RS Contract, only the first value is used when setting the `Content-Type` or `Accept` header when using `@Consumes` or `@Produces` annotations respectively.

I would like for the JAX-RS Contract to support all the annotated types as the spec for HTTP says multiple values can be supplied. 

I'm happy to try my hand a PR to add this support.

**Comment by kdavisk6** [comment]
Closed via #765
