### ISSUE TITLE
Encoding of request parameters not working

### ISSUE THREAD

**Issue by jrbevan** [OpenFeign/feign#768]
We have configured our feign clients to use the JacksonEncoders so that requests are encoded as JSON.  However, request parameters (using @RequestParam) are not being JSON encoded.  Instead, their toString() method is called. So toString needed to be changed to return a JSON string.

Is this the expected behaviour?

**Comment by kdavisk6** [comment]
When using Request Parameters, yes, this is expected.  `@RequestParam` is a Spring annotation, as defined by the Spring Cloud OpenFeign Contract.  It's equivalent to OpenFeign's `@Param` annotation and follows the same rules.  `@Param` annotated fields end up on the Query String, url encoded.  If your intent is to send them as a request body, they don't need to be annotated at all.  

If your intent is to have them on the Query String, I don't think it's possible with the Spring Annotations.  With `@Param`, you can provide a custom `Expander`. 

I would also ask this question in Spring Cloud OpenFeign.
