### ISSUE TITLE
Usage of PATCH method with JaxRs2Contract

### ISSUE THREAD

**Issue by Shask** [OpenFeign/feign#785]
Hi,

I'm trying to send a PATCH Http request while using the JaxRs2Contract (and jersey http client)
however, I can't manage to get it right, I try a few ways already :+1: 

- including `@PATCH` from dropwizzard

- use `@RequestLine` on only the Patch Method ( Is there anyway to still use is with the JaxRs2Contract set ?)

Both were unsuccessful, can anyone recommend the best way to achieve this ?

Edit - formatting and addings

**Comment by kdavisk6** [comment]
Can you provide an example?  It will me and others diagnose your issue.

**Comment by Shask** [comment]
Sure,

I'm trying to achieve this.

 ```
    @GET()
    @Path("/{id}")
    Foo getFoo(@PathParam("id") String id);

    @POST()
    @Path("/")
    Foo createFoo(Foo foo);
    
    //trying to do this
    // Is there any knows support for @PATCH from dropwizzard.io
    @PATCH
    @Path("/{id}")
    Foo patchFoo(@PathParam("id") String id, Foo foo);
    
    //Or this
    //mix RequestLine and JAXRS2Contract in a single client
    @RequestLine("PATCH /{id}")
    Foo patchFoo2(@PathParam("id") String id, Foo foo);
```

But unfortunately, I can manage to find any solution to use PATCH method within a `FeignClient `with the `JaxRS2Contract `set.

**Comment by kdavisk6** [comment]
Nothing jumps out at me. Does the request get sent or do you get an exception?

**Comment by Shask** [comment]
At boot, I get a `java.lang.IllegalStateException: Method patchFoo not annotated with HTTP method type (ex. GET, POST)`

with both the `@PATCH` and the `@RequestLine("PATCH /{id}")`

More info in case that helps : 

Client initialization : 
```
 @Bean
    @Qualifier("fooClient")
    public FooClient fooClient() {
        return HystrixFeign.builder()
            .client(new ApacheHttpClient(httpClient()))
            .encoder(new JacksonEncoder(jacksonObjectMapper()))
            .decoder(new JacksonDecoder(jacksonObjectMapper()))
            .contract(new JAXRS2Contract())
            .target(FooClient.class, applicationProperties.getFgad().getServerUrl());
    }
```

**Comment by kdavisk6** [comment]
That helps a lot thank you.  That error indicates that Feign was unable to determine the HTTP method for the request based on the annotations on the Interface method.  My guess is that there is a conflict regarding which version of the `javax.ws.rs.HttpMethod` class Feign is using to parse the contract.

For starters, can you verify that you have only one JAXRS library on your class path?  If you have both 1.1 and 2.x, Feign will fallback to 1.1 support.  Also, you can't mix regular Feign annotations with other contracts.  Using `@RequestLine` will not work when you specify a different contract.

I'll look into the test cases as well, to see if there are any gaps regarding `@PATCH` support and any other JAXRS 2.x specific features.  What you have *should* work.

**Comment by Shask** [comment]
Unfortunately some dependencies are still using JAXRS 1.1, but I'm using JAXRS 2.1 `@PATCH` within my `FeignClient`.

Do you think it is the reason Feign couldn't recognize `@PATCH` as a HttpMethod ? 
I think with the proper `JaxRs2Contract` set on my `FeignClient` and the proper `javax.ws.rs.PATCH` annotation on my Client, Feign should be able to recognize the PATCH `HttpMethod` shouldn't it ?

**Comment by kdavisk6** [comment]
I believe your issue is not related to Feign, but the conflict between JAXRS 1.1 and JAXRS 2.1 jar files and your classpath.  The JAXRS Annotations share the same package names in both versions.  Their order on the classpath will determine which version of the annotation your application will use when they are in conflict.  While this is out of the scope of feign, one suggestion I can make is to see if you can have the jaxrs-2.1 library placed before the jaxrs-1.1 library in your classpath.

Feign will support the JAXRS-2.1 annotations if you can resolve this conflict.  I would strongly consider, if possible, refactoring your 1.1 dependencies and 2.1 dependencies into different artifacts.

**Comment by Shask** [comment]
Thank you for your helpful feedback.
