### ISSUE TITLE
RibbonClient uses hostname as clientname

### ISSUE THREAD

**Issue by CXgamer** [OpenFeign/feign#790]
My project uses Feign (10.0.1) with Ribbon and Eureka integration.

In RibbonClient#execute, the hostname of the request is used as the loadbalancer client. My VipAddress doesn't match its hostname however, so the RibbonClient is attempting to create a new one for the same service.

```java
  @Override
  public Response execute(Request request, Request.Options options) throws IOException {
    try {
      URI asUri = URI.create(request.url());
      String clientName = asUri.getHost();
      URI uriWithoutHost = cleanUrl(request.url(), clientName);
      LBClient.RibbonRequest ribbonRequest =
          new LBClient.RibbonRequest(delegate, request, uriWithoutHost);
      return lbClient(clientName).executeWithLoadBalancer(ribbonRequest,
          new FeignOptionsClientConfig(options)).toResponse();
    } catch (ClientException e) {
      propagateFirstIOException(e);
      throw new RuntimeException(e);
    }
  }
```

In particular, this method is entered with a Request object pointing to the correct URI which Eureka provided (in my case `http://192.168.x.x:8080/appName/path/to/rest/service`). Then it wrongly creates a new loadbalancer which will ask Eureka for the client `192.168.x.x`, which of course it won't find.

How is this supposed to work?

**Comment by kdavisk6** [comment]
Can you provide your Feign Builder?  My experience with Ribbon is limited, but I'll try to help.

**Comment by CXgamer** [comment]
Turns out it was my own fault (surprise). I was using `final Target<T> target = LoadBalancingTarget.create(client, uri);`, but should have used a `HardCodedTarget` instead. Thanks for your help anyway though. :)
