### ISSUE TITLE
SAXParseException: Premature end of file when Status Code is 204

### ISSUE THREAD

**Issue by selimok** [OpenFeign/feign#791]
Hi There, 

I just came across a problem with feign clients JaxbDecoder. While trying to decode it checks first the response status and if it's 404 then it returns a empty value of target type. This should be also the case for status code 204, since it indicates by design a response with no body. 

The current implementation missed the case and cause a SaxParseException

```
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]] with root cause
org.xml.sax.SAXParseException: Premature end of file.
```

Thanks.

**Comment by kdavisk6** [comment]
I believe the root cause of this is that `SynchronousMethodHandler` assumes that all `2xx` responses should be decoded.  It may be more appropriate the logic there to explicitly skip decoding on `204 No Content`.  Thoughts?
