### ISSUE TITLE
Question: @FeignClient info in ErrorDecoder implementation

### ISSUE THREAD

**Issue by SCesar93** [OpenFeign/feign#796]
Hello, I would like to know if inside an Error Decoder, has some way to retrieve the name and url values ​​of the @FeignClient responsible for the error.
Sorry for the dummy question. ;p
Thanks!!

**Comment by kdavisk6** [comment]
In our most recent set of updates, the original `Request` is part of `Response`, which is provided to the `ErrorDecoder`'s `decode` method.  From that you will be able to get the url that was used. 

`@FeignClient` is a Spring annotation and not from Feign.  If you need to know the name of the client, I would suggest asking that question of the Spring Cloud OpenFeign team.

**Comment by SCesar93** [comment]
Thanks @kdavisk6  !
