### ISSUE TITLE
JaxRsContract sends multiple Content-Type values

### ISSUE THREAD

**Issue by cakofony** [OpenFeign/feign#797]
Interfaces with multiple `@Consumes` annotations cause requests to be created with multiple Content-Type header values, which is invalid.

This regression was intruded with #763 (pr #765).  It makes sense for the `Accept` header, but I've had issues with interfaces annotated with multiple `@Consumes` values. Is there ever a case when we would want to send multiple content types? The request body can only be one type of content.

**Comment by cakofony** [comment]
@dangoslen I'm curious of your thoughts on this behavior

**Comment by cakofony** [comment]
It looks like we're never actually removing headers from the template despite comments which suggest otherwise

**Comment by dangoslen** [comment]
@cakofony looks like you are right and I was too greedy to add it to `@consumes`. I don't understand your last question though: 
> It looks like we're never actually removing headers from the template despite comments which suggest otherwise

Which comment are you referring to? It might be a previous comment that I missed updating.

sorry for introducing the regression :(

**Comment by cakofony** [comment]
Not a problem, your improvement to the `Accept` header allows me to get rid of some custom code in my project :-)

Regarding that comment, it's entirely unrelated to your change, just another issue I noticed while debugging this one. I filed a second issue to track it #798, and included the fix in my PR (#797).

Thanks for the quick reply, and for your contributions!
