### ISSUE TITLE
How can I give timeout while using openFeign(Not spring cloud feign). here is my configuration

### ISSUE THREAD

**Issue by ambujmobikwik** [OpenFeign/feign#808]
return Feign.builder()
                .client(new OkHttpClient())
                .encoder(new GsonEncoder())
                .decoder(new GsonDecoder())
                .errorDecoder(new RedirectFeignExceptionDecoder())
                .target(XYZ.class, "XYZabc");

Do I need to do Hysterix configuration also? if yes do we have a example

**Comment by kdavisk6** [comment]
You are missing one step in the builder.  There is an `options` method that takes a `Request.Options` object where you can define the timeout.

**Comment by ambujmobikwik** [comment]
Sorted. thanks
