### ISSUE TITLE
JacksonDecoder probably ignores decode404 flag

### ISSUE THREAD

**Issue by darrenxyli** [OpenFeign/feign#809]
For this line of code, https://github.com/OpenFeign/feign/blob/6ad5584f037164aacafc72307e6a8e44a62b3f92/jackson/src/main/java/feign/jackson/JacksonDecoder.java#L48

Even decode404 is enabled, after this https://github.com/OpenFeign/feign/blob/2d761cb6a92efc6b4a95e7092c945f47431b76cd/core/src/main/java/feign/SynchronousMethodHandler.java#L133, calling the decoder, but JacksonDecoder still will ignore the 404 response.

Please correct me if it's not working as this way.

**Comment by kdavisk6** [comment]
You are correct.  The Jackson Encode does not honor `404` responses.  Would you consider a PR to address this?

**Comment by darrenxyli** [comment]
@kdavisk6 for sure, will submit a PR later.

**Comment by dharmeshjogadia** [comment]
Hey @darrenxyli , @kdavisk6 
Very good findings. I encounter the same issue. I would like you to raise the PR for the same.

**Comment by velo** [comment]
Sure, I will take a look ASAP

**Comment by dharmeshjogadia** [comment]
Hey @velo 
Can you take a look at my [PR](https://github.com/OpenFeign/feign/pull/1012) ?

**Comment by velo** [comment]
Hi, did you had a chance to at comments Kevin placed on your PR?

**Comment by dharmeshjogadia** [comment]
Hi @velo, I have updated the PR as per comments by Kevin
