### ISSUE TITLE
Logging IOException

### ISSUE THREAD

**Issue by RobertMaj** [OpenFeign/feign#811]
I'm facing a problem with logging request and response - when IOException is thrown there is no way (eg. when read timeout exception occurs) to figure out what is the request that exception occurred for. There is an url but for POST request, it would be good to know what the body request is for read timeout analyze. I use unique traceId that is added to header in RequestInterceptor. I propose to add Request method parameter into Logger.logIOException() method.

**Comment by kdavisk6** [comment]
This issue and #845 could be solved by adding the original `Request` to `FeignException`.  Would this work?

**Comment by RobertMaj** [comment]
Yes, that would work in all situations expect catching and logging IOException in feign.Logger interface. Please take a look at feign.Logger.logIOException(String configKey, Level logLevel, IOException io, long elapsedTime) - unfortunately here we're not aware of request. Could be done by passing request in some class wrapping IOException or just adding request as another method parameter like in the other feign.Logger methods.

**Comment by finnetrolle** [comment]
I can add Request as argument into feign.Logger#logIOException and support this in usages inside
feign.SynchronousMethodHandler#executeAndDecode. I think this patch can solve problem. @kdavisk6 am I understand task right?

**Comment by kdavisk6** [comment]
Looking over the code again, @RobertMaj, the changes we've made to `FeignException` should allow you to accomplish this.  The original `Request` is now included during these scenarios.  I'm going to close this issue as it looks like we've added this support.

**Comment by jixiang-zhu** [comment]
I think this issue is still valid. I want to be able to log the request payload when an `IOException` is thrown. In `logIOException` method, there is no `Request` argument provided. And the exception argument `ioe` is of `IOException` type, which is not convertible type of
the `FeignException`, so having the `request` accessible from `FeignException` doesn't help here.
