### ISSUE TITLE
IllegalStateException on 1xx response codes

### ISSUE THREAD

**Issue by wirelessMousetail** [OpenFeign/feign#836]
Looks like there is no support for 1xx responses - Illegal state exception is thrown by Feign on any  response with code less than 200 during response building:
https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Response.java#L47

**Comment by rage-shadowman** [comment]
I wonder why it checks at all. It doesn't check for `>= 600` (which is where all the status lists I see stop).

**Comment by kdavisk6** [comment]
This seems like a fairly simple change.  There are enough checks in the `Client` that the additional check when creating the response seems unnecessary.  Since the `body` can be `null`, we should be able to support 1xx responses.
