### ISSUE TITLE
Incorrect parse @RequestLine @Param with question mark (/index.php?/)

### ISSUE THREAD

**Issue by shaburov** [OpenFeign/feign#838]
### Interface for DefaultContractTest.class
RequestLine contains `index.php?`
```
interface IndexPHPQuery {
    @RequestLine(value = "GET /index.php?/api/v2/get_case/{case_id}")
    void getCase(@Param("case_id") Integer caseID);
  }
```
### Test for DefaultContractTest.class
```
  @Test
  public void indexPHPQuestionMark throws Exception {
    List<MethodMetadata> mds = contract.parseAndValidatateMetadata(IndexPHPQuery.class);

    assertThat(mds.get(0).template().queries()).containsExactly(
            entry("case_id", asList("{case_id}")));
    assertThat(mds.get(0).formParams()).isEmpty(); // Prevent issue 424
  }
```

### Result
```
java.lang.AssertionError: 
Expecting:
  <{"/api/v2/get_case/{case_id}"=[]}>
to contain exactly (and in same order):
  <[MapEntry[key="case_id", value=["{case_id}"]]]>
but some elements were not found:
  <[MapEntry[key="case_id", value=["{case_id}"]]]>
and others were not expected:
  <[MapEntry[key="/api/v2/get_case/{case_id}", value=[]]]>
```

### Feign client log
```
[TestRailClient#getCase] ---> GET https://test.testrail.io/index.php?/api/v2/get_case/{case_id} HTTP/1.1
[TestRailClient#getCase] Content-Type: application/json
[TestRailClient#getCase] Content-Length: 19
[TestRailClient#getCase] Authorization: Basic cA2hhYnvyb2==
[TestRailClient#getCase] 
[TestRailClient#getCase] {
  "case_id" : 1
}
[TestRailClient#getCase] ---> END HTTP (19-byte body)
[TestRailClient#getCase] <--- HTTP/1.1 500 Internal Server Error (152ms)
[TestRailClient#getCase] connection: keep-alive
[TestRailClient#getCase] content-length: 71
[TestRailClient#getCase] content-type: application/json; charset=utf-8
[TestRailClient#getCase] date: Sun, 11 Nov 2018 21:48:42 GMT
[TestRailClient#getCase] server: nginx/1.13.12
[TestRailClient#getCase] 
[TestRailClient#getCase] {"error":"Invalid characters in URI: [\/api\/v2\/get_case\/{case_id}]"}
[TestRailClient#getCase] <--- END HTTP (71-byte body)
```
# Actual
`https://test.testrail.io/index.php?/api/v2/get_case/`**{case_id}**

# Expected
`https://test.testrail.io/index.php?/api/v2/get_case/1`

**Comment by shaburov** [comment]
If `/index.php?/api/v2` move to `target` request turns rubbish

### Interaface
```java
interface TestRailClient {
    @RequestLine(value = "GET /get_project/{projectID}", decodeSlash = false)
    Project getProject(@Param("projectID") Integer projectID);
}
```

### Test
```java
    public static void test_20181112013255() {
        TestRailClient client = new Feign.Builder()
                .encoder(new JacksonEncoder())
                .decoder(new JacksonDecoder())
                .logger(new FeignCallLogger())
                .logLevel(FULL)
                .target(TestRailClient.class, "https://test.testrail.io/index.php?/api/v2");
        Project testCase1 = client.getProject(1);
        assert testCase1.getId() == 1;
    }
```

### Feign client log
```
[TestRailClient#getProject] ---> GET https://test.testrail.io/index.php/get_project/1?/api/v2 HTTP/1.1
[TestRailClient#getProject] Content-Type: application/json
[TestRailClient#getProject] ---> END HTTP (0-byte body)
[TestRailClient#getProject] <--- HTTP/1.1 404 File Not Found (1078ms)
[TestRailClient#getProject] connection: keep-alive
[TestRailClient#getProject] content-length: 34
[TestRailClient#getProject] content-type: application/json; charset=utf-8
[TestRailClient#getProject] date: Sun, 11 Nov 2018 22:49:18 GMT
[TestRailClient#getProject] server: nginx/1.13.12
[TestRailClient#getProject] 
[TestRailClient#getProject] {"error":"Unknown method 'index'"}
[TestRailClient#getProject] <--- END HTTP (34-byte body)
```    

# Actual
`https://test.testrail.io/index.php/get_project/1?/api/v2`

# Expected
`https://test.testrail.io/index.php?/api/v2/get_project/1`

**Comment by shaburov** [comment]
If use `%3F` instead `?` then the problem can be solved by `RequestInterceptor`

### RequestLine
`"GET /index.php%3F/api/v2/get_projects&is_completed={is_completed}"`

### RequestInterceptor
```java
public class TestRailRequestInterceptor implements RequestInterceptor {
    @Override
    public final void apply(RequestTemplate template) {
        String fixIssue838 = template.request().url().replace("%3F", "?");
        template.uri(fixIssue838);
    }
}
```

**Comment by kdavisk6** [comment]
> ### Interface
> ```java
> interface TestRailClient {
>     @RequestLine(value = "GET /get_project/{projectID}", decodeSlash = false)
>     Project getProject(@Param("projectID") Integer projectID);
> }
> ```
> 
> ### Test
> ```java
>     public static void test_20181112013255() {
>         TestRailClient client = new Feign.Builder()
>                 .encoder(new JacksonEncoder())
>                 .decoder(new JacksonDecoder())
>                 .logger(new FeignCallLogger())
>                 .logLevel(FULL)
>                 .target(TestRailClient.class, "https://test.testrail.io/index.php?/api/v2");
>         Project testCase1 = client.getProject(1);
>         assert testCase1.getId() == 1;
>     }
> ```
> 
> # Actual
> `https://test.testrail.io/index.php/get_project/1?/api/v2`
> 
> # Expected
> `https://test.testrail.io/index.php?/api/v2/get_project/1`

This is correct behavior.  First, any Query parameters assigned to the `Target` will be separated from the base url.  Next, the request line will be appended to the base url along with all remaining queries.  From your configuration, the base url is:

`https://test.testrail.io/index.php`

Your `@RequestLine` defined a relative path with a uri template expression: `/get_project/{projectID}`, resulting in a new request line:

`https://test.testrail.io/index.php/get_project/{projectID}`

To achieve you expected result, you will need to adjust your request line.

```java
interface TestRailClient {
     @RequestLine(value = "GET ?/api/v2/get_project/{projectID}", decodeSlash = false)
     Project getProject(@Param("projectID") Integer projectID);
 }

TestRailClient client = new Feign.Builder()
                 .target(TestRailClient.class, "https://test.testrail.io/index.php");
```
This will result in your expected result.
