### ISSUE TITLE
Url field in FeignException

### ISSUE THREAD

**Issue by maxvetrenko** [OpenFeign/feign#845]
When RetryableException was caused we have information about url only in exception message. I think it will be useful to have url like an exception field. 

Some argumentation. Suppose we have several feign clients with same api type but different url. When RetryableException was caused we have information about unhealthy url only in exception message. Url  like field will give more possibilities to handle error more correctly

**Comment by kdavisk6** [comment]
I think what we may want to do is what we've done elsewhere and store the original request as part of `FeignException`.  Would this work for you?
