### ISSUE TITLE
How to return 404 as a normal call

### ISSUE THREAD

**Issue by vision1v1** [OpenFeign/feign#848]
The microservice I called returns 404, representing that the resource does not exist instead of an exception, how do I modify feign?
I tried to customize the Errordecoder but had to return an exception, so I tracked the source code and found that I might have to implement it again MethodHandler

**Comment by kdavisk6** [comment]
A 404 is a failed request.  It is Feign's perspective that any status not in the 2xx is considered an error.  If you want to override this behavior, you will need to provide your own `Client` implementation that does not throw an error on `404` response code.

**Comment by vision1v1** [comment]
Thank you for your answer, and if you follow RESTful's point of view, this part of the code should be customizable. For example, the httpclient generated by Autorest + swagger. In the actual project, this is a bit complex, feign although not in accordance with the restful to achieve, but the implementation of feign easy to understand.

**Comment by rage-shadowman** [comment]
Checkout `Feign.Builder.decode404()`
