### ISSUE TITLE
Should default implementations of QueryMapEncoder accept null parms?

### ISSUE THREAD

**Issue by derekmok** [OpenFeign/feign#851]
Hi! First of all just want to say that this is a great library, and thank you to all the maintainers and contributors.

On to the meat of the issue, what are people's thoughts on letting the default implementations of QueryMapEncoder allow null parameter values i.e. 

```
interface MyApi {
  @RequestLine("GET /foo")
  Foo getFoo(@QueryMap Bar bar)
}

class Bar {
  String baz;
}

class ApiClient {
  MyApi myApi = ...; // Get an instance of MyApi without overriding the default QueryMapEncoder
  void callApi() {
    Foo foo = myApi.getFoo(new Bar()); // This is fine, final url is /foo
    Foo foo = myApi.getFoo(null); // NPE.
  }
}
```
I would expect that passing in null would still be valid and the final url would be without query params, however that is not the case. What are everyone's thoughts on this?

**Comment by kdavisk6** [comment]
I think this is a violation of the interface contract and not an `@QueryMap` with query map.  For this specific case, you could solve the problem by defining two functions in your interface.

```java
interface MyApi {
  @RequestLine("GET /foo")
  Foo getFoo(@QueryMap Bar bar);
  
  @RequestLine("GET /foo")
  Foo getFoo();
}
```
Now you no longer need to provide or support `null` and you can use both methods when you need them.  Does that answer your question?

**Comment by derekmok** [comment]
Yep that indeed solves the problem, I hadn't realised you could define identical `@RequestLine` on methods with different signatures.

Out of curiosity though, where exactly do we say that `@QueryMap` method args cannot be null? I looked through the docs and can't seem to find where this is stated, so just wondering if I've missed it somewhere. 

Taking this a bit further, non-nullability of `@QueryMap` seems to be inconsistent with `@Param` when the variable is used as a query string, as nulls are allowed for query string `@Param` arguments, hence why I had the initial confusion:
```
interface MyApi {
  @RequestLine("GET /foo?fooId={fooId}")
  Foo getFooById(@Param("fooId") String fooId);
}

class UseMyApi {
  MyApi myApi = ...;
  void callApi() {
    Foo foo = myApi.getFooById(null); // Executes GET request on /foo
  }
}
```

**Comment by kdavisk6** [comment]
As part of feign 10.2, we corrected the inconsistency between `@QueryMap` and `@Param`.  I will double check the documentation and make sure that it correctly states that `@QueryMap` cannot be `null`

**Comment by kdavisk6** [comment]
Documentation is up to date and states that QueryMap can contain `null`, it just cannot be `null`.

https://github.com/OpenFeign/feign#dynamic-query-parameters
