### ISSUE TITLE
NPE when building `Response` without headers

### ISSUE THREAD

**Issue by micd** [OpenFeign/feign#853]
There is a NPE thrown when I'm trying to build `Response` without providing headers. I would propose to add a check in constructor such as for status and throw exception with proper message. Currently message does not say anything helpful. What do you think?

**Comment by velo** [comment]
Well, I think should be ok to create a `Response` with no headers... but, in general servers do add some.

What are you doing that you have no headers?

**Comment by kdavisk6** [comment]
@micd

I've submitted a PR that addresses this issue, but I would like to hear more about your situation.  As @velo has said, it's rare that a Response does not provide headers.

**Comment by micd** [comment]
Thanks for such quick response! I appreciate it! 

I have encountered that while building response just for tests. 
In real world there always (or usually) are headers (or header) present. I've just found inconsistency in logic. There was not a null check for headers and after that there was an operation on the map assuming that headers are present, but there is a possibility to build response without them.
