### ISSUE TITLE
feign load balance lead to lower service throughput

### ISSUE THREAD

**Issue by love-jay** [OpenFeign/feign#862]
I use the spring cloud with Finchley.RELEASE and spring boot 2.0.3.RELEASE;
For example, I have a service named 'A' and create two 'A' in port 8761,8762 , service B call the A by feign use default feign load balance  strategy.
The pressure test result`s that service throughput became lower.
I don`t know how to explain this. Any question in my word?

**Comment by kdavisk6** [comment]
There are so many variables that could account for something like this.  My suggestion is that you perform some more testing of your applications to determine exactly where the performance issue is.  Second, this is OpenFeign and not Spring Cloud.  Please open issues related to Spring Cloud with the Spring Cloud Team.
