### ISSUE TITLE
Feign SOAP

### ISSUE THREAD

**Issue by diegossilveira** [OpenFeign/feign#863]
Hey!

I started using feign-soap (10.2.0-SNAPSHOT version) module on a project and I would like to know when will it be released and available on maven central repository.

Thanks!

**Comment by kdavisk6** [comment]
Not really sure.  We don't have a regular release cadence.  We may want to start.  Either way, I'll check in with the other maintainers and see if we have anything else we would like to get into 10.2.

**Comment by kdavisk6** [comment]
This was released with 10.2

**Comment by megha0703** [comment]
Can any one provide any example for SOAP feign client.
