### ISSUE TITLE
Is the feignclient post request parameter limited in length？

### ISSUE THREAD

**Issue by alant77** [OpenFeign/feign#865]
eg:
@RequestMapping(value="/crl-centre/v2/hel", method = RequestMethod.POST)
JSONObject test(@RequestParam(required = false, name = "jsonString") String jsonString);

fallback when the jsonString size is 8k. 
so,
is the parameter jsonString limited in length? How to deal with it？please

**Comment by rage-shadowman** [comment]
Many web servers have a max character limit on URL length (request params are part of the URL) and may truncate your request if you pass that limit.

Because of this, many people recommend using a POST with a body instead of very large query param sets.

**Comment by alant77** [comment]
good! But I am using the post method, still not working.

**Comment by alant77** [comment]
> Many web servers have a max character limit on URL length (request params are part of the URL) and may truncate your request if you pass that limit.
> 
> Because of this, many people recommend using a POST with a body instead of very large query param sets.

good!  But I am using the post method, still not working.

**Comment by kdavisk6** [comment]
I believe your issue is that you have specified your data as a RequestParam. This will place the value on the query string and not in the request body. You may need to refactor your interface to remove the annotation to have the value placed in the body.

**Comment by kdavisk6** [comment]
Another important note, this is OpenFeign and not Spring Cloud.  Spring Cloud provides an extension to OpenFeign and is responsible for the Contract you are using.  When using Spring Cloud, please open issues with the Spring Cloud team.
