### ISSUE TITLE
feign.OkHttpClient does not close response when requests complete exceptionally

### ISSUE THREAD

**Issue by azulkarnyaev** [OpenFeign/feign#868]
Hi Feign Team!
I use SpringCloud with FiegnClient / OkHttpClient and I have a problem: when feign client requests failed exceptionally, the client start to write warn messages "A connection to web_server_ulr was leaked. Did you forget to close a response body?".
May be it would be better to handle exceptionally cases in feign.okhttp.OkHttpClient#execute() method and close the response?

**Comment by kdavisk6** [comment]
@azulkarnyaev 

Do you have a sample project or test case you can provide that can reproduce this situation?  The responses should be closed before returning, unless you specifically specify that the response of your method is a `Response` like so:

```java
public interface TestService {
   @RequestLine("GET /stuff)
   feign.Response getStuff();
}
```
If you are doing this, it's your responsibility to close the `Response` or you will have a resource leak.

**Comment by kdavisk6** [comment]
Given that almost a year has gone by on this issue, I'm going to assume you either got the issue corrected or moved on.  If this is not the case, please respond with a test case and we can resume this discussion.

**Comment by LoopKarma** [comment]
Sorry for resurrecting old issue, but I stuck with this case where I have Response type returned from endpoint. Also I have a custom Client that should return Response from the execute method.
Custom client code is simple:
```
public class CustomClient implements Client {
    private final Client client;

    @Override
    public Response execute(final Request request, final Request.Options options) throws IOException {
        log.debug("About to call feign endpoint {} {}", request.httpMethod(), request.url());
        Response response = client.execute(request, options);
        return response;
    }
```

 According to what I figured out, after client execution, response instance is taken by `feign.AsyncResponseHandler#handleResponse` where it checks if body length is null, then do not close response. This exactly what I have for some endpoints, that resulting in complaining from Okhttp that connection is leaked. 
Do you have a suggestion how to close Response, when body is empty? 
Thank you
