### ISSUE TITLE
Feign 10.1, '+' in query param is not encoded

### ISSUE THREAD

**Issue by grusell** [OpenFeign/feign#895]
I would expect a '+' inside a query parameter value to be encoded to '%2B'. With feign 10.1, it seems the '+' is left untouched when the param is encoded.

**Comment by cecchisandrone** [comment]
I noticed the same while migrating from 9.3.1 to 10.0.1.

**Comment by kdavisk6** [comment]
It is a duplicate.  It has been fixed via #882
