### ISSUE TITLE
Support for specifying custom criteria for error

### ISSUE THREAD

**Issue by amjd** [OpenFeign/feign#907]
Hi there,

I have a feature request for Feign. In `ErrorDecoder`, can we have a method to specify custom criteria for an error? Currently Feign considers all non-2xx status code responses as errors (with the exception of 404, which is configurable).

So along with `decode`, we could have a `hasError` method as well, which would also be passed a `Response` object. That method could then return a boolean value indicating whether the `ErrorDecoder#decode` method should be invoked, or a non-error decode should be attempted. This is not unlike how you implement custom error handlers in Spring RestTemplate.

An example use case would be, for some reason all my Feign interfaces have String or JsonNode as their return type and I want Feign to decode the responses in the regular fashion, regardless of the response status.

Let me know if this behaviour is already supported. I couldn't find it after going through the wiki and documentation.

**Comment by kdavisk6** [comment]
@amjd 

This is the primary use case for the `ErrorDecoder`.  It's the opinion of Feign that responses that present HTTP Status Codes outside of the defined range are exceptions.

The preferred pattern is for users to handle these status codes in an `ErrorDecoder` and produce application and/or domain specific exceptions.

Take a look at the following example:

```java
interface GitHub {
   @RequestLine("GET /repos/{owner}/{repo}/contributors
   List<Contributor> getContributors(@Param("owner") String owner, @Param("repo") String repository);
}
```

```java
public class GitHubErrorDecoder implements ErrorDecoder {
   /* decoder to use when parsing the response body */
   private final Decoder delegate;

   public GitHubErrorDecoder(Decoder delegate) {
      this.delegate = delegate;
   }
   public Exception decode(String method, Response response) {
      /* get the response body */
      Error error = this.delegate.decode(Response response, Error.class);

      if (404 == response.status()) {
         // handle the 404, including the response body with the exception
         throw new RepositoryNotFoundException(error);
      }
      // add additional status handlers here.
   }
}
```

```java
public class GitHubClient {
   private final GitHub gitHub;

   public GitHubClient() {
      this.gitHub = Feign.builder()
         .decoder(new JacksonDecoder())
         .errorDecoder(new GitHubErrorDecoder(new JacksonDecoder()))
         .target(GitHub.class, "https://api.github.com");
   }
   
   public List<Contributor> getContributorsForRepository(String owner, String repository) {
      try {
         return this.gitHub.getContributors(owner, repository);
      } catch (RepositoryNotFoundException nfe) {
         // deal with 404, the body is available on the exception for further inspection
     } catch (ServiceUnavailableException se) {
         // deal with 503
     }
   }
}
```

This technique separates the internal request management from the components that rely on the Feign clients, enforcing the **Separation of Concerns** pattern.  I suspect this may not be exactly what you are asking for, but I challenge you to consider this approach.  

Ask yourself the following questions when thinking about this.

- How are dealing with failures now?  
- What patterns am I using today?  
- Could a pattern like the one suggested work?

**Comment by kdavisk6** [comment]
Please see my comment in https://github.com/OpenFeign/feign/issues/1013#issuecomment-554539796 for a more thorough explanation
