### ISSUE TITLE
NullPointerException if content in FeignException is null

### ISSUE THREAD

**Issue by robachmann** [OpenFeign/feign#912]
I tried to parse and react on a FeignException and noticed that accessing `FeignException::contentUTF8` throws a NullPointerException if `content` is null:
https://github.com/OpenFeign/feign/blob/db44bfe7077705e6249565893f96470574815c38/core/src/main/java/feign/FeignException.java#L60

The value was null because there was an underlying connection issue (`status` was 0).

Could this be rewritten to return 'null' if the value of `content` is also null? 

Thank you very much!

**Comment by kdavisk6** [comment]
@robachmann 

Thank you for bringing this to our attention.  This is clearly a bug.  Would you be able to help us by creating a PR correcting the issue?

**Comment by robachmann** [comment]
Thanks, I will try and come up with a PR or further questions :-)
