### ISSUE TITLE
Query param with comma produce multiple query params

### ISSUE THREAD

**Issue by StasKolodyuk** [OpenFeign/feign#924]
Hi,

The behavior for query params containing a comma has changed in 10.2.0
Consider the following example:
```
@FeignClient(name = "postman", url = "https://postman-echo.com")
public interface PostmanEchoClient {
    @GetMapping("/get")
    void echo(@RequestParam String param);
}

@SpringBootTest
@RunWith(SpringRunner.class)
public class FeignCommaQueryParameterIssueTest {

    @Autowired
    PostmanEchoClient postmanEchoClient;

    @Test
    public void test() {
        postmanEchoClient.echo("first,second");
    }
}
```
10.1.0 produces the following request (what I think is correct): `https://postman-echo.com/get?param=first%2Csecond`
10.2.0 produces: `https://postman-echo.com/get?param=first&param=second`

I've prepared an example reproducing the issue [here](https://github.com/StasKolodyuk/feign-comma-issue). See `master` and `feign_10.1.0` brances to point the difference

Thanks

**Comment by kdavisk6** [comment]
@StasKolodyuk 

Thank you for bringing this to our attention.  This is a similar issue to #922.  I'm pretty sure it has to do with Collection based Query Parameters and how our logic is identifying parameter lists versus parameter values.  

In the meantime, you can work around this bug by encoding the values before passing them to the method and updating your `@Param` annotation to set the `encoded` value to true.
