### ISSUE TITLE
CDI module has an error when looking for the bean scope

### ISSUE THREAD

**Issue by garcia-jj** [OpenFeign/feign#925]
There are an error in the Feign CDI module, when the producer bean tries to get the bean client scope annotation. 

Calling `getClass()` on an annotation may return a proxy class instead of wanted class.

Related pull request: OpenFeign/feign-cdi#7

**Comment by kdavisk6** [comment]
Can you please open this issue in the feign-cdi project as it relates directly to that module?

**Comment by garcia-jj** [comment]
> Can you please open this issue in the feign-cdi project as it relates directly to that module?

I did, but I think feign-cdi project is not active anymore. Anyway, thank you.

Best regards.

**Comment by kdavisk6** [comment]
@garcia-jj 

I would help more if I knew more about it.
