### ISSUE TITLE
ClassNotFoundException: feign.Request$Body

### ISSUE THREAD

**Issue by neketsushonen** [OpenFeign/feign#926]
Hi, I am implementing upload file with this library, but it always throw this exception (like pictures)
<img width="995" alt="image" src="https://user-images.githubusercontent.com/6796975/54945594-ffbc9500-4f14-11e9-8f18-fe5a2a3c06f3.png">

So I go to the library to verify if that class is existed (Request.Body), and I found there is not the inner class Request.Body only Request.Option, the class Body is out of Request.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/6796975/54945717-3d212280-4f15-11e9-930f-a5bf0f1b9b5a.png">

But in the code of the version 3.7.0, 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/6796975/54945920-be78b500-4f15-11e9-9335-a1722098bf7d.png">

it is always use "Request.Body" please your help

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/6796975/54945862-9426f780-4f15-11e9-9039-98af81bf3468.png">

**Comment by kdavisk6** [comment]
@neketsushonen 

You will need to use Feign 10.x or higher.  Please check your dependencies.

**Comment by LareinaH** [comment]
if you use feign-form, only Feign **10.1.x** or higher is supported
however, what makes me confused is that 10.1.0 does not appear in release list while  exist in repo：https://mvnrepository.com/artifact/io.github.openfeign/feign-core/10.1.0

**Comment by kdavisk6** [comment]
The general rule here is to use the most recent, stable version of Feign.  As of this comment, that version is 10.2.3
