### ISSUE TITLE
feign.httpclient.ApacheHttpClient should not setEntity when request body is null in order to support application/x-www-form-urlencode

### ISSUE THREAD

**Issue by starrybleu** [OpenFeign/feign#932]
In recently, I replaced "com.netflix.feign:feign-httpclient:8.18.0" with "io.github.openfeign:feign-httpclient" along with spring boot application, because which from netflix is deprecated.

I found a difference between two dependencies that one from netflix let entity null on building request, the other from openfeign(this repo.) let entity be an empty byte array.

So, `org.apache.http.client.methods.RequestBuilder` comes to finally build  a `HttpUriRequest` of `InternalRequest` skipping making entityCopy be `UrlEncodedFormEntity`, even if headers has 'Content-Type: application/x-www-form-urlencoded'.

So I finally got 400 Bad Request from other spring cloud server.

I think, as a wrapper of apache http client, feign.httpclient  should follow apache's implementation.

**Comment by kdavisk6** [comment]
Support for forms including multi-part and x-www-form-urlencoded requests has been moved into another library, feign-form.  Please add that dependency, update your Feign Target [per their documentation](https://github.com/OpenFeign/feign-form) and try again.

**Comment by starrybleu** [comment]
@kdavisk6 Thanks you for your response. I have already known feign-form library, you mentioned, and had a dependency in my project. However, I think the problem is not regarded with feign-form or en/decoding. The fact that `feign.httpclient.ApacheHttpClient` makes entity not null cause `org.apache.http.client.methods.RequestBuilder` not to UrlEncode parameters is the problem.

For additional information, spring boot 2.0.8.RELEASE, spring-cloud-starter-openfeign:2.0.2.RELEASE, io.github.openfeign:feign-httpclient:9.7.0, feign-form:3.3.0

**Comment by kdavisk6** [comment]
@starrybleu 

I recommend, if at all possible, upgrading to the latest versions of those libraries.  Feign is now at 10.2.3 and Spring Cloud Stater Open Feign is at 2.1.0.RELEASE.

There is a strong possibility your issue has been addressed.

**Comment by starrybleu** [comment]
@kdavisk6 

Thank you for your notice. 

If it was resolved when I check out, I'll close this issue.

**Comment by starrybleu** [comment]
I have tried, but doesn't work.

I will create a pull request that I think what should be fixed is.

**Comment by starrybleu** [comment]
I found it has conflict with #510, #511. But after failed to test, dug into the `RequestBuilder`. Test of `withoutBody` should be done along without `@PUT` or `@POST`.

**Comment by kdavisk6** [comment]
From what I can tell looking into this, the issue lies with our use of the `RequestBuilder`, which explicitly states: 

> Please note that this class treats parameters differently depending on composition of the request: if the request has a content entity explicitly set with setEntity(org.apache.http.HttpEntity) or it is not an entity enclosing method (such as POST or PUT), parameters will be added to the query component of the request URI. Otherwise, parameters will be added as a URL encoded entity.

Since you appear to be one of a few with this issue, I suspect the issue is in your implementation.  Can you please provide a test case the replicates your issue?
