### ISSUE TITLE
Body parameter was null problem when MultipartFile param is null

### ISSUE THREAD

**Issue by genter** [OpenFeign/feign#933]
Request has a nullable parameter which type is MultipartFile，here is a demo:
```java
@PostMapping(value = "test", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
void test(@RequestPart(value = "file", required = false) MultipartFile file);
```

But feign will do param check，body param can't be null，below is the exception:
```java
Caused by: java.lang.IllegalArgumentException: Body parameter 6 was null
	at feign.Util.checkArgument(Util.java:102) ~[feign-core-9.4.0.jar:na]
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:348) ~[feign-core-9.4.0.jar:na]
```

**Comment by kdavisk6** [comment]
In this case, I suspect that you don't have the right version of Feign and Feign Form.  Please make sure that your Feign Form versions are compatible with your Feign version.  Check the readme here https://github.com/OpenFeign/feign-form

**Comment by genter** [comment]
The requirements section in [feign-form's readme](https://github.com/OpenFeign/feign-form)：
`all feign-form releases before 3.5.0 works with OpenFeign 9.* versions`

I use spring boot **2.0.6.RELEASE**、 spring cloud **Finchley.SR1(use openfeign 9.5.1)** for test and hardcode the `feign-form、feign-form-spring` version to **3.4.1**，but the problem is still in.

This is full demo，Assuming that i want to call a send mail api，the attatchments is nullable.
```java
@FeignClient(value = "service2", configuration = RemoteService2.MultipartSupportConfig.class)
public interface RemoteService2 {

    @PostMapping(value = "test", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    void test(@RequestPart(value = "file", required = false) MultipartFile file);

    @Configuration
    class MultipartSupportConfig {
        @Bean
        public Encoder feignFormEncoder() {
            return new SpringFormEncoder();
        }
    }
}
```

**Comment by kdavisk6** [comment]
@genter 

The error message is telling you what you need to know.  Feign does not support optional Request Body data.  This is expected behavior.  In your case, you will need two methods, one with the multipart and one without, if you want to use Feign and Feign Form.

```java
public interface MailClient {

   @PostMapping("/send", consumes = MediaType.APPLICATION_FORM_URL_ENCODED)
   void send(@RequestParam("message") String message);

   @PostMapping("/send", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
   void send(@RequestParam("message") String message, @RequestPart("attachment") MultipartFile file);
}
```

**Comment by genter** [comment]
@kdavisk6 Thanks. i got it
