### ISSUE TITLE
Fragment identifiers are handled incorrectly

### ISSUE THREAD

**Issue by rejierd** [OpenFeign/feign#936]
When making requests with fragment identifiers in the URL, the hash mark "#" gets URL encoded as "%23" and put in front of the the query.

E.g. what should be "/path?key1=value1#fragment" becomes "/path%23fragment?key1=value1".

You can read more about fragment identifiers here:
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax
https://en.wikipedia.org/wiki/Fragment_identifier

**Comment by rejierd** [comment]
@kdavisk6 when do you expect to make the next release?

**Comment by flisky** [comment]
It's backward incompatible, and conflicts with rfc3986. See my [comment](https://github.com/OpenFeign/feign/pull/937#issuecomment-483521737)
