### ISSUE TITLE
[feign-jackson] Use Jackson-module "Afterburner"

### ISSUE THREAD

**Issue by SchulteMarkus** [OpenFeign/feign#943]
Hi there,

there is a [Jackson-module "Afterburner"](https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#compatible-easy-afterburner) available. 

As far as I can see, feign-jackson is not using Afterburner. I suggest trying it.

From my point of view, it seems to be quite promising to improve the performance of feign-jackson.

> After going through couple of compromises (easy OR compatible), there is one approach that is both easy AND compatible (yay!): Jackson Afterburner Module.
> 
> The Afterburner module optimizes the underlying serializers and deserializers.
> 
> - Uses byte code generation to replace Java Reflection calls (used for field and method access and constructor calls) with actual byte code -- similar to how one would write explicit field access and method calls from Java code
> - Inlines handling of a small set of basic types (String, int, long -- possibly more in future), so that if the default serializer/deserializer is used, calls are replaced by equivalent standard handling (which eliminates a couple of method calls, and possible argument/return value boxing)
> - Speculative "match/parsing" of ordered property names, using special matching calls in JsonParser -- this can eliminate symbol table lookups if field names are serialized in the same order that Jackson serializes them (which may be indicated by use of @JsonPropertyOrder)
>
> Since these optimizations more or less mimic more efficient patterns used by "hand-written" converters (i.e. our first option, use of the Streaming API), performance improvements could theoretically reach the level of such converters. In practice, we have observed improvements in 60-70% range of this maximum (that is, Afterburner can eliminate 2/3 of overhead that standard databinding has over hand-written alternatives).

The integration of the module seems to be easy to do. But I cannot overview the effect for people using feign-jackson.

**Comment by kdavisk6** [comment]
@SchulteMarkus 

Thanks for the information.  The Jackson Encoder can support a user provided instance of the `ObjectMapper`.  If user's want to use Afterburner, they are free to do so.  It is this project's stance that we limit the number of external dependencies required to only the minimum required for the core library to work.  With that said, I don't think we should enable Afterburner by default.  That decision is better left up to the users.

**Comment by SchulteMarkus** [comment]
You're welcome.

You are right, one more dependency, which is not used by everyone, seems not to be useful. On the other side, I am using feign-jackson for having jackson as part of my dependencies. If I add jackson-afterburner myself, I will have to keep the jackson-afterburner version in sync with that one, feign-jackson is using, when I update feign-jackson.

What do you think about including jackson-afterburner as an [optional Maven dependency](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)? And maybe pointing to https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#compatible-easy-afterburner or https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance at https://github.com/OpenFeign/feign/tree/master/jackson ?

**Comment by velo** [comment]
May be extra docs on how to Afterburner?

**Comment by kdavisk6** [comment]
I think adding more documentation would be a great idea here.

**Comment by SchulteMarkus** [comment]
What do you think about my idea, adding jackson-afterburner module as an optional Maven dependency?

I had the additional idea to declare every Jackson-module as an optional dependency, or even better I think, declare a Maven "Bill of material" (BOM) which can be used for dependency management in any project, which uses feign-jackson.

**Comment by velo** [comment]
I don't understand why the dependency would be necessary, of this is something set when using feign

**Comment by SchulteMarkus** [comment]
Well.. for convenience.
If I use feign-jackson, and I want to use the Jackson module "Afterburner" (for example), I would myself include Afterburner v.2.9.8. into my project, beside feign-jackson v.10.2.0, as time of writing. For being sure to include the correct version of the Jackson module, I had to have a look at jackson.version in feign/pom.xml https://github.com/OpenFeign/feign/blob/master/pom.xml#L75 
Every time I update feign-jackson in the future, I will have to repeat this step. Otherwise, the versions will mismatch.
If feign-jackson would declare an optional dependency, or BOM, I would not have to take care of the versions being in sync.

**Comment by SchulteMarkus** [comment]
By the way, Jackson has itself a BOM https://github.com/FasterXML/jackson-bom
In my opinion, because feign-jackson includes / depends on Jackson, it kind of inherits the reasons for having a BOM.

**Comment by kdavisk6** [comment]
@SchulteMarkus 

Our reluctance here is that we feel that Feign should not be used to manage an applications transient dependencies.  That is the responsibility of the application owners.  We aim to keep the number of dependencies as low as possible, including only what we need to compile and test what we provide.  This allows us to keep Feign simple and maintainable over the long term.

Using your example, applications that use Feign can include the Jackson BOM in their project, above Feign, allowing the Jackson BOM to manage feign-jackson's dependencies for you.

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson</groupId>
            <artifactId>jackson-bom</artifactId>
            <version>2.9.8</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>   
    </dependencies>
</dependencyManagement>
<dependencies>
   <dependency>
      <!-- jackson dependencies of feign will be managed by the jackson bom -->
      <groupId>io.github.openfeign</groupId>
      <artifactId>feign-jackson</artifactId>
      <version>10.2.0</version>
   </dependency>
</dependencies>
```

But, the point here is, that is up to the application and not Feign.

**Comment by SchulteMarkus** [comment]
Excellent feedback. You are right, that's the way to go.
