### ISSUE TITLE
if have to set <client>.ribbon.listOfServers?

### ISSUE THREAD

**Issue by l-qiang** [OpenFeign/feign#951]
I can use @LoadBalanced, but if i use Feign I have to set <client>.ribbon.listOfServers.
if i don't set ,the (Server currentServer = lb.chooseServer(null);) currentServer is null.

**Comment by kdavisk6** [comment]
@l-qiang 

You will need to pose this question to the Spring Cloud OpenFeign team.  The `@LoadBalanced` annotation is part of their Ribbon support and is different from our support.

**Comment by l-qiang** [comment]
Sorry, I didn’t express it clearly.
 I saw that “This integration relies on the Feign Target.url() being encoded like https://myAppProd where myAppProd is the ribbon client or loadbalancer name and myAppProd.ribbon.listOfServers configuration is set.” 
But in Spring Cloud docs,  if I use Ribbon with Eureka，I do not need to set `<client>.ribbon.listOfServers` . if `<client>.ribbon.listOfServers` configuration is not set,the `@LoadBalanced` is workable, but `feign.ribbon.RibbonClient` is unworkable.
