### ISSUE TITLE
Improve Release Process with Travis

### ISSUE THREAD

**Issue by kdavisk6** [OpenFeign/feign#963]
Releasing `feign`, while simple, can be troublesome due to the updates we've made recently in an attempt to provide initial support for JDK 11.  

The current release process assumes a single job in travis and our changes to support JDK 11 split each build into 2 jobs, one for JDK 8 and other for JDK 11.  This poses an issue when releasing as the build process will attempt to tag and release twice.  To avoid this, we, the maintainers, temporarily disable the JDK 11 builds, push the release, then re-enable them again after the release is complete.

In addition, the release process requires a temporary tag to trigger the process.  This results in two tags for each release.  We typically delete the trigger tag afterwards to reduce confusion.

I feel this should not be necessary and that releasing should be "easy".  To make this "easier", I'm proposing the following changes:

1. Take advantage for Travis' [Conditional Build Stages](https://docs.travis-ci.com/user/build-stages/) to separate the `test` stage from the `deploy` stage.
2. Update this new `deploy` stage to run only when a **tag** is created, removing the need to create a temporary **release** tag.
3. Provide an automated way of creating the release **tag**, to reduce errors.

I've create a PR #962 that demonstrates these changes.  Looking forward to your feedback.

**Comment by velo** [comment]
The new release page looks awesome
