### ISSUE TITLE
Document POST body example

### ISSUE THREAD

**Issue by wulftone** [OpenFeign/feign#978]
After a bunch of experimentation, I figured out that you can use a POJO as a POST body, but I couldn't find it anywhere in the documentation.  e.g. You can do
```java
public interface Boop {
    @RequestLine("POST /boop/{someParam}")
    @Headers({
        "Accept: application/json",
        "Content-Type: application/json"
    })
    BoopResponse createBoopUsingPOST(Boop boop, @Param("someParam") String someParam);

    class Boop {
        public String value;
    }
}
```
But the tricky part is that the POJO param (`boop`, in the example), _must_ come first in the parameter list of the method.  That was difficult to find out!

**Comment by kdavisk6** [comment]
@wulftone 

Thanks for this example.  It is missing from the documentation.  You can define the body of the request two ways:

* annotating the parameter with `@Body`
* the first method parameter without an annotation is assumed to be the `Body`

We should update the documentation to explain this and add you example.

**Comment by eiselems** [comment]
@wulftone  @kdavisk6 is this like you had it in mind?

**Comment by wulftone** [comment]
Pretty much, I commented on the pr: https://github.com/OpenFeign/feign/pull/986#issuecomment-500635251

**Comment by eiselems** [comment]
@wulftone is it really failing for you when you put the boop paramater in any other position?
I updated the github-example in the repository and it works in all positions.

**Comment by wulftone** [comment]
Yes, let me verify exactly why and get back to you... It is interesting that you found it doesn't matter in the example

**Comment by sleroy** [comment]
Indeed I lost 10 minutes to find an Example. Could not guess it easily from the readme...

**Comment by eiselems** [comment]
@sleroy hoped the example would be sufficient 

```
  @RequestLine("POST /repos/{owner}/{repo}/issues")
  void createIssue(Issue issue, @Param("owner") String owner, @Param("repo") String repo);

```

How should we improve it?
