### ISSUE TITLE
Template variables NOT expanded in the target URL (Feign 9.5.1)

### ISSUE THREAD

**Issue by xorcus** [OpenFeign/feign#983]
```
SynchronousMethodHandler.invoke():72
    ReflectiveFeign$BuildTemplateByResolvingArgs.create():213
    ReflectiveFeign$BuildTemplateByResolvingArgs.resolve():326
    ReflectiveFeign$BuildTemplateByResolvingArgs.resolve():297
    ReflectiveFeign$BuildTemplateByResolvingArgs.resolve():297
    RequestTemplate.resolve():223
    // Expanding of template variables happens in this call:
    RequestTemplate.expand():119

SynchronousMethodHandler.invoke():76
  SynchronousMethodHandler.executeAndDecode():88
  SynchronousMethodHandler.targetRequest():160
  Target$HardCodedTarget<T>.apply():90
  // The base URL is inserted at this point, so its path variables do not get expanded:
  RequestTemplate.insert():302
```

**Comment by kdavisk6** [comment]
@xorcus 

Thank you for your report.  To help us better understand your issue, can you please provide the following:

- A Brief explanation of what you are trying to achieve
- What behavior you expect
- What behavior you experienced
- If possible, a small test case reproducing the issue.

In your particular case, you are using an older version of Feign.  Your issue may be resolved in a recent update.  If you can, please try using our most recent version, which as of today is 10.2.3

**Comment by kdavisk6** [comment]
If this is still an issue, please add the requested information and re-open.

**Comment by xorcus** [comment]
In the example below, I would like to move the repeating part `/{tenantId}/v1/example` from `@GetMapping` to the annotation `@FeignClient` attribute `url`.

The problem is that `{tenantId}` placeholder does not get resolved to the value of `String tenantId` argument because of the execution flow, as explained in my original issue description. In short, `SynchronousMethodHandler.invoke():72` resolves the variables, but the `url` gets pre-pended later, in `SynchronousMethodHandler.invoke():76`.

Note: The example uses Spring integration, but it simply passes these values down to Open Feign, i.e. it would be possible to create similar example using only Feign, without Spring.

```
import javax.validation.constraints.NotNull;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;

@FeignClient(name = "contracts-example", url = "${rest.client.server-url}/contracts/example")
@Validated
public interface ExampleRestClient {

  @GetMapping("/{tenantId}/v1/example/{id}")
  ExampleDto getExample(@NotNull @PathVariable("tenantId") String tenantId, @NotNull @PathVariable("id") Identifier id);

  @GetMapping("/{tenantId}/v1/example")
  ExampleDto getExampleByMnemonic(@NotNull @PathVariable("tenantId") String tenantId, @NotNull @RequestParam("mnemonic") String mnemonic);
}
```

**Comment by xorcus** [comment]
Sorry, I could not figure out how to reopen this issue. No reopen button, I can only add comments and unsubscribe from notifications.
