### ISSUE TITLE
Invalid Utf-8 middle byte

### ISSUE THREAD

**Issue by metalpalo** [OpenFeign/feign#984]
Hi guys,

I use feign-httpclient version 9.5.0 in my project and want to send json as body to another service receiver. Json contains special characters like "ì" and when receiver (controller on receiver microservice) receive that it crash with folliwing error.

> org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Invalid UTF-8 middle byte 0x74
at [Source: (PushbackInputStream); line: 9, column: 24]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 middle byte 0x74

I simulated this error when encoding it in ISO-8859-1 charset a post it via Postman for instance. 
So my is how does client encode my body by default? Does is use ISO-8859-1?

Is possible on client to set encoding charset for my body?

thanks
brpalo

**Comment by kdavisk6** [comment]
@metalpalo 

Unless overridden in an `Encoder`, feign will use UTF-8 by default.  On your client are you using Spring Cloud or vanilla Feign?  Do you happen to know which Encoder you are using?

**Comment by metalpalo** [comment]
we use spring cloud feign I think. AFAIK we don't define any encoder bean. We just added feign-core and feign-httpclient dependencies into project. What do you think of encoder? Encoder used within httpclient?

**Comment by kdavisk6** [comment]
Spring Cloud defines it own encoder that inspects the Media Type included in the `@RequestMapping` annotation to determine to determine the correct encoder to use before sending it to your downstream service.  Looking over their most recent code, it always uses `UTF-8` as the charset as well.

In your case, it appears that your JSON payload is not being generated using UTF-8 charset but rather your system charset.  Would you happen to reading your payload from a file system?

**Comment by metalpalo** [comment]
We don't read json from filesystem, but simply filled pojo is serialized by jackson and sent to service via feign. In all machines we have set file.encoding=UTF-8. 

But when I removed dependecy feign-httpclient from maven, default client from feign-core is used and everything works fine. We preffer to use feign-httpclient due to issues when executing PATCH operation.

I will investigate about encoder after weekend. Perhaps it's better to debug it and find somewhere something like encoding usage.

Can you tell me what is difference between Spring Cloud and vanilla feign. Now I'm not sure if I answered your question well?

Thank You very much.

**Comment by kdavisk6** [comment]
@metalpalo 

I found the cause, you are correct that it's in the version of `feign-httpclient` you are using.  If there is no charset specified the value of `ContentType.DEFAULT_TEXT` is used.  This is an alias for `TEXT_PLAIN`:

```java
public static final ContentType TEXT_PLAIN = create(
            "text/plain", Consts.ISO_8859_1);
```

Newer versions of `feign-httpclient` do not set the default content type, avoiding your issue.  If at all possible I recommend using our latest versions to avoid this bug.  If that's not possible, consider setting the `Content-Type` header specifically to avoid any auto-detection.

**Comment by metalpalo** [comment]
Thank You very much!

I will try both possibilities and inform about results

**Comment by metalpalo** [comment]
@kdavisk6

Hi,

I looked at our source code and here are results when comparing several versions of feign-httpclient.

Generally, we define Content-Type on our feign endpoints via following:
`@RequestMapping(value = "/api/dummies", consumes = "application/json", method = RequestMethod.POST)`

That means that we didn't define charset for request body. Your suggestion `ContentType.DEFAULT_TEXT` is really used when not **Content-Type** is defined.

I compare three versions of feign-httpclients when charset not defined in **Content-Type** as `charset=UTF-8`:

- 8.18.0(netlix brand) - it works, by default request.charset(UTF-8) is used

- 9.5.0 - it doesn't work, no request.charset is used, but `StringEntity` from `http-core` uses default charset 
`public static final Charset DEF_CONTENT_CHARSET = Consts.ISO_8859_1;`

- 9.6.0 - it works, by default request.charset(UTF-8) is used 

thanks again for your support
brpalo

**Comment by kdavisk6** [comment]
Glad to help.
