### ISSUE TITLE
How can I send a SOAP formated XML with a feign client?

### ISSUE THREAD

**Issue by adelgadorioja** [OpenFeign/feign#988]
I have this feign client:

```
@FeignClient(name = "calculatorServer", url = "http://www.dneonline.com/calculator.asmx")
public interface AEMWebServiceFeignClient{

    @PostMapping(value = "", consumes = MediaType.TEXT_XML, produces = MediaType.TEXT_XML)
    AddResponse calculate(@RequestBody Add addRequest);

}
```

I want to send a SOAP formated message, but I am sending this:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Add xmlns="http://tempuri.org/">
    <intA>2</intA>
    <intB>0</intB>
</Add>`

How can I do this, guys?

**Comment by megha0703** [comment]
Can you please let me know how did you manage it. I am not able to find any example to consume SOAP API via feign.

**Comment by adelgadorioja** [comment]
> Can you please let me know how did you manage it. I am not able to find any example to consume SOAP API via feign.

You can see the solution in: https://stackoverflow.com/questions/56621218/how-to-send-a-soap-object-with-feign-client

**Comment by jshubham1** [comment]
I used this: 

@Bean
  public RequestInterceptor xmlDeclarationRemovingInterceptor() {
    return requestTemplate -> {
      // Remove the XML declaration from the body if present
      // <?xml version="1.0" encoding="UTF-8" ?>
      byte[] bodyBytes = requestTemplate.body();
      if (bodyBytes != null) {
        String body = new String(bodyBytes, StandardCharsets.UTF_8);
        if (body.startsWith("<?xml")) {
          body = body.substring(body.indexOf("?>") + 2).trim();
          requestTemplate.body(body.getBytes(), StandardCharsets.UTF_8); // Use the correct body method
        }
      }
    };
  }
  
  
  
   @Bean
  protected Feign.Builder feignBuilder(SSLContext sslContext) {
    return Feign.builder()
        .errorDecoder(new SOAPErrorDecoder())
        .client(new Client.Default(sslContext.getSocketFactory(), null))
        .encoder(new SOAPEncoder(jaxbFactory))
        .decoder(new SOAPDecoder(jaxbFactory))
        .requestInterceptor(xmlDeclarationRemovingInterceptor());
  }
