### ISSUE TITLE
Feign 10, Ampersand and semicolon is not encoded in query parameter

### ISSUE THREAD

**Issue by dvidovic** [OpenFeign/feign#993]
Upgrading to Open feign version to 10.2.3 the '&' and ';' are not encoded.
The query parameter passed in was: +&12;22
and it gets resolved to: 
POST /capture/2?captureId=%2B&captureId=22&12 HTTP/1.1

**Comment by kdavisk6** [comment]
Ampersands and semi-colons are valid as part of the query component and will not be encoded.  If you need to include them as query values, you must provide them to feign pct-encoded and set the `encoded` flag on the `@Param` to `true`.
