### ISSUE TITLE
Don't add slash to URI  if it is a matrix parameter like (;matrixparam=value)

### ISSUE THREAD

**Issue by ranjitc5** [OpenFeign/feign#998]
After updating **openfeign**  latest version I found that  matrix parameters behaviour got changed. Seems its similar like **OpenFeign#889**

**OpenFeign version : 10.1.0 or Latest**

**Please find below scenarios in which its creating a problem**
 When we have API end point with dynamic  path and we try to get details using matrix params its creating a problem 
For example:
```
Path ("{prefix}")
EmployeController {

  EmployeeList getEmployee(@PathParam("prefix") PathSegment pathSegment,
            @QueryParam("flag") String flag) throws Exception;
} 
```
Now when we try to call above mention api with latest version and after calling **RequestTemplate -->> uri(matrix paramete details, true):**  its generate template **uri** like below
```
api/gituser/;includeDetails=false
```

**Which was with earlier version  like below**
```
api/gituser;includeDetails=false
```
I have checked the same and I think we should add one more condition with  **semicolon**  in RequestTemplate --> url(string, boolean) method like 
 **!uri.startsWith(";")**  for the matrix parameter.

I have few more scenarios which are creating same issue with latest version of open feign
**Let me know if you need more details**

**Comment by ranjitc5** [comment]
Can anyone please check above pull request ?

**Comment by ranjitc5** [comment]
Hi @kdavisk6 ,

I can see my PR is merged and as per milestone it should be in  **10.2.4** and **10.3.0**  but I can't see any release with above mentioned version.

Can you please help me for the same ?

**Comment by kdavisk6** [comment]
It's been built and released as we speak.
